/** Barnaul tourist hub pack (owner 2026-08-23). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { BARNAUL_LINE_DAY_ROUTE_PRESETS } from './barnaul-line-presets.ts';

function place(
  name: string,
  desc: string,
  latitude: number,
  longitude: number,
  opts: {
    address: string;
    locationSlug?: string;
    venueSlug?: string;
    mustSeeFilter?: string;
    visitMinutes?: number | string;
    alsoMain?: boolean;
  },
): any {
  return {
    name,
    desc,
    address: opts.address,
    latitude,
    longitude,
    mustSeeFilter: opts.mustSeeFilter || 'main',
    visitMinutes: opts.visitMinutes ?? 20,
    ...(opts.locationSlug ? { locationSlug: opts.locationSlug } : {}),
    ...(opts.venueSlug ? { venueSlug: opts.venueSlug } : {}),
    ...(typeof opts.alsoMain === 'boolean' ? { alsoMain: opts.alsoMain } : {}),
  };
}

export const BARNAUL_MUST_SEE: any[] = [
  place('Демидовский столп', 'Старейший обелиск города в честь столетия горного производства на Алтае.', 53.328525, 83.783711, { address: 'Демидовская площадь', locationSlug: 'barnaul-demidovskiy-stolp', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Нагорный парк и буквы «БАРНАУЛ»', 'Террасный парк на холме с семиметровыми белыми буквами и панорамой Оби.', 53.321852, 83.79155, { address: 'ул. Мамонтова, 19', locationSlug: 'barnaul-nagornyy-park-i-bukvy-barnaul', mustSeeFilter: 'park', visitMinutes: 60, alsoMain: true }),
  place('Памятник И. И. Ползунову', 'Монумент изобретателю первого в мире двухцилиндрового парового двигателя у АлтГТУ.', 53.344401, 83.774431, { address: 'пр. Ленина, 46', locationSlug: 'barnaul-pamyatnik-polzunovu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник В. М. Шукшину', 'Скульптура алтайского писателя, актера и режиссера на одноименной улице.', 53.355122, 83.675121, { address: 'ул. Шукшина, 2', locationSlug: 'barnaul-pamyatnik-shukshinu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Виктору Цою', 'Первый в Сибири памятник рок-музыканту с гитарой, выходящей из пламени.', 53.347514, 83.766321, { address: 'пр. Социалистический, 126', locationSlug: 'barnaul-pamyatnik-viktoru-tsoyu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник переселенцам на Алтай', 'Скульптурная группа сеятеля с сыном на площади Октября.', 53.360112, 83.764421, { address: 'площадь Октября', locationSlug: 'barnaul-pamyatnik-pereselentsam-na-altay', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник А. С. Пушкину', 'Классический бронзовый бюст поэта на тихой исторической улице.', 53.329431, 83.788102, { address: 'ул. Пушкина, 54', locationSlug: 'barnaul-pamyatnik-pushkinu', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Чарли Чаплину', 'Уличный арт-объект с комиком, опирающимся на трость.', 53.329811, 83.793751, { address: 'пр. Ленина, 7', locationSlug: 'barnaul-pamyatnik-charli-chaplinu', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Скульптурная композиция «Снимается кино»', 'Арт-объект в виде винтажной кинокамеры и кресла режиссера на барнаульском Арбате.', 53.326211, 83.79153, { address: 'ул. Мало-Тобольская, 28', locationSlug: 'barnaul-skulptura-snimaetsya-kino', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Скульптура «Медведь»', 'Деревянный тотемный хищник - символ алтайской тайги и ДНК региона.', 53.325514, 83.79211, { address: 'ул. Мало-Тобольская, 30', locationSlug: 'barnaul-skulptura-medved', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Т-34', 'Легендарный танк Великой Отечественной у кинотеатра «Мир».', 53.352431, 83.754821, { address: 'площадь Победы, 1', locationSlug: 'barnaul-pamyatnik-t-34', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Мемориал Славы', 'Архитектурно-скульптурный комплекс с Вечным огнем на площади Победы.', 53.353321, 83.755431, { address: 'площадь Победы, 6', locationSlug: 'barnaul-memorial-slavy', mustSeeFilter: 'monument', visitMinutes: 25 }),
  place('Арт-объект «Зонтик»', 'Романтичная кованая инсталляция с уличным фонарем на Арбате.', 53.327311, 83.791102, { address: 'ул. Мало-Тобольская, 20', locationSlug: 'barnaul-art-obekt-zontik', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Свифтовскому Гулливеру', 'Яркая скульптура сказочного великана в парке «Лесная сказка».', 53.344112, 83.676101, { address: 'ул. Энтузиастов, 12', locationSlug: 'barnaul-pamyatnik-gulliveru', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник В. И. Ленину на площади Советов', 'Монументальный гранитный вождь на главной административной площади.', 53.348102, 83.771121, { address: 'пр. Ленина, 59', locationSlug: 'barnaul-pamyatnik-leninu-ploshchad-sovetov', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Барнаульский сереброплавильный завод («Спичка»)', 'Руины грандиозного предприятия XVIII века, где выплавлялось 90% российского серебра.', 53.325833, 83.787778, { address: 'ул. Ползунова, 37', locationSlug: 'barnaul-barnaul-skiy-serebroplavil-nyy-zavod-spichka', mustSeeFilter: 'houses', visitMinutes: 45, alsoMain: true }),
  place('Дом купцов Шадриных', 'Шедевр деревянного зодчества начала XX века с кружевной резьбой и башнями-луковками.', 53.327521, 83.78521, { address: 'Красноармейский пр., 8', locationSlug: 'barnaul-dom-kuptsov-shadrinyh', mustSeeFilter: 'houses', visitMinutes: 25 }),
  place('Усадьба инженера Лесневского', 'Двухэтажный деревянный дом в стиле модерн, уцелевший после пожара 1917 года.', 53.322812, 83.788502, { address: 'ул. Ползунова, 56', locationSlug: 'barnaul-usadba-inzhenera-lesnevskogo', mustSeeFilter: 'houses', visitMinutes: 25 }),
  place('Дом Полякова и Яковлева', 'Каменный купеческий особняк начала XX века с кирпичной кладкой и башенками.', 53.328312, 83.78791, { address: 'ул. Гоголя, 44', locationSlug: 'barnaul-dom-polyakova-i-yakovleva', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Доходный дом Аверина', 'Первый барнаульский «небоскреб» в четыре этажа из темно-красного кирпича.', 53.324811, 83.784402, { address: 'ул. Гоголя, 76', locationSlug: 'barnaul-dohodnyy-dom-averina', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Здание Городской думы', 'Эклектичная ратуша с часовой башней в сердце купеческого квартала.', 53.327112, 83.79251, { address: 'ул. Льва Толстого, 24', locationSlug: 'barnaul-zdanie-gorodskoy-dumy', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Магазин Трубицына', 'Массивное каменное торговое здание конца XIX века.', 53.330514, 83.789121, { address: 'ул. Пушкина, 48', locationSlug: 'barnaul-magazin-trubitsyna', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Красный магазин купца Яковлева', 'Историческое торговое здание в стиле модерн с арочными окнами.', 53.328902, 83.790112, { address: 'ул. Короленко, 50', locationSlug: 'barnaul-krasnyy-magazin-kuptsa-yakovleva', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Туристический центр «Горная аптека»', 'Музей аптечного дела 1793 года с винтажной лабораторией и рестораном.', 53.32684, 83.789421, { address: 'ул. Ползунова, 42', locationSlug: 'barnaul-turistskiy-tsentr-gornaya-apteka', mustSeeFilter: 'museum', visitMinutes: 50 }),
  place('Алтайский краеведческий музей', 'Старейший музей Сибири с моделями паровых машин и скелетом мамонта.', 53.325511, 83.788501, { address: 'ул. Ползунова, 46', venueSlug: 'barnaul-altayskiy-kraevedcheskiy-muzey', mustSeeFilter: 'museum', visitMinutes: 70 }),
  place('Музей истории литературы, искусства и культуры Алтая (ГМИЛИКА)', 'Старинная усадьба о Рерихе, Шукшине и культуре коренных народов.', 53.330811, 83.796301, { address: 'ул. Льва Толстого, 2', venueSlug: 'barnaul-muzey-istorii-literatury-iskusstva-i-kultury-altaya-gmilika', mustSeeFilter: 'museum', visitMinutes: 60 }),
  place('Музей «Мир камня»', 'Частная коллекция алтайских минералов, метеоритов и полудрагоценных самоцветов.', 53.325802, 83.78841, { address: 'ул. Ползунова, 39', venueSlug: 'barnaul-muzey-mir-kamnya', mustSeeFilter: 'museum', visitMinutes: 45 }),
  place('Музей «Город»', 'Городское выставочное пространство об этапах развития Барнаула.', 53.32711, 83.792505, { address: 'ул. Льва Толстого, 24', venueSlug: 'barnaul-muzey-gorod', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Музей автоугона имени Юрия Деточкина', 'Ироничная экспозиция со скрытыми отмычками, капканами и уловками взломщиков.', 53.327311, 83.774431, { address: 'ул. Анатолия, 130', venueSlug: 'barnaul-muzey-avtougona-imeni-yuriya-detochkina', mustSeeFilter: 'museum', visitMinutes: 50 }),
  place('Государственный художественный музей Алтайского края (ГХМАК)', 'Собрание шедевров русского искусства со строгановскими иконами и классикой.', 53.329612, 83.794402, { address: 'ул. Максима Горького, 16', venueSlug: 'barnaul-gosudarstvennyy-hudozhestvennyy-muzey-altayskogo-kraya-ghmak', mustSeeFilter: 'museum', visitMinutes: 75, alsoMain: true }),
  place('Музей «Мир времени»', 'Интерактивное пространство, где можно потрогать редкие предметы быта прошлых веков.', 53.359614, 83.731102, { address: 'ул. Матросова, 12', venueSlug: 'barnaul-muzey-mir-vremeni', mustSeeFilter: 'museum', visitMinutes: 50, alsoMain: true }),
  place('Покровский кафедральный собор', 'Краснокирпичный собор в русско-византийском стиле с лазурными куполами.', 53.329914, 83.77253, { address: 'ул. Никитина, 137', venueSlug: 'barnaul-pokrovskiy-kafedralnyy-sobor', mustSeeFilter: 'temple', visitMinutes: 40 }),
  place('Знаменский женский монастырь', 'Монастырский комплекс с белокаменным собором и ухоженной территорией.', 53.325121, 83.795102, { address: 'ул. Большая Олонская, 42', locationSlug: 'barnaul-znamenskiy-zhenskiy-monastyr', mustSeeFilter: 'temple', visitMinutes: 35 }),
  place('Иоанно-Предтеченский храм', 'Византийская церковь в Нагорном парке на месте разрушенного некрополя.', 53.321601, 83.792202, { address: 'ул. Мамонтова, 19/2', locationSlug: 'barnaul-ioanno-predtechenskiy-hram', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Католический храм Христа Царя', 'Современный костел с лаконичной европейской архитектурой и органными вечерами.', 53.344812, 83.72583, { address: 'ул. Матросова, 113', locationSlug: 'barnaul-katolicheskiy-hram-hrista-tsarya', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Никольская церковь', 'Старинный полковой храм из красного кирпича на проспекте Ленина.', 53.339431, 83.78241, { address: 'пр. Ленина, 36', locationSlug: 'barnaul-nikolskaya-tserkov', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Храм Димитрия Ростовского', 'Классическая барочная церковь на старейшей Демидовской площади.', 53.328312, 83.785402, { address: 'площадь Спартака, 8', locationSlug: 'barnaul-hram-dimitriya-rostovskogo', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Армянская церковь Святой Рипсиме', 'Храм из розового туфа с кавказской резьбой по камню.', 53.349912, 83.65581, { address: 'ул. Попова, 14б', locationSlug: 'barnaul-armyanskaya-tserkov-svyatoy-ripsime', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Парк «Изумрудный»', 'Современный экопарк с прудом, беговыми дорожками и амфитеатром.', 53.352812, 83.780102, { address: 'Комсомольский пр., 128', locationSlug: 'barnaul-park-izumrudnyy', mustSeeFilter: 'park', visitMinutes: 50 }),
  place('Городская набережная реки Оби', 'Благоустроенный променад со смотровыми балконами и речным вокзалом.', 53.323521, 83.801502, { address: 'ул. Дамба Оби, 1', locationSlug: 'barnaul-gorodskaya-naberezhnaya-obi', mustSeeFilter: 'park', visitMinutes: 45 }),
  place('Парк культуры и отдыха «Центральный»', 'Старейший зеленый парк города, основанный еще при демидовском заводе.', 53.324312, 83.791821, { address: 'Социалистический пр., 11', locationSlug: 'barnaul-park-kultury-i-otdyha-tsentralnyy', mustSeeFilter: 'park', visitMinutes: 40 }),
  place('Парк «Лесная сказка»', 'Семейный парк развлечений с собственным зоопарком.', 53.343912, 83.675402, { address: 'ул. Энтузиастов, 12', locationSlug: 'barnaul-park-lesnaya-skazka', mustSeeFilter: 'park', visitMinutes: 60 }),
  place('Реликтовый Ленточный бор', 'Естественный сосновый массив - уникальный природный феномен Сибири.', 53.315121, 83.65821, { address: 'ул. Власихинская, 67', locationSlug: 'barnaul-reliktovyy-lentochnyy-bor', mustSeeFilter: 'park', visitMinutes: 60 }),
  place('Мало-Тобольская улица (Барнаульский Арбат)', 'Первая полностью пешеходная улица с купеческими рядами и уличными арт-объектами.', 53.326211, 83.79153, { address: 'ул. Мало-Тобольская', locationSlug: 'barnaul-malo-tobol-skaya-ulitsa-barnaul-skiy-arbat', mustSeeFilter: 'street', visitMinutes: 40, alsoMain: true }),
  place('Ресторация «Горная аптека»', 'Ресторан сибирской кухни XIX века с блюдами из дичи по старинным рецептам.', 53.32684, 83.789421, { address: 'ул. Ползунова, 42', locationSlug: 'barnaul-restoratsiya-gornaya-apteka', mustSeeFilter: 'gastro', visitMinutes: 75 }),
  place('Театр драмы имени В. М. Шукшина', 'Главная академическая сцена края в здании советского неоклассицизма.', 53.346812, 83.763301, { address: 'ул. Молодежная, 15', venueSlug: 'barnaul-teatr-dramy-imeni-shukshina', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Государственная филармония Алтайского края', 'Концертный зал с уникальной акустикой и сибирским органом.', 53.326511, 83.787102, { address: 'ул. Ползунова, 35', venueSlug: 'barnaul-gosudarstvennaya-filarmoniya-altayskogo-kraya', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Молодежный театр Алтая имени В. С. Золотухина', 'Экспериментальное театральное пространство в бывшем ДК БМК.', 53.360812, 83.763102, { address: 'площадь Октября, 2', venueSlug: 'barnaul-molodezhnyy-teatr-altaia-imeni-zolotuhina', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Музыкальный театр Алтайского края', 'Центр оперетты, мюзиклов и ярких музыкальных постановок.', 53.345812, 83.779402, { address: 'Комсомольский пр., 108', venueSlug: 'barnaul-muzykalnyy-teatr-altayskogo-kraya', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Крафтовый ресторан «Бивер»', 'Гастрономическое место с большим выбором мясных сибирских сетов.', 53.328312, 83.79511, { address: 'пр. Ленина, 3', locationSlug: 'barnaul-kraftovyy-restoran-biver', mustSeeFilter: 'gastro', visitMinutes: 75 }),
];

export const BARNAUL_SUBURBS: any[] = [
  {
    name: 'Озеро Красилово / база «Красилово»',
    desc: 'Уникальное озеро в нетронутом ленточном бору с чистейшей водой и гнездовьями редких птиц - первозданная тишина Алтая без дальней дороги в горы.',
    locationSlug: 'barnaul-ozero-krasilovo',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 53.211421,
    longitude: 84.341102,
    address: 'Косихинский район, озеро Красилово',
    travelVector: 'Авто / автобус до Боровлянки ~1 ч 20 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль или рейсовый автобус до села Боровлянка около 1 часа 20 минут, чтобы приехать к 9:00 утра.',
    timingNote:
      'По береговой линии двигайтесь на юг в сторону векового бора, напоследок оставив песчаный косогор для панорамных снимков.',
    places: [
      place('Центральный песчаный пляж', 'Место для старта трека и купания.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-peschaniy-plyazh', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Экологическая тропа в бору', 'Маршрут среди столетних корабельных сосен.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-ekologicheskaya-tropa', mustSeeFilter: 'park', visitMinutes: 50 }),
      place('Гнездовья цапель', 'Заболоченный северо-восточный плес озера.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-gnezdovya-tsapels', mustSeeFilter: 'views', visitMinutes: 30 }),
      place('Смотровая вышка', 'Деревянная платформа для наблюдения за птицами.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-smotrovaya-vyshka', mustSeeFilter: 'views', visitMinutes: 25 }),
      place('Черничный мыс', 'Ягодные поляны, созревающие в середине лета.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-chernichnyy-mys', mustSeeFilter: 'park', visitMinutes: 30 }),
      place('Старая лодочная станция', 'Атмосферный объект для винтажных фотографий.', 53.211421, 84.341102, { address: 'озеро Красилово', locationSlug: 'barnaul-krasilovo-lodochnaya-stantsiya', mustSeeFilter: 'houses', visitMinutes: 20 }),
    ],
  },
  {
    name: 'Страусиная ранчо во Власихе',
    desc: 'Первая на Алтае эко-ферма, где африканские страусы адаптировались к сибирским зимам - контраст экзотики и сельского колорита.',
    locationSlug: 'barnaul-strausinaya-rancho-vlasikha',
    mustSeeFilter: 'main',
    visitMinutes: '3-4 ч',
    latitude: 53.308112,
    longitude: 83.604421,
    address: 'пос. Власиха, ул. Сосновая, 27',
    travelVector: 'Маршрутное такси №120 ~40 мин',
    travelVectorBlurb:
      'Закладывайте на пригородное маршрутное такси №120 около 40 минут, чтобы приехать к 10:00 утра.',
    timingNote:
      'По главной аллее фермы двигайтесь направо мимо вольеров с птицами, напоследок оставив конный загон и зону отдыха.',
    places: [
      place('Главный вольер африканских страусов', 'Знакомство с гигантскими птицами.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-volyer-strausov', mustSeeFilter: 'park', visitMinutes: 30 }),
      place('Загон австралийских эму', 'Площадка с более дружелюбными обитателями.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-emus', mustSeeFilter: 'park', visitMinutes: 25 }),
      place('Контактный двор с козлятами', 'Зона, где можно покормить животных.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-kontaktnyy-dvor', mustSeeFilter: 'park', visitMinutes: 25 }),
      place('Инкубаторий', 'Место, где выводят маленьких страусят.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-inkubatoriy', mustSeeFilter: 'museum', visitMinutes: 20 }),
      place('Сувенирная лавка', 'Поделки из огромной страусиной скорлупы.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-suvenirnaya-lavka', mustSeeFilter: 'gastro', visitMinutes: 20 }),
      place('Кафе на территории', 'Дегустация фермерских продуктов и выпечки.', 53.308112, 83.604421, { address: 'пос. Власиха', locationSlug: 'barnaul-vlasikha-kafe', mustSeeFilter: 'gastro', visitMinutes: 40 }),
    ],
  },
  {
    name: 'Нагорная часть Павловска / Серебряный бор',
    desc: 'Старинное поселение-завод-дублер Барнаула с серебряным прудом и вековым бором - эталонный пейзаж предгорной провинции.',
    locationSlug: 'barnaul-pavlovsk-serebryanyy-bor',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 53.312102,
    longitude: 82.985411,
    address: 'с. Павловск, Набережная улица',
    travelVector: 'Междугородний автобус ~1 ч',
    travelVectorBlurb:
      'Закладывайте на междугородний автобус от автовокзала около 1 часа, чтобы приехать к 9:30 утра.',
    timingNote:
      'По дамбе павловского пруда двигайтесь на запад в гору, напоследок оставив вековой сосновый бор.',
    places: [
      place('Павловский серебряный пруд', 'Огромный искусственный водоем XVIII века.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-serebryanyy-prud', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Старинная заводская плотина', 'Инженерное сооружение демидовской эпохи.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-zavodskaya-plotina', mustSeeFilter: 'houses', visitMinutes: 30 }),
      place('Введенская церковь', 'Восстанавливаемый исторический храм в центре.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-vvedenskaya-tserkov', mustSeeFilter: 'temple', visitMinutes: 30 }),
      place('Павловский историко-художественный музей', 'Экспозиция о быте мастеровых.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-istoriko-hudozhestvennyy-muzey', mustSeeFilter: 'museum', visitMinutes: 45 }),
      place('Смотровая площадка на холме', 'Панорама на водную гладь и крыши села.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-smotrovaya-ploshchadka', mustSeeFilter: 'views', visitMinutes: 25 }),
      place('Пешеходный мостик влюбленных', 'Уютное место над заводским каналом.', 53.312102, 82.985411, { address: 'с. Павловск', locationSlug: 'barnaul-pavlovsk-mostik-vlyublennyh', mustSeeFilter: 'views', visitMinutes: 20 }),
    ],
  },
];

export const BARNAUL_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'barnaul-gornozavodskoy-kupecheskiy',
    title: 'Горнозаводской купеческий Барнаул',
    description:
      'Классический трек по историческому сердцу: Демидовский столп, Шадрины, «Горная аптека», завод «Спичка», Арбат и Нагорный парк.',
    travelVector: 'Пешком по старому центру',
    timingNote:
      'Около 8-9 часов: столп - Шадрины - «Горная аптека» - обед - завод - Арбат - Нагорный парк на закате.',
    coverImageUrl: '/images/venues/barnaul/barnaul-skiy-serebroplavil-nyy-zavod-spichka.jpg',
    stops: [
      {
        name: 'Демидовский столп',
        desc: '15 минут у центра старейшей площади.',
        locationSlug: 'barnaul-demidovskiy-stolp',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'Демидовская площадь',
        latitude: 53.328525,
        longitude: 83.783711,
      },
      {
        name: 'Дом купцов Шадриных',
        desc: '15 минут на деревянное кружево.',
        locationSlug: 'barnaul-dom-kuptsov-shadrinyh',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'Красноармейский пр., 8',
        latitude: 53.327521,
        longitude: 83.78521,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Туристический центр «Горная аптека»',
        desc: '45 минут на театрализованную экскурсию.',
        locationSlug: 'barnaul-turistskiy-tsentr-gornaya-apteka',
        mustSeeFilter: 'museum',
        visitMinutes: 45,
        address: 'ул. Ползунова, 42',
        latitude: 53.32684,
        longitude: 83.789421,
        transitTip: 'Пешком 7 минут',
      },
      {
        name: 'Ресторация «Горная аптека»',
        desc: '1 час на обед с алтайской дичью и таежным чаем.',
        locationSlug: 'barnaul-restoratsiya-gornaya-apteka',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Ползунова, 42',
        latitude: 53.32684,
        longitude: 83.789421,
        transitTip: 'Пешком 1 минута',
      },
      {
        name: 'Барнаульский сереброплавильный завод («Спичка»)',
        desc: '30 минут у исторических руин завода.',
        locationSlug: 'barnaul-barnaul-skiy-serebroplavil-nyy-zavod-spichka',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        address: 'ул. Ползунова, 37',
        latitude: 53.325833,
        longitude: 83.787778,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Мало-Тобольская улица (Барнаульский Арбат)',
        desc: '40 минут по пешеходной зоне с арт-объектами.',
        locationSlug: 'barnaul-malo-tobol-skaya-ulitsa-barnaul-skiy-arbat',
        mustSeeFilter: 'street',
        visitMinutes: 40,
        address: 'ул. Мало-Тобольская',
        latitude: 53.326211,
        longitude: 83.79153,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Нагорный парк и буквы «БАРНАУЛ»',
        desc: '1 час на подъем и панораму Оби на закате.',
        locationSlug: 'barnaul-nagornyy-park-i-bukvy-barnaul',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'ул. Мамонтова, 19',
        latitude: 53.321852,
        longitude: 83.79155,
        transitTip: 'Пешком 10 минут',
      },
    ],
  },
  {
    id: 'barnaul-aristokraticheskiy-prospekt',
    title: 'Аристократический проспект и культура',
    description:
      'Маршрут по проспекту Ленина: площадь Победы, театр Шукшина, Цой, площадь Советов, Ползунов, Никольская церковь и «Бивер».',
    travelVector: 'Проспект Ленина',
    timingNote:
      'Около 8 часов: Победа - Шукшин - Цой - Советы - Ползунов - Никольская - ужин в «Бивере».',
    coverImageUrl: '/images/venues/barnaul/teatr-dramy-imeni-shukshina.jpg',
    stops: [
      {
        name: 'Площадь Победы и Мемориал Славы',
        desc: '20 минут у Т-34 и Вечного огня.',
        locationSlug: 'barnaul-memorial-slavy',
        mustSeeFilter: 'monument',
        visitMinutes: 20,
        address: 'площадь Победы',
        latitude: 53.353321,
        longitude: 83.755431,
      },
      {
        name: 'Театр драмы имени В. М. Шукшина',
        desc: '15 минут у здания и театральной площади.',
        venueSlug: 'barnaul-teatr-dramy-imeni-shukshina',
        mustSeeFilter: 'creative',
        visitMinutes: 15,
        address: 'ул. Молодежная, 15',
        latitude: 53.346812,
        longitude: 83.763301,
        transitTip: 'Пешком 12 минут по аллее',
      },
      {
        name: 'Памятник Виктору Цою',
        desc: '10 минут у легендарной скульптуры.',
        locationSlug: 'barnaul-pamyatnik-viktoru-tsoyu',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'пр. Социалистический, 126',
        latitude: 53.347514,
        longitude: 83.766321,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Площадь Советов и Памятник Ленину',
        desc: '15 минут в административном центре.',
        locationSlug: 'barnaul-pamyatnik-leninu-ploshchad-sovetov',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'пр. Ленина, 59',
        latitude: 53.348102,
        longitude: 83.771121,
        transitTip: 'Пешком 10 минут',
      },
      {
        name: 'Памятник И. И. Ползунову',
        desc: '10 минут у монумента перед Политехом.',
        locationSlug: 'barnaul-pamyatnik-polzunovu',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'пр. Ленина, 46',
        latitude: 53.344401,
        longitude: 83.774431,
        transitTip: 'Пешком 4 минуты',
      },
      {
        name: 'Никольская церковь',
        desc: '20 минут у красного полкового храма.',
        locationSlug: 'barnaul-nikolskaya-tserkov',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'пр. Ленина, 36',
        latitude: 53.339431,
        longitude: 83.78241,
        transitTip: 'Пешком 12 минут',
      },
      {
        name: 'Крафтовый ресторан «Бивер»',
        desc: '1.5 часа на ужин в сибирском стиле.',
        locationSlug: 'barnaul-kraftovyy-restoran-biver',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'пр. Ленина, 3',
        latitude: 53.328312,
        longitude: 83.79511,
        transitTip: 'Пешком 8 минут',
      },
    ],
  },
  ...BARNAUL_LINE_DAY_ROUTE_PRESETS,
];

export const BARNAUL_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как лучше всего добраться из аэропорта до центра города без переплат?',
    a: 'Из аэропорта имени Германа Титова в центр ходит городской автобус №110 и маршрутка №144 - проезд копеечный по сравнению с такси, маршруты идут через главные проспекты до железнодорожного вокзала. Такси лучше заказывать через агрегаторы, избегая частников у терминала с завышенной ценой.',
  },
  {
    q: 'Правда ли, что под Барнаулом есть сеть секретных старинных подземных ходов?',
    a: 'Это один из главных городских мифов. Легенды гласят, что от Демидовского завода и «Горной аптеки» к Оби вели подземные галереи для тайной транспортировки серебра. Историки подтверждают старые водоотводные каналы и купеческие подвалы, но полноценного «подземного города» нет. Атмосферу подземелий можно ощутить в подвале «Горной аптеки».',
  },
  {
    q: 'Как посмотреть знаменитый Ленточный бор, не уезжая далеко от центра?',
    a: 'Не нужны гиды и поездка в глухую тайгу. Садитесь в центре на трамвай №7 до конечной «Депо №3» или в сторону Змеиногорского тракта - вы высадитесь у кромки реликтового бора с «Лыжней здоровья». Зимой можно взять лыжи напрокат, летом - велосипед.',
  },
  {
    q: 'Какая главная транспортная боль ждет туриста в Барнауле и как ее избежать?',
    a: 'Это пробки на Новом мосту через Обь и на площади Октября в утренние (08:00-09:30) и вечерние (17:00-19:00) часы. Для поездок на правый берег закладывайте лишний час или выезжайте вне пиков. Внутри центра удобнее трамваи - они идут по выделенным линиям и не зависят от заторов.',
  },
];

export const BARNAUL_TRAVEL =
  'Международный аэропорт Барнаула имени Германа Титова: прямые рейсы из Москвы около 4,5 часов. Город - крупный железнодорожный узел с поездами в Новосибирск, Красноярск и Казахстан. Зима: сибирская сказка с сухими морозами до -25 °C и пушистым снегом, лыжи в реликтовом Ленточном бору прямо в черте города; метели усложняют логистику, но спасает развитый общественный транспорт. Весна: март еще зимний, таяние с апреля, в мае зелень и ледоход на Оби - лучшее время для пеших маршрутов старого центра. Лето: жаркое и солнечное около +25 °C, речные круизы, набережная и уличные кафе; идеально для прогулок и поездок на соленые озера. Осень: золотая пора до середины октября с мягким «бабьим летом», бор в багряных тонах - удобно для экскурсий и загородных выездов. Лучший сезон для центра и Мало-Тобольской - с конца мая по сентябрь; для гор Алтая - июль, август и сентябрь.';
