/** Chelyabinsk tourist hub pack (owner 2026-08-17). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { CHELYABINSK_LINE_DAY_ROUTE_PRESETS } from './chelyabinsk-line-presets.ts';

export const CHELYABINSK_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Скульптура «Сказ об Урале»',
    desc: 'Монументальный богатырь на привокзальной площади - встреча с городом у Челябинск-Главного.',
    address: 'привокзальная площадь',
    locationSlug: 'chelyabinsk-skaz-ob-urale',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 55.142212,
    longitude: 61.415891,
  },
  {
    name: 'Памятник И. В. Курчатову',
    desc: 'Раскрытый атом у входа в парк Гагарина: фототочка и белки в соснах рядом.',
    address: 'ул. Ленина / парк Гагарина',
    locationSlug: 'chelyabinsk-pamyatnik-kurchatovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.149112,
    longitude: 61.371901,
  },
  {
    name: 'Памятник Левше',
    desc: 'Бронзовый умелец на Кировке у дома 163 - фирменная скульптура челябинского Арбата.',
    address: 'ул. Кирова, 163',
    locationSlug: 'chelyabinsk-pamyatnik-levshe',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.163112,
    longitude: 61.401112,
  },
  {
    name: 'Скульптура «Нищий»',
    desc: 'Контактная фигура на Кировке у дома 116, рядом с ТЮЗом.',
    address: 'ул. Кирова, 116',
    locationSlug: 'chelyabinsk-pamyatnik-nishchemu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.164901,
    longitude: 61.401891,
  },
  {
    name: 'Памятник танкистам-добровольцам',
    desc: 'Воинский монумент на стыке Кирова и Коммуны, у начала бульвара Славы.',
    address: 'ул. Кирова / ул. Коммуны',
    locationSlug: 'chelyabinsk-pamyatnik-tankistam-dobrovoltsam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.161112,
    longitude: 61.401412,
  },
  {
    name: 'Скульптура «Ходок с собакой»',
    desc: 'Бронзовая прогулка на Кировке у дома 143 - типичный челябинский уличный юмор.',
    address: 'ул. Кирова, 143',
    locationSlug: 'chelyabinsk-hodok-s-sobakoy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.162901,
    longitude: 61.400912,
  },
  {
    name: '«Доблестным сынам Отечества» / Роза ветров',
    desc: 'Мемориальный ансамбль на Комсомольской площади с розой ветров.',
    address: 'Комсомольская площадь',
    locationSlug: 'chelyabinsk-roza-vetrov',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.158912,
    longitude: 61.453112,
  },
  {
    name: 'Памятник М. И. Глинке',
    desc: 'Композитор у театра оперы и балета на площади Ярославского.',
    address: 'пл. Ярославского, 1',
    locationSlug: 'chelyabinsk-pamyatnik-glinke',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.166912,
    longitude: 61.401112,
  },
  {
    name: 'Скульптура «Извозчик»',
    desc: 'Бронзовый кучер на Кировке у дома 104 - фото с пролеткой.',
    address: 'ул. Кирова, 104',
    locationSlug: 'chelyabinsk-pamyatnik-izvozchiku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.165891,
    longitude: 61.401791,
  },
  {
    name: 'Памятник «Орленок»',
    desc: 'Пионерский монумент в парке Алое поле, рядом с храмом Александра Невского.',
    address: 'Алое поле',
    locationSlug: 'chelyabinsk-pamyatnik-orlenku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.160112,
    longitude: 61.391901,
  },
  {
    name: 'Скульптура «Венский вальс»',
    desc: 'Танцующая пара у пассажа Яушевых на Труда, 92.',
    address: 'ул. Труда, 92',
    locationSlug: 'chelyabinsk-venskiy-vals',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.167812,
    longitude: 61.403112,
  },
  {
    name: 'Памятник С. С. Прокофьеву',
    desc: 'Композитор у пассажа на Труда, 92А, на пути к набережной Миасса.',
    address: 'ул. Труда, 92А',
    locationSlug: 'chelyabinsk-pamyatnik-prokofievu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.168112,
    longitude: 61.402312,
  },
  {
    name: 'Челябинский верблюд',
    desc: 'Городской символ на Кировке у Театральной: верблюд как код Южного Урала.',
    address: 'ул. Кирова / ул. Театральная',
    locationSlug: 'chelyabinsk-chelyabinskiy-verblyud',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.161901,
    longitude: 61.400811,
  },
  {
    name: 'Памятник основателям Челябинска',
    desc: 'Четыре бронзовые фигуры и шпиль с Архангелом Михаилом на месте крепости 1736 года, в начале Кировки.',
    address: 'ул. Кирова, 82',
    locationSlug: 'chelyabinsk-pamyatnik-osnovatelyam',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 55.167371,
    longitude: 61.400389,
  },
  {
    name: 'Памятник Ленину на площади Революции',
    desc: 'Классический монумент на главной площади, напротив музея изобразительных искусств.',
    address: 'площадь Революции',
    locationSlug: 'chelyabinsk-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.159612,
    longitude: 61.402312,
  },

  // --- Историческое наследие (1-12 из 50 локаций) ---
  {
    name: 'Элеватор Госбанка',
    desc: 'Заброшенное 40-метровое зернохранилище начала XX века, похожее на готический замок - индустриальный авангард Челябинска.',
    address: 'ул. Кирова, 130Р',
    locationSlug: 'chelyabinsk-elevator',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.163412,
    longitude: 61.400812,
  },
  {
    name: 'Пассаж Яушевых',
    desc: 'Купеческий пассаж с витринами и лепниной - старт зеленой линии и Кировки со стороны Труда.',
    address: 'ул. Труда, 92А',
    locationSlug: 'chelyabinsk-passage-yaushevyh',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.168112,
    longitude: 61.402312,
  },
  {
    name: 'Особняк Архипова',
    desc: 'Парадный купеческий дом на Труда, 90, рядом с «Венским вальсом».',
    address: 'ул. Труда, 90',
    locationSlug: 'chelyabinsk-osobnyak-arhipova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.167812,
    longitude: 61.403112,
  },
  {
    name: 'Дом облисполкома',
    desc: 'Сталинский административный ансамбль на Ленина, 54 - финал зеленой линии.',
    address: 'ул. Ленина, 54',
    locationSlug: 'chelyabinsk-dom-oblispolkoma',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.159412,
    longitude: 61.402012,
  },
  {
    name: 'Театр оперы и балета им. Глинки',
    desc: 'Главная музыкальная сцена Южного Урала на площади Ярославского.',
    address: 'пл. Ярославского, 1',
    venueSlug: 'chelyabinsk-teatr-opery-glinki',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 55.166912,
    longitude: 61.401112,
  },
  {
    name: 'Дом Данцигера',
    desc: 'Особняк начала XX века на Пушкина - переход от купеческого центра к ампиру Ленина.',
    address: 'ул. Пушкина, 1',
    locationSlug: 'chelyabinsk-dom-dantsigera',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.161412,
    longitude: 61.400512,
  },
  {
    name: 'Ансамбль ЧТЗ',
    desc: 'Танкоград: заводские корпуса и Дворец культуры на Ленина, 15-25. Брутальная эстетика, конструктивизм и трудовая гордость.',
    address: 'пр. Ленина, 15-25',
    locationSlug: 'chelyabinsk-chtz',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 55.159212,
    longitude: 61.478112,
  },
  {
    name: 'Дом печати',
    desc: 'Конструктивистский комплекс на Свердловском проспекте, 60.',
    address: 'Свердловский проспект, 60',
    locationSlug: 'chelyabinsk-dom-pechati',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.160812,
    longitude: 61.392512,
  },
  {
    name: 'Вокзал Челябинск-Главный',
    desc: 'Парадный железнодорожный фасад и площадь со «Сказом об Урале».',
    address: 'привокзальная площадь',
    locationSlug: 'chelyabinsk-vokzal-glavnyy',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.142212,
    longitude: 61.415891,
  },
  {
    name: 'Купольный пассаж на Каслинской',
    desc: 'Торговый купол на Каслинской, 64 - редкая для города купольная конструкция.',
    address: 'ул. Каслинская, 64',
    locationSlug: 'chelyabinsk-kaslinskaya-64',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.155512,
    longitude: 61.378112,
  },
  {
    name: 'Деревянный дом Холодова',
    desc: 'Купеческий деревянный дом на Кировке, 139А - редкий сохранившийся сруб в пешеходном центре.',
    address: 'ул. Кирова, 139А',
    locationSlug: 'chelyabinsk-dom-holodova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.163812,
    longitude: 61.401212,
  },
  {
    name: 'Здание Госбанка',
    desc: 'Монументальный сталинский ампир на Ленина, 52: колонны и строгий ритм фасада.',
    address: 'ул. Ленина, 52',
    locationSlug: 'chelyabinsk-gosbank',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.159812,
    longitude: 61.401512,
  },

  // --- Музеи (13-21) ---
  {
    name: 'Государственный исторический музей Южного Урала',
    desc: 'Крупнейший осколок челябинского метеорита (больше 500 кг) под стеклянным куполом на Труда, 100.',
    address: 'ул. Труда, 100',
    venueSlug: 'chelyabinsk-gosudarstvennyy-istoricheskiy-muzey-yuzhnogo-urala',
    mustSeeFilter: 'main',
    visitMinutes: 75,
    latitude: 55.167512,
    longitude: 61.400412,
  },
  {
    name: 'Музей изобразительных искусств',
    desc: 'Картинная галерея на площади Революции, 1. Первый четверг месяца - бесплатно для студентов и до 18 лет.',
    address: 'площадь Революции, 1',
    venueSlug: 'chelyabinsk-muzey-izobrazitelnyh-iskusstv',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.159612,
    longitude: 61.402812,
  },
  {
    name: 'Музей истории ЧТЗ',
    desc: 'Танки ИС и КВ, заводская летопись Танкограда на Ленина, 19.',
    address: 'пр. Ленина, 19',
    venueSlug: 'chelyabinsk-muzey-istorii-chtz',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.159212,
    longitude: 61.476512,
  },
  {
    name: 'Музей ретроавтомобилей',
    desc: 'Коллекция классических машин на Новоелеваторной, 51.',
    address: 'ул. Новоелеваторная, 51',
    venueSlug: 'chelyabinsk-muzey-retro-avtomobiley',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.172112,
    longitude: 61.389212,
  },
  {
    name: 'Музей Южно-Уральской железной дороги',
    desc: 'Железнодорожная история края на Цвиллинга, 63А.',
    address: 'ул. Цвиллинга, 63А',
    venueSlug: 'chelyabinsk-muzey-yuzhno-uralskoy-zheleznoy-dorogi',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.157212,
    longitude: 61.405812,
  },
  {
    name: 'Почтовый музей',
    desc: 'Связь и почта Южного Урала в здании на Ленина, 64.',
    address: 'ул. Ленина, 64',
    venueSlug: 'chelyabinsk-pochtovyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.157412,
    longitude: 61.400212,
  },
  {
    name: 'Старый краеведческий музей',
    desc: 'Историческое здание краеведения на Елкина, 45.',
    address: 'ул. Елкина, 45',
    venueSlug: 'chelyabinsk-staryy-kraevedcheskiy',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.157812,
    longitude: 61.397512,
  },
  {
    name: 'Научный музей «Экспериментус»',
    desc: 'Интерактивная физика и опыты на Орджоникидзе, 54А.',
    address: 'ул. Орджоникидзе, 54А',
    venueSlug: 'chelyabinsk-experimentus',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.146812,
    longitude: 61.368512,
  },
  {
    name: 'Геологический музей «Гармония»',
    desc: 'Уральские минералы и самоцветы на Кировке, 114.',
    address: 'ул. Кирова, 114',
    venueSlug: 'chelyabinsk-muzey-geologii-garmoniya',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.165212,
    longitude: 61.401612,
  },

  // --- Храмы (22-30) ---
  {
    name: 'Симеоновский кафедральный собор',
    desc: 'Главный православный собор города на Кыштымской, 32.',
    address: 'ул. Кыштымская, 32',
    locationSlug: 'chelyabinsk-simeonovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.154212,
    longitude: 61.381212,
  },
  {
    name: 'Храм Александра Невского',
    desc: 'Краснокирпичный храм в парке Алое поле - якорь красной линии.',
    address: 'Алое поле, 1',
    locationSlug: 'chelyabinsk-hram-aleksandra-nevskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.160112,
    longitude: 61.391901,
  },
  {
    name: 'Одигитриевский монастырь',
    desc: 'Действующий женский монастырь на Энергетиков, 21А.',
    address: 'ул. Энергетиков, 21А',
    locationSlug: 'chelyabinsk-odigitrievskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 55.118512,
    longitude: 61.393212,
  },
  {
    name: 'Свято-Троицкий храм',
    desc: 'Историческая церковь на Кирова, 60А, у купеческого центра.',
    address: 'ул. Кирова, 60А',
    locationSlug: 'chelyabinsk-troitskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.168512,
    longitude: 61.400212,
  },
  {
    name: 'Соборная мечеть',
    desc: 'Главная мечеть Челябинска на Елкина, 16.',
    address: 'ул. Елкина, 16',
    locationSlug: 'chelyabinsk-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.159112,
    longitude: 61.398812,
  },
  {
    name: 'Католический храм Непорочного Зачатия',
    desc: 'Действующий католический приход на ул. 50-летия ВЛКСМ, 15А.',
    address: 'ул. 50-летия ВЛКСМ, 15А',
    locationSlug: 'chelyabinsk-katolicheskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.141212,
    longitude: 61.369512,
  },
  {
    name: 'Храм Георгия Победоносца',
    desc: 'Православный храм на Жукова, 30.',
    address: 'ул. Жукова, 30',
    locationSlug: 'chelyabinsk-hram-georgiya-pobedonostsa',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.151212,
    longitude: 61.428512,
  },
  {
    name: 'Храм Иоанна Воина',
    desc: 'Храм на ул. 40-летия Победы, 31С.',
    address: 'ул. 40-летия Победы, 31С',
    locationSlug: 'chelyabinsk-hram-ioanna-voina',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.132512,
    longitude: 61.385212,
  },
  {
    name: 'Синагога Хабад',
    desc: 'Еврейский общинный центр на Маркса, 110.',
    address: 'ул. Карла Маркса, 110',
    locationSlug: 'chelyabinsk-sinagoga-chabad',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.162412,
    longitude: 61.405112,
  },

  // --- Парки и смотровые (31-39) ---
  {
    name: 'Парк культуры и отдыха им. Ю. А. Гагарина',
    desc: 'Сосновый массив в городе: зимой большой каток среди старых сосен, у Курчатова - белки.',
    address: 'ул. Ленина, парк Гагарина',
    locationSlug: 'chelyabinsk-park-kul-tury-i-otdyha-im-yu-a-gagarina',
    mustSeeFilter: 'park',
    visitMinutes: 75,
    latitude: 55.149112,
    longitude: 61.371901,
  },
  {
    name: 'Челябинский городской бор',
    desc: 'Реликтовый сосновый лес естественного происхождения у центральных кварталов. Осенью золотеет, зимой встречаются лисы - не кормить.',
    address: 'Челябинский городской бор',
    locationSlug: 'chelyabinsk-gorodskoy-bor',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 55.138512,
    longitude: 61.352112,
  },
  {
    name: 'Алое поле',
    desc: 'Исторический парк с храмом Александра Невского и памятником «Орленок».',
    address: 'Алое поле',
    locationSlug: 'chelyabinsk-aloe-pole',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 55.160112,
    longitude: 61.391901,
  },
  {
    name: 'Набережная реки Миасс',
    desc: 'Бесплатная смотровая у музея и филармонии. Весной лучшие долгие прогулки без летней пыли и жары.',
    address: 'набережная реки Миасс',
    locationSlug: 'chelyabinsk-naberezhnaya-reki-miass',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 55.167212,
    longitude: 61.399812,
  },
  {
    name: 'Изумрудный (Смолинский) карьер',
    desc: 'Бирюзовая вода в карьере. В мае - сап и лодки, летом пляж.',
    address: 'Смолинский карьер',
    locationSlug: 'chelyabinsk-izumrudnyy-karer',
    mustSeeFilter: 'views',
    visitMinutes: 90,
    latitude: 55.092512,
    longitude: 61.341212,
  },
  {
    name: 'Сад Победы',
    desc: 'Уличная танковая выставка под открытым небом, бесплатно и круглосуточно.',
    address: 'Сад Победы',
    locationSlug: 'chelyabinsk-sad-pobedy',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 55.160512,
    longitude: 61.412812,
  },
  {
    name: 'Парк Пушкина',
    desc: 'Теневой городской парк для паузы между центром и Алым полем.',
    address: 'парк Пушкина',
    locationSlug: 'chelyabinsk-park-pushkina',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 55.161812,
    longitude: 61.385212,
  },
  {
    name: 'Смотровая «Челябинск-Сити»',
    desc: '23-й этаж делового центра на Кирова, 159 - панорама Кировки и площади Революции.',
    address: 'ул. Кирова, 159',
    locationSlug: 'chelyabinsk-chelyabinsk-siti',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 55.161512,
    longitude: 61.401212,
  },
  {
    name: 'Площадь Искусств',
    desc: 'Площадь у Труда: пассаж, «Венский вальс» и выход к набережной Миасса.',
    address: 'площадь Искусств / ул. Труда',
    locationSlug: 'chelyabinsk-ploschad-iskusstv',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 55.167512,
    longitude: 61.402812,
  },

  // --- Театры, гастро и креатив (40-50) ---
  {
    name: 'Камерный театр',
    desc: 'Драма в усадьбе Бреслиных на Цвиллинга, 15 - камерная сцена в доме позднего модерна.',
    address: 'ул. Цвиллинга, 15',
    venueSlug: 'chelyabinsk-kamernyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 55.165847,
    longitude: 61.404314,
  },
  {
    name: 'Молодежный театр / ТЮЗ',
    desc: 'ТЮЗ на Кирова, 116, рядом со скульптурой «Нищий».',
    address: 'ул. Кирова, 116',
    venueSlug: 'chelyabinsk-tyuz',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 55.164901,
    longitude: 61.401891,
  },
  {
    name: 'Белый рынок',
    desc: 'Террасы, фермерские прилавки и вечерняя гастрономия на Тернопольской, 6. Летом город уходит сюда с Кировки.',
    address: 'ул. Тернопольская, 6',
    locationSlug: 'chelyabinsk-belyy-rynok',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 55.154212,
    longitude: 61.375412,
  },
  {
    name: 'Ресторан «Купеческий»',
    desc: 'Уральская кухня на Кирова, 110: пельмени трех мяс, дичь и пироги со снытью.',
    address: 'ул. Кирова, 110',
    locationSlug: 'chelyabinsk-restoran-kupecheskiy',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 55.165412,
    longitude: 61.401612,
  },
  {
    name: '«По Чесноку»',
    desc: 'Локальная кухня на Свердловском, 51А - современная подача таежной ДНК.',
    address: 'Свердловский проспект, 51А',
    locationSlug: 'chelyabinsk-po-chesnoku',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 55.161812,
    longitude: 61.394212,
  },
  {
    name: 'Кластер «Свечка»',
    desc: 'Креативный двор на Воровского, 11А: бары, мастерские и неофициальный вечерний Челябинск.',
    address: 'ул. Воровского, 11А',
    locationSlug: 'chelyabinsk-svechka',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 55.154912,
    longitude: 61.397912,
  },
  {
    name: 'Театр кукол «Вольховский»',
    desc: 'Кукольная сцена на Кирова, 8, у северной кромки пешеходной улицы.',
    address: 'ул. Кирова, 8',
    venueSlug: 'chelyabinsk-teatr-kukol-volkhovskiy',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 55.171812,
    longitude: 61.399212,
  },
  {
    name: 'Кофейня UDOBNO',
    desc: 'Кофейная пауза на Ленина, 61 между Алым полем и Белым рынком.',
    address: 'ул. Ленина, 61',
    locationSlug: 'chelyabinsk-kofeynya-udobno',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 55.157812,
    longitude: 61.400612,
  },
  {
    name: 'Бар «Тортуга»',
    desc: 'Неофициальный бар на Труда, 161 - двор без вывески, куда ходят свои.',
    address: 'ул. Труда, 161',
    locationSlug: 'chelyabinsk-bar-tortuga',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 55.170212,
    longitude: 61.392812,
  },
  {
    name: 'Пивоварня «Брудершафт»',
    desc: 'Крафт на Свердловском, 51Б, сосед «По Чесноку».',
    address: 'Свердловский проспект, 51Б',
    locationSlug: 'chelyabinsk-brudershaft',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 55.161912,
    longitude: 61.394512,
  },
  {
    name: 'Органный зал «Родина»',
    desc: 'Концертный орган в историческом кинотеатре на Кирова, 78.',
    address: 'ул. Кирова, 78',
    venueSlug: 'chelyabinsk-organnyy-zal-rodina',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.167212,
    longitude: 61.400512,
  },
];

export const CHELYABINSK_SUBURBS: any[] = [
  {
    name: 'Таганай / Двуглавая сопка',
    desc: 'Национальный парк у Златоуста: Центральная усадьба, Тёщин язык, Большая Каменная река, Белый ключ, лестница в 200 ступеней, скалы «Перья» и метеостанция. Верхняя тропа от усадьбы, железную лестницу к Перьям оставьте напоследок.',
    locationSlug: 'chelyabinsk-taganay',
    mustSeeFilter: 'main',
    visitMinutes: '7-8 ч',
    latitude: 55.221412,
    longitude: 59.731901,
    address: 'Челябинская обл., Златоуст, НП «Таганай»',
    travelVector: 'Авто ~2 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль около 2 часов, чтобы приехать к 09:00 утра к Центральной усадьбе.',
    timingNote:
      'Верхняя тропа от Центральной усадьбы. Железную лестницу к скалам «Перья» оставьте напоследок.',
    places: [
      {
        name: 'Центральная усадьба НП «Таганай»',
        desc: 'Старт маршрута: визит-центр, тропы и короткая подготовка к подъему.',
        locationSlug: 'chelyabinsk-taganay-usadba',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 25,
      },
      {
        name: 'Тёщин язык',
        desc: 'Каменный останец у начала верхней тропы.',
        locationSlug: 'chelyabinsk-taganay-teschin-yazyk',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 20,
      },
      {
        name: 'Большая Каменная река',
        desc: 'Курум из кварцитов - каменная река без воды, главная видовая пауза трека.',
        locationSlug: 'chelyabinsk-taganay-kamennaya-reka',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 40,
      },
      {
        name: 'Белый ключ',
        desc: 'Родник на склоне, пауза перед лестницей.',
        locationSlug: 'chelyabinsk-taganay-belyy-klyuch',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 15,
      },
      {
        name: 'Лестница в 200 ступеней',
        desc: 'Крутой подъем к гребню Двуглавой сопки.',
        locationSlug: 'chelyabinsk-taganay-lestnitsa',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 25,
      },
      {
        name: 'Скалы «Перья»',
        desc: 'Финал: останцы на гребне. Железную лестницу к ним оставьте напоследок.',
        locationSlug: 'chelyabinsk-taganay-perya',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 30,
      },
      {
        name: 'Метеостанция',
        desc: 'Высокогорная метеостанция на хребте - ориентир после Перьев.',
        locationSlug: 'chelyabinsk-taganay-meteostantsiya',
        address: 'Челябинская обл., Златоуст, НП «Таганай»',
        latitude: 55.221412,
        longitude: 59.731901,
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Тургояк / остров Веры',
    desc: '«Младший брат Байкала»: прозрачное озеро у Миасса, лодка на западный мыс острова Веры, дольмены и экотропа. Пляж, мегалит 1, менгиры, старообрядческий скит, скала «Символ веры» и бухта тримаранов.',
    locationSlug: 'chelyabinsk-turgoyak',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 55.158912,
    longitude: 60.101112,
    address: 'Челябинская обл., Миасс, озеро Тургояк',
    travelVector: 'Авто ~1,5 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль около 1,5 часов до Миасса, чтобы быть у причала к 09:30.',
    timingNote:
      'Лодка на западный мыс острова Веры к дольменам. Напоследок - экотропа и бухта тримаранов.',
    places: [
      {
        name: 'Пляж Тургояка',
        desc: 'Оборудованный берег прозрачного озера, старт лодок на остров Веры.',
        locationSlug: 'chelyabinsk-turgoyak-plyazh',
        address: 'Челябинская обл., Миасс, озеро Тургояк',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 30,
      },
      {
        name: 'Мегалит 1 на острове Веры',
        desc: 'Главный мегалитический комплекс западного мыса.',
        locationSlug: 'chelyabinsk-turgoyak-megalit-1',
        address: 'Челябинская обл., Миасс, остров Веры',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 30,
        transitTip: 'Лодка на западный мыс',
      },
      {
        name: 'Менгиры',
        desc: 'Каменные столбы рядом с мегалитом 1.',
        locationSlug: 'chelyabinsk-turgoyak-mengiry',
        address: 'Челябинская обл., Миасс, остров Веры',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 15,
      },
      {
        name: 'Старообрядческий скит',
        desc: 'Следы скита на острове - тихая точка после мегалитов.',
        locationSlug: 'chelyabinsk-turgoyak-skit',
        address: 'Челябинская обл., Миасс, остров Веры',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 20,
      },
      {
        name: 'Скала «Символ веры»',
        desc: 'Скальный выход на береговой линии острова.',
        locationSlug: 'chelyabinsk-turgoyak-simvol-very',
        address: 'Челябинская обл., Миасс, остров Веры',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 15,
      },
      {
        name: 'Бухта тримаранов',
        desc: 'Тихая бухта, где швартуются лодки и тримараны.',
        locationSlug: 'chelyabinsk-turgoyak-buhta-trimaranov',
        address: 'Челябинская обл., Миасс, озеро Тургояк',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 20,
      },
      {
        name: 'Экотропа',
        desc: 'Береговая экотропа вокруг острова и мыса.',
        locationSlug: 'chelyabinsk-turgoyak-ekotropa',
        address: 'Челябинская обл., Миасс, остров Веры',
        latitude: 55.158912,
        longitude: 60.101112,
        visitMinutes: 40,
      },
    ],
  },
  {
    name: 'Аркаим / Уральская Троя',
    desc: 'Культовый степной выезд к укрепленному поселению эпохи средней бронзы - стране городов, парку древней цивилизации и музею реконструкций.',
    locationSlug: 'chelyabinsk-arkaim',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 52.648912,
    longitude: 59.541112,
    address: 'Челябинская обл., Брединский район, пос. Амурский',
    travelVector: 'Авто или экскурсионный автобус ~4 часа',
    travelVectorBlurb:
      'Закладывайте на автомобиль или экскурсионный автобус ~4 часа, чтобы приехать к 11:00 утра.',
    timingNote:
      'По открытым степным экотропам археологического комплекса двигайтесь к кургану Темир и Шаман-горе, напоследок оставив встречу заката на высшей точке горы Покаяния.',
    places: [
      {
        name: 'Музей воссозданного поселения Аркаим',
        desc: 'Интерактивные залы с макетами оборонительных стен и подлинными артефактами раскопок.',
        locationSlug: 'chelyabinsk-arkaim-muzey-vosssozdanogo-poseleniya',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 60,
      },
      {
        name: 'Курган «Темир»',
        desc: 'Полноразмерная точная реконструкция родовой усыпальницы кочевников раннего железного века.',
        locationSlug: 'chelyabinsk-arkaim-kurgan-temir',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 25,
      },
      {
        name: 'Шаман-гора (Лысая)',
        desc: 'Священный холм с выложенной из камней спиралью желаний на вершине.',
        locationSlug: 'chelyabinsk-arkaim-gora-shamanka-lysaya',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 20,
      },
      {
        name: 'Поселок медного века (реконструкция)',
        desc: 'Глинобитные и деревянные жилища древних металлургов Южного Урала.',
        locationSlug: 'chelyabinsk-arkaim-poselok-mednogo-veka',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 35,
      },
      {
        name: 'Историческая ветряная мельница',
        desc: 'Подлинная деревянная мельница начала XX века, перенесенная из казачьего хутора.',
        locationSlug: 'chelyabinsk-arkaim-vetryanaya-melnitsa',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 20,
      },
      {
        name: 'Музей природы и человека',
        desc: 'Экспозиция редких минералов степи и скелетов доисторических животных.',
        locationSlug: 'chelyabinsk-arkaim-muzey-prirody-i-cheloveka',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 35,
      },
      {
        name: 'Гора Разума',
        desc: 'Одиночный скалистый холм для медитаций и закатных фото.',
        locationSlug: 'chelyabinsk-arkaim-gora-razuma',
        address: 'Челябинская обл., Брединский район, пос. Амурский',
        latitude: 52.648912,
        longitude: 59.541112,
        visitMinutes: 25,
      },
    ],
  },
  {
    name: 'Озеро Увильды (Жемчужина уральских курортов)',
    desc: 'Семейный курорт у глубочайшего озера Южного Урала: радоновые источники, грязи, сосновый лес и прозрачные воды Увильдов.',
    locationSlug: 'chelyabinsk-uvildy',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 55.518912,
    longitude: 60.501112,
    address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
    travelVector: 'Авто или пригородный автобус ~1 час 15 минут',
    travelVectorBlurb:
      'Закладывайте на автомобиль или рейсовый пригородный автобус ~1 час 15 минут, чтобы приехать к 09:30 утра.',
    timingNote:
      'По тенистым тропам песчаных пляжей двигайтесь к скалистым мысам Стрелки, напоследок оставив экскурсию на катере к затерянному острову Вязовый.',
    places: [
      {
        name: 'Центральный пляж курорта «Увильды»',
        desc: 'Благоустроенная песчано-галечная коса с пирсами и прокатом лодок.',
        locationSlug: 'chelyabinsk-uvildy-tsentralnyy-plyazh',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 60,
      },
      {
        name: 'Остров «Вязовый»',
        desc: 'Заповедный остров посреди озера с рощей вековых южных вязов.',
        locationSlug: 'chelyabinsk-uvildy-ostrov-vyazovyy',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 45,
      },
      {
        name: 'Радоновый питьевой бювет',
        desc: 'Павильон с целебной минеральной водой из глубоких подземных скважин.',
        locationSlug: 'chelyabinsk-uvildy-radonovyy-byuvet',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 20,
      },
      {
        name: 'Мыс «Красный»',
        desc: 'Живописный скалистый выступ, поросший вековыми соснами.',
        locationSlug: 'chelyabinsk-uvildy-mys-krasnyy',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 25,
      },
      {
        name: 'Остров «Голодай»',
        desc: 'Уединенный лесной остров для стоянок яхт и палаточного отдыха.',
        locationSlug: 'chelyabinsk-uvildy-ostrov-golodai',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 35,
      },
      {
        name: 'Лесное озеро «Малое Увильды»',
        desc: 'Чистый залив в западной части озера, окруженный зарослями кувшинок.',
        locationSlug: 'chelyabinsk-uvildy-lesnoe-ozero-maloe-uvildy',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 25,
      },
      {
        name: 'Экотропа «Увильдинские зори»',
        desc: 'Пешеходный грунтовый маршрут по сосново-березовому бору вдоль берега.',
        locationSlug: 'chelyabinsk-uvildy-ekotropa-uvildinskie-zori',
        address: 'Челябинская обл., Кыштымский городской округ, пос. Увильды',
        latitude: 55.518912,
        longitude: 60.501112,
        visitMinutes: 60,
      },
    ],
  },
  {
    name: 'Национальный парк «Зюраткуль» (Горное сердце Урала)',
    desc: 'Уникальный высокогорный парк Урала: альпийские луга, темнохвойная тайга, курумы и виды на озера с высоты более 700 метров.',
    locationSlug: 'chelyabinsk-zyuratkul',
    mustSeeFilter: 'main',
    visitMinutes: '7-8 ч',
    latitude: 54.913112,
    longitude: 59.222312,
    address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
    travelVector: 'Автомобиль повышенной проходимости ~2,5 часа',
    travelVectorBlurb:
      'Закладывайте на автомобиль повышенной проходимости ~2,5 часа, чтобы приехать к 09:00 утра.',
    timingNote:
      'По деревянной экологической тропе сквозь таежный бор двигайтесь строго вверх к скалам-останцам, напоследок оставив закат на берегу самого высокогорного озера Урала.',
    places: [
      {
        name: 'Высокогорное озеро «Зюраткуль»',
        desc: 'Чистейший водоем в окружении грозных горных хребтов.',
        locationSlug: 'chelyabinsk-zyuratkul-vysokogornoe-ozero',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 45,
      },
      {
        name: 'Экотропа на хребет Зюраткуль',
        desc: 'Длинная деревянная пешеходная мостовая (около 6 км) для комфортного подъема на гору.',
        locationSlug: 'chelyabinsk-zyuratkul-ekotropa-na-hrebet',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 120,
      },
      {
        name: 'Скалы-останцы «Медведи»',
        desc: 'Каменные столбы на вершине хребта (около 1175 метров) с круговой панорамой тайги.',
        locationSlug: 'chelyabinsk-zyuratkul-skaly-medvedi',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 30,
      },
      {
        name: 'Мараловая ферма',
        desc: 'Питомник, где можно с рук покормить благородных оленей (маралов).',
        locationSlug: 'chelyabinsk-zyuratkul-maralovaya-ferma',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 30,
      },
      {
        name: 'Кипящий ключ',
        desc: 'Оборудованный таежный родник с кристально ледяной бурлящей водой.',
        locationSlug: 'chelyabinsk-zyuratkul-kipyashchiy-klyuch',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 20,
      },
      {
        name: 'Река Большая Сатка',
        desc: 'Горная река, берущая начало из озера, с каскадами небольших порогов.',
        locationSlug: 'chelyabinsk-zyuratkul-reka-bolshaya-satka',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 30,
      },
      {
        name: 'Гора Лукаш',
        desc: 'Одиночная скалистая вершина на противоположном берегу озера.',
        locationSlug: 'chelyabinsk-zyuratkul-gora-lukash',
        address: 'Челябинская обл., Саткинский район, Национальный парк «Зюраткуль»',
        latitude: 54.913112,
        longitude: 59.222312,
        visitMinutes: 20,
      },
    ],
  },
];

export const CHELYABINSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'chelyabinsk-cosmic-arbat',
    title: 'Космический пришелец и Уральский Арбат',
    description:
      'Классический день: Кировка и пассаж Яушевых, опера, набережная Миасса, метеорит в историческом музее, органный зал «Родина» и ужин в «Купеческом».',
    travelVector: 'Пешеходный центр и набережная',
    timingNote:
      'Около 5 часов: Кировка / Яушевы - опера - набережная Миасса - метеорит - «Родина» - «Купеческий».',
    stops: [
      {
        name: 'Кировка и пассаж Яушевых',
        desc: '30 минут на купеческий старт, «Венский вальс» и бронзу Арбата.',
        locationSlug: 'chelyabinsk-passage-yaushevyh',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        address: 'ул. Труда, 92А',
        latitude: 55.168112,
        longitude: 61.402312,
      },
      {
        name: 'Театр оперы и балета им. Глинки',
        desc: '15 минут на фасад и памятник Глинке.',
        venueSlug: 'chelyabinsk-teatr-opery-glinki',
        mustSeeFilter: 'creative',
        visitMinutes: 15,
        address: 'пл. Ярославского, 1',
        latitude: 55.166912,
        longitude: 61.401112,
        transitTip: 'Пешком 4 минуты',
      },
      {
        name: 'Набережная реки Миасс',
        desc: '25 минут на бесплатную смотровую у музея.',
        locationSlug: 'chelyabinsk-naberezhnaya-reki-miass',
        mustSeeFilter: 'views',
        visitMinutes: 25,
        address: 'набережная реки Миасс',
        latitude: 55.167212,
        longitude: 61.399812,
        transitTip: 'Пешком 6 минут',
      },
      {
        name: 'Исторический музей / метеорит',
        desc: 'Час на главный космический экспонат города.',
        venueSlug: 'chelyabinsk-gosudarstvennyy-istoricheskiy-muzey-yuzhnogo-urala',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'ул. Труда, 100',
        latitude: 55.167512,
        longitude: 61.400412,
        transitTip: 'Пешком 2 минуты',
      },
      {
        name: 'Органный зал «Родина»',
        desc: '20 минут на фасад кинотеатра и афишу органа, вечером стоит зайти на концерт.',
        venueSlug: 'chelyabinsk-organnyy-zal-rodina',
        mustSeeFilter: 'creative',
        visitMinutes: 20,
        address: 'ул. Кирова, 78',
        latitude: 55.167212,
        longitude: 61.400512,
        transitTip: 'Пешком 8 минут по Кировке',
      },
      {
        name: 'Ресторан «Купеческий»',
        desc: 'Ужин: пельмени трех мяс и уральская дичь.',
        locationSlug: 'chelyabinsk-restoran-kupecheskiy',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Кирова, 110',
        latitude: 55.165412,
        longitude: 61.401612,
        transitTip: 'Пешком 5 минут',
      },
    ],
  },
  {
    id: 'chelyabinsk-constructivism-market',
    title: 'Конструктивизм, Алое поле и Белый рынок',
    description:
      'День индустриального центра: дом облисполкома, Алое поле и Невский, кофе UDOBNO, элеватор и финал на террасах Белого рынка.',
    travelVector: 'Ампир, парк и гастро-рынок',
    timingNote:
      'Около 4 часов: облисполком - Алое поле / Невский - UDOBNO - элеватор - Белый рынок.',
    stops: [
      {
        name: 'Дом облисполкома',
        desc: '15 минут на сталинский ансамбль Ленина, 54.',
        locationSlug: 'chelyabinsk-dom-oblispolkoma',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'ул. Ленина, 54',
        latitude: 55.159412,
        longitude: 61.402012,
      },
      {
        name: 'Алое поле и храм Александра Невского',
        desc: '40 минут на парк, «Орленка» и краснокирпичный храм.',
        locationSlug: 'chelyabinsk-aloe-pole',
        mustSeeFilter: 'park',
        visitMinutes: 40,
        address: 'Алое поле, 1',
        latitude: 55.160112,
        longitude: 61.391901,
        transitTip: 'Пешком 12 минут',
      },
      {
        name: 'Кофейня UDOBNO',
        desc: '20 минут на кофе перед элеватором.',
        locationSlug: 'chelyabinsk-kofeynya-udobno',
        mustSeeFilter: 'gastro',
        visitMinutes: 20,
        address: 'ул. Ленина, 61',
        latitude: 55.157812,
        longitude: 61.400612,
        transitTip: 'Пешком 10 минут',
      },
      {
        name: 'Элеватор Госбанка',
        desc: '20 минут на готический силуэт зернохранилища с Кирова, 130Р.',
        locationSlug: 'chelyabinsk-elevator',
        mustSeeFilter: 'houses',
        visitMinutes: 20,
        address: 'ул. Кирова, 130Р',
        latitude: 55.163412,
        longitude: 61.400812,
        transitTip: 'Пешком 8 минут',
      },
      {
        name: 'Белый рынок',
        desc: 'Час на террасы, фермерские прилавки и ужин.',
        locationSlug: 'chelyabinsk-belyy-rynok',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Тернопольская, 6',
        latitude: 55.154212,
        longitude: 61.375412,
        transitTip: 'Трамвай или такси 15 минут',
      },
    ],
  },
  ...CHELYABINSK_LINE_DAY_ROUTE_PRESETS,
];

export const CHELYABINSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как попасть на экскурсию по «Высоте 239»?',
    a: 'Это действующий цех Челябинского трубопрокатного завода, а не музей выходного дня. Запись на промышленный тур заранее, паспорт, закрытая обувь и каска на месте. Спонтанно с Кировки не пройти: группы собирают через заводской визит-центр и партнеров ЧТПЗ.',
  },
  {
    q: 'Правда ли, что в городском бору живут ручные лисы?',
    a: 'Лисы в реликтовом Челябинском бору встречаются, но кормить их нельзя: звери дикие, привыкание к еде людей опасно и для них, и для гостей. Белок у памятника Курчатову в парке Гагарина смотреть можно - они давно привыкли к людям, но лучше не совать руки в морду.',
  },
  {
    q: 'Где в Челябинске метро?',
    a: 'Подземное метро так и не достроили. Вместо него работает метротрам: скоростной трамвай с подземными участками. Для гостя это обычный городской транспорт по транспортной карте, не отдельная достопримечательность вроде московского метро.',
  },
  {
    q: 'Куда идти вечером, если не хочется сетевых баров?',
    a: 'Неофициальный контур - бар «Тортуга» на Труда, 161 и кластер «Свечка» на Воровского, 11А. Дворы без кричащих вывесок, свои и креатив. На Красной линии они стоят рядом с UDOBNO и Белым рынком.',
  },
];

export const CHELYABINSK_TRAVEL =
  'Аэропорт имени Игоря Курчатова: прямые рейсы из Москвы около 2,5 часов, также Петербург и крупные хабы. Южно-Уральская железная дорога и трасса М-5. Зима: скрипучий снег, солнце и около -12...-16 °C, сноуборд в «Солнечной долине» у города, большой каток в парке Гагарина среди старых сосен; улицы чистят быстро, мороз пережидают в ресторанах уральской кухни. Весна: апрель сбрасывает зиму, в мае +15...+18 °C - лучшие долгие прогулки по историческим улицам и набережной Миасса без летней пыли и жары; в мае сап и лодки на Изумрудном карьере. Лето: ярко, сухо, часто +30 °C, на Кировке плавится асфальт; город уходит на террасы Белого рынка и пляжи Смолино, Тургояка, Увильдов. Лучшая логистика для однодневных выездов на Таганай и Зюраткуль. Осень: в сентябре бабье лето около +15 °C, в октябре реликтовый городской бор золотеет. Самая дешевая логистика: меньше транзитных туристов к озерам, билеты на поезда и цены отелей падают.';
