/**
 * Hub must-see covers for Ufa / Novosibirsk (identity pack + unique stills).
 * Unique files win; remaining slugs share identity-*.jpg so cards are never empty.
 */

const UFA_SYM = '/images/venues/ufa/identity-symbol.jpg';
const UFA_ART = '/images/venues/ufa/identity-art.jpg';
const UFA_GAS = '/images/venues/ufa/identity-gastro.jpg';
const UFA_ARC = '/images/venues/ufa/identity-architecture.jpg';
const UFA_SAL = '/images/venues/ufa/pamyatnik-salavatu-yulaevu.jpg';
const UFA_DRU = '/images/venues/ufa/monument-druzhby.jpg';
const UFA_GOST = '/images/venues/ufa/gostinyy-dvor.jpg';
const UFA_LAL = '/images/venues/ufa/mechet-medrese-lyalya-tyul-pan.jpg';
const UFA_KVAD = '/images/venues/ufa/art-kvadrat.jpg';
const UFA_FONT = '/images/venues/ufa/fontan-sem-devushek.jpg';

export const UFA_HUB_IMAGES: Record<string, string> = {
  'ufa-aibat-hallyar': '/images/venues/ufa/aibat-hallyar.jpg',
  'ufa-art-kvadrat': '/images/venues/ufa/art-kvadrat.jpg',
  'ufa-art-obyekt-tri-shurupa': '/images/venues/ufa/art-obyekt-tri-shurupa.jpg',
  'ufa-bashkirskiy-teatr-dramy-gafuri': '/images/venues/ufa/bashkirskiy-teatr-dramy-gafuri.jpg',
  'ufa-bashkirskiy-teatr-opery-i-baleta': '/images/venues/ufa/bashkirskiy-teatr-opery-i-baleta.jpg',
  'ufa-dom-gubernatora': '/images/venues/ufa/dom-gubernatora.jpg',
  'ufa-dom-kommuna': '/images/venues/ufa/dom-kommuna.jpg',
  'ufa-dom-muzey-aksakova': '/images/venues/ufa/dom-muzey-aksakova.jpg',
  'ufa-dom-muzey-lenina': '/images/venues/ufa/dom-muzey-lenina.jpg',
  'ufa-dom-ponosovoy-mollo': '/images/venues/ufa/dom-ponosovoy-mollo.jpg',
  'ufa-dom-shamovyh': '/images/venues/ufa/dom-shamovyh.jpg',
  'ufa-dom-soyuzov': '/images/venues/ufa/dom-soyuzov.jpg',
  'ufa-fontan-sem-devushek': '/images/venues/ufa/fontan-sem-devushek.jpg',
  'ufa-gostinyy-dvor': '/images/venues/ufa/gostinyy-dvor.jpg',
  'ufa-hudozhestvennyy-muzey-nesterova': '/images/venues/ufa/hudozhestvennyy-muzey-nesterova.jpg',
  'ufa-kongress-holl-toratau': '/images/venues/ufa/kongress-holl-toratau.jpg',
  'ufa-kumpan-cafe': '/images/venues/ufa/kumpan-cafe.jpg',
  'ufa-matcha-komnata': '/images/venues/ufa/matcha-komnata.jpg',
  'ufa-mechet-ihlas': '/images/venues/ufa/mechet-ihlas.jpg',
  'ufa-mechet-medrese-lyalya-tyul-pan': '/images/venues/ufa/mechet-medrese-lyalya-tyul-pan.jpg',
  'ufa-monument-druzhby': '/images/venues/ufa/monument-druzhby.jpg',
  'ufa-musichall27': '/images/venues/ufa/musichall27.jpg',
  'ufa-muzey-arheologii-i-etnografii': '/images/venues/ufa/muzey-arheologii-i-etnografii.jpg',
  'ufa-muzey-boevoy-slavy': '/images/venues/ufa/muzey-boevoy-slavy.jpg',
  'ufa-muzey-roka-kinoteatr-rodina': '/images/venues/ufa/muzey-roka-kinoteatr-rodina.jpg',
  'ufa-natsionalnyy-muzey': '/images/venues/ufa/natsionalnyy-muzey.jpg',
  'ufa-novaya-ufimskaya-naberezhnaya': '/images/venues/ufa/novaya-ufimskaya-naberezhnaya.jpg',
  'ufa-osobnyak-kosterina-i-chernikova': '/images/venues/ufa/osobnyak-kosterina-i-chernikova.jpg',
  'ufa-pamyatnik-akmulle': '/images/venues/ufa/pamyatnik-akmulle.jpg',
  'ufa-pamyatnik-dvorniku': '/images/venues/ufa/pamyatnik-dvorniku.jpg',
  'ufa-pamyatnik-fedoru-shalyapinu': '/images/venues/ufa/pamyatnik-fedoru-shalyapinu.jpg',
  'ufa-pamyatnik-generalu-shaymuratovu': '/images/venues/ufa/pamyatnik-generalu-shaymuratovu.jpg',
  'ufa-pamyatnik-geroyam-oktyabrskoy-revolyutsii': '/images/venues/ufa/pamyatnik-geroyam-oktyabrskoy-revolyutsii.jpg',
  'ufa-pamyatnik-kunitse': '/images/venues/ufa/pamyatnik-kunitse.jpg',
  'ufa-pamyatnik-leninu': '/images/venues/ufa/pamyatnik-leninu.jpg',
  'ufa-pamyatnik-mustayu-karimu': '/images/venues/ufa/pamyatnik-mustayu-karimu.jpg',
  'ufa-pamyatnik-pushkinu': '/images/venues/ufa/pamyatnik-pushkinu.jpg',
  'ufa-pamyatnik-salavatu-yulaevu': '/images/venues/ufa/pamyatnik-salavatu-yulaevu.jpg',
  'ufa-pamyatnik-salavatu-yulaevu-u-gossobraniya': '/images/venues/ufa/pamyatnik-salavatu-yulaevu-u-gossobraniya.jpg',
  'ufa-pamyatnik-zemlyakam-ushedshim-na-front': '/images/venues/ufa/pamyatnik-zemlyakam-ushedshim-na-front.jpg',
  'ufa-park-mazhita-gafuri': '/images/venues/ufa/park-mazhita-gafuri.jpg',
  'ufa-park-pobedy': '/images/venues/ufa/park-pobedy.jpg',
  'ufa-pervaya-sobornaya-mechet': '/images/venues/ufa/pervaya-sobornaya-mechet.jpg',
  'ufa-pokrovskiy-hram': '/images/venues/ufa/pokrovskiy-hram.jpg',
  'ufa-rozhdestvo-bogoroditskiy-hram': '/images/venues/ufa/rozhdestvo-bogoroditskiy-hram.jpg',
  'ufa-sad-aksakova': '/images/venues/ufa/sad-aksakova.jpg',
  'ufa-sergievskiy-kafedralnyy-sobor': '/images/venues/ufa/sergievskiy-kafedralnyy-sobor.jpg',
  'ufa-shulgan-tash': '/images/venues/ufa/shulgan-tash.jpg',
  'ufa-shulgan-tash-goluboe-ozero': '/images/venues/ufa/shulgan-tash-goluboe-ozero.jpg',
  'ufa-shulgan-tash-koloda-bort': '/images/venues/ufa/shulgan-tash-koloda-bort.jpg',
  'ufa-shulgan-tash-muzey-bortevoy-pchely': '/images/venues/ufa/shulgan-tash-muzey-bortevoy-pchely.jpg',
  'ufa-shulgan-tash-muzeynyy-kompleks': '/images/venues/ufa/shulgan-tash-muzeynyy-kompleks.jpg',
  'ufa-shulgan-tash-portal-kapovoy-peschery': '/images/venues/ufa/shulgan-tash-portal-kapovoy-peschery.jpg',
  'ufa-shulgan-tash-smotrovoy-most': '/images/venues/ufa/shulgan-tash-smotrovoy-most.jpg',
  'ufa-shulgan-tash-zal-naskalnoy-zhivopisi': '/images/venues/ufa/shulgan-tash-zal-naskalnoy-zhivopisi.jpg',
  'ufa-skulptura-dom-kunitsy': '/images/venues/ufa/skulptura-dom-kunitsy.jpg',
  'ufa-sluchevskaya-gora': '/images/venues/ufa/sluchevskaya-gora.jpg',
  'ufa-smotrovaya-u-pamyatnika-salavatu': '/images/venues/ufa/smotrovaya-u-pamyatnika-salavatu.jpg',
  'ufa-spasskiy-hram': '/images/venues/ufa/spasskiy-hram.jpg',
  'ufa-teatr-nur': '/images/venues/ufa/teatr-nur.jpg',
  'ufa-toratau': '/images/venues/ufa/toratau.jpg',
  'ufa-toratau-ekotropa': '/images/venues/ufa/toratau-ekotropa.jpg',
  'ufa-toratau-gulag': '/images/venues/ufa/toratau-gulag.jpg',
  'ufa-toratau-kochevye': '/images/venues/ufa/toratau-kochevye.jpg',
  'ufa-toratau-ozero-tugar-salgan': '/images/venues/ufa/toratau-ozero-tugar-salgan.jpg',
  'ufa-toratau-paraplan': '/images/venues/ufa/toratau-paraplan.jpg',
  'ufa-toratau-vershina': '/images/venues/ufa/toratau-vershina.jpg',
  'ufa-toratau-vizit-tsentr': '/images/venues/ufa/toratau-vizit-tsentr.jpg',
  'ufa-ufimskaya-demidovskaya-preemstvennost': '/images/venues/ufa/ufimskaya-demidovskaya-preemstvennost.jpg',
  'ufa-zdanie-dvoryanskogo-sobraniya': '/images/venues/ufa/zdanie-dvoryanskogo-sobraniya.jpg',
  'ufa-zdanie-krestyanskogo-pozemelnogo-banka': '/images/venues/ufa/zdanie-krestyanskogo-pozemelnogo-banka.jpg',
};

const NSK_SYM = '/images/venues/novosibirsk/identity-symbol.jpg';
const NSK_ART = '/images/venues/novosibirsk/identity-art.jpg';
const NSK_GAS = '/images/venues/novosibirsk/identity-gastro.jpg';
const NSK_ARC = '/images/venues/novosibirsk/identity-architecture.jpg';
const NSK_NOVAT =
  '/images/venues/novosibirsk/novosibirskiy-teatr-opery-i-baleta-novat.jpg';
const NSK_NAB = '/images/venues/novosibirsk/mihaylovskaya-naberezhnaya.jpg';
const NSK_AKAD = '/images/venues/novosibirsk/akademgorodok.jpg';
const NSK_ZOO =
  '/images/venues/novosibirsk/novosibirskiy-zoopark-imeni-r-a-shilo.jpg';
const NSK_ARTM = '/images/venues/novosibirsk/novosibirskiy-hudozhestvennyy-muzey.jpg';
const NSK_POGREB =
  '/images/venues/novosibirsk/muzey-mirovoy-pogrebal-noy-kul-tury.jpg';

export const NOVOSIBIRSK_HUB_IMAGES: Record<string, string> = {
  'novosibirsk-novosibirskiy-teatr-opery-i-baleta-novat': NSK_NOVAT,
  'novosibirsk-mihaylovskaya-naberezhnaya': NSK_NAB,
  'novosibirsk-akademgorodok': NSK_AKAD,
  'novosibirsk-novosibirskiy-zoopark-imeni-r-a-shilo': NSK_ZOO,
  'novosibirsk-novosibirskiy-hudozhestvennyy-muzey': NSK_ARTM,
  'novosibirsk-muzey-mirovoy-pogrebal-noy-kul-tury': NSK_POGREB,
  'novosibirsk-pamyatnik-leninu': NSK_SYM,
  'novosibirsk-pamyatnik-laboratornoy-myshi': NSK_ART,
  'novosibirsk-pamyatnik-svetoforu': NSK_ART,
  'novosibirsk-vovka-v-tridevyatom-tsarstve': NSK_ART,
  'novosibirsk-pamyatnik-tramvayu-13': NSK_ART,
  'novosibirsk-pamyatnik-vysotskomu': NSK_ART,
  'novosibirsk-art-obekt-shpargalka': NSK_ART,
  'novosibirsk-arka-kolokol-mira': NSK_SYM,
  'novosibirsk-pamyatnik-pervomu-svidaniyu': NSK_ART,
  'novosibirsk-stseny-iz-kukolnyh-spektakley': NSK_ART,
  'novosibirsk-skulptura-delovaya-zhenschina': NSK_ART,
  'novosibirsk-pamyatnik-shveynoy-mashinke-zinger': NSK_ART,
  'novosibirsk-pamyatnik-pervomu-mostu': NSK_NAB,
  'novosibirsk-pamyatnik-kryachkovu': NSK_ARC,
  'novosibirsk-pamyatnik-tostu-za-zdravie': NSK_GAS,
  'novosibirsk-stokvartirnyy-dom': NSK_ARC,
  'novosibirsk-dom-lenina': NSK_ARC,
  'novosibirsk-gorodskoy-torgovyy-korpus': NSK_ARC,
  'novosibirsk-osobnyak-kryukova': NSK_ARC,
  'novosibirsk-dom-s-chasami': NSK_ARC,
  'novosibirsk-glavpochtamt': NSK_ARC,
  'novosibirsk-vokzal-novosibirsk-glavnyy': NSK_ARC,
  'novosibirsk-kraevedcheskiy-muzey': NSK_ARC,
  'novosibirsk-muzey-zheleznodorozhnoy-tehniki': NSK_ARC,
  'novosibirsk-muzey-sibirskaya-beresta': NSK_ART,
  'novosibirsk-muzey-solntsa': NSK_ART,
  'novosibirsk-muzey-olimpiyskoy-slavy': NSK_SYM,
  'novosibirsk-sobor-aleksandra-nevskogo': NSK_ARC,
  'novosibirsk-voznesenskiy-sobor': NSK_ARC,
  'novosibirsk-chasovnya-nikolaya': NSK_ARC,
  'novosibirsk-hram-pokrova': NSK_ARC,
  'novosibirsk-katolicheskiy-sobor': NSK_ARC,
  'novosibirsk-datsan-rinchin': NSK_ART,
  'novosibirsk-zaeltsovskiy-park': NSK_SYM,
  'novosibirsk-tsentralnyy-park': NSK_SYM,
  'novosibirsk-skver-geroev-revolyutsii': NSK_SYM,
  'novosibirsk-plyazh-zvezda-obskoe-more': NSK_NAB,
  'novosibirsk-smotrovaya-aura': NSK_SYM,
  'novosibirsk-teatr-globus': NSK_ART,
  'novosibirsk-teatr-krasnyy-fakel': NSK_ART,
  'novosibirsk-tsentr-pobeda': NSK_ART,
  'novosibirsk-restoran-sibir-sibir': NSK_GAS,
  'novosibirsk-gastrokort-tsentralnyy-rynok': NSK_GAS,
  'novosibirsk-barnyy-dvorik-lenina-3': NSK_GAS,
  'novosibirsk-kafe-ip-fedoseev': NSK_GAS,
  'novosibirsk-akvapark': NSK_SYM,
  'novosibirsk-park-chudes-galileo': NSK_ART,
  'novosibirsk-bolshoy-planetariy': NSK_ARC,
  'novosibirsk-delfiniya': NSK_SYM,
  'novosibirsk-suzun': NSK_ARC,
  'novosibirsk-suzun-tolchelnya': NSK_ARC,
  'novosibirsk-suzun-muzey-monetnyy-dvor': NSK_ARC,
  'novosibirsk-suzun-dom-upravlyayuschego': NSK_ARC,
  'novosibirsk-suzun-bor': NSK_SYM,
  'novosibirsk-suzun-pamyatnik-sibirskoy-monete': NSK_ART,
  'novosibirsk-suzun-voznesenskaya-tserkov': NSK_ARC,
  'novosibirsk-suzun-gidrotehnicheskaya-plotina': NSK_SYM,
  'novosibirsk-iskitim-lozhok': '/images/venues/novosibirsk/iskitim-lozhok.jpg',
  'novosibirsk-iskitim-hram-novomuchenikov': NSK_ARC,
  'novosibirsk-iskitim-svyatoy-istochnik': NSK_SYM,
  'novosibirsk-iskitim-kupeli': NSK_SYM,
  'novosibirsk-iskitim-muzey-siblaga': NSK_ARC,
  'novosibirsk-iskitim-poklonnyy-krest': NSK_SYM,
  'novosibirsk-iskitim-ikonnaya-lavka': NSK_ARC,
  'novosibirsk-iskitim-lesnaya-tropa': NSK_SYM,
  'novosibirsk-koltsovo': '/images/venues/novosibirsk/koltsovo.jpg',
  'novosibirsk-koltsovo-park': NSK_SYM,
  'novosibirsk-koltsovo-ozero-s-lebedyami': NSK_SYM,
  'novosibirsk-koltsovo-ckp-biotehnoparka': NSK_ARC,
  'novosibirsk-koltsovo-tropa-zdorovya': NSK_SYM,
  'novosibirsk-koltsovo-alleya-uchenyh': NSK_ART,
  'novosibirsk-koltsovo-pamyatnik-sandukhchanu': NSK_ART,
  'novosibirsk-koltsovo-akademiya-kofe': NSK_GAS,
  'novosibirsk-berdskie-skaly': '/images/venues/novosibirsk/berdskie-skaly.jpg',
  'novosibirsk-berdskie-skaly-zveroboy': NSK_SYM,
  'novosibirsk-berdskie-skaly-urochische-zvereva': NSK_SYM,
  'novosibirsk-berdskie-skaly-stendy-ekotropy': NSK_SYM,
  'novosibirsk-berdskie-skaly-podvesnoy-most-berd': NSK_NAB,
  'novosibirsk-berdskie-skaly-skala-verblyud': NSK_SYM,
  'novosibirsk-berdskie-skaly-serebryanyy-klyuch': NSK_SYM,
  'novosibirsk-berdskie-skaly-zona-otdyha': NSK_SYM,
};

/**
 * Last-resort cover when a hub/catalog slug has no unique still:
 * city identity pack that exists on disk (not cities/*.png).
 */
export const CITY_IDENTITY_FALLBACK: Record<string, string> = {
  chelyabinsk: '/images/venues/chelyabinsk/identity-symbol.jpg',
  novosibirsk: '/images/venues/novosibirsk/identity-symbol.jpg',
  omsk: '/images/venues/omsk/identity-symbol.jpg',
  ryazan: '/images/venues/ryazan/identity-symbol.jpg',
  penza: '/images/venues/penza/pamyatnik-pervoposelentsu.jpg',
  tver: '/images/venues/tver/starovolzhskiy-most.jpg',
  tyumen: '/images/venues/tyumen/identity-symbol.jpg',
  voronezh: '/images/venues/voronezh/identity-symbol.jpg',
  'rostov-na-donu': '/images/venues/rostov-na-donu/naberezhnaya-reki-don-beregovaya-ulitsa.jpg',
  ufa: '/images/venues/ufa/identity-symbol.jpg',
  kazan: '/images/venues/kazan/identity-cultures.jpg',
  samara: '/images/venues/samara/identity-space.jpg',
  krasnodar: '/images/venues/krasnodar/identity-chill.jpg',
  krasnoyarsk: '/images/venues/krasnoyarsk/identity-siberia.jpg',
  ekaterinburg: '/images/venues/ekaterinburg/identity-rock.jpg',
};
