/** Ekaterinburg tourist hub pack (owner 2026-08-15). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export const EKB_MUST_SEE: any[] = [
  // --- Core ---
  {
    name: 'Плотинка (Исторический сквер)',
    desc: 'Сердце города: место основания завода, старинные цеха и прогулка у Исети.',
    address: 'пр. Ленина (Исторический сквер)',
    locationSlug: 'ekaterinburg-plotinka-istoricheskiy-skver',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 56.8385,
    longitude: 60.6028,
  },
  {
    name: 'Храм-на-Крови',
    desc: 'Построен на месте гибели семьи Романовых - одно из главных мест памяти города.',
    address: 'ул. Царская, 10',
    locationSlug: 'ekaterinburg-hram-na-krovi',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 56.8433,
    longitude: 60.6086,
  },
  {
    name: 'Ельцин Центр',
    desc: 'Крупное интерактивное пространство и музей современной истории у Городского пруда.',
    address: 'ул. Бориса Ельцина, 3',
    locationSlug: 'ekaterinburg-el-tsin-tsentr',
    mustSeeFilter: 'museum',
    visitMinutes: 120,
    latitude: 56.8431,
    longitude: 60.5956,
  },
  {
    name: 'Смотровая площадка БЦ «Высоцкий»',
    desc: 'Панорама Екатеринбурга с 52 этажа небоскреба.',
    address: 'ул. Малышева, 51',
    locationSlug: 'ekaterinburg-smotrovaya-ploschadka-bts-vysotskiy',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 56.836106,
    longitude: 60.614605,
  },
  {
    name: 'Городок чекистов',
    desc: 'Жилой комплекс 1930-х в форме серпа и молота - визитка уральского конструктивизма.',
    address: 'пр. Ленина / Первомайская',
    locationSlug: 'ekaterinburg-gorodok-chekistov',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 56.840727,
    longitude: 60.620917,
  },
  {
    name: 'Улица Вайнера',
    desc: 'Пешеходный центр со скульптурами, купеческими фасадами и витринами.',
    address: 'ул. Вайнера',
    locationSlug: 'ekaterinburg-ulitsa-vaynera',
    mustSeeFilter: 'street',
    visitMinutes: 40,
    latitude: 56.8365,
    longitude: 60.5975,
  },

  // --- Monuments ---
  {
    name: 'Памятник Татищеву и де Геннину',
    desc: 'Бронзовый монумент основателям города, отлитый на Уралмаше.',
    address: 'Площадь Труда',
    locationSlug: 'ekaterinburg-pamyatnik-tatischevu-i-de-genninu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.838158,
    longitude: 60.605889,
  },
  {
    name: 'Памятник А. С. Попову',
    desc: 'Чугунная скульптура изобретателя радио на скамейке.',
    address: 'пр. Ленина, 39',
    locationSlug: 'ekaterinburg-pamyatnik-popovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.839619,
    longitude: 60.6078,
  },
  {
    name: 'Бюст Д. Н. Мамина-Сибиряка',
    desc: 'Бронзовый бюст уральского писателя на Плотинке.',
    address: 'пр. Ленина (Исторический сквер)',
    locationSlug: 'ekaterinburg-byust-mamina-sibiryaka',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.838278,
    longitude: 60.602778,
  },
  {
    name: 'Памятник маршалу Жукову',
    desc: 'Конная статуя полководца, командовавшего Уральским военным округом.',
    address: 'пр. Ленина, 71',
    locationSlug: 'ekaterinburg-pamyatnik-zhukovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.841068,
    longitude: 60.624437,
  },
  {
    name: 'Памятник клавиатуре',
    desc: 'Гигантская ландшафтная скульптура из бетона в масштабе 1:30 на набережной Исети.',
    address: 'Набережная реки Исеть (ул. Горького)',
    locationSlug: 'ekaterinburg-pamyatnik-klaviatura',
    mustSeeFilter: 'monument',
    visitMinutes: 30,
    latitude: 56.8298,
    longitude: 60.6125,
  },
  {
    name: 'Памятник П. П. Бажову',
    desc: 'Бюст автора уральских сказов в Литературном квартале.',
    address: 'ул. Пролетарская, 14',
    locationSlug: 'ekaterinburg-pamyatnik-bazhovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.8415,
    longitude: 60.6083,
  },
  {
    name: 'Памятник Высоцкому и Марине Влади',
    desc: 'Бронзовая композиция у небоскреба, посвященная визиту поэта в Свердловск.',
    address: 'ул. Малышева, 51',
    locationSlug: 'ekaterinburg-pamyatnik-vysotskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.8358,
    longitude: 60.6162,
  },
  {
    name: 'Памятник The Beatles',
    desc: 'Один из первых в СНГ чугунных монументов ливерпульской четверке.',
    address: 'ул. Горького, 8',
    locationSlug: 'ekaterinburg-pamyatnik-beatles',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 56.834,
    longitude: 60.606874,
  },
  {
    name: 'Памятник воинам Уральского добровольческого танкового корпуса',
    desc: 'Мемориал на привокзальной площади - фронт и тыл Урала.',
    address: 'Привокзальная площадь',
    locationSlug: 'ekaterinburg-pamyatnik-uralskiy-tankovyy-korpus',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.8583,
    longitude: 60.6042,
  },
  {
    name: 'Памятник Первой учительнице',
    desc: 'Трогательная композиция перед гимназией № 9.',
    address: 'ул. Ленина, 33',
    locationSlug: 'ekaterinburg-pamyatnik-pervoy-uchitelnitse',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.8378,
    longitude: 60.6091,
  },
  {
    name: 'Памятник изобретателям велосипеда (Артамонову)',
    desc: 'Памятник крепостному мастеру Ефиму Артамонову у Плотинки.',
    address: 'Набережная у Плотинки',
    locationSlug: 'ekaterinburg-pamyatnik-artamonovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.8369,
    longitude: 60.6031,
  },
  {
    name: 'Памятник семье Николая II',
    desc: 'Скульптура последнего императора и его семьи у Храма-на-Крови.',
    address: 'ул. Царская, 10',
    locationSlug: 'ekaterinburg-pamyatnik-semye-nikolaya-ii',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.8436,
    longitude: 60.6089,
  },
  {
    name: 'Памятник Мамину-Сибиряку (ул. Пушкина)',
    desc: 'Памятник у дома-музея писателя.',
    address: 'ул. Пушкина, 27',
    locationSlug: 'ekaterinburg-pamyatnik-mamina-sibiryaka-pushkina',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.8342,
    longitude: 60.6108,
  },
  {
    name: 'Памятник братьям Черепановым',
    desc: 'Создателям первого русского паровоза у политехнического музея.',
    address: 'ул. Первомайская',
    locationSlug: 'ekaterinburg-pamyatnik-cherepanovym',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.8402,
    longitude: 60.615,
  },
  {
    name: 'Памятник А. С. Пушкину',
    desc: 'Классический памятник поэту в Литературном сквере.',
    address: 'Литературный квартал (ул. Толмачева)',
    locationSlug: 'ekaterinburg-pamyatnik-pushkinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.8419,
    longitude: 60.6078,
  },

  // --- Museums / heritage ---
  {
    name: 'Дом Севастьянова',
    desc: 'Жемчужина псевдоготики на главной оси города.',
    address: 'пр. Ленина, 35',
    locationSlug: 'ekaterinburg-dom-sevastyanova',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.8372,
    longitude: 60.6094,
  },
  {
    name: 'Екатеринбургский музей изобразительных искусств',
    desc: 'Дом Каслинского чугунного павильона и уральской пластики.',
    address: 'ул. Воеводина, 5',
    locationSlug: 'ekaterinburg-muzey-izobrazitelnyh-iskusstv',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 56.8336,
    longitude: 60.6006,
  },
  {
    name: 'Музей истории науки и техники Свердловской ж/д',
    desc: 'Железнодорожная техника и история магистрали у вокзала.',
    address: 'ул. Вокзальная, 14',
    locationSlug: 'ekaterinburg-muzey-istorii-nauki-i-tehniki-szhd',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 56.8589,
    longitude: 60.605,
  },
  {
    name: 'Музей истории камнерезного и ювелирного искусства',
    desc: 'Уральские камни, резьба и ювелирная школа региона.',
    address: 'пр. Ленина, 37',
    locationSlug: 'ekaterinburg-muzey-kamnereznogo-iskusstva',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 56.8378,
    longitude: 60.6075,
  },
  {
    name: 'Свердловский областной краеведческий музей',
    desc: 'Хранитель Шигирского идола и истории края.',
    address: 'пр. Ленина, 69/10',
    locationSlug: 'ekaterinburg-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 56.8411,
    longitude: 60.6142,
  },
  {
    name: 'Музей радио им. А. С. Попова',
    desc: 'История радиосвязи в городе изобретателя.',
    address: 'ул. Розы Люксембург, 9',
    locationSlug: 'ekaterinburg-muzey-radio-popova',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 56.8317,
    longitude: 60.6178,
  },
  {
    name: 'Дом-музей П. П. Бажова',
    desc: 'Мемориальный дом автора уральских сказов.',
    address: 'ул. Бажова, 11',
    locationSlug: 'ekaterinburg-dom-muzey-bazhova',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 56.8286,
    longitude: 60.6225,
  },
  {
    name: 'Музей архитектуры и дизайна',
    desc: 'Индустриальное наследие и дизайн Урала у набережной.',
    address: 'ул. Горького, 4а',
    locationSlug: 'ekaterinburg-muzey-arhitektury-i-dizayna',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 56.8361,
    longitude: 60.6072,
  },

  // --- Constructivism ---
  {
    name: 'Белая башня',
    desc: 'Шедевр авангарда на Уралмаше: бывшая водонапорная башня, ныне культурный объект.',
    address: 'ул. Бакинских Комиссаров, 2а',
    locationSlug: 'ekaterinburg-belaya-bashnya',
    mustSeeFilter: 'houses',
    visitMinutes: 45,
    latitude: 56.8839,
    longitude: 60.6031,
  },
  {
    name: 'Гостиница «Исеть»',
    desc: 'Символ советского конструктивизма 1933 года на оси Ленина.',
    address: 'пр. Ленина, 69/1',
    locationSlug: 'ekaterinburg-gostinitsa-iset',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.840803,
    longitude: 60.621242,
  },
  {
    name: 'Главпочтамт',
    desc: 'Конструктивистский узел на проспекте Ленина.',
    address: 'пр. Ленина, 39',
    locationSlug: 'ekaterinburg-glavpochtamt',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.839513,
    longitude: 60.608435,
  },
  {
    name: 'Водонапорная башня на Плотинке',
    desc: 'Памятник промышленной архитектуры и музей в Историческом сквере.',
    address: 'ул. Горького, 4в',
    locationSlug: 'ekaterinburg-vodonapornaya-bashnya-plotinka',
    mustSeeFilter: 'main',
    visitMinutes: 30,
    latitude: 56.837892,
    longitude: 60.605469,
  },
  {
    name: 'Стрит-арт «Переход Цоя»',
    desc: 'Подземный рок-переход под проспектом Ленина с легальными муралами.',
    address: 'пр. Ленина (подземный переход у Плотинки)',
    locationSlug: 'ekaterinburg-perekhod-tsoya',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 56.8376,
    longitude: 60.6059,
  },
  {
    name: 'Креативный кластер «Л52»',
    desc: 'Выставки и события в бывшей конструктивистской поликлинике.',
    address: 'ул. Бажова, 124а',
    locationSlug: 'ekaterinburg-l52',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 56.839644,
    longitude: 60.625818,
  },
  {
    name: 'Дом обороны',
    desc: 'Конструктивистский комплекс с самолетом на крыше.',
    address: 'ул. Малышева, 31д',
    locationSlug: 'ekaterinburg-dom-oborony',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 56.835002,
    longitude: 60.601052,
  },
  {
    name: 'Мурал «Уральский барс»',
    desc: 'Крупный уличный мурал во всю стену на 8 Марта.',
    address: 'ул. 8 Марта, 22-24',
    locationSlug: 'ekaterinburg-mural-uralskiy-bars',
    mustSeeFilter: 'creative',
    visitMinutes: 15,
    latitude: 56.831814,
    longitude: 60.600172,
  },
  {
    name: 'Ресторан «Пельмени Клуб»',
    desc: 'Посикунчики и таежные пельмени из дичи - культовый уральский фастфуд.',
    address: 'ул. Красноармейская, 2',
    locationSlug: 'ekaterinburg-pelmeni-klub',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 56.839051,
    longitude: 60.615075,
  },
  {
    name: 'Окружной дом офицеров (ОДО)',
    desc: 'Сталинский ампир со шпилем - доминанта на Луначарского.',
    address: 'ул. Луначарского, 137',
    locationSlug: 'ekaterinburg-okruzhnoy-dom-ofitserov',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.8383,
    longitude: 60.6247,
  },
  {
    name: 'Усадьба Расторгуевых-Харитоновых',
    desc: 'Классическая усадьба с садом в центре.',
    address: 'ул. Карла Либкнехта, 44',
    locationSlug: 'ekaterinburg-usadba-kharitonova-rastorguevyh',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 56.8422,
    longitude: 60.6106,
  },
  {
    name: 'Администрация города (Мэрия)',
    desc: 'Один из узнаваемых фасадов на проспекте Ленина.',
    address: 'пр. Ленина, 24а',
    locationSlug: 'ekaterinburg-meriya',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 56.8378,
    longitude: 60.5975,
  },
  {
    name: 'Белый дом (Правительство СО)',
    desc: 'Советская доминанта на Октябрьской площади.',
    address: 'Октябрьская пл., 1',
    locationSlug: 'ekaterinburg-belyy-dom',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 56.8436,
    longitude: 60.5997,
  },
  {
    name: 'Дом печати',
    desc: 'Конструктивистский корпус на главной оси.',
    address: 'пр. Ленина, 49',
    locationSlug: 'ekaterinburg-dom-pechati',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 56.8394,
    longitude: 60.6097,
  },
  {
    name: 'Главный учебный корпус УрФУ',
    desc: 'Кампусный якорь на ул. Мира.',
    address: 'ул. Мира, 19',
    locationSlug: 'ekaterinburg-urfu-glavnyy-korpus',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.8444,
    longitude: 60.6522,
  },

  // --- Modern / parks ---
  {
    name: 'Квартал Екатеринбург-Сити',
    desc: 'Деловой кластер с высоткой «Исеть» у пруда.',
    address: 'ул. Бориса Ельцина',
    locationSlug: 'ekaterinburg-ekaterinburg-siti',
    mustSeeFilter: 'views',
    visitMinutes: 40,
    latitude: 56.8447,
    longitude: 60.5969,
  },
  {
    name: 'Набережная Рабочей Молодёжи',
    desc: 'Парадный променад вдоль Городского пруда к Сити.',
    address: 'ул. Рабочей Молодёжи',
    locationSlug: 'ekaterinburg-naberezhnaya-rabochey-molodezhi',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 56.842107,
    longitude: 60.598157,
  },
  {
    name: 'ЦПКиО им. Маяковского',
    desc: 'Главный городской парк с аллеями и сезонными событиями.',
    address: 'ул. Мичурина, 230',
    locationSlug: 'ekaterinburg-cpkio-mayakovskogo',
    mustSeeFilter: 'park',
    visitMinutes: '1-2 ч',
    latitude: 56.815,
    longitude: 60.6358,
  },
  {
    name: 'Шарташские каменные палатки',
    desc: 'Гранитные скалы-останцы в Шарташском лесопарке.',
    address: 'Шарташский лесопарк',
    locationSlug: 'ekaterinburg-shartashskie-kamennye-palatki',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 56.8519,
    longitude: 60.6722,
  },
  {
    name: 'Харитоновский сад',
    desc: 'Тихий сад у усадьбы Харитоновых.',
    address: 'ул. Карла Либкнехта / Дзержинского',
    locationSlug: 'ekaterinburg-kharitonovskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 56.8431,
    longitude: 60.6111,
  },
  {
    name: 'Дендрологический парк',
    desc: 'Зеленый оазис в центре на ул. 8 Марта.',
    address: 'ул. 8 Марта, 37а',
    locationSlug: 'ekaterinburg-dendropark',
    mustSeeFilter: 'park',
    visitMinutes: 45,
    latitude: 56.8272,
    longitude: 60.6033,
  },
  {
    name: 'Метеогорка',
    desc: 'Панорамная площадка над городом.',
    address: 'ул. Мира / Бажова',
    locationSlug: 'ekaterinburg-meteogorka',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 56.8333,
    longitude: 60.6333,
  },
  {
    name: 'Парк Уктус',
    desc: 'Лесопарк и зимний спорт в черте города.',
    address: 'ул. Зимняя, 27',
    locationSlug: 'ekaterinburg-park-uktus',
    mustSeeFilter: 'park',
    visitMinutes: '1-2 ч',
    latitude: 56.7869,
    longitude: 60.6431,
  },

  // --- Culture / gastro / night ---
  {
    name: 'Урал Опера Балет',
    desc: 'Главная оперно-балетная сцена Урала.',
    address: 'пр. Ленина, 46а',
    locationSlug: 'ekaterinburg-ural-opera-balet',
    mustSeeFilter: 'museum',
    visitMinutes: 30,
    latitude: 56.8389,
    longitude: 60.6111,
  },
  {
    name: 'Коляда-Театр',
    desc: 'Авторский театр Николая Коляды.',
    address: 'пр. Ленина, 97',
    locationSlug: 'ekaterinburg-kolyada-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 56.8428,
    longitude: 60.6231,
  },
  {
    name: 'Джаз-клуб EverJazz',
    desc: 'Первый профессиональный джаз-клуб города с живым звуком.',
    address: 'ул. Тургенева, 22',
    locationSlug: 'ekaterinburg-everjazz',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 56.8419,
    longitude: 60.6094,
  },
  {
    name: 'Гастро-рынок Estory',
    desc: 'Фуд-холл в «Гринвиче» с локальными и мировыми кухнями.',
    address: 'ул. 8 Марта, 46 (ТРЦ «Гринвич»)',
    locationSlug: 'ekaterinburg-estory',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 56.8281,
    longitude: 60.6067,
  },
  {
    name: 'Свердловская государственная филармония',
    desc: 'Главная концертная площадка классики и марафона «Безумные дни».',
    address: 'ул. Карла Либкнехта, 38а',
    locationSlug: 'ekaterinburg-filarmoniya',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 56.8392,
    longitude: 60.6083,
  },
  {
    name: 'Офис «ЕКАРТА»',
    desc: 'Сервисный центр единой транспортной карты: проездные для туристов.',
    address: 'ул. Малышева, 44',
    locationSlug: 'ekaterinburg-ekarta',
    mustSeeFilter: 'main',
    visitMinutes: 20,
    latitude: 56.834458,
    longitude: 60.601912,
  },
  {
    name: 'Рок-бар «Цынь»',
    desc: 'Место силы уральского рока с живыми концертами локальных групп.',
    address: 'ул. Попова, 2',
    locationSlug: 'ekaterinburg-rok-bar-tsyn',
    mustSeeFilter: 'creative',
    visitMinutes: 120,
    latitude: 56.835987,
    longitude: 60.591214,
  },
  {
    name: 'Музыкальный клуб «Фабрика» (Tele-Club Central)',
    desc: 'Крупная концертная площадка центра: привозные артисты и инди-ночи.',
    address: 'ул. Центральный рынок, 6',
    locationSlug: 'ekaterinburg-tele-club-fabrika',
    mustSeeFilter: 'creative',
    visitMinutes: 120,
    latitude: 56.835339,
    longitude: 60.592551,
  },
  {
    name: 'New Bar',
    desc: 'Культовый бар на мансарде: джаз, инди-акустика и городская интеллигенция.',
    address: 'ул. 8 Марта, 8д (вход со двора, 3 этаж)',
    locationSlug: 'ekaterinburg-new-bar',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 56.835198,
    longitude: 60.599167,
  },
  {
    name: 'Ресторан «Змееед»',
    desc: 'Новая уральская кухня в Ельцин Центре с видом на пруд.',
    address: 'ул. Бориса Ельцина, 3 (2-й пешеходный уровень)',
    locationSlug: 'ekaterinburg-zmeeed',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 56.843112,
    longitude: 60.595611,
  },
  {
    name: 'Ресторан «Паштет»',
    desc: 'Домашняя уральская кухня: пельмени ручной лепки и фирменные настойки.',
    address: 'ул. Толмачева, 23',
    locationSlug: 'ekaterinburg-pashtet',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 56.840795,
    longitude: 60.608474,
  },
  {
    name: 'Горнолыжный комплекс «Уктус»',
    desc: 'Трассы для лыж и сноуборда в черте города.',
    address: 'ул. Зимняя, 27',
    locationSlug: 'ekaterinburg-uktus-gornolyzhnyy',
    mustSeeFilter: 'park',
    visitMinutes: '2-3 ч',
    latitude: 56.786911,
    longitude: 60.643112,
  },
  {
    name: 'Баден-Баден Термы Уктус',
    desc: 'Открытый подогреваемый бассейн среди сосен - зимний хит Уктуса.',
    address: 'ул. Зимняя, 23',
    locationSlug: 'ekaterinburg-baden-baden-uktus',
    mustSeeFilter: 'main',
    visitMinutes: '2-3 ч',
    latitude: 56.784512,
    longitude: 60.645688,
  },
  {
    name: 'Октябрьская площадь и Драмтеатр',
    desc: 'Фонтан «Шар» и вечерняя набережная у драмтеатра.',
    address: 'Октябрьская площадь',
    locationSlug: 'ekaterinburg-oktyabrskaya-ploschad',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 56.843699,
    longitude: 60.593248,
  },
];

export const EKB_SUBURBS: any[] = [
  {
    name: 'Верхняя Пышма: музейный комплекс УГМК',
    desc: 'Крупнейшая коллекция ретро-машин, военной техники и авиации под открытым небом и в павильонах.',
    locationSlug: 'ekaterinburg-verkhnyaya-pyshma-ugmk',
    mustSeeFilter: 'museum',
    visitMinutes: '4-5 ч',
    latitude: 56.9705,
    longitude: 60.5885,
    travelVector: 'Трамвай ~40 минут',
    travelVectorBlurb: 'Закладывайте на трамвай около 40 минут, чтобы приехать к 10 утра.',
    timingNote: 'От павильона автотехники к уличной экспозиции поездов и самолетов.',
    places: [
      { name: 'Музей автомобильной техники', desc: 'Четырехэтажное собрание ретро-каров и мотоциклов.', visitMinutes: 90 },
      { name: 'Музей военной техники', desc: 'Форма, награды и редкое стрелковое оружие.', visitMinutes: 60 },
      { name: 'Павильон «Крылья Победы»', desc: 'Истребители и бомбардировщики под крышей.', visitMinutes: 45 },
      { name: 'Железнодорожная станция «Урал»', desc: 'Ретро-вокзал с паровозами и поездами.', visitMinutes: 40 },
      { name: 'Экспозиция под открытым небом', desc: 'Танки, орудия, подлодки и ракеты.', visitMinutes: 60 },
      { name: 'Музей авиации', desc: 'Вертолеты и транспортные самолеты на стендах.', visitMinutes: 40 },
      { name: 'Аллея славы', desc: 'Финал с мемориалом и видом на цех.', visitMinutes: 20 },
    ],
  },
  {
    name: 'Сысерть: природный парк «Бажовские места»',
    desc: 'Уральская тайга Бажова: тропы, Кипящий ключ и озеро Тальков Камень.',
    locationSlug: 'ekaterinburg-sysert-bazhovskie-mesta',
    mustSeeFilter: 'park',
    visitMinutes: '4-5 ч',
    latitude: 56.502,
    longitude: 60.755,
    travelVector: 'Автобус ~1 ч 20 мин',
    travelVectorBlurb: 'Закладывайте на автобус около 1 часа 20 минут, чтобы приехать к 11 утра.',
    timingNote: 'По деревянному настилу по часовой стрелке, карьер и мост - напоследок.',
    places: [
      { name: 'Входная группа и арт-объекты', desc: 'Резные ворота и фигуры из сказов Бажова.', visitMinutes: 20 },
      { name: 'Мостик влюбленных', desc: 'Переход через лесной ручей.', visitMinutes: 15 },
      { name: 'Кипящий ключ', desc: 'Родник с ледяной водой из земли.', visitMinutes: 20 },
      { name: 'Мыс Великого Полоза', desc: 'Точка из уральских легенд.', visitMinutes: 20 },
      { name: 'Озеро Тальков Камень', desc: 'Затопленный карьер с зелеными водами.', visitMinutes: 40 },
      { name: 'Тальковые скалы', desc: 'Отвесные стены старой выработки.', visitMinutes: 30 },
      { name: 'Смотровая над карьером', desc: 'Панорама для финального кадра.', visitMinutes: 20 },
    ],
  },
  {
    name: 'Берёзовский: музей-шахта «Русское золото»',
    desc: 'Первая золотодобывающая шахта России XVIII века с подземным маршрутом и промывкой песка.',
    locationSlug: 'ekaterinburg-berezovskiy-russkoe-zoloto',
    mustSeeFilter: 'museum',
    visitMinutes: '3-4 ч',
    latitude: 56.908,
    longitude: 60.802,
    travelVector: 'Маршрутка ~40 минут',
    travelVectorBlurb: 'Закладывайте на пригородную маршрутку около 40 минут, чтобы приехать к 12 часам.',
    timingNote: 'Подземные штреки только с гидом; промывка песка - финал на улице.',
    places: [
      { name: 'Наземный павильон', desc: 'Карты, самородки и инструменты старателей.', visitMinutes: 30 },
      { name: 'Наклонный ствол шахты', desc: 'Спуск в касках под гул вагонеток.', visitMinutes: 20 },
      { name: 'Подземный штрек', desc: 'Деревянная крепь и узкоколейка.', visitMinutes: 40 },
      { name: 'Зона бурения', desc: 'Отбойные молотки и инструменты XIX века.', visitMinutes: 20 },
      { name: 'Подземное озеро', desc: 'Затопленная выработка с подсветкой.', visitMinutes: 15 },
      { name: 'Шахтная вагонетка', desc: 'Фото в оригинальном рудничном транспорте.', visitMinutes: 10 },
      { name: 'Уличный лоток промывки', desc: 'Мастер-класс по намыванию «золота».', visitMinutes: 25 },
    ],
  },
  {
    name: 'Посёлок Исеть: скалы Чёртово Городище',
    desc: 'Гранитный останец с панорамой тайги и Исетского озера.',
    locationSlug: 'ekaterinburg-chertovo-gorodishche',
    mustSeeFilter: 'park',
    visitMinutes: '4-5 ч',
    latitude: 56.941,
    longitude: 60.347,
    travelVector: 'Электричка ~40 мин + пеший подъем ~1 ч',
    travelVectorBlurb: 'Электричка до станции «Исеть», далее маркированная тропа около 4 км.',
    timingNote: 'На вершину - по металлической лестнице; оставьте силы на финал.',
    places: [
      { name: 'Подножие горы', desc: 'Поляна среди сосен и валунов.', visitMinutes: 20 },
      { name: 'Малые Черти', desc: 'Скалы-спутники на подходе.', visitMinutes: 20 },
      { name: 'Северная стена', desc: 'Отвесный щит высотой около 20 метров.', visitMinutes: 20 },
      { name: 'Южный пологий склон', desc: 'Ступенчатые гранитные «матрасы».', visitMinutes: 25 },
      { name: 'Каменные чаши', desc: 'Углубления на вершине скал.', visitMinutes: 15 },
      { name: 'Металлическая лестница', desc: 'Безопасный подъем на верхний ярус.', visitMinutes: 15 },
      { name: 'Вершина Городища', desc: 'Круговая панорама тайги и озера.', visitMinutes: 30 },
    ],
  },
];

export const EKB_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'ekaterinburg-demidovy-siti',
    title: 'От Демидовых до Сити',
    description:
      'Классический пешеходный трек на 1 день: контраст суровых заводов XVIII века и зеркальных небоскребов.',
    travelVector: 'Парадный пешеходный променад',
    timingNote: 'Около 6-7 часов пешком по центру и пруду.',
    stops: [
      {
        name: 'Исторический сквер (Плотинка)',
        desc: 'Сердце города: старинная плотина дореволюционного завода на Исети.',
        locationSlug: 'ekaterinburg-plotinka-istoricheskiy-skver',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        latitude: 56.8385,
        longitude: 60.6028,
      },
      {
        name: 'Водонапорная башня на Плотинке',
        desc: 'Осматриваем старинный символ города и берем сувениры.',
        locationSlug: 'ekaterinburg-vodonapornaya-bashnya-plotinka',
        mustSeeFilter: 'main',
        visitMinutes: 30,
        address: 'ул. Горького, 4в',
        latitude: 56.837892,
        longitude: 60.605469,
      },
      {
        name: 'Стрит-арт «Переход Цоя»',
        desc: 'Подземный рок-переход под проспектом Ленина с муралами.',
        locationSlug: 'ekaterinburg-perekhod-tsoya',
        mustSeeFilter: 'creative',
        visitMinutes: 20,
        latitude: 56.8376,
        longitude: 60.6059,
      },
      {
        name: 'Уральский пельменный «Паштет»',
        desc: 'Обед уральскими пельменями ручной лепки и настойками.',
        locationSlug: 'ekaterinburg-pashtet',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Толмачева, 23',
        latitude: 56.840795,
        longitude: 60.608474,
      },
      {
        name: 'Набережная Рабочей Молодёжи',
        desc: 'Парадная прогулка вдоль Городского пруда к хайтек-кварталу.',
        locationSlug: 'ekaterinburg-naberezhnaya-rabochey-molodezhi',
        mustSeeFilter: 'main',
        visitMinutes: 45,
        latitude: 56.842107,
        longitude: 60.598157,
      },
      {
        name: 'Ельцин Центр',
        desc: 'Финал дня в интерактивном хайтек-пространстве у воды.',
        locationSlug: 'ekaterinburg-el-tsin-tsentr',
        mustSeeFilter: 'museum',
        visitMinutes: 120,
        address: 'ул. Бориса Ельцина, 3',
        latitude: 56.8431,
        longitude: 60.5956,
      },
    ],
  },
  {
    id: 'ekaterinburg-avangard-vysotnyy',
    title: 'Архитектурный авангард',
    description:
      'Мировые шедевры советского авангарда 1930-х и лучшие смотровые площадки мегаполиса.',
    travelVector: 'Эстетика бетона и геометрии',
    timingNote: 'Около 5-6 часов по центру; Белую башню на Уралмаше лучше отдельным выездом.',
    stops: [
      {
        name: 'Здание Главпочтамта',
        desc: 'Старт от знаменитого авангардного «трактора» на Ленина.',
        locationSlug: 'ekaterinburg-glavpochtamt',
        mustSeeFilter: 'houses',
        visitMinutes: 20,
        address: 'пр. Ленина, 39',
        latitude: 56.839513,
        longitude: 60.608435,
      },
      {
        name: 'Городок чекистов и гостиница «Исеть»',
        desc: 'Легендарный квартал-серп и икона свердловского авангарда.',
        locationSlug: 'ekaterinburg-gorodok-chekistov',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        address: 'пр. Ленина, 69',
        latitude: 56.840727,
        longitude: 60.620917,
      },
      {
        name: 'Креативный кластер «Л52»',
        desc: 'Выставки в залах бывшей конструктивистской поликлиники.',
        locationSlug: 'ekaterinburg-l52',
        mustSeeFilter: 'creative',
        visitMinutes: 60,
        address: 'ул. Бажова, 124а',
        latitude: 56.839644,
        longitude: 60.625818,
        transitTip: 'От городка чекистов коротко на восток по Бажова',
      },
      {
        name: 'Дом обороны',
        desc: 'Конструктивистское здание с самолетом на крыше - кадр обязателен.',
        locationSlug: 'ekaterinburg-dom-oborony',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        address: 'ул. Малышева, 31д',
        latitude: 56.835002,
        longitude: 60.601052,
        transitTip: 'Возврат к Малышева / центру',
      },
      {
        name: 'БЦ «Высоцкий» и смотровая',
        desc: 'Подъем на 52 этаж за панорамой 360° и бассейном на крыше.',
        locationSlug: 'ekaterinburg-smotrovaya-ploschadka-bts-vysotskiy',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'ул. Малышева, 51',
        latitude: 56.836106,
        longitude: 60.614605,
      },
      {
        name: 'Арт-отель и New Bar',
        desc: 'Финал на мансарде с джазовой инди-акустикой под коктейли.',
        locationSlug: 'ekaterinburg-new-bar',
        mustSeeFilter: 'creative',
        visitMinutes: 90,
        address: 'ул. 8 Марта, 8д',
        latitude: 56.835198,
        longitude: 60.599167,
      },
    ],
  },
  {
    id: 'ekaterinburg-neformalnyy-ural',
    title: 'Неформальный Урал',
    description:
      'Рок, стрит-арт STENOGRAFFIA и культовый уральский фастфуд: The Beatles, барсы и посикунчики.',
    travelVector: 'Музыкальный и стрит-арт культ',
    timingNote: 'День по центру + ночной финал в рок-клубе.',
    stops: [
      {
        name: 'Мурал «Уральский барс»',
        desc: 'Старт от огромного уличного барса во всю стену многоэтажки.',
        locationSlug: 'ekaterinburg-mural-uralskiy-bars',
        mustSeeFilter: 'creative',
        visitMinutes: 15,
        address: 'ул. 8 Марта, 22-24',
        latitude: 56.831814,
        longitude: 60.600172,
      },
      {
        name: 'Ресторан «Пельмени Клуб»',
        desc: 'Горячие посикунчики и таежные пельмени из дичи.',
        locationSlug: 'ekaterinburg-pelmeni-klub',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Красноармейская, 2',
        latitude: 56.839051,
        longitude: 60.615075,
      },
      {
        name: 'Памятник Клавиатуре',
        desc: 'Прыжки по бетонным клавишам гигантского QWERTY-монумента.',
        locationSlug: 'ekaterinburg-pamyatnik-klaviatura',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'ул. Горького, 14а',
        latitude: 56.8298,
        longitude: 60.6125,
      },
      {
        name: 'Памятник группе The Beatles',
        desc: 'Первый в СНГ чугунный силуэт легендарной четверки.',
        locationSlug: 'ekaterinburg-pamyatnik-beatles',
        mustSeeFilter: 'monument',
        visitMinutes: 20,
        address: 'ул. Горького, 8',
        latitude: 56.834,
        longitude: 60.606874,
      },
      {
        name: 'Фонтан «Шар» у Театра Драмы',
        desc: 'Золотой закат на ступенях у воды с видом на Сити.',
        locationSlug: 'ekaterinburg-oktyabrskaya-ploschad',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'Октябрьская площадь, 2',
        latitude: 56.843699,
        longitude: 60.593248,
      },
      {
        name: 'Рок-бар «Цынь» / клуб «Фабрика»',
        desc: 'Ночной отрыв под живой уральский рок, тяжелые гитары или инди-сеты.',
        locationSlug: 'ekaterinburg-rok-bar-tsyn',
        mustSeeFilter: 'creative',
        visitMinutes: 120,
        latitude: 56.835987,
        longitude: 60.591214,
        transitTip: 'Альтернатива - клуб «Фабрика» (Tele-Club Central)',
      },
    ],
  },
];

export const EKB_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как работает Красная линия на тротуарах Екатеринбурга?',
    a: 'Это официальный пешеходный маршрут длиной около 6,5 км, нанесенный краской прямо на асфальт. Он начинается на Плотинке и кругом ведет туристов мимо 35 главных исторических и архитектурных достопримечательностей центра. Обойти его самостоятельно можно за 2-3 часа.',
  },
  {
    q: 'Как легально попасть внутрь знаменитой Белой башни?',
    a: 'Шедевр мирового конструктивизма (бывшая водонапорная башня Уралмаша) сейчас законсервирован и превращен в культурный объект. Попасть внутрь, подняться на бак и смотровую можно легально только в составе организованных экскурсий по выходным. Билеты лучше бронировать онлайн заранее.',
  },
  {
    q: 'Где в городе послушать живой уральский рок и джаз?',
    a: 'Главные места с живым звуком - EverJazz, легендарный New Bar, рок-бар «Цынь» и клуб «Фабрика». Билеты на вечерние концерты местных групп и привозных артистов доступны в афише Дайбилета.',
  },
  {
    q: 'Как проще всего добраться до скал Чёртово Городище или Ганиной Ямы?',
    a: 'До монастыря на Ганиной Яме ходят автобусы № 223 от Северного автовокзала. До Чёртова Городища удобнее пригородная электричка до станции «Исеть» (направление на Нижний Тагил), а оттуда около 4 км пешком по маркированной лесной тропе.',
  },
];

export const EKB_TRAVEL =
  'Крупнейший международный аэропорт Кольцово принимает ежедневные прямые рейсы из Москвы (около 2,5 часов в полете), Санкт-Петербурга и десятков других городов. Екатеринбург - ключевой узел Транссиба, поэтому сюда легко добраться поездом восточного направления. По центру удобно идти пешком по «Красной линии»; для Уралмаша, Уктуса и пригородов берите ЕКАРТУ или такси.';
