import type { PublicCatalogListItemDto, PublicSessionDto } from '@daibilet/contracts/public';

import { resolveCityCardImage } from '@/lib/city-images';
import { resolveEditorialEventImage } from '@/lib/event-cover-images';
import { isEphemeralAutoGeneratedCoverUrl, sessionHasCoverImage } from '@/lib/session-cover-image';

type EventCardImageSource = Pick<
  PublicCatalogListItemDto | PublicSessionDto,
  'imageUrl' | 'city' | 'destination'
> & {
  id?: string | null;
  slug?: string | null;
  citySlug?: string | null;
  sourceCitySlug?: string | null;
};

/**
 * Primary cover for EventCard. Prefers EVENT_PACK editorial overrides, then skips
 * city / teplohod / evt-auto stubs so SafeImage can fall through to venue/city art.
 */
export function resolveEventCardPrimaryImage(session: EventCardImageSource): string | null {
  const editorial = resolveEditorialEventImage(session.id, session.slug, null);
  if (editorial) return editorial;

  const url = String(session.imageUrl || '').trim();
  if (!url) return null;
  if (!sessionHasCoverImage({ imageUrl: url })) return null;
  if (isEphemeralAutoGeneratedCoverUrl(url)) return null;
  return url;
}

/**
 * Last-resort cover when primary `imageUrl` is empty or fails to load (404 / broken CDN).
 * Prefer city asset on disk over empty SafeImage fallback.
 */
export function resolveEventCardFallbackImage(session: EventCardImageSource): string | null {
  const cityName = String(session.city || session.destination || '').trim() || 'город';
  return resolveCityCardImage({
    slug: session.citySlug,
    sourceSlug: 'sourceCitySlug' in session ? session.sourceCitySlug : undefined,
    name: cityName,
    heroImageUrl: null,
  });
}
