/** Kazan tourist hub pack (owner 2026-08-15). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export const KAZAN_MUST_SEE: any[] = [
  // --- Core heritage ---
  {
    name: 'Казанский Кремль',
    desc: 'Объект ЮНЕСКО - белокаменная крепость, где рядом живут мечеть Кул-Шариф и Благовещенский собор.',
    address: 'Кремль',
    locationSlug: 'kazan-kazanskiy-kreml',
    mustSeeFilter: 'main',
    visitMinutes: 120,
    latitude: 55.799112,
    longitude: 49.106411,
  },
  {
    name: 'Мечеть Кул-Шариф',
    desc: 'Главная мечеть Татарстана с бирюзовыми куполами - символ возрождения культуры.',
    address: 'Кремль',
    locationSlug: 'kazan-mechet-kul-sharif',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 55.798312,
    longitude: 49.105111,
  },
  {
    name: 'Улица Баумана',
    desc: 'Пешеходный «казанский Арбат»: музыканты, витрины, колокольня и сувениры.',
    address: 'ул. Баумана',
    locationSlug: 'kazan-ulitsa-baumana',
    mustSeeFilter: 'street',
    visitMinutes: 50,
    latitude: 55.7895,
    longitude: 49.116,
  },
  {
    name: 'Башня Сююмбике',
    desc: 'Падающая дозорная башня Кремля и визитная карточка крепости.',
    address: 'Кремль',
    locationSlug: 'kazan-bashnya-syuyumbike',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 55.800511,
    longitude: 49.105112,
  },
  {
    name: 'Дворец земледельцев',
    desc: 'Парадный дворец с зеленой крышей и садом у стен Кремля.',
    address: 'ул. Федосеевская, 36',
    locationSlug: 'kazan-dvorets-zemledeltsev',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 55.800542,
    longitude: 49.111911,
  },
  {
    name: 'Кремлевская набережная',
    desc: 'Благоустроенный променад у стен Кремля с видами на Казанку.',
    address: 'Кремлевская набережная',
    locationSlug: 'kazan-kremlevskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 55.803112,
    longitude: 49.115611,
  },

  // --- Monuments ---
  {
    name: 'Памятник коту казанскому',
    desc: 'Бронзовый кот улыбается туристам - любимая точка для фото на Баумана.',
    address: 'ул. Баумана, 13',
    locationSlug: 'kazan-pamyatnik-kotu-kazanskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.792341,
    longitude: 49.111452,
  },
  {
    name: 'Памятник Мусе Джалилю',
    desc: 'Монумент поэту-герою на площади 1 Мая у стен Кремля.',
    address: 'пл. 1 Мая',
    locationSlug: 'kazan-pamyatnik-muse-dzhaliyu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.794612,
    longitude: 49.106211,
  },
  {
    name: 'Памятник Габдулле Тукаю',
    desc: 'Памятник классику татарской поэзии у театра Камала.',
    address: 'пл. Тукая',
    locationSlug: 'kazan-pamyatnik-gabdulle-tukayu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.786521,
    longitude: 49.124512,
  },
  {
    name: 'Памятник Федору Шаляпину',
    desc: 'Бронзовый Шаляпин у Богоявленской колокольни на Баумана.',
    address: 'ул. Баумана, 78',
    locationSlug: 'kazan-pamyatnik-fedoru-shalyapinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.787723,
    longitude: 49.120112,
  },
  {
    name: 'Карета Екатерины II',
    desc: 'Скульптура императорской кареты - фотостоп посреди Баумана.',
    address: 'ул. Баумана, 42',
    locationSlug: 'kazan-kareta-ekateriny-ii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.790512,
    longitude: 49.114901,
  },
  {
    name: 'Памятник дракону Зиланту',
    desc: 'Геральдический змей-хранитель Казани у кремлевских стен.',
    address: 'у Казанского кремля',
    locationSlug: 'kazan-pamyatnik-drakonu-zilantu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.794122,
    longitude: 49.106511,
  },
  {
    name: 'Памятник Благотворителю',
    desc: 'Скульптура мецената с ребенком у Дворца земледельцев.',
    address: 'ул. Федосеевская',
    locationSlug: 'kazan-pamyatnik-blagotvoritelyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.795211,
    longitude: 49.102911,
  },
  {
    name: 'Памятник Льву Толстому',
    desc: 'Памятник писателю, учившемуся в Казанском университете.',
    address: 'ул. Л. Толстого',
    locationSlug: 'kazan-pamyatnik-tolstomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.791533,
    longitude: 49.141211,
  },
  {
    name: 'Скульптура «Загадки Шурале»',
    desc: 'Лесной дух из сказок Тукая - игровая скульптура у театра Камала.',
    address: 'ул. Татарстан',
    locationSlug: 'kazan-skulptura-zagadki-shurale',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.783412,
    longitude: 49.118901,
  },
  {
    name: 'Памятник Лобачевскому',
    desc: 'Бюст математика у Казанского университета.',
    address: 'ул. Кремлевская / Лобачевского',
    locationSlug: 'kazan-pamyatnik-lobachevskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.790912,
    longitude: 49.119511,
  },
  {
    name: 'Часы в татарском стиле',
    desc: 'Цветочные куранты с орнаментом - ориентир на Баумана.',
    address: 'ул. Баумана',
    locationSlug: 'kazan-chasy-v-tatarskom-stile',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.786912,
    longitude: 49.123901,
  },
  {
    name: 'Памятник Карлу Фуксу',
    desc: 'Памятник врачу и краеведу у Фуксавского сада.',
    address: 'ул. Федосеевская / сад Фукса',
    locationSlug: 'kazan-pamyatnik-karlu-fuksu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.801612,
    longitude: 49.132511,
  },
  {
    name: 'Памятник зодчим Казанского кремля',
    desc: 'Скульптура мастеров-строителей у стен крепости.',
    address: 'Кремль',
    locationSlug: 'kazan-pamyatnik-zodchim-kremlya',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.799511,
    longitude: 49.105511,
  },
  {
    name: 'Скульптура «Тайказан»',
    desc: 'Гигантский котел-символ изобилия у Центра семьи «Казан».',
    address: 'ул. Сибгата Хакима',
    locationSlug: 'kazan-skulptura-taykazan',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.812411,
    longitude: 49.108211,
  },
  {
    name: 'Памятник воинам-интернационалистам',
    desc: 'Мемориал в Парке Победы на правом берегу Казанки.',
    address: 'Парк Победы',
    locationSlug: 'kazan-pamyatnik-voinam-internatsionalistam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.829811,
    longitude: 49.121512,
  },

  // --- Museums / houses ---
  {
    name: 'Национальный музей РТ',
    desc: 'Главный музей республики в бывших Гостиных рядах у Кремля.',
    address: 'ул. Кремлевская, 2',
    locationSlug: 'kazan-natsionalnyy-muzey-rt',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 55.794611,
    longitude: 49.108112,
  },
  {
    name: 'Дом Шамиля / музей Тукая',
    desc: 'Деревянный особняк и музей поэта в Старо-Татарской слободе.',
    address: 'ул. Г. Тукая, 74',
    locationSlug: 'kazan-dom-shamilya-muzey-tukaya',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.7779,
    longitude: 49.1172,
  },
  {
    name: 'Музей чак-чака',
    desc: 'Сладкая экспозиция и дегустация главного татарского десерта.',
    address: 'ул. Парижской Коммуны, 18',
    locationSlug: 'kazan-muzey-chak-chaka',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 55.782811,
    longitude: 49.111812,
  },
  {
    name: 'Казанский университет',
    desc: 'Исторический корпус alma mater Толстого, Ленина и Лобачевского.',
    address: 'ул. Кремлевская, 18',
    locationSlug: 'kazan-kazanskiy-universitet',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 55.790822,
    longitude: 49.121211,
  },
  {
    name: 'Дом Ушковой',
    desc: 'Особняк с легендарной «восточной» комнатой и витражами.',
    address: 'ул. Кремлевская, 33',
    locationSlug: 'kazan-dom-ushkovoy',
    mustSeeFilter: 'houses',
    visitMinutes: 45,
    latitude: 55.792511,
    longitude: 49.118912,
  },
  {
    name: 'Эрмитаж-Казань',
    desc: 'Филиал Государственного Эрмитажа в стенах Кремля.',
    address: 'Кремль',
    locationSlug: 'kazan-ermitazh-kazan',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.798112,
    longitude: 49.106233,
  },
  {
    name: 'Дом-музей Ленина',
    desc: 'Мемориальный дом, где жила семья Ульяновых.',
    address: 'ул. Ульянова-Ленина',
    locationSlug: 'kazan-dom-muzey-lenina',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 55.786112,
    longitude: 49.133211,
  },

  // --- Temples ---
  {
    name: 'Благовещенский собор',
    desc: 'Древнейший храм Кремля напротив мечети Кул-Шариф.',
    address: 'Кремль',
    locationSlug: 'kazan-blagoveschenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.799412,
    longitude: 49.106133,
  },
  {
    name: 'Петропавловский собор',
    desc: 'Барочный храм с богатым иконостасом у Баумана.',
    address: 'ул. М. Джалиля, 21',
    locationSlug: 'kazan-petropavlovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.792742,
    longitude: 49.111911,
  },
  {
    name: 'Богоявленская колокольня',
    desc: 'Высокая колокольня - ориентир и фотостоп на Баумана.',
    address: 'ул. Баумана, 78/1',
    locationSlug: 'kazan-bogoyavlenskaya-kolokolnya',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.787611,
    longitude: 49.120712,
  },
  {
    name: 'Мечеть аль-Марджани',
    desc: 'Старейшая каменная мечеть Казани в Старо-Татарской слободе.',
    address: 'ул. К. Насыри, 17',
    locationSlug: 'kazan-mechet-al-mardzhani',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.779831,
    longitude: 49.119212,
  },
  {
    name: 'Азимовская мечеть',
    desc: 'Краснокирпичная мечеть с высокими минаретами.',
    address: 'ул. Фаткуллина, 15',
    locationSlug: 'kazan-azimovskaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.766112,
    longitude: 49.120113,
  },
  {
    name: 'Богородицкий монастырь',
    desc: 'Монастырь у места обретения Казанской иконы.',
    address: 'ул. Большая Красная, 5',
    locationSlug: 'kazan-bogoroditskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 55.798411,
    longitude: 49.112112,
  },
  {
    name: 'Закабанная мечеть',
    desc: 'Историческая мечеть у озера Кабан.',
    address: 'ул. Х. Такташа, 26',
    locationSlug: 'kazan-zakabannaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.776112,
    longitude: 49.124211,
  },
  {
    name: 'Храм всех религий',
    desc: 'Авторский комплекс 16 конфессий в Старом Аракчино.',
    address: 'пос. Старое Аракчино, 4',
    locationSlug: 'kazan-hram-vseh-religiy',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 55.800511,
    longitude: 49.008112,
  },
  {
    name: 'Султановская мечеть',
    desc: 'Компактная мечеть XIX века в центре слободы.',
    address: 'ул. Г. Тукая, 14',
    locationSlug: 'kazan-sultanovskaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.784411,
    longitude: 49.1102,
  },

  // --- Parks / views ---
  {
    name: 'Центр семьи «Казан» (Чаша)',
    desc: 'Дворец бракосочетания-чаша и смотровая с видом на Кремль.',
    address: 'ул. Сибгата Хакима, 4',
    locationSlug: 'kazan-tsentr-semi-kazan',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 55.812812,
    longitude: 49.108311,
  },
  {
    name: 'Старо-Татарская слобода',
    desc: 'Деревянные усадьбы, мечети и дворики исторического татарского квартала.',
    address: 'ул. К. Насыри',
    locationSlug: 'kazan-staro-tatarskaya-sloboda',
    mustSeeFilter: 'street',
    visitMinutes: 60,
    latitude: 55.779711,
    longitude: 49.119912,
  },
  {
    name: 'Парк «Черное озеро»',
    desc: 'Камерный городской парк у центра с прудом и аллеями.',
    address: 'ул. Дзержинского / Черное озеро',
    locationSlug: 'kazan-park-chernoe-ozero',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 55.7972,
    longitude: 49.118311,
  },
  {
    name: 'Набережная озера Нижний Кабан',
    desc: 'Просторный променад у воды после тесных улиц слободы.',
    address: 'наб. озера Нижний Кабан',
    locationSlug: 'kazan-naberezhnaya-nizhniy-kaban',
    mustSeeFilter: 'views',
    visitMinutes: 40,
    latitude: 55.781501,
    longitude: 49.119811,
  },
  {
    name: 'Парк Горького',
    desc: 'Классический городской парк с аттракционами и аллеями.',
    address: 'ул. Эршова',
    locationSlug: 'kazan-park-gorkogo',
    mustSeeFilter: 'park',
    visitMinutes: 50,
    latitude: 55.799312,
    longitude: 49.151211,
  },
  {
    name: 'Горкинско-Ометьевский лес',
    desc: 'Городской лесопарк с экотропами и смотровыми.',
    address: 'ул. Ю. Фукса / Ометьево',
    locationSlug: 'kazan-gorkinsko-ometevskiy-les',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 55.760122,
    longitude: 49.213111,
  },
  {
    name: 'Фуксовский сад',
    desc: 'Тихий сад у Казанки с памятником Карлу Фуксу.',
    address: 'ул. Федосеевская',
    locationSlug: 'kazan-fuksovskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 55.801811,
    longitude: 49.132912,
  },
  {
    name: 'Парк Победы',
    desc: 'Мемориальный парк и панорамы правого берега.',
    address: 'ул. Мусина / Парк Победы',
    locationSlug: 'kazan-park-pobedy',
    mustSeeFilter: 'park',
    visitMinutes: 50,
    latitude: 55.828711,
    longitude: 49.120512,
  },
  {
    name: 'Экстрим-парк «УРАМ»',
    desc: 'Скейт-парк, бетон и уличная графика на правом берегу Казанки.',
    address: 'ул. Сибгата Хакима',
    locationSlug: 'kazan-ekstrim-park-uram',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.804112,
    longitude: 49.141511,
  },

  // --- Culture / gastro ---
  {
    name: 'Театр имени Камала',
    desc: 'Главная сцена татарской драмы у озера Кабан.',
    address: 'ул. Татарстан, 1',
    locationSlug: 'kazan-teatr-kamala',
    mustSeeFilter: 'creative',
    visitMinutes: 120,
    latitude: 55.783911,
    longitude: 49.118112,
  },
  {
    name: 'Театр оперы и балета',
    desc: 'Классическая сцена у сквера и улицы Пушкина.',
    address: 'ул. Пушкина, 56',
    locationSlug: 'kazan-teatr-opery-i-baleta',
    mustSeeFilter: 'creative',
    visitMinutes: 120,
    latitude: 55.796812,
    longitude: 49.126111,
  },
  {
    name: 'Креативный кластер «Штаб»',
    desc: 'Дизайн-пространства, мастерские и кофе в бывшем промышленном корпусе.',
    address: 'ул. Татарстан, 20',
    locationSlug: 'kazan-kreativnyy-klaster-shtab',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.781912,
    longitude: 49.114411,
  },
  {
    name: '«Туган Авылым»',
    desc: 'Этнодеревня с татарской кухней, двориками и сувенирами.',
    address: 'ул. Г. Миннуллина, 14/56',
    locationSlug: 'kazan-tugan-avylim',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 55.778111,
    longitude: 49.131712,
  },
  {
    name: 'Ресторан «Тюбетей»',
    desc: 'Татарская кухня в центре - эчпочмак, кыстыбый и чай из пиал.',
    address: 'ул. Баумана, 21',
    locationSlug: 'kazan-tyubetey',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 55.791412,
    longitude: 49.113211,
  },
];

export const KAZAN_SUBURBS: any[] = [
  {
    name: 'Остров-град Свияжск',
    desc: 'Древний город-крепость на острове в устье Свияги с монастырями и музеями.',
    locationSlug: 'kazan-ostrov-grad-sviyazhsk',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 55.771142,
    longitude: 48.658311,
    travelVector: 'Метеор ~1 час',
    travelVectorBlurb: 'Закладывайте на «Метеор» около часа, чтобы быть на острове к 10 утра.',
    timingNote: 'Идите по острову по часовой стрелке: монастырь - соборы - музеи - смотровая.',
    places: [
      {
        name: 'Успенский монастырь',
        locationSlug: 'kazan-uspenskiy-monastyr-sviyazhsk',
        desc: 'Белокаменный ансамбль ЮНЕСКО - ядро острова.',
        visitMinutes: 60,
      },
      {
        name: 'Собор иконы Божией Матери «Всех скорбящих Радость»',
        locationSlug: 'kazan-sobor-vseh-skorbyaschih-sviyazhsk',
        desc: 'Краснокирпичный храм с высокой колокольней.',
        visitMinutes: 30,
      },
      {
        name: 'Троицкая церковь',
        locationSlug: 'kazan-troitskaya-tserkov-sviyazhsk',
        desc: 'Деревянный храм XVI века - один из старейших на острове.',
        visitMinutes: 25,
      },
      {
        name: 'Музей археологического дерева',
        locationSlug: 'kazan-muzey-arheologicheskogo-dereva',
        desc: 'Находки из влажной почвы Свияжска под крышей.',
        visitMinutes: 40,
      },
      {
        name: 'Рождественская площадь',
        locationSlug: 'kazan-rozhdestvenskaya-ploschad-sviyazhsk',
        desc: 'Центральная площадь с видами на Волгу.',
        visitMinutes: 20,
      },
      {
        name: 'Конный двор',
        locationSlug: 'kazan-konnyy-dvor-sviyazhsk',
        desc: 'Ремесленные мастерские, кафе и сувениры.',
        visitMinutes: 40,
      },
      {
        name: 'Смотровая площадка',
        locationSlug: 'kazan-smotrovaya-sviyazhsk',
        desc: 'Панорама Волги и Свияги на финал маршрута.',
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Великий Болгар',
    desc: 'Древняя столица Волжской Булгарии - руины, минареты и Белая мечеть.',
    locationSlug: 'kazan-bolgar',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 54.987211,
    longitude: 49.055112,
    travelVector: 'Метеор ~2 ч 20 мин',
    travelVectorBlurb: 'Закладывайте на «Метеор» около 2 часов 20 минут, чтобы прибыть к 11 утра.',
    timingNote: 'От мемориала ислама к руинам городища, музей цивилизации и Белая мечеть - напоследок.',
    places: [
      {
        name: 'Мемориальный знак принятия ислама',
        locationSlug: 'kazan-memorial-prinyatiya-islama-bolgar',
        desc: 'Точка памяти о крещении Волжской Булгарии в ислам.',
        visitMinutes: 20,
      },
      {
        name: 'Соборная мечеть',
        locationSlug: 'kazan-sobornaya-mechet-bolgar',
        desc: 'Руины главной мечети средневекового Болгара.',
        visitMinutes: 30,
      },
      {
        name: 'Восточная палата',
        locationSlug: 'kazan-vostochnaya-palata-bolgar',
        desc: 'Остатки дворцового комплекса булгарской знати.',
        visitMinutes: 25,
      },
      {
        name: 'Черная палата',
        locationSlug: 'kazan-chernaya-palata-bolgar',
        desc: 'Загадочное купольное сооружение городища.',
        visitMinutes: 25,
      },
      {
        name: 'Малый минарет',
        locationSlug: 'kazan-malyy-minaret-bolgar',
        desc: 'Сохранившийся минарет с узкой винтовой лестницей.',
        visitMinutes: 20,
      },
      {
        name: 'Музей болгарской цивилизации',
        locationSlug: 'kazan-muzey-bolgarskoy-tsivilizatsii',
        desc: 'Артефакты и история Волжской Булгарии.',
        visitMinutes: 60,
      },
      {
        name: 'Белая мечеть',
        locationSlug: 'kazan-belaya-mechet-bolgar',
        desc: 'Современный беломраморный храм у воды - финальный кадр.',
        visitMinutes: 30,
      },
    ],
  },
  {
    name: 'Раифский Богородицкий мужской монастырь',
    desc: 'Крупнейший монастырь Казанской епархии среди соснового леса и ледникового озера, известный легендой о «неквакающих» лягушках.',
    locationSlug: 'kazan-raifskiy-monastyr',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 55.901112,
    longitude: 48.731112,
    address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
    travelVector: 'Автобус №400 / авто ~40 минут',
    travelVectorBlurb:
      'Закладывайте на пригородный автобус №400 или автомобиль ~40 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'По ухоженным цветущим аллеям монастырского двора двигайтесь вниз к заповедной набережной озера, напоследок оставив покупку фигурок местных «неквакающих» лягушек.',
    places: [
      {
        name: 'Собор Грузинской иконы Божией Матери',
        desc: 'Главный монастырский храм с чудотворным списком Грузинской иконы XVII века.',
        locationSlug: 'kazan-raifa-sobor-gruzinskoy-ikony',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 40,
      },
      {
        name: 'Троицкий собор',
        desc: 'Великолепный собор в русско-византийском стиле с сильной внутренней акустикой.',
        locationSlug: 'kazan-raifa-troitskiy-sobor',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 30,
      },
      {
        name: 'Софийская церковь',
        desc: 'Очень маленькая церковь, куда одновременно помещаются всего несколько человек.',
        locationSlug: 'kazan-raifa-sofiyskaya-tserkov',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 15,
      },
      {
        name: 'Раифское озеро',
        desc: 'Заповедный ледниковый водоем у стен обители, зимой здесь строят ледовый городок.',
        locationSlug: 'kazan-raifa-raifskoe-ozero',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 30,
      },
      {
        name: 'Часовня со Святым источником',
        desc: 'Благоустроенный артезианский источник с чистой Раифской водой.',
        locationSlug: 'kazan-raifa-chasovnya-svyatoy-istochnik',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 20,
      },
      {
        name: 'Экспозиция деревянных скульптур',
        desc: 'Выставка под открытым небом работ местного мастера-послушника.',
        locationSlug: 'kazan-raifa-derevyannye-skulptury',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 20,
      },
      {
        name: 'Экотропа Волжско-Камского заповедника',
        desc: 'Прогулочный маршрут среди гигантских сосен вокруг монастыря.',
        locationSlug: 'kazan-raifa-ekotropa-zapovednika',
        address: 'Татарстан, Зеленодольский район, пос. местечко Раифа',
        latitude: 55.901112,
        longitude: 48.731112,
        visitMinutes: 45,
      },
    ],
  },
];

export const KAZAN_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'kazan-classic-one-day',
    title: 'Классика за 1 день',
    description:
      'Парадный день по центру: Кремль и Кул-Шариф, Дворец земледельцев, набережная, Баумана и татарский обед.',
    travelVector: 'Парадный пешеходный променад',
    timingNote: 'Около 6-7 часов пешком по центру и Кабану.',
    coverImageUrl: '/images/venues/kazan/kazanskiy-kreml.jpg',
    stops: [
      {
        name: 'Казанский Кремль и Кул-Шариф',
        desc: 'Стартуйте с крепости ЮНЕСКО и мечети с бирюзовыми куполами.',
        locationSlug: 'kazan-kazanskiy-kreml',
        mustSeeFilter: 'main',
        visitMinutes: 120,
        latitude: 55.799112,
        longitude: 49.106411,
      },
      {
        name: 'Дворец земледельцев',
        desc: 'Парадный фасад и сад у кремлевских стен.',
        locationSlug: 'kazan-dvorets-zemledeltsev',
        mustSeeFilter: 'houses',
        visitMinutes: 25,
        address: 'ул. Федосеевская, 36',
        latitude: 55.800542,
        longitude: 49.111911,
      },
      {
        name: 'Кремлевская набережная',
        desc: 'Променад вдоль Казанки с видами на стены.',
        locationSlug: 'kazan-kremlevskaya-naberezhnaya',
        mustSeeFilter: 'views',
        visitMinutes: 40,
        latitude: 55.803112,
        longitude: 49.115611,
      },
      {
        name: 'Улица Баумана',
        desc: 'Пешеходный Арбат: колокольня, музыканты и витрины.',
        locationSlug: 'kazan-ulitsa-baumana',
        mustSeeFilter: 'street',
        visitMinutes: 50,
        latitude: 55.7895,
        longitude: 49.116,
      },
      {
        name: 'Ресторан «Тюбетей»',
        desc: 'Обед татарской кухней - эчпочмак и чай из пиал.',
        locationSlug: 'kazan-tyubetey',
        mustSeeFilter: 'gastro',
        visitMinutes: 75,
        address: 'ул. Баумана, 21',
        latitude: 55.791412,
        longitude: 49.113211,
      },
      {
        name: 'Набережная Нижнего Кабана',
        desc: 'Финал дня у воды после центральных улиц.',
        locationSlug: 'kazan-naberezhnaya-nizhniy-kaban',
        mustSeeFilter: 'views',
        visitMinutes: 40,
        latitude: 55.781501,
        longitude: 49.119811,
      },
    ],
  },
  {
    id: 'kazan-creative',
    title: 'Креативная Казань',
    description:
      'Парк и особняки центра, затем правый берег: Чаша, УРАМ и дизайн-кластер «Штаб».',
    travelVector: 'Экстрим, смотровые и дизайн-кластеры',
    timingNote: 'Около 5-6 часов; на Чашу поднимайтесь только в ясную погоду.',
    coverImageUrl: '/images/venues/kazan/park-chernoe-ozero.jpg',
    stops: [
      {
        name: 'Парк «Черное озеро»',
        desc: 'Спокойный старт среди аллей и пруда у центра.',
        locationSlug: 'kazan-park-chernoe-ozero',
        mustSeeFilter: 'park',
        visitMinutes: 40,
        latitude: 55.7972,
        longitude: 49.118311,
      },
      {
        name: 'Дом Ушковой',
        desc: 'Особняк с «восточной» комнатой и витражами.',
        locationSlug: 'kazan-dom-ushkovoy',
        mustSeeFilter: 'houses',
        visitMinutes: 45,
        address: 'ул. Кремлевская, 33',
        latitude: 55.792511,
        longitude: 49.118912,
      },
      {
        name: 'Центр семьи «Казан» (Чаша)',
        desc: 'Смотровая с открыточным видом на Кремль.',
        locationSlug: 'kazan-tsentr-semi-kazan',
        mustSeeFilter: 'views',
        visitMinutes: 45,
        address: 'ул. Сибгата Хакима, 4',
        latitude: 55.812812,
        longitude: 49.108311,
        transitTip: 'Переезд на правый берег Казанки (метро / такси)',
      },
      {
        name: 'Экстрим-парк «УРАМ»',
        desc: 'Скейт, бетон и стрит-арт у воды - возьмите ветровку.',
        locationSlug: 'kazan-ekstrim-park-uram',
        mustSeeFilter: 'creative',
        visitMinutes: 60,
        latitude: 55.804112,
        longitude: 49.141511,
      },
      {
        name: 'Креативный кластер «Штаб»',
        desc: 'Финал в мастерских и кофе дизайн-кластера.',
        locationSlug: 'kazan-kreativnyy-klaster-shtab',
        mustSeeFilter: 'creative',
        visitMinutes: 60,
        address: 'ул. Татарстан, 20',
        latitude: 55.781912,
        longitude: 49.114411,
        transitTip: 'Возврат к слободе / Татарстан',
      },
    ],
  },
];

export const KAZAN_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Нужен ли загранпаспорт для поездки в Казань и на каком языке там все говорят?',
    a: 'Загранпаспорт не нужен: Казань - столица Республики Татарстан в составе РФ, въезд по обычному российскому паспорту. В городе два официальных языка - русский и татарский. Абсолютно все вывески, указатели и объявления в метро дублируются, а местные жители свободно говорят на русском.',
  },
  {
    q: 'Как работает единый билет в Казанский Кремль и что в него входит?',
    a: 'Территория самого Кремля и вход в мечеть Кул-Шариф полностью бесплатны. Платными являются только музеи внутри крепости (Музей ислама, «Эрмитаж-Казань», Музей истории). Выгодно покупать «Единый билет в музеи Кремля» онлайн - это экономит до 30% бюджета по сравнению с покупкой отдельных билетов в кассах.',
  },
  {
    q: 'Как быстрее всего добраться из Казани до острова Свияжск и Болгара?',
    a: 'В период навигации (с мая по октябрь) самый красивый и быстрый способ - скоростные теплоходы «Метеор» от Центрального речного порта Казани (до Свияжска около 40-60 минут, до Болгара - 2 часа 20 минут). Зимой до Свияжска ходят пригородные электрички и автобусы, до Болгара - рейсовые автобусы от Южного автовокзала.',
  },
  {
    q: 'Где в Казани попробовать самую правильную национальную татарскую еду?',
    a: 'Для быстрого знакомства с кыстыбыями и эчпочмаками выбирайте сеть татарского фастфуда «Тюбетей». За аутентичной купеческой атмосферой и сложными блюдами (ханский плов, вяленый гусь, шурпа) отправляйтесь в рестораны Старо-Татарской слободы или в этно-комплекс «Туган Авылым».',
  },
];

export const KAZAN_TRAVEL =
  'В международный аэропорт Казани имени Габдуллы Тукая ежедневно летают рейсы из Москвы (около 1,5 часа в полете) и регионов России. Из столицы также ходят двухэтажные поезда - около 11-12 часов в пути; на автомобиле по трассе М-12 «Восток» - примерно 6,5-7 часов. Лучший сезон - с мая по сентябрь: фонтаны, веранды на Баумана и удобные выезды на Свияжск и Болгар. Зимой Казань хороша иллюминацией Кремля и катками на Кремлевской набережной. По центру удобно пешком; до правого берега (Чаша, УРАМ) - метро или такси.';
