/** Novosibirsk tourist hub pack (owner 2026-08-16). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { NOVOSIBIRSK_LINE_DAY_ROUTE_PRESETS } from './novosibirsk-line-presets.ts';

export const NOVOSIBIRSK_MUST_SEE: any[] = [
  // --- Core / main ---
  {
    name: 'НОВАТ (Театр оперы и балета)',
    desc: 'Главный театр Сибири под серебристым чешуйчатым куполом - крупнейшее театральное здание России.',
    address: 'Красный проспект, 36',
    venueSlug: 'novosibirsk-novosibirskiy-teatr-opery-i-baleta-novat',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 55.030214,
    longitude: 82.924841,
  },
  {
    name: 'Михайловская набережная',
    desc: 'Двухуровневый променад вдоль Оби с видом на Коммунальный и Бугринский мосты.',
    address: 'ул. Обская, 2',
    locationSlug: 'novosibirsk-mihaylovskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 55.010214,
    longitude: 82.940115,
  },
  {
    name: 'Академгородок',
    desc: 'Научный анклав среди тайги: ручные белки, НГУ и технопарк «Гуси».',
    address: 'Академгородок',
    locationSlug: 'novosibirsk-akademgorodok',
    mustSeeFilter: 'main',
    visitMinutes: 180,
    latitude: 54.849202,
    longitude: 83.106209,
  },
  {
    name: 'Новосибирский зоопарк имени Р. А. Шило',
    desc: 'Один из крупнейших зоопарков России в сосновом бору, знаменит лиграми.',
    address: 'ул. Тимирязева, 71/1',
    locationSlug: 'novosibirsk-novosibirskiy-zoopark-imeni-r-a-shilo',
    mustSeeFilter: 'science',
    visitMinutes: 150,
    latitude: 55.053145,
    longitude: 82.884112,
  },
  {
    name: 'Новосибирский государственный художественный музей',
    desc: 'Русская классика и коллекция из 60 подлинных полотен Николая Рериха.',
    address: 'Красный проспект, 5',
    venueSlug: 'novosibirsk-novosibirskiy-hudozhestvennyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.018145,
    longitude: 82.924147,
  },
  {
    name: 'Музей мировой погребальной культуры',
    desc: 'Единственный в России музей смерти при крематории - траурные традиции разных веков.',
    address: 'пос. Восход, ул. Военторговская, 4/1',
    venueSlug: 'novosibirsk-muzey-mirovoy-pogrebal-noy-kul-tury',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.038415,
    longitude: 83.104112,
  },

  // --- Памятники и уличные арт-объекты (15) ---
  {
    name: 'Памятник Ленину и фигурам революции',
    desc: 'Монументальный бронзовый ансамбль на главной площади города.',
    address: 'Красный проспект, 36 (Площадь Ленина)',
    locationSlug: 'novosibirsk-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.030221,
    longitude: 82.920556,
  },
  {
    name: 'Памятник лабораторной мыши',
    desc: 'Мышь, вяжущая нить ДНК - благодарность ученых лабораторным животным в Академгородке.',
    address: 'ул. Академика Лаврентьева, 6/1',
    locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.849202,
    longitude: 83.106209,
  },
  {
    name: 'Памятник светофору',
    desc: 'Постовой у первого городского светофора - фирменная фототочка.',
    address: 'пересечение ул. Серебренниковской и Сибревкома',
    locationSlug: 'novosibirsk-pamyatnik-svetoforu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.023249,
    longitude: 82.925424,
  },
  {
    name: 'Скульптура «Вовка в Тридевятом царстве»',
    desc: 'Металлический мультгерой на троне у аллеи Экономического лицея.',
    address: 'ул. Крылова, 44',
    locationSlug: 'novosibirsk-vovka-v-tridevyatom-tsarstve',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.042312,
    longitude: 82.930411,
  },
  {
    name: 'Памятник трамваю №13',
    desc: 'Железный вагон-памятник самому аварийному и легендарному маршруту города.',
    address: 'ул. Мичурина, 2 (за Оперным театром)',
    locationSlug: 'novosibirsk-pamyatnik-tramvayu-13',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.031548,
    longitude: 82.924874,
  },
  {
    name: 'Памятник Высоцкому',
    desc: 'Бронзовый силуэт поэта с гитарой у театра «Глобус».',
    address: 'ул. Каменская, 1',
    locationSlug: 'novosibirsk-pamyatnik-vysotskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.026411,
    longitude: 82.930214,
  },
  {
    name: 'Арт-объект «Шпаргалка»',
    desc: 'Бетонная скамейка у НГУ, исписанная формулами и графиками.',
    address: 'ул. Коптюга, 4 (около НГУ)',
    locationSlug: 'novosibirsk-art-obekt-shpargalka',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.843622,
    longitude: 83.094511,
  },
  {
    name: 'Арка «Колокол мира»',
    desc: 'Белоснежная арка с колоколом - символ единения и мира.',
    address: 'ул. Коммунистическая, 38',
    locationSlug: 'novosibirsk-arka-kolokol-mira',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.023124,
    longitude: 82.920447,
  },
  {
    name: 'Памятник первому свиданию',
    desc: 'Влюбленная пара под часами - традиционное место встреч.',
    address: 'Красный проспект, 38',
    locationSlug: 'novosibirsk-pamyatnik-pervomu-svidaniyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.032115,
    longitude: 82.921245,
  },
  {
    name: 'Скульптурная композиция «Сцены из кукольных спектаклей»',
    desc: 'Сказочные башенки с бронзовыми персонажами у театра кукол.',
    address: 'ул. Ленина, 22',
    locationSlug: 'novosibirsk-stseny-iz-kukolnyh-spektakley',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.031201,
    longitude: 82.910245,
  },
  {
    name: 'Скульптура «Деловая женщина»',
    desc: 'Бизнес-леди за рабочим столом у офисного центра.',
    address: 'ул. Мичурина, 12б',
    locationSlug: 'novosibirsk-skulptura-delovaya-zhenschina',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.036541,
    longitude: 82.924115,
  },
  {
    name: 'Памятник швейной машинке «Зингер»',
    desc: 'Винтажная швейная техника перед фабрикой «Синар».',
    address: 'ул. Серебренниковская, 14',
    locationSlug: 'novosibirsk-pamyatnik-shveynoy-mashinke-zinger',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.022145,
    longitude: 82.926214,
  },
  {
    name: 'Памятник первому мосту через Обь',
    desc: 'Исторический пролет старого железнодорожного моста на набережной.',
    address: 'ул. Обская, 4',
    locationSlug: 'novosibirsk-pamyatnik-pervomu-mostu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.011245,
    longitude: 82.935147,
  },
  {
    name: 'Памятник архитектору Андрею Крячкову',
    desc: 'Зодчий конструктивизма и классики Новосибирска на площади Свердлова.',
    address: 'Площадь Свердлова',
    locationSlug: 'novosibirsk-pamyatnik-kryachkovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.018541,
    longitude: 82.922115,
  },
  {
    name: 'Памятник тосту «За здравие»',
    desc: 'Кованый трон из бутылок и рюмки - популярная фототочка.',
    address: 'ул. Каменская, 53',
    locationSlug: 'novosibirsk-pamyatnik-tostu-za-zdravie',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.038145,
    longitude: 82.931241,
  },

  // --- Историческое наследие (7) ---
  {
    name: 'Стоквартирный дом',
    desc: 'Шедевр постконструктивизма Крячкова - Гран-при Парижской выставки 1937 года.',
    address: 'Красный проспект, 16',
    locationSlug: 'novosibirsk-stokvartirnyy-dom',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.018142,
    longitude: 82.923145,
  },
  {
    name: 'Дом Ленина',
    desc: 'Здание на народные пожертвования, ныне - Филармония.',
    address: 'Красный проспект, 32',
    locationSlug: 'novosibirsk-dom-lenina',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.028451,
    longitude: 82.922145,
  },
  {
    name: 'Здание Городского торгового корпуса',
    desc: 'Модерн 1911 года - символ купеческого Ново-Николаевска, сегодня краеведческий музей.',
    address: 'Красный проспект, 23',
    locationSlug: 'novosibirsk-gorodskoy-torgovyy-korpus',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 55.029841,
    longitude: 82.920145,
  },
  {
    name: 'Особняк купца Крюкова',
    desc: 'Один из первых кирпичных жилых домов с нарядным фасадом.',
    address: 'ул. Советская, 25',
    locationSlug: 'novosibirsk-osobnyak-kryukova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.027145,
    longitude: 82.917412,
  },
  {
    name: 'Дом с часами',
    desc: 'Конструктивистский жилой дом галерейного типа - символ советского авангарда.',
    address: 'Красный проспект, 11',
    locationSlug: 'novosibirsk-dom-s-chasami',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.021145,
    longitude: 82.922415,
  },
  {
    name: 'Главпочтамт (Контора связи)',
    desc: 'Суровый конструктивизм с часами на углу главных пешеходных траекторий.',
    address: 'ул. Советская, 33',
    locationSlug: 'novosibirsk-glavpochtamt',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.030541,
    longitude: 82.918412,
  },
  {
    name: 'Железнодорожный вокзал «Новосибирск-Главный»',
    desc: 'Зеленый фасад в форме мчащегося на восток паровоза.',
    address: 'ул. Шамшурина, 43',
    locationSlug: 'novosibirsk-vokzal-novosibirsk-glavnyy',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 55.035142,
    longitude: 82.897415,
  },

  // --- Музеи (7) ---
  {
    name: 'Новосибирский государственный краеведческий музей',
    desc: 'История региона, скелет мамонта Матильда и шаманские артефакты.',
    address: 'Красный проспект, 23',
    venueSlug: 'novosibirsk-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.029854,
    longitude: 82.920214,
  },
  {
    name: 'Музей железнодорожной техники им. Н. А. Акулинина',
    desc: 'Паровозы, тепловозы и вагоны царских поездов под открытым небом.',
    address: 'ул. Шатурская, 2/2',
    locationSlug: 'novosibirsk-muzey-zheleznodorozhnoy-tehniki',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 54.851241,
    longitude: 83.056214,
  },
  {
    name: 'Музей «Сибирская береста»',
    desc: 'Ироничные и теплые арт-объекты из березовой коры.',
    address: 'ул. Свердлова, 21',
    locationSlug: 'novosibirsk-muzey-sibirskaya-beresta',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.019412,
    longitude: 82.918451,
  },
  {
    name: 'Музей солнца',
    desc: 'Маски и артефакты солярных культов народов мира.',
    address: 'ул. Дуси Ковальчук, 274',
    locationSlug: 'novosibirsk-muzey-solntsa',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.056541,
    longitude: 82.918114,
  },
  {
    name: 'Музей олимпийской славы',
    desc: 'Триумфы сибирских спортсменов - от Карелина до Подгорного.',
    address: 'ул. Советская, 33',
    locationSlug: 'novosibirsk-muzey-olimpiyskoy-slavy',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 55.030412,
    longitude: 82.918541,
  },

  // --- Храмы (6) ---
  {
    name: 'Собор во имя Александра Невского',
    desc: 'Краснокирпичный византийский храм - первое каменное здание города.',
    address: 'Красный проспект, 1а',
    locationSlug: 'novosibirsk-sobor-aleksandra-nevskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.016214,
    longitude: 82.924841,
  },
  {
    name: 'Вознесенский кафедральный собор',
    desc: 'Главный собор города с золотыми куполами.',
    address: 'ул. Советская, 91',
    locationSlug: 'novosibirsk-voznesenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.045412,
    longitude: 82.914115,
  },
  {
    name: 'Часовня во имя Святителя Николая Чудотворца',
    desc: 'Белоснежная часовня на Красном проспекте - бывший географический центр империи.',
    address: 'Красный проспект, 17а',
    locationSlug: 'novosibirsk-chasovnya-nikolaya',
    mustSeeFilter: 'temple',
    visitMinutes: 15,
    latitude: 55.025985,
    longitude: 82.921474,
  },
  {
    name: 'Храм Покрова Пресвятой Богородицы',
    desc: 'Старейшая деревянная церковь, уцелевшая в пожаре 1909 года.',
    address: 'ул. Октябрьская, 9',
    locationSlug: 'novosibirsk-hram-pokrova',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.021115,
    longitude: 82.916214,
  },
  {
    name: 'Католический Кафедральный собор Преображения Господня',
    desc: 'Неоготика из темного кирпича с модернистской крышей.',
    address: 'ул. Максима Горького, 100',
    locationSlug: 'novosibirsk-katolicheskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.028541,
    longitude: 82.928114,
  },
  {
    name: 'Новосибирская буддийская пагода (Дацан «Ринчин»)',
    desc: 'Буддийский храмовый комплекс с духом Бурятии в Сибири.',
    address: 'ул. Зеленая горка, 1/1а',
    locationSlug: 'novosibirsk-datsan-rinchin',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 54.881241,
    longitude: 83.071415,
  },

  // --- Парки и смотровые (оставшиеся) ---
  {
    name: 'Заельцовский парк',
    desc: 'Лесной эко-парк с вековыми соснами и детской железной дорогой.',
    address: 'ул. Парковая, 88',
    locationSlug: 'novosibirsk-zaeltsovskiy-park',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 55.051145,
    longitude: 82.843115,
  },
  {
    name: 'Центральный парк',
    desc: 'Старейший зеленый оазис со светомузыкальным фонтаном и летним театром.',
    address: 'ул. Мичурина, 8',
    locationSlug: 'novosibirsk-tsentralnyy-park',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 55.034142,
    longitude: 82.925412,
  },
  {
    name: 'Сквер Героев Революции',
    desc: 'Исторический сквер с факельной рукой, пробивающей мраморную скалу.',
    address: 'Красный проспект, 32в',
    locationSlug: 'novosibirsk-skver-geroev-revolyutsii',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 55.029141,
    longitude: 82.922115,
  },
  {
    name: 'Пляж «Звезда» и Обское море',
    desc: 'Песчаное побережье Новосибирского водохранилища с сосновым лесом.',
    address: 'Бердский тупик, 10',
    locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
    mustSeeFilter: 'park',
    visitMinutes: 120,
    latitude: 54.829145,
    longitude: 83.031142,
  },
  {
    name: 'Смотровая площадка у ТРЦ «Аура»',
    desc: 'Панорама на вантовый мост и огни вечернего центра.',
    address: 'ул. Вовоенная, 5',
    locationSlug: 'novosibirsk-smotrovaya-aura',
    mustSeeFilter: 'views',
    visitMinutes: 25,
    latitude: 55.026115,
    longitude: 82.937415,
  },

  // --- Гастрономия и театры (8) ---
  {
    name: 'Театр «Глобус»',
    desc: 'Модернистское здание-корабль молодежного театра.',
    address: 'ул. Каменская, 1',
    venueSlug: 'novosibirsk-teatr-globus',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 55.025145,
    longitude: 82.931214,
  },
  {
    name: 'Драматический театр «Красный факел»',
    desc: '«Сибирский МХАТ» в историческом здании Коммерческого собрания.',
    address: 'ул. Ленина, 19',
    venueSlug: 'novosibirsk-teatr-krasnyy-fakel',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 55.031145,
    longitude: 82.912415,
  },
  {
    name: 'Центр культуры и отдыха «Победа»',
    desc: 'Кинокомплекс в сталинском ампире с фестивальным кино.',
    address: 'ул. Ленина, 7',
    locationSlug: 'novosibirsk-tsentr-pobeda',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.030541,
    longitude: 82.916112,
  },
  {
    name: 'Ресторан «#СибирьСибирь»',
    desc: 'Новая сибирская кухня: строганина, пельмени с лосем и настойки.',
    address: 'ул. Ленина, 21',
    locationSlug: 'novosibirsk-restoran-sibir-sibir',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 55.031245,
    longitude: 82.911412,
  },
  {
    name: 'Гастрокорт на Центральном рынке',
    desc: 'Сотня корнеров кухонь мира и живая музыка по выходным.',
    address: 'ул. Мичурина, 12',
    locationSlug: 'novosibirsk-gastrokort-tsentralnyy-rynok',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 55.038412,
    longitude: 82.925145,
  },
  {
    name: 'Бар-хоппинг дворик на Ленина, 3',
    desc: 'Закрытый двор с крафтовыми барами и рюмочными.',
    address: 'ул. Ленина, 3 (внутренний двор)',
    locationSlug: 'novosibirsk-barnyy-dvorik-lenina-3',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 55.029985,
    longitude: 82.918114,
  },
  {
    name: 'Кафе-кондитерская «ИП Федосеев»',
    desc: 'Сибирские десерты, тарты и кедровый раф.',
    address: 'ул. Коммунистическая, 45',
    locationSlug: 'novosibirsk-kafe-ip-fedoseev',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 55.024412,
    longitude: 82.921145,
  },

  // --- Семейное (доп. к зоопарку) ---
  {
    name: 'Аквапарк Новосибирск',
    desc: 'Крупнейший крытый аквапарк страны (комплекс «Аквамир») с горками и волновым бассейном.',
    address: 'ул. Яринская, 8',
    locationSlug: 'novosibirsk-akvapark',
    mustSeeFilter: 'science',
    visitMinutes: 180,
    latitude: 55.042189,
    longitude: 82.903142,
  },
  {
    name: 'Парк чудес Галилео',
    desc: 'Интерактивный музей науки: опыты, иллюзии и зеркальный лабиринт.',
    address: 'ул. Добролюбова, 16А',
    locationSlug: 'novosibirsk-park-chudes-galileo',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 55.018942,
    longitude: 82.935124,
  },
  {
    name: 'Большой новосибирский планетарий',
    desc: 'Астрофизический центр с башней Фуко и звездным залом.',
    address: 'ул. Ключ-Камышенское Плато, 1/1',
    locationSlug: 'novosibirsk-bolshoy-planetariy',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 54.981242,
    longitude: 82.972145,
  },
  {
    name: 'Дельфиния',
    desc: 'Центр океанографии: акулы, экзотические рыбы и шоу с дельфинами.',
    address: 'ул. Жуковского, 100/4',
    locationSlug: 'novosibirsk-delfiniya',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 55.068214,
    longitude: 82.895123,
  },
];

export const NOVOSIBIRSK_SUBURBS: any[] = [
  {
    name: 'Академгородок',
    desc: 'Научный пригород среди тайги: НГУ, технопарк, ручные белки и Обское море.',
    address: 'Академгородок, Новосибирск',
    locationSlug: 'novosibirsk-akademgorodok',
    latitude: 54.849202,
    longitude: 83.106209,
    travelVector: 'Южный / Академгородок',
    travelVectorBlurb:
      'Электричка от «Новосибирск-Главный» до «Сеятель» или «Обское море» - дешевле и без пробок на Большевистской.',
    timingNote: 'Закладывайте полдня: мышь ДНК, «Шпаргалка», прогулка по Морской и закат у Обского моря.',
    places: [
      {
        name: 'Памятник лабораторной мыши',
        desc: 'Мышь, вяжущая ДНК - фотосимвол Академгородка.',
        locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
        latitude: 54.849202,
        longitude: 83.106209,
      },
      {
        name: 'Арт-объект «Шпаргалка»',
        desc: 'Скамейка с формулами у НГУ.',
        locationSlug: 'novosibirsk-art-obekt-shpargalka',
        latitude: 54.843622,
        longitude: 83.094511,
      },
      {
        name: 'Улица Морская',
        desc: 'Хай-тек и вековой лес в одном кадре.',
        locationSlug: 'novosibirsk-ulitsa-morskaya',
        dayRouteId: 'novosibirsk-suburb-ulitsa-morskaya',
        latitude: 54.8475,
        longitude: 83.0985,
      },
      {
        name: 'Пляж «Звезда» / Обское море',
        desc: 'Песчаный берег водохранилища - финал дня.',
        locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
        latitude: 54.829145,
        longitude: 83.031142,
        transitTip: 'Электричка или автобус к Обскому морю',
      },
    ],
  },
  {
    name: 'Сузун',
    desc: 'Заводской поселок с монетным двором Сибири: толчельня, музей и плотина на Нижнем Сузуне. Исторический выезд на юг области на весь день.',
    address: 'р.п. Сузун, ул. Ленина, 22А',
    locationSlug: 'novosibirsk-suzun',
    mustSeeFilter: 'main',
    visitMinutes: '6-8 ч',
    latitude: 53.781204,
    longitude: 82.311402,
    travelVector: 'Авто / автобус ~2,5 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль или автобус ~2,5 часа, чтобы приехать к 10:00 утра.',
    timingNote:
      'Трек вдоль Нижнего Сузуна к гидротехнической плотине, затем Монетный двор, толчельня и музейный квартал.',
    places: [
      {
        name: 'Толчельня',
        desc: 'Водяная толчея заводского комплекса: здесь дробили руду для сибирской меди.',
        locationSlug: 'novosibirsk-suzun-tolchelnya',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 25,
      },
      {
        name: 'Музей Монетный двор',
        desc: 'Музей на месте Сузунского монетного двора, где чеканили сибирскую монету.',
        locationSlug: 'novosibirsk-suzun-muzey-monetnyy-dvor',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 50,
        transitTip: 'От толчельни к музейному двору',
      },
      {
        name: 'Дом управляющего',
        desc: 'Исторический дом управляющего заводом в музейном квартале поселка.',
        locationSlug: 'novosibirsk-suzun-dom-upravlyayuschego',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 20,
      },
      {
        name: 'Сузунский бор',
        desc: 'Сосновый бор вокруг поселка - тенистая прогулка после музеев.',
        locationSlug: 'novosibirsk-suzun-bor',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 40,
      },
      {
        name: 'Памятник сибирской монете',
        desc: 'Памятник сибирской монете - фототочка у монетного двора.',
        locationSlug: 'novosibirsk-suzun-pamyatnik-sibirskoy-monete',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 10,
      },
      {
        name: 'Вознесенская церковь',
        desc: 'Вознесенская церковь поселка - ориентир на пути к плотине.',
        locationSlug: 'novosibirsk-suzun-voznesenskaya-tserkov',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 20,
      },
      {
        name: 'Гидротехническая плотина',
        desc: 'Плотина на Нижнем Сузуне: финал трека вдоль реки к заводскому каскаду.',
        locationSlug: 'novosibirsk-suzun-gidrotehnicheskaya-plotina',
        address: 'р.п. Сузун, ул. Ленина, 22А',
        latitude: 53.781204,
        longitude: 82.311402,
        visitMinutes: 25,
        transitTip: 'Вдоль Нижнего Сузуна к плотине',
      },
    ],
  },
  {
    name: 'Искитим / Ложок',
    desc: 'Святой ключ в Ложке: храм Новомучеников, источник, купели и музей Сиблага под открытым небом. Короткий выезд из Новосибирска на полдня.',
    address: 'мкр. Ложок, ул. Центральная, 1',
    locationSlug: 'novosibirsk-iskitim-lozhok',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 54.606811,
    longitude: 83.332304,
    travelVector: 'Электричка / авто ~1 ч 20 мин',
    travelVectorBlurb:
      'Закладывайте на электричку или автомобиль ~1 час 20 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'Святой ключ: храм и источник, затем купели, музей Сиблага и короткая лесная тропа.',
    places: [
      {
        name: 'Храм Новомучеников',
        desc: 'Храм Новомучеников и исповедников Церкви Русской у Святого ключа.',
        locationSlug: 'novosibirsk-iskitim-hram-novomuchenikov',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 25,
      },
      {
        name: 'Святой источник',
        desc: 'Святой источник в Ложке - главная точка паломнического выезда.',
        locationSlug: 'novosibirsk-iskitim-svyatoy-istochnik',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 20,
        transitTip: 'К источнику от храма',
      },
      {
        name: 'Купели',
        desc: 'Купели у источника: купание холодной водой даже летом.',
        locationSlug: 'novosibirsk-iskitim-kupeli',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 20,
      },
      {
        name: 'Музей Сиблага под открытым небом',
        desc: 'Музей Сиблага под открытым небом - лагерная история Искитимского района.',
        locationSlug: 'novosibirsk-iskitim-muzey-siblaga',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 40,
      },
      {
        name: 'Поклонный крест',
        desc: 'Поклонный крест над ложбиной источника.',
        locationSlug: 'novosibirsk-iskitim-poklonnyy-krest',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 10,
      },
      {
        name: 'Иконная лавка',
        desc: 'Иконная лавка при храме - свечи и просфоры после источника.',
        locationSlug: 'novosibirsk-iskitim-ikonnaya-lavka',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 15,
      },
      {
        name: 'Лесная тропа',
        desc: 'Короткая лесная тропа вокруг ключа и храма.',
        locationSlug: 'novosibirsk-iskitim-lesnaya-tropa',
        address: 'мкр. Ложок, ул. Центральная, 1',
        latitude: 54.606811,
        longitude: 83.332304,
        visitMinutes: 25,
      },
    ],
  },
  {
    name: 'Наукоград Кольцово',
    desc: 'Наукоград у Новосибирска: биотехнопарк, каскад прудов и парк с лебедями. Компактный выезд на маршрутке 322, не путать с Академгородком.',
    address: 'р.п. Кольцово, ул. Технопарковая, 1',
    locationSlug: 'novosibirsk-koltsovo',
    mustSeeFilter: 'main',
    visitMinutes: '3-4 ч',
    latitude: 54.939223,
    longitude: 83.184305,
    travelVector: 'Маршрутка 322 ~45 мин',
    travelVectorBlurb:
      'Маршрутка 322 от метро «Речной вокзал» или автомобиль ~45 минут, чтобы приехать к 10:00. Наукоград Кольцово - отдельный поселок у биотех-кластера.',
    timingNote:
      'По проспектам наукограда к каскаду прудов, селфи у ЦКП Биотехнопарка, затем парк, Аллея ученых и кофе.',
    places: [
      {
        name: 'Парк Кольцово',
        desc: 'Центральный парк наукограда с проспектами к каскаду прудов.',
        locationSlug: 'novosibirsk-koltsovo-park',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 35,
      },
      {
        name: 'Озеро с лебедями',
        desc: 'Озеро с лебедями - пауза между биотех-кластером и жилыми кварталами.',
        locationSlug: 'novosibirsk-koltsovo-ozero-s-lebedyami',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 20,
        transitTip: 'К каскаду прудов по проспектам',
      },
      {
        name: 'Здание ЦКП Биотехнопарка',
        desc: 'Здание ЦКП Биотехнопарка - селфи на фоне наукограда.',
        locationSlug: 'novosibirsk-koltsovo-ckp-biotehnoparka',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 20,
        transitTip: 'Селфи у биотехнопарка',
      },
      {
        name: 'Тропа здоровья',
        desc: 'Тропа здоровья кольцом по зелени поселка.',
        locationSlug: 'novosibirsk-koltsovo-tropa-zdorovya',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 30,
      },
      {
        name: 'Аллея ученых',
        desc: 'Аллея ученых - именные таблички и тенистая прогулка наукограда.',
        locationSlug: 'novosibirsk-koltsovo-alleya-uchenyh',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 20,
      },
      {
        name: 'Памятник Сандухчану',
        desc: 'Памятник Сандухчану - локальный якорь наукограда.',
        locationSlug: 'novosibirsk-koltsovo-pamyatnik-sandukhchanu',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 10,
      },
      {
        name: 'Кофейня «Академия кофе»',
        desc: 'Кофейня «Академия кофе»: крепкий раф в наукограде за Уралом после биотех-парка.',
        locationSlug: 'novosibirsk-koltsovo-akademiya-kofe',
        address: 'р.п. Кольцово, ул. Технопарковая, 1',
        latitude: 54.939223,
        longitude: 83.184305,
        visitMinutes: 30,
      },
    ],
  },
  {
    name: 'Бердские скалы, экотропа «Зверей и птиц»',
    desc: 'Экотропа у Бердских скал: подвесной мост через Бердь, скала Верблюд и родник Серебряный ключ. Выезд на внедорожнике к Новососедово в Искитимском районе.',
    address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
    locationSlug: 'novosibirsk-berdskie-skaly',
    mustSeeFilter: 'park',
    visitMinutes: '5-6 ч',
    latitude: 54.618054,
    longitude: 83.985831,
    travelVector: 'Внедорожник ~1 ч 40 мин',
    travelVectorBlurb:
      'Закладывайте на внедорожник ~1 час 40 минут, чтобы приехать к 09:30. Рядом с селом Новососедово, Искитимский район.',
    timingNote:
      'Экотропа «Зверей и птиц»: от Зверобоя и урочища Зверева к подвесному мосту через Бердь и скале Верблюд.',
    places: [
      {
        name: 'Зверобой',
        desc: 'Скальный выход Зверобой - старт экотропы «Зверей и птиц».',
        locationSlug: 'novosibirsk-berdskie-skaly-zveroboy',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 25,
      },
      {
        name: 'Урочище Зверева',
        desc: 'Урочище Зверева в Искитимском районе у Новососедово.',
        locationSlug: 'novosibirsk-berdskie-skaly-urochische-zvereva',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 20,
      },
      {
        name: 'Стенды экотропы',
        desc: 'Стенды экотропы про зверей и птиц Бердских скал.',
        locationSlug: 'novosibirsk-berdskie-skaly-stendy-ekotropy',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 15,
      },
      {
        name: 'Подвесной мост через Бердь',
        desc: 'Подвесной мост через Бердь - самый фотогеничный переход маршрута.',
        locationSlug: 'novosibirsk-berdskie-skaly-podvesnoy-most-berd',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 20,
        transitTip: 'К подвесному мосту по экотропе',
      },
      {
        name: 'Скала Верблюд',
        desc: 'Скала Верблюд над долиной - видовая точка тропы.',
        locationSlug: 'novosibirsk-berdskie-skaly-skala-verblyud',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 25,
      },
      {
        name: 'Родник Серебряный ключ',
        desc: 'Родник Серебряный ключ - вода и короткая остановка на тропе.',
        locationSlug: 'novosibirsk-berdskie-skaly-serebryanyy-klyuch',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 15,
      },
      {
        name: 'Зона отдыха',
        desc: 'Зона отдыха у тропы: пауза перед обратной дорогой на внедорожнике.',
        locationSlug: 'novosibirsk-berdskie-skaly-zona-otdyha',
        address: 'Новосибирская обл., Искитимский район, близ села Новососедово',
        latitude: 54.618054,
        longitude: 83.985831,
        visitMinutes: 20,
      },
    ],
  },
];

export const NOVOSIBIRSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'novosibirsk-classic-one-day',
    title: 'Классический Новосибирск за 1 день',
    description: 'НОВАТ, Красный проспект, набережная Оби и сибирская кухня.',
    coverImageUrl: '/images/venues/novosibirsk/novosibirskiy-teatr-opery-i-baleta-novat.jpg',
    stops: [
      {
        name: 'НОВАТ (Театр оперы и балета)',
        desc: 'Старт у купола',
        venueSlug: 'novosibirsk-novosibirskiy-teatr-opery-i-baleta-novat',
      },
      {
        name: 'Памятник Ленину и фигурам революции',
        desc: 'Площадь Ленина',
        locationSlug: 'novosibirsk-pamyatnik-leninu',
      },
      {
        name: 'Часовня во имя Святителя Николая Чудотворца',
        desc: 'Центр Красного проспекта',
        locationSlug: 'novosibirsk-chasovnya-nikolaya',
      },
      {
        name: 'Новосибирский государственный художественный музей',
        desc: 'Рерих и русская классика',
        venueSlug: 'novosibirsk-novosibirskiy-hudozhestvennyy-muzey',
      },
      {
        name: 'Ресторан «#СибирьСибирь»',
        desc: 'Обед сибирской кухни',
        locationSlug: 'novosibirsk-restoran-sibir-sibir',
      },
      {
        name: 'Михайловская набережная',
        desc: 'Закат над Обью',
        locationSlug: 'novosibirsk-mihaylovskaya-naberezhnaya',
      },
    ],
  },
  {
    id: 'novosibirsk-family-day',
    title: 'Новосибирск для всей семьи',
    description:
      'Зоопарк с лиграми, аквапарк, Галилео, планетарий и дельфинарий - главные точки с детьми.',
    timingNote: 'Не пытайтесь закрыть всё за день: выберите 2-3 точки и заложите трансферы.',
    coverImageUrl: '/images/venues/novosibirsk/novosibirskiy-zoopark-imeni-r-a-shilo.jpg',
    stops: [
      {
        name: 'Новосибирский зоопарк имени Р. А. Шило',
        desc: 'Лигры и сосновый бор',
        locationSlug: 'novosibirsk-novosibirskiy-zoopark-imeni-r-a-shilo',
        address: 'ул. Тимирязева, 71/1',
        latitude: 55.053145,
        longitude: 82.884112,
        mustSeeFilter: 'science',
        visitMinutes: 150,
      },
      {
        name: 'Аквапарк Новосибирск',
        desc: 'Крытый комплекс «Аквамир»',
        locationSlug: 'novosibirsk-akvapark',
        address: 'ул. Яринская, 8',
        latitude: 55.042189,
        longitude: 82.903142,
        mustSeeFilter: 'science',
        visitMinutes: 180,
        transitTip: 'Переезд к аквапарку',
      },
      {
        name: 'Парк чудес Галилео',
        desc: 'Интерактивная наука',
        locationSlug: 'novosibirsk-park-chudes-galileo',
        address: 'ул. Добролюбова, 16А',
        latitude: 55.018942,
        longitude: 82.935124,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к Галилео',
      },
      {
        name: 'Большой новосибирский планетарий',
        desc: 'Звездный зал и башня Фуко',
        locationSlug: 'novosibirsk-bolshoy-planetariy',
        address: 'ул. Ключ-Камышенское Плато, 1/1',
        latitude: 54.981242,
        longitude: 82.972145,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к планетарию',
      },
      {
        name: 'Дельфиния',
        desc: 'Шоу с дельфинами',
        locationSlug: 'novosibirsk-delfiniya',
        address: 'ул. Жуковского, 100/4',
        latitude: 55.068214,
        longitude: 82.895123,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к Дельфинии',
      },
    ],
  },
  {
    id: 'novosibirsk-akadem-day',
    title: 'День в Академгородке',
    description: 'Научный пригород: мышь ДНК, «Шпаргалка», Морская и Обское море.',
    travelVectorBlurb:
      'Электричка до «Сеятель» или «Обское море» - около 40 ₽ и без пробок на Большевистской.',
    coverImageUrl: '/images/venues/novosibirsk/akademgorodok.jpg',
    stops: [
      { name: 'Академгородок', desc: 'Въезд', locationSlug: 'novosibirsk-akademgorodok' },
      {
        name: 'Памятник лабораторной мыши',
        desc: 'Фотосимвол',
        locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
      },
      {
        name: 'Арт-объект «Шпаргалка»',
        desc: 'У НГУ',
        locationSlug: 'novosibirsk-art-obekt-shpargalka',
      },
      {
        name: 'Пляж «Звезда» и Обское море',
        desc: 'Финал у воды',
        locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
      },
    ],
  },
  ...NOVOSIBIRSK_LINE_DAY_ROUTE_PRESETS,
];

export const NOVOSIBIRSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что Новосибирский театр оперы и балета - самый большой в России?',
    a: 'Да, здание НОВАТ - крупнейший театральный комплекс страны: под его куполом мог бы поместиться московский Большой театр вместе с площадью.',
  },
  {
    q: 'Как добраться из центра до Академгородка без такси?',
    a: 'Пригородная электричка от вокзала «Новосибирск-Главный» до станций «Сеятель» или «Обское море» - самый дешевый и быстрый способ обойти пробки на Большевистской. Альтернатива - маршрутка №35 от метро «Речной вокзал».',
  },
  {
    q: 'Чем знаменит Новосибирский зоопарк имени Р. А. Шило?',
    a: 'Это один из крупнейших зоопарков России в сосновом бору. Его визитная карточка - успешное разведение редких кошачьих, включая лигров.',
  },
  {
    q: 'Где бесплатно посмотреть панораму Оби?',
    a: 'С верхней террасы Михайловской набережной у памятника Александру III на закате открывается вид на Коммунальный и Бугринский мосты - без платных смотровых в отелях.',
  },
  {
    q: 'Когда откроют станцию метро «Спортивная»?',
    a: 'Сроки снова сдвинули: «Спортивная» на левом берегу строится годами, и ориентироваться на обещанную дату не стоит. К ЛДС и «Арене» закладывайте автобус или такси, а не метро.',
  },
  {
    q: 'Почему в Академгородок лучше ехать на электричке, а не по Большевистской?',
    a: 'Большевистская по утрам и вечерам стоит глухо. Электричка от «Новосибирск-Главный» до «Сеятель» или «Обское море» обходит пробку и выходит дешевле такси.',
  },
  {
    q: 'Правда ли, что под НОВАТ есть секретный бункер?',
    a: 'Нет. Под куполом - резервуары противопожарного запаса воды, а не бомбоубежище. Экскурсии по «бункеру» - городская легенда.',
  },
  {
    q: 'Насколько опасны шторма на Обском море?',
    a: 'На водохранилище волны бывают 2,5-3 метра. В ветреный день купание и лодки без опыта - плохая идея; следите за прогнозом и держитесь пляжа «Звезда» у берега.',
  },
];

export const NOVOSIBIRSK_TRAVEL =
  'Крупнейший за Уралом аэропорт Толмачёво имени А. И. Покрышкина принимает ежедневные рейсы из Москвы (около 4 часов), Санкт-Петербурга и городов СНГ. Новосибирск - ключевой узел Транссиба с вокзалом «Новосибирск-Главный». Лучшее окно для визита - лето (июнь-август): набережная, Академгородок и Обское море. Зима морозная и снежная - время для НОВАТ, катка и крытого аквапарка.';
