import { SAMARA_LINE_DAY_ROUTE_PRESETS } from './samara-line-presets.ts';

/** Samara tourist hub pack (owner 2026-08-15). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export const SAMARA_MUST_SEE: any[] = [
  // --- Core / main ---
  {
    name: 'Самарская набережная',
    desc: 'Гигантский 5-километровый каскадный променад с песчаными пляжами прямо в центре.',
    address: 'ул. Максима Горького / Волжский проспект',
    locationSlug: 'samara-samarskaya-naberezhnaya',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 53.195611,
    longitude: 50.091211,
  },
  {
    name: 'Памятник ракете «Союз» (Музей «Самара Космическая»)',
    desc: 'Настоящая ракета «Союз» у фасада музея - самый фотографируемый символ города.',
    address: 'проспект Ленина, 21',
    venueSlug: 'samara-muzey-samara-kosmicheskaya',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 53.223112,
    longitude: 50.145611,
  },
  {
    name: 'Бункер Сталина',
    desc: 'Секретный объект глубиной 37 метров (1942) - экскурсии только с записью.',
    address: 'ул. Фрунзе, 167',
    locationSlug: 'samara-bunker-stalina',
    mustSeeFilter: 'secret',
    visitMinutes: 75,
    latitude: 53.196612,
    longitude: 50.101811,
  },
  {
    name: 'Жигулёвский пивоваренный завод',
    desc: 'Краснокирпичные корпуса XIX века, где варят то самое «Жигулёвское».',
    address: 'Волжский проспект, 4',
    locationSlug: 'samara-zhigulevskiy-pivovarennyy-zavod',
    mustSeeFilter: 'main',
    visitMinutes: 40,
    latitude: 53.201611,
    longitude: 50.098912,
  },
  {
    name: 'Улица Ленинградская',
    desc: 'Самарский Арбат: купеческие особняки, фонтаны и Дядя Стёпа.',
    address: 'ул. Ленинградская',
    locationSlug: 'samara-ulitsa-leningradskaya',
    mustSeeFilter: 'street',
    visitMinutes: 50,
    latitude: 53.188311,
    longitude: 50.091512,
  },
  {
    name: 'Площадь Славы и Амфитеатр',
    desc: 'Смотровая у Белого дома с каскадным поющим фонтаном.',
    address: 'ул. Молодогвардейская',
    locationSlug: 'samara-ploschad-slavy',
    mustSeeFilter: 'views',
    visitMinutes: 40,
    latitude: 53.202811,
    longitude: 50.113912,
  },

  // --- Monuments ---
  {
    name: 'Монумент Славы',
    desc: '13-метровый рабочий на 40-метровом пилоне с крыльями - символ авиастроителей.',
    address: 'Площадь Славы',
    locationSlug: 'samara-monument-slavy',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 53.203312,
    longitude: 50.113411,
  },
  {
    name: 'Памятник Григорию Засекину',
    desc: 'Бронзовый основатель Самарской крепости на коне со знаменем.',
    address: 'Полевой спуск (Набережная)',
    locationSlug: 'samara-pamyatnik-grigoriyu-zasekinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.210512,
    longitude: 50.124511,
  },
  {
    name: 'Памятник Товарищу Сухову',
    desc: 'Герой «Белого солнца пустыни», по сюжету родом из Самары.',
    address: 'Некрасовский спуск (Набережная)',
    locationSlug: 'samara-pamyatnik-tovarischu-suhovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.189412,
    longitude: 50.088311,
  },
  {
    name: 'Скульптура «Бурлаки на Волге»',
    desc: 'Бронзовая рамка-картина по Репину на фоне настоящей Волги.',
    address: 'Ленинградский спуск (Набережная)',
    locationSlug: 'samara-skulptura-burlaki-na-volge',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.187211,
    longitude: 50.084112,
  },
  {
    name: 'Памятник В. В. Куйбышеву',
    desc: 'Советский монумент революционеру, в честь которого город носил имя Куйбышев.',
    address: 'Площадь Куйбышева',
    locationSlug: 'samara-pamyatnik-kuybyshevu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.195211,
    longitude: 50.102211,
  },
  {
    name: 'Памятник Юрию Деточкину',
    desc: 'Герой «Берегись автомобиля» у музея Эльдара Рязанова.',
    address: 'ул. Фрунзе, 120',
    locationSlug: 'samara-pamyatnik-yuriyu-detochkinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.193112,
    longitude: 50.098911,
  },
  {
    name: 'Памятник Дяде Стёпе',
    desc: '5-метровая скульптура милиционера работы Церетели на Арбате.',
    address: 'ул. Ленинградская, 45',
    locationSlug: 'samara-pamyatnik-dyade-stepe',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.189112,
    longitude: 50.093112,
  },
  {
    name: 'Памятник отопительной батарее',
    desc: 'Кошка на окошке у Самарской ГРЭС - трут нос на удачу.',
    address: 'Волжский проспект, 8',
    locationSlug: 'samara-pamyatnik-otopitelnoy-bataree',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.202311,
    longitude: 50.100911,
  },
  {
    name: 'Памятник Петру и Февронии',
    desc: 'Покровители семьи в сквере у площади Славы.',
    address: 'Сквер 30-летия Победы',
    locationSlug: 'samara-pamyatnik-petru-i-fevronii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.202112,
    longitude: 50.111811,
  },
  {
    name: 'Скульптура «Дама с ракеткой»',
    desc: 'Модерновый памятник 100-летию самарского тенниса у Струковского сада.',
    address: 'ул. Куйбышева / Струковский сад',
    locationSlug: 'samara-skulptura-dama-s-raketkoy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.199411,
    longitude: 50.096411,
  },
  {
    name: 'Памятник Алексею Толстому',
    desc: 'Автор «Золотого ключика» у Литературного музея на Фрунзе.',
    address: 'ул. Фрунзе, 155',
    locationSlug: 'samara-pamyatnik-alekseyu-tolstomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.196912,
    longitude: 50.103912,
  },
  {
    name: 'Памятник Алеше Пешкову',
    desc: 'Молодой Горький - журналист «Самарской газеты».',
    address: 'ул. Фрунзе / Струковский сад',
    locationSlug: 'samara-pamyatnik-aleshe-peshkovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.198311,
    longitude: 50.093911,
  },
  {
    name: 'Скульптура «Князь Владимир»',
    desc: 'Памятник князю Владимиру на Софийской набережной.',
    address: 'Софийская набережная (4-я очередь)',
    locationSlug: 'samara-skulptura-knyaz-vladimir',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.212411,
    longitude: 50.128211,
  },
  {
    name: 'Памятник первому самарскому трамваю',
    desc: 'Исторический вагон начала XX века на рельсах у Полевой.',
    address: 'ул. Полевая / ул. Мичурина',
    locationSlug: 'samara-pamyatnik-pervomu-tramvayu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 53.213112,
    longitude: 50.141211,
  },

  // --- Museums / heritage ---
  {
    name: 'Самарский художественный музей',
    desc: 'Крупнейшее собрание живописи Поволжья в здании Волжско-Камского банка.',
    address: 'ул. Куйбышева, 92',
    locationSlug: 'samara-samarskiy-hudozhestvennyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 53.191412,
    longitude: 50.095411,
  },
  {
    name: 'Музей Модерна (Усадьба Курлиной)',
    desc: 'Единственный в России музей, целиком посвященный стилю модерн.',
    address: 'ул. Фрунзе, 159',
    locationSlug: 'samara-muzey-moderna-usadba-kurlinoy',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 53.197211,
    longitude: 50.104211,
  },
  {
    name: 'Самарский литературный музей им. М. Горького',
    desc: 'Усадьба, связанная с молодым Горьким и Алексеем Толстым.',
    address: 'ул. Фрунзе, 155',
    locationSlug: 'samara-literaturnyy-muzey-gorkogo',
    mustSeeFilter: 'literature',
    visitMinutes: 50,
    latitude: 53.196811,
    longitude: 50.103312,
  },
  {
    name: 'Музей Эльдара Рязанова',
    desc: 'Интерактивный музей в доме, где родился режиссер.',
    address: 'ул. Фрунзе, 120',
    locationSlug: 'samara-muzey-eldara-ryazanova',
    mustSeeFilter: 'museum',
    visitMinutes: 50,
    latitude: 53.193012,
    longitude: 50.098711,
  },
  {
    name: 'Особняк Клодта',
    desc: 'Сказочный теремок с башенками в духе немецкого ренессанса.',
    address: 'ул. Куйбышева, 139',
    locationSlug: 'samara-osobnyak-klodta',
    mustSeeFilter: 'mansions',
    visitMinutes: 25,
    latitude: 53.196112,
    longitude: 50.100512,
  },
  {
    name: 'Особняк Альфреда фон Вакано',
    desc: 'Резиденция основателя Жигулёвского пивзавода.',
    address: 'ул. Шостаковича, 3',
    locationSlug: 'samara-osobnyak-fon-vakano',
    mustSeeFilter: 'mansions',
    visitMinutes: 20,
    latitude: 53.197811,
    longitude: 50.099412,
  },
  {
    name: 'Краеведческий музей им. П. В. Алабина',
    desc: 'Монументальное здание с богатой исторической коллекцией.',
    address: 'ул. Ленинская, 142',
    locationSlug: 'samara-kraevedcheskiy-muzey-alabina',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 53.189312,
    longitude: 50.111811,
  },
  {
    name: 'Особняк Неронова',
    desc: 'Купеческий дом, где в эвакуации жила Светлана Аллилуева.',
    address: 'ул. Пионерская, 19',
    locationSlug: 'samara-osobnyak-neronova',
    mustSeeFilter: 'mansions',
    visitMinutes: 20,
    latitude: 53.184411,
    longitude: 50.086712,
  },

  // --- Architecture / temples ---
  {
    name: 'Католический костёл Пресвятого Сердца Иисуса',
    desc: 'Неоготический краснокирпичный собор со шпилями на Фрунзе.',
    address: 'ул. Фрунзе, 157',
    locationSlug: 'samara-katolicheskiy-kostel-presvyatogo-serdtsa-iisusa',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 53.196912,
    longitude: 50.103611,
  },
  {
    name: 'Лютеранская кирха Святого Георга',
    desc: 'Немецкая протестантская церковь на исторической Куйбышева.',
    address: 'ул. Куйбышева, 115',
    locationSlug: 'samara-lyuteranskaya-kirha',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 53.193312,
    longitude: 50.096711,
  },
  {
    name: 'Иверский женский монастырь',
    desc: 'Краснокирпичный комплекс на холме над Волгой.',
    address: 'Волжский проспект, 1',
    locationSlug: 'samara-iverskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 53.200511,
    longitude: 50.101112,
  },
  {
    name: 'Покровский кафедральный собор',
    desc: 'Византийский собор с лазурными куполами.',
    address: 'ул. Ленинская, 75',
    locationSlug: 'samara-pokrovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 53.186112,
    longitude: 50.108211,
  },
  {
    name: 'Самарская соборная мечеть',
    desc: 'Современный исламский центр с минаретом высотой 67 метров.',
    address: 'ул. Стара-Загора, 54',
    locationSlug: 'samara-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 53.220112,
    longitude: 50.198311,
  },
  {
    name: 'Здание Жигулёвского пивоваренного комбината',
    desc: 'Индустриальный шедевр немецкого барокко у Волги.',
    address: 'Волжский проспект, 4а',
    locationSlug: 'samara-zdanie-zhigulevskogo-kombinata',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 53.201211,
    longitude: 50.097511,
  },
  {
    name: 'Здание Крестьянского поземельного банка',
    desc: 'Северный модерн с неорусскими мотивами (ныне химтех).',
    address: 'ул. Куйбышева, 153',
    locationSlug: 'samara-krestyanskiy-pozemelnyy-bank',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 53.197811,
    longitude: 50.102112,
  },
  {
    name: 'Дом с атлантами (Особняк Шихобаловых)',
    desc: 'Фасад держат массивные фигуры атлантов.',
    address: 'ул. Венцека, 55',
    locationSlug: 'samara-dom-s-atlantami',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 53.185211,
    longitude: 50.089411,
  },
  {
    name: 'Фабрика-кухня завода ЗИМ',
    desc: 'Единственное здание в форме серпа и молота - филиал Третьяковки.',
    address: 'ул. Ново-Садовая, 149',
    locationSlug: 'samara-fabrika-kuhnya-zim',
    mustSeeFilter: 'creative',
    visitMinutes: 75,
    latitude: 53.222511,
    longitude: 50.149112,
  },
  {
    name: 'Дом-чемодан (управление СЖД)',
    desc: 'Монументальный конструктивизм у вокзала.',
    address: 'Комсомольская площадь, 2/3',
    locationSlug: 'samara-dom-chemodan',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 53.185611,
    longitude: 50.123312,
  },
  {
    name: 'Дом обороны',
    desc: 'Конструктивистское здание-корабль - стоп на маршруте к ракете.',
    address: 'ул. Самарская',
    locationSlug: 'samara-dom-oborony',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 53.1995,
    longitude: 50.1215,
  },

  // --- Embankments / parks ---
  {
    name: 'Струковский сад',
    desc: 'Старейший парк с фонтанами и спуском к Волге.',
    address: 'ул. Куйбышева, 2',
    locationSlug: 'samara-strukovskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 53.198912,
    longitude: 50.094411,
  },
  {
    name: 'Смотровая «Вертолётка»',
    desc: 'Панорама Жигулей с холма в посёлке Управленческий.',
    address: 'пос. Управленческий, ул. Ветлужская',
    locationSlug: 'samara-smotrovaya-vertolyotka',
    mustSeeFilter: 'views',
    visitMinutes: 90,
    latitude: 53.344411,
    longitude: 50.198311,
  },
  {
    name: 'Загородный парк',
    desc: 'Лесной массив со столетними дубами и спуском к Волге.',
    address: 'ул. Ново-Садовая, 150',
    locationSlug: 'samara-zagorodnyy-park',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 53.229112,
    longitude: 50.168311,
  },
  {
    name: 'Парк имени Юрия Гагарина',
    desc: 'Озеро, лебеди, аттракционы и колесо обозрения.',
    address: 'ул. Советской Армии, 181в',
    locationSlug: 'samara-park-gagarina',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 53.223312,
    longitude: 50.201211,
  },
  {
    name: 'Волжский пляж',
    desc: 'Песчаная полоса прямо на центральной набережной.',
    address: 'Волжский проспект',
    locationSlug: 'samara-volzhskiy-plyazh',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 53.204112,
    longitude: 50.108112,
  },
  {
    name: 'Ботанический сад Самарского университета',
    desc: 'Оранжереи и коллекция редких растений.',
    address: 'ул. Московское шоссе, 36',
    locationSlug: 'samara-botanicheskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 53.214411,
    longitude: 50.169112,
  },
  {
    name: 'Южный город / Парк Амфитеатр',
    desc: 'Новое урбан-пространство на юге Самары.',
    address: 'пос. Южный Город',
    locationSlug: 'samara-yuzhnyy-gorod-amfiteatr',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 53.109112,
    longitude: 50.151211,
  },

  // --- Gastro / culture ---
  {
    name: 'Театр драмы им. М. Горького',
    desc: '«Пряничный домик» в неорусском стиле на площади Чапаева.',
    address: 'ул. Фрунзе, 167',
    locationSlug: 'samara-teatr-dramy-gorkogo',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 53.196911,
    longitude: 50.099112,
  },
  {
    name: 'Пивной бар «На Дне»',
    desc: 'Легендарный розлив у стен Жигулёвского завода - очереди со своими бутылками.',
    address: 'Волжский проспект, 4/1',
    locationSlug: 'samara-pivnoy-bar-na-dne',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 53.200811,
    longitude: 50.098311,
  },
  {
    name: 'Ресторан «Ваще Огонь»',
    desc: 'Концептуальный мясной ресторан в историческом центре.',
    address: 'ул. Куйбышева, 81',
    locationSlug: 'samara-restoran-vasche-ogon',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 53.190812,
    longitude: 50.093311,
  },
  {
    name: 'Гриль-бар «По-чесноку»',
    desc: 'Ресторан у набережной с видом на Волгу.',
    address: 'ул. Максима Горького, 119',
    locationSlug: 'samara-gril-bar-po-chesnoku',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 53.189111,
    longitude: 50.083112,
  },
  {
    name: 'Театр оперы и балета',
    desc: 'Монументальный советский ампир на площади Куйбышева.',
    address: 'площадь Куйбышева, 1',
    locationSlug: 'samara-teatr-opery-i-baleta',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 53.195811,
    longitude: 50.100812,
  },
];

export const SAMARA_SUBURBS: any[] = [
  {
    name: 'Самарская Лука и село Ширяево',
    desc: 'Жигулёвский заповедник: Репин, штольни, горы и виды на Волгу.',
    locationSlug: 'samara-shiryaevo-samarskaya-luka',
    mustSeeFilter: 'main',
    visitMinutes: '6-8 ч',
    latitude: 53.416112,
    longitude: 50.017511,
    address:
      'Самарская область, Ставропольский район, национальный парк Самарская Лука, с. Ширяево',
    travelVector: 'Теплоход «Валдай» / ОМ ~40 мин',
    travelVectorBlurb:
      'Закладывайте на скоростной теплоход около 40 минут, чтобы приехать к 10 утра.',
    timingNote:
      'От пристани Ширяево вглубь к горам; штольни и смотровые - напоследок.',
    places: [
      {
        name: 'Музейный комплекс Ильи Репина',
        desc: 'Изба крестьянина Буянова, где художник жил летом 1870 года.',
        visitMinutes: 40,
      },
      {
        name: 'Попова гора',
        desc: 'Смотровая тропа и панорама Волги.',
        visitMinutes: 45,
      },
      {
        name: 'Ширяевские штольни',
        desc: 'Прохладные известняковые пещеры старых каменоломен.',
        visitMinutes: 50,
      },
      {
        name: 'Монастырская гора',
        desc: 'Холм вокруг села для пешего хайкинга.',
        visitMinutes: 40,
      },
      {
        name: 'Святой источник «Каменная чаша»',
        desc: 'Родник в овраге с часовней Николая Чудотворца.',
        visitMinutes: 30,
      },
      {
        name: 'Гора Стрельная',
        desc: 'Одна из высочайших точек Жигулей с металлическим настилом.',
        visitMinutes: 60,
      },
      {
        name: 'Пристань Ширяево',
        desc: 'Финал у воды в ожидании обратного теплохода.',
        visitMinutes: 20,
      },
    ],
  },
];

export const SAMARA_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'samara-resort-one-day',
    title: 'Самарский курорт',
    description:
      'Парадный день: Арбат, костёл и модерн, Струковский сад, Жигулёвский завод с «На Дне», Площадь Славы и закат на набережной.',
    travelVector: 'Парадный променад вдоль Волги',
    timingNote: 'Около 7-8 часов пешком по центру и набережной.',
    stops: [
      {
        name: 'Улица Ленинградская',
        desc: 'Старт среди купеческих особняков, фонтанов и Дяди Стёпы.',
        locationSlug: 'samara-ulitsa-leningradskaya',
        mustSeeFilter: 'street',
        visitMinutes: 60,
        latitude: 53.188311,
        longitude: 50.091512,
      },
      {
        name: 'Костёл и Музей Модерна',
        desc: 'Готические шпили и Усадьба Курлиной на Фрунзе.',
        locationSlug: 'samara-katolicheskiy-kostel-presvyatogo-serdtsa-iisusa',
        mustSeeFilter: 'temple',
        visitMinutes: 90,
        address: 'ул. Фрунзе, 157',
        latitude: 53.196912,
        longitude: 50.103611,
      },
      {
        name: 'Струковский сад',
        desc: 'Тенистый парк со спуском к берегу.',
        locationSlug: 'samara-strukovskiy-sad',
        mustSeeFilter: 'park',
        visitMinutes: 45,
        latitude: 53.198912,
        longitude: 50.094411,
      },
      {
        name: 'Жигулёвский завод и бар «На Дне»',
        desc: 'Свежее «Жигулёвское» с волжскими раками у стен завода.',
        locationSlug: 'samara-pivnoy-bar-na-dne',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'Волжский проспект, 4/1',
        latitude: 53.200811,
        longitude: 50.098311,
      },
      {
        name: 'Площадь Славы и Монумент',
        desc: 'Панорама у Белого дома и крылатый монумент.',
        locationSlug: 'samara-ploschad-slavy',
        mustSeeFilter: 'views',
        visitMinutes: 60,
        latitude: 53.202811,
        longitude: 50.113912,
      },
      {
        name: 'Самарская набережная',
        desc: 'Финал на песчаном пляже к волжскому закату.',
        locationSlug: 'samara-samarskaya-naberezhnaya',
        mustSeeFilter: 'main',
        visitMinutes: 90,
        latitude: 53.195611,
        longitude: 50.091211,
      },
    ],
  },
  {
    id: 'samara-space-constructivism',
    title: 'Космос и конструктивизм',
    description:
      'От Дома-чемодана и Дома обороны к ракете «Союз», фабрике-кухне ЗИМ и закату на Вертолётке.',
    travelVector: 'Советский авангард и ракета «Союз»',
    timingNote: 'Около 6-7 часов; на Вертолётку лучше на такси или автобусе.',
    stops: [
      {
        name: 'Дом-чемодан СЖД',
        desc: 'Старт у вокзала у геометричного конструктивизма.',
        locationSlug: 'samara-dom-chemodan',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        latitude: 53.185611,
        longitude: 50.123312,
      },
      {
        name: 'Дом обороны',
        desc: 'Здание-корабль советского авангарда.',
        locationSlug: 'samara-dom-oborony',
        mustSeeFilter: 'houses',
        visitMinutes: 40,
        latitude: 53.1995,
        longitude: 50.1215,
      },
      {
        name: 'Ракета «Союз»',
        desc: 'Фото у настоящей 68-метровой ракеты на Ленина, 21.',
        venueSlug: 'samara-muzey-samara-kosmicheskaya',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'проспект Ленина, 21',
        latitude: 53.223112,
        longitude: 50.145611,
        transitTip: 'Автобус / такси вдоль Ново-Садовой',
      },
      {
        name: 'Фабрика-кухня ЗИМ',
        desc: 'Серп и молот в плане здания - филиал Третьяковки.',
        locationSlug: 'samara-fabrika-kuhnya-zim',
        mustSeeFilter: 'creative',
        visitMinutes: 90,
        address: 'ул. Ново-Садовая, 149',
        latitude: 53.222511,
        longitude: 50.149112,
      },
      {
        name: 'Смотровая «Вертолётка»',
        desc: 'Закат над Жигулёвскими воротами с холма Управленческого.',
        locationSlug: 'samara-smotrovaya-vertolyotka',
        mustSeeFilter: 'views',
        visitMinutes: 120,
        latitude: 53.344411,
        longitude: 50.198311,
        transitTip: 'Переезд в пос. Управленческий (такси / автобус)',
      },
    ],
  },
  ...SAMARA_LINE_DAY_ROUTE_PRESETS,
];

export const SAMARA_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как работает знаменитый пивной бар «На Дне» и как там купить пиво?',
    a: 'Бар у стен Жигулёвского завода: классический зал с волжской кухней и окошко розлива «около завода». Очереди подскажут место - люди приходят со своими бутылками или покупают фирменные канистры. Пиво идет в краны напрямую по трубопроводу из цехов.',
  },
  {
    q: 'Правда ли, что в Самаре находится самый высокий железнодорожный вокзал в Европе?',
    a: 'Да. Здание из стекла и металла в виде космического корабля высотой со шпилем 86 метров. На 18 этаже (около 64 м) под куполом - открытая смотровая площадка с экскурсиями.',
  },
  {
    q: 'Пускают ли обычных туристов в секретный «Бункер Сталина»?',
    a: 'Да, но только в составе экскурсий по предварительной записи. Объект глубиной 37 метров под Академией культуры. Лифтов нет - спуск и подъем по винтовым лестницам на высоту 12 этажей.',
  },
  {
    q: 'Как удобнее всего передвигаться между очередями Самарской набережной?',
    a: 'Длина около 5 км, четыре очереди. Удобнее всего на электросамокатах или велосипедах: вдоль променада - широкая велодорожка. Пункты шеринга есть на каждом спуске к реке.',
  },
];

export const SAMARA_TRAVEL =
  'Международный аэропорт Курумоч имени С. П. Королёва принимает прямые рейсы из Москвы (около 1,5 часа в полете), Санкт-Петербурга и регионов. Также ходят двухэтажные поезда; на автомобиле - трасса М-5 «Урал». Лучший сезон - июнь-август: набережная работает как курорт, пляжи в центре, теплоходы в Жигули. Зимой - катки на площади Куйбышева и заснеженный променад. Центр удобен пешком; до ракеты и Вертолётки - автобус или такси.';
