/** Saratov tourist hub pack (owner 2026-08-21). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { SARATOV_LINE_DAY_ROUTE_PRESETS } from './saratov-line-presets.ts';

export const SARATOV_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник «Журавли»',
    desc: 'Величественный мемориал на вершине Соколовой горы, посвященный саратовцам, погибшим в ВОВ.',
    address: 'Парк Победы, Соколовая гора',
    locationSlug: 'saratov-pamyatnik-zhuravli',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 51.542289,
    longitude: 46.046342,
  },
  {
    name: 'Памятник Саратовской гармошке',
    desc: 'Бронзовый гармонист в кепке на проспекте, изнутри которого звучат переливы знаменитого инструмента.',
    address: 'просп. имени Петра Столыпина, 9',
    locationSlug: 'saratov-pamyatnik-garmoshke',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.531278,
    longitude: 46.033501,
  },
  {
    name: 'Памятник Юрию Гагарину',
    desc: 'Трехметровый бронзовый монумент первому космонавту, чья судьба связана со службой и учебой в Саратове.',
    address: 'Набережная Космонавтов, 4',
    locationSlug: 'saratov-pamyatnik-yuriyu-gagarinu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 51.527315,
    longitude: 46.048386,
  },
  {
    name: 'Скульптура «Огней так много золотых»',
    desc: 'Романтичный бронзовый юноша с букетом под часами - неофициальный гимн города из советского кино.',
    address: 'просп. имени Петра Столыпина, 15',
    locationSlug: 'saratov-skulptura-ogney-tak-mnogo-zolotyh',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.531702,
    longitude: 46.031548,
  },
  {
    name: 'Памятник Николаю Чернышевскому',
    desc: 'Монументальная фигура писателя и философа-демократа, уроженца Саратова, у входа в Липки.',
    address: 'площадь имени Н.Г. Чернышевского',
    locationSlug: 'saratov-pamyatnik-chernyshevskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.530351,
    longitude: 46.035411,
  },
  {
    name: 'Памятник Петру Столыпину',
    desc: 'Парадный монумент реформатору и бывшему саратовскому губернатору перед думой.',
    address: 'площадь имени Ф.А. Плеханова',
    locationSlug: 'saratov-pamyatnik-petru-stolypinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.531742,
    longitude: 46.037142,
  },
  {
    name: 'Памятник однополчанам (Связист и собака)',
    desc: 'Фронтовой арт-объект у ж/д вокзала: военный связист с верным псом.',
    address: 'Привокзальная площадь, 1',
    locationSlug: 'saratov-pamyatnik-odnopolchanam',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.541315,
    longitude: 46.002875,
  },
  {
    name: 'Арт-объект «Я люблю Саратов»',
    desc: 'Обязательная селфи-точка на обновленной Новой набережной с видом на Волгу.',
    address: 'Новая Набережная (в районе ул. Вольской)',
    locationSlug: 'saratov-ya-lyublyu-saratov',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.517312,
    longitude: 46.038144,
  },
  {
    name: 'Памятник Студенту',
    desc: 'Скульптура присевшего на лавочку студента перед корпусом экономического вуза.',
    address: 'ул. Радищева, 89',
    locationSlug: 'saratov-pamyatnik-studentu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.539344,
    longitude: 46.037142,
  },
  {
    name: 'Памятник Олегу Янковскому',
    desc: 'Бронзовая фигура актера в образе барона Мюнхгаузена на веревочной лестнице в небо.',
    address: 'ул. Киселева, 1',
    locationSlug: 'saratov-pamyatnik-olegu-yankovskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 51.533215,
    longitude: 46.021312,
  },
  {
    name: 'Скульптурная композиция «Хлеб всему голова»',
    desc: 'Арт-объект у аграрного университета в честь саратовского калача и хлеборобов.',
    address: 'ул. Чапаева, 56',
    locationSlug: 'saratov-skulptura-hleb-vsemu-golova',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.533722,
    longitude: 46.024515,
  },
  {
    name: 'Памятник Сердцу (Памятник Влюбленным)',
    desc: 'Кованая уличная ротонда-сердце на набережной - точка паломничества свадебных процессий.',
    address: 'Набережная Космонавтов, 1',
    locationSlug: 'saratov-pamyatnik-serdtsu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.523412,
    longitude: 46.053114,
  },
  {
    name: 'Памятник Строителю',
    desc: 'Монументальный уличный знак созидателям и архитекторам современного Саратова.',
    address: 'ул. Чернышевского, 60',
    locationSlug: 'saratov-pamyatnik-stroitelyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.516142,
    longitude: 45.999812,
  },
  {
    name: 'Бронзовый памятник первой учительнице',
    desc: 'Изящная скульптура царских времен в сквере у министерства образования.',
    address: 'ул. Соляная, 32',
    locationSlug: 'saratov-pamyatnik-pervoy-uchitelnitse',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.532345,
    longitude: 46.044122,
  },
  {
    name: 'Памятник Вавилову',
    desc: 'Строгий памятник ученому-генетику Николаю Вавилову, чей триумф и трагедия связаны с Саратовом.',
    address: 'площадь имени Н.И. Вавилова',
    locationSlug: 'saratov-pamyatnik-vavilovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.532915,
    longitude: 46.019125,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Здание Государственной Консерватории',
    desc: 'Архитектурный шедевр в стиле псевдоготики - визитная карточка города.',
    address: 'просп. имени Петра Столыпина, 1',
    locationSlug: 'saratov-konservatoriya-im-sobinova',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 51.530732,
    longitude: 46.035012,
  },
  {
    name: 'Особняк К. Рейнеке',
    desc: 'Памятник саратовского модерна работы Шехтеля с майоликовыми панно на фасаде.',
    address: 'ул. Соборная, 22',
    locationSlug: 'saratov-osobnyak-k-reyneke',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.528312,
    longitude: 46.038145,
  },
  {
    name: 'Крытый рынок',
    desc: 'Инженерное сооружение начала XX века с уникальным стеклянным куполом архитектора Люкшина.',
    address: 'ул. Чапаева, 59',
    locationSlug: 'saratov-krytyy-rynok',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 51.533612,
    longitude: 46.025345,
  },
  {
    name: 'Отель «Астория» (Волга)',
    desc: 'Историческое здание гостиницы 1917 года со скульптурами рыцарей и готическими пинаклями.',
    address: 'просп. имени Петра Столыпина, 34',
    locationSlug: 'saratov-otel-astoriya-volga',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.532314,
    longitude: 46.026122,
  },
  {
    name: 'Дом-коммуна «Инженер»',
    desc: 'Памятник советского конструктивизма 1930-х - образец жилой утопии нового быта.',
    address: 'ул. Провиантская, 7',
    locationSlug: 'saratov-dom-kommuna-inzhener',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.524125,
    longitude: 46.039345,
  },
  {
    name: 'Усадьба Чернышевского',
    desc: 'Мемориальный купеческий комплекс деревянных построек с садом, где родился писатель.',
    address: 'ул. Чернышевского, 142',
    locationSlug: 'saratov-usadba-chernyshevskogo',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 51.522125,
    longitude: 46.046122,
  },
  {
    name: 'Мельница Бореля',
    desc: 'Краснокирпичный индустриальный замок конца XIX века на берегу Волги.',
    address: 'ул. Чернышевского, 116',
    locationSlug: 'saratov-melnitsa-borelya',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 51.517315,
    longitude: 46.033125,
  },

  // --- Музеи (23-27) ---
  {
    name: 'Саратовский художественный музей имени А.Н. Радищева',
    desc: 'Первая публичная художественная галерея в провинции с шедеврами мирового уровня.',
    address: 'ул. Радищева, 39',
    locationSlug: 'saratov-hudozhestvennyy-muzey-radischeva',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 51.531644,
    longitude: 46.035926,
  },
  {
    name: 'Саратовский областной музей краеведения',
    desc: 'Крупнейшее хранилище истории края с коллекцией золотоордынских древностей Увекского городища.',
    address: 'ул. Лермонтова, 34',
    locationSlug: 'saratov-oblastnoy-muzey-kraevedeniya',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 51.530124,
    longitude: 46.046956,
  },
  {
    name: 'Музей стекла на заводе',
    desc: 'Богатая экспозиция хрусталя и художественного стекла со времен Российской империи.',
    address: 'ул. Ломоносова, 1',
    locationSlug: 'saratov-muzey-stekla-na-zavode',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 51.594239,
    longitude: 45.961188,
  },
  {
    name: 'Народный музей Ю.А. Гагарина',
    desc: 'Музей в стенах бывшего индустриального техникума, где учился первый космонавт.',
    address: 'ул. Сакко и Ванцетти, 15',
    locationSlug: 'saratov-narodnyy-muzey-gagarina',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 51.528093,
    longitude: 46.034025,
  },
  {
    name: 'Государственный музей К.А. Федина',
    desc: 'Музей истории русской литературы XX века в здании бывшей Сретенской школы.',
    address: 'ул. Чернышевского, 154',
    locationSlug: 'saratov-muzey-fedina',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 51.526307,
    longitude: 46.048838,
  },

  // --- Храмы (28-31) ---
  {
    name: 'Свято-Троицкий собор',
    desc: 'Старейшее каменное здание Саратова (конец XVII века) в стиле нарышкинского барокко.',
    address: 'ул. Лермонтова, 36',
    locationSlug: 'saratov-svyato-troitskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 51.530621,
    longitude: 46.0471,
  },
  {
    name: 'Храм «Утоли моя печали»',
    desc: 'Нарядный храм с разноцветными фигурными куполами в стиле собора Василия Блаженного.',
    address: 'ул. Волжская, 36',
    locationSlug: 'saratov-hram-utoli-moya-pechali',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.530348,
    longitude: 46.036516,
  },
  {
    name: 'Покровский собор',
    desc: 'Красно-белый собор с высокой пятиярусной колокольней - доминанта старого центра.',
    address: 'ул. Горького, 85',
    locationSlug: 'saratov-pokrovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.538001,
    longitude: 46.033454,
  },
  {
    name: 'Саратовская соборная мечеть',
    desc: 'Современный мусульманский комплекс с минаретами из двухцветного кирпича в саратовском стиле.',
    address: 'ул. Татарская, 10/12',
    locationSlug: 'saratov-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 51.542152,
    longitude: 46.048662,
  },

  // --- Парки / смотровые (32-39) ---
  {
    name: 'Городской сад «Липки»',
    desc: 'Старейший общественный парк города с вековыми дубами, основанный в 1824 году.',
    address: 'Соборная площадь, 1',
    locationSlug: 'saratov-gorodskoy-sad-lipki',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 51.529822,
    longitude: 46.033343,
  },
  {
    name: 'Парк Победы на Соколовой горе',
    desc: 'Мемориальный комплекс под открытым небом с гигантской выставкой военной техники.',
    address: 'Соколовая гора, Парк Победы',
    locationSlug: 'saratov-park-pobedy-na-sokolovoy-gore',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 51.543389,
    longitude: 46.044606,
  },
  {
    name: 'Набережная Космонавтов',
    desc: 'Четырехъярусный пешеходный променад вдоль Волги - визитная карточка города.',
    address: 'Набережная Космонавтов',
    locationSlug: 'saratov-naberezhnaya-kosmonavtov',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 51.526122,
    longitude: 46.050118,
  },
  {
    name: 'Новая Набережная',
    desc: 'Обновленное прогулочное пространство с пляжем, спортплощадками и велодорожками.',
    address: 'Новая Набережная',
    locationSlug: 'saratov-novaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 51.514445,
    longitude: 46.03351,
  },
  {
    name: 'Городской парк имени Горького',
    desc: 'Ландшафтный парк с системой вековых дубовых прудов и лебедями.',
    address: 'ул. Чернышевского, 177/181',
    locationSlug: 'saratov-park-imeni-gorkogo',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 51.513703,
    longitude: 46.012105,
  },
  {
    name: 'Смотровая площадка у аэропорта «Центральный»',
    desc: 'Панорамная точка ночного города с видом на Глебучев овраг и Волгу.',
    address: 'площадь Аэропорта, 1',
    locationSlug: 'saratov-smotrovaya-aeroport-tsentralnyy',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 51.554076,
    longitude: 46.030605,
  },
  {
    name: 'Кумысная поляна (Смотровая «Завокзальная»)',
    desc: 'Лесной массив на Лысогорском плато с дикими тропами и видами на весь Саратов.',
    address: 'Лысогорское плато, Кумысная поляна',
    locationSlug: 'saratov-kumysnaya-polyana',
    mustSeeFilter: 'views',
    visitMinutes: 90,
    latitude: 51.536345,
    longitude: 45.952456,
  },
  {
    name: 'Детский парк',
    desc: 'Уютная зеленая зона в центре с детскими городками, фонтанами и спортивными треками.',
    address: 'ул. Астраханская, 1С',
    locationSlug: 'saratov-detskiy-park',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 51.530436,
    longitude: 46.01292,
  },

  // --- Гастрономия и театры (40-49) ---
  {
    name: 'Саратовский академический театр оперы и балета',
    desc: 'Один из старейших музыкальных театров России с традициями классической школы.',
    address: 'Театральная площадь, 1',
    locationSlug: 'saratov-teatr-opery-i-baleta',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 51.532464,
    longitude: 46.034303,
  },
  {
    name: 'Саратовский ТЮЗ имени Ю.П. Киселева (Новая сцена)',
    desc: 'Первый в мире профессиональный театр для детей в футуристичном здании.',
    address: 'площадь им. Ю.П. Киселева, 1',
    locationSlug: 'saratov-tyuz-im-kiseleva',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 51.533442,
    longitude: 46.019165,
  },
  {
    name: 'Ресторан «SOHO»',
    desc: 'Премиальный гастрономический ресторан авторской кухни на пешеходном кольце города.',
    address: 'просп. имени Петра Столыпина, 2',
    locationSlug: 'saratov-restoran-soho',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 51.531115,
    longitude: 46.035602,
  },
  {
    name: 'Гастробар «Культура»',
    desc: 'Модное пространство с упором на локальные волжские продукты и крафтовые напитки.',
    address: 'просп. имени Петра Столыпина, 12',
    locationSlug: 'saratov-gastrobar-kultura',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 51.531631,
    longitude: 46.031112,
  },
  {
    name: 'Ресторан «Одесса»',
    desc: 'Заведение на набережной с панорамными окнами на Волгу и рыбным меню.',
    address: 'Набережная Космонавтов, 3',
    locationSlug: 'saratov-restoran-odessa',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 51.526456,
    longitude: 46.050619,
  },
  {
    name: 'Ресторан «Реноме»',
    desc: 'Элегантный ресторан высокой кухни в историческом здании старого Саратова.',
    address: 'ул. Горького, 28',
    locationSlug: 'saratov-restoran-renome',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 51.528823,
    longitude: 46.031817,
  },
  {
    name: 'Кофейня «Coupe»',
    desc: 'Локальный спешелти-кофе-рум у здания Консерватории с сильными десертами.',
    address: 'ул. Радищева, 32',
    locationSlug: 'saratov-kofeynya-coupe',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 51.530043,
    longitude: 46.035501,
  },
  {
    name: 'Саратовская областная филармония им. Шнитке',
    desc: 'Главная академическая концертная площадка региона имени великого земляка-композитора.',
    address: 'Соборная площадь, 9',
    locationSlug: 'saratov-filarmoniya-im-shnitke',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 51.529166,
    longitude: 46.035921,
  },
  {
    name: 'Ресторан «Морковь»',
    desc: 'Семейное заведение с современной русской и европейской кухней в центре города.',
    address: 'просп. имени Петра Столыпина, 46',
    locationSlug: 'saratov-restoran-morkov',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 51.53389,
    longitude: 46.022455,
  },
  {
    name: 'Кафе «Арабелла»',
    desc: 'Морское концепт-кафе с традиционной кухней и волжскими деликатесами.',
    address: 'ул. Радищева, 18',
    locationSlug: 'saratov-kafe-arabella',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 51.525788,
    longitude: 46.039875,
  },
  {
    name: 'Театр драмы имени И.А. Слонова',
    desc: 'Крупнейшая драматическая сцена города с авангардными и классическими постановками.',
    address: 'ул. Рабочая, 116',
    locationSlug: 'saratov-teatr-dramy-im-slonova',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 51.531421,
    longitude: 46.009456,
  },

  // --- 50: мост как архитектурный символ ---
  {
    name: 'Автодорожный мост Саратов-Энгельс',
    desc: 'Почти трехкилометровый мост с «горбами» - главный урбанистический силуэт региона над Волгой.',
    address: 'Автодорожный мост Саратов-Энгельс',
    locationSlug: 'saratov-avtodorozhnyy-most-saratov-engel-s',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 51.5215,
    longitude: 46.0558,
  },
];

export const SARATOV_SUBURBS: any[] = [
  {
    name: 'Место приземления Юрия Гагарина / Парк покорителей космоса',
    desc: 'Степной хаб под Энгельсом, где 12 апреля 1961 года приземлился первый космонавт. Сегодня - архитектурный парк со стелой-ракетой, капсулой «Восток-1» и Стеной славы.',
    locationSlug: 'saratov-mesto-prizemleniya-gagarina',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 51.280456,
    longitude: 45.993412,
    address: 'Саратовская область, Энгельсский район, с. Смеловка',
    travelVector: 'Автобус 246 / экспресс ~1 ч 15 мин',
    travelVectorBlurb:
      'Закладывайте на автобус №246 или пригородный экспресс из Саратова ~1 час 15 минут, чтобы приехать к 09:30 утра.',
    timingNote:
      'По центральной мемориальной аллее двигайтесь строго на юг к исторической стеле-ракете, напоследок оставив осмотр капсулы корабля «Восток-1».',
    places: [
      {
        name: 'Мемориальная стела',
        desc: '27-метровый обелиск в виде стального шлейфа ракеты.',
        locationSlug: 'saratov-gagarin-memorialnaya-stela',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 20,
      },
      {
        name: 'Памятник Юрию Гагарину',
        desc: 'Центровой монумент первому космонавту в скафандре на месте приземления.',
        locationSlug: 'saratov-gagarin-pamyatnik-na-meste-prizemleniya',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 20,
      },
      {
        name: 'Мемориальная стена',
        desc: 'Гранитная инсталляция с хронологией освоения космоса.',
        locationSlug: 'saratov-gagarin-memorialnaya-stena',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 20,
      },
      {
        name: 'Площадь Космонавтов',
        desc: 'Круглая парадная площадь с цитатами Циолковского в брусчатке.',
        locationSlug: 'saratov-gagarin-ploschad-kosmonavtov',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 15,
      },
      {
        name: 'Капсула «Восток-1»',
        desc: 'Точная копия спускаемого аппарата, в котором Гагарин вернулся на Землю.',
        locationSlug: 'saratov-gagarin-kapsula-vostok-1',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 25,
      },
      {
        name: 'Аллея кедров',
        desc: 'Хвойные посадки, символизирующие позывной первого космонавта («Кедр»).',
        locationSlug: 'saratov-gagarin-alleya-kedrov',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 15,
      },
      {
        name: 'Смотровая площадка на Волгу',
        desc: 'Панорамная точка на степные просторы, куда летел космонавт на парашюте.',
        locationSlug: 'saratov-gagarin-smotrovaya-na-volgu',
        address: 'Саратовская область, Энгельсский район, с. Смеловка',
        latitude: 51.280456,
        longitude: 45.993412,
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Утёс Степана Разина',
    desc: 'Белые меловые обрывы над Волгоградским водохранилищем. По легендам - лагерь атамана, откуда выслеживали купеческие корабли.',
    locationSlug: 'saratov-utes-stepana-razina',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 50.615112,
    longitude: 45.658341,
    address: 'Красноармейский район, с. Белогорское',
    travelVector: 'Авто / внедорожный трансфер ~1 ч 45 мин',
    travelVectorBlurb:
      'Закладывайте на личный автомобиль или внедорожный трансфер ~1 час 45 минут, чтобы приехать к 08:30 утра.',
    timingNote:
      'По гребню мелового обрыва двигайтесь вдоль береговой линии Волги к Дурман-горе, напоследок оставив спуск в Тюрьму Стеньки Разина.',
    places: [
      {
        name: 'Меловые обрывы утеса',
        desc: 'Белые скалы, обрывающиеся прямо в Волгу.',
        locationSlug: 'saratov-razin-melovye-obryvy',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 30,
      },
      {
        name: 'Дурман-гора',
        desc: 'Высочайшая точка гряды, где по легендам разбойники жгли сигнальные костры.',
        locationSlug: 'saratov-razin-durman-gora',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 25,
      },
      {
        name: 'Пещера Степана Разина',
        desc: 'Карстовый грот, где атаман якобы прятал царское золото.',
        locationSlug: 'saratov-razin-peschera-stepana-razina',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 20,
      },
      {
        name: 'Ущелье «Тюрьма»',
        desc: 'Глубокий овраг, где разбойники удерживали пленных купцов.',
        locationSlug: 'saratov-razin-uschele-tyurma',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 20,
      },
      {
        name: 'Старинная печь для обжига',
        desc: 'Остатки дореволюционного индустриального промысла у подножия холма.',
        locationSlug: 'saratov-razin-starinnaya-pech-obzhiga',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 15,
      },
      {
        name: 'Поворот «Старая Волга»',
        desc: 'Место максимального разлива реки - иллюзия бескрайнего океана.',
        locationSlug: 'saratov-razin-povorot-staraya-volga',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 20,
      },
      {
        name: 'Остатки лагеря археологов',
        desc: 'Тематический палаточный спот на диком пляже.',
        locationSlug: 'saratov-razin-lager-arheologov',
        address: 'Красноармейский район, с. Белогорское',
        latitude: 50.615112,
        longitude: 45.658341,
        visitMinutes: 15,
      },
    ],
  },
];

export const SARATOV_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'saratov-nemetskiy-prospekt',
    title: 'Немецкий проспект и Золотые купола',
    description:
      'Линейный трек по главному пешеходному кольцу: от Крытого рынка и «Астории» через Консерваторию и Липки к Троицкому собору и Набережной Космонавтов.',
    travelVector: 'Парадный пешеходный променад',
    timingNote:
      'Около 3,5-4 часов: рынок - гармошка - «Огней так много» - Консерватория - Липки - «Культура» - набережная.',
    coverImageUrl: '/images/venues/saratov/prospekt-stolypina.jpg',
    stops: [
      {
        name: 'Крытый рынок',
        desc: '20 минут на осмотр торгового дворца с часами и куполом Люкшина.',
        locationSlug: 'saratov-krytyy-rynok',
        mustSeeFilter: 'houses',
        visitMinutes: 20,
        address: 'ул. Чапаева, 59',
        latitude: 51.533612,
        longitude: 46.025345,
      },
      {
        name: 'Отель «Астория» и Памятник гармошке',
        desc: '15 минут на фото у готического отеля и прослушивание мелодий гармониста.',
        locationSlug: 'saratov-pamyatnik-garmoshke',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'просп. имени Петра Столыпина, 9',
        latitude: 51.531278,
        longitude: 46.033501,
        transitTip: 'Пешком 2 минуты (150 метров)',
      },
      {
        name: 'Скульптура «Огней так много золотых»',
        desc: '10 минут на фото у культового памятника под часами.',
        locationSlug: 'saratov-skulptura-ogney-tak-mnogo-zolotyh',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'просп. имени Петра Столыпина, 15',
        latitude: 51.531702,
        longitude: 46.031548,
        transitTip: 'Пешком 5 минут (400 метров)',
      },
      {
        name: 'Консерватория им. Собинова и Храм «Утоли моя печали»',
        desc: '25 минут на готические шпили консерватории и разноцветные купола храма.',
        locationSlug: 'saratov-konservatoriya-im-sobinova',
        mustSeeFilter: 'houses',
        visitMinutes: 25,
        address: 'просп. имени Петра Столыпина, 1',
        latitude: 51.530732,
        longitude: 46.035012,
        transitTip: 'Пешком 7 минут (550 метров)',
      },
      {
        name: 'Городской сад «Липки» и Памятник Чернышевскому',
        desc: '30 минут по вековым аллеям купеческого сада.',
        locationSlug: 'saratov-gorodskoy-sad-lipki',
        mustSeeFilter: 'park',
        visitMinutes: 30,
        address: 'Соборная площадь, 1',
        latitude: 51.529822,
        longitude: 46.033343,
        transitTip: 'Пешком 3 минуты (200 метров)',
      },
      {
        name: 'Обед в Гастробаре «Культура»',
        desc: 'Час на крафтовые настойки и блюда из локальной волжской рыбы.',
        locationSlug: 'saratov-gastrobar-kultura',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'просп. имени Петра Столыпина, 12',
        latitude: 51.531631,
        longitude: 46.031112,
        transitTip: 'Пешком 5 минут (400 метров)',
      },
      {
        name: 'Свято-Троицкий собор и Набережная Космонавтов',
        desc: '40 минут: старейший храм XVII века и вечерний променад с видом на мост.',
        locationSlug: 'saratov-naberezhnaya-kosmonavtov',
        mustSeeFilter: 'views',
        visitMinutes: 40,
        address: 'Набережная Космонавтов',
        latitude: 51.526122,
        longitude: 46.050118,
        transitTip: 'Пешком 8 минут (650 метров)',
      },
    ],
  },
  {
    id: 'saratov-volga-sokolova',
    title: 'Волга, мост и Соколова гора',
    description:
      'Видовой день: Набережная Космонавтов и мост, Радищевский музей, Парк Победы с «Журавлями» и закат на Новой набережной.',
    travelVector: 'Набережная и смотровые',
    timingNote: 'Около 4-5 часов; на Соколову гору удобнее коротким подъемом или такси.',
    coverImageUrl: '/images/venues/saratov/park-pobedy-na-sokolovoy-gore.jpg',
    stops: [
      {
        name: 'Набережная Космонавтов и памятник Гагарину',
        desc: '40 минут променада вдоль Волги у трехметрового космонавта.',
        locationSlug: 'saratov-naberezhnaya-kosmonavtov',
        mustSeeFilter: 'views',
        visitMinutes: 40,
        address: 'Набережная Космонавтов',
        latitude: 51.526122,
        longitude: 46.050118,
      },
      {
        name: 'Автодорожный мост Саратов-Энгельс',
        desc: '20 минут на силуэт «горбов» и закатные кадры с нижней набережной.',
        locationSlug: 'saratov-avtodorozhnyy-most-saratov-engel-s',
        mustSeeFilter: 'views',
        visitMinutes: 20,
        address: 'Автодорожный мост Саратов-Энгельс',
        latitude: 51.5215,
        longitude: 46.0558,
        transitTip: 'Пешком вдоль набережной ~10 минут',
      },
      {
        name: 'Саратовский художественный музей имени А.Н. Радищева',
        desc: '90 минут в «Поволжском Эрмитаже».',
        locationSlug: 'saratov-hudozhestvennyy-muzey-radischeva',
        mustSeeFilter: 'museum',
        visitMinutes: 90,
        address: 'ул. Радищева, 39',
        latitude: 51.531644,
        longitude: 46.035926,
        transitTip: 'Пешком / трамвай к центру ~15 минут',
      },
      {
        name: 'Парк Победы и памятник «Журавли»',
        desc: '60 минут мемориала и военной техники на Соколовой горе.',
        locationSlug: 'saratov-park-pobedy-na-sokolovoy-gore',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'Соколовая гора, Парк Победы',
        latitude: 51.543389,
        longitude: 46.044606,
        transitTip: 'Такси или автобус на Соколову гору ~20 минут',
      },
      {
        name: 'Ресторан «Одесса»',
        desc: 'Час обеда с панорамой Волги.',
        locationSlug: 'saratov-restoran-odessa',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'Набережная Космонавтов, 3',
        latitude: 51.526456,
        longitude: 46.050619,
        transitTip: 'Спуск к набережной ~20 минут',
      },
      {
        name: 'Новая Набережная и «Я люблю Саратов»',
        desc: '30 минут финального променада и селфи у арт-объекта.',
        locationSlug: 'saratov-ya-lyublyu-saratov',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'Новая Набережная (в районе ул. Вольской)',
        latitude: 51.517312,
        longitude: 46.038144,
        transitTip: 'Пешком по набережной ~12 минут',
      },
    ],
  },
  ...SARATOV_LINE_DAY_ROUTE_PRESETS,
];

export const SARATOV_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как удобнее добраться до места приземления Гагарина под Энгельсом?',
    a: 'Закладывайте около 1 часа 15 минут на автобус №246 или пригородный экспресс из Саратова. Приезжайте к 09:30: сначала мемориальная аллея и стела-ракета, капсулу «Восток-1» оставьте напоследок. Электрички от ж/д вокзала обычно дешевле междугороднего такси.',
  },
  {
    q: 'Стоит ли ехать к утесу Степана Разина без своего автомобиля?',
    a: 'Лучше на личном авто или внедорожном трансфере (~1 час 45 минут до с. Белогорское). Общественный транспорт редкий, а трек идет по гребню мелового обрыва к Дурман-горе и «Тюрьме» Стеньки Разина. Выезжайте рано, к 08:30 утра.',
  },
  {
    q: 'Где в Саратове попробовать настоящий калач, а не туристический сувенир?',
    a: 'Местные берут свежие мини-калачи и сочню в кулинариях у Крытого рынка на ул. Чапаева. Для «ресторанной» версии волжской рыбы и стерляди - гастробар «Культура» на проспекте Столыпина или «Одесса» на Набережной Космонавтов.',
  },
  {
    q: 'Какой бесплатный вид на город лучше смотровой у старого аэропорта?',
    a: 'Секрет местных - смотровая «Завокзальная» на склоне Кумысной поляны. Обзор на ночной город, мост и Волгу шире, вход на экотропу бесплатный. Смотровая у аэропорта «Центральный» шумнее и чаще переполнена экскурсиями.',
  },
];

export const SARATOV_TRAVEL =
  'Саратов удобно брать поездом или через аэропорт Гагарин. Лучшее окно - май-сентябрь: навигация теплоходов, сапы под мостом, пляжи Городских песков и выезды к месту приземления Гагарина и утесу Степана Разина. Весной (+18 °C к маю) город цветет каштанами и сиренью. Осенью (+20 °C в сентябре) - арбузы, золото Кумысной поляны и музеи. Зимой - коньки у «Динамо», купеческий центр и горнолыжка в Хвалынске. В городе окупаются карта «Поехали», бесплатный четверг в Радищевском музее и прогулки по Зеленой и Красной линиям.';
