/** Smolensk tourist hub pack (owner 2026-08-22). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { SMOLENSK_LINE_DAY_ROUTE_PRESETS } from './smolensk-line-presets.ts';

function place(
  name: string,
  desc: string,
  latitude: number,
  longitude: number,
  opts: {
    address: string;
    locationSlug?: string;
    venueSlug?: string;
    mustSeeFilter?: string;
    visitMinutes?: number | string;
    alsoMain?: boolean;
  },
): any {
  return {
    name,
    desc,
    address: opts.address,
    latitude,
    longitude,
    mustSeeFilter: opts.mustSeeFilter || 'main',
    visitMinutes: opts.visitMinutes ?? 20,
    ...(opts.locationSlug ? { locationSlug: opts.locationSlug } : {}),
    ...(opts.venueSlug ? { venueSlug: opts.venueSlug } : {}),
    ...(typeof opts.alsoMain === 'boolean' ? { alsoMain: opts.alsoMain } : {}),
  };
}

export const SMOLENSK_MUST_SEE: any[] = [
  place('Памятник «Благодарная Россия героям 1812 года» (Памятник с орлами)', 'Монумент с бронзовыми орлами в сквере Памяти Героев - главный символ смоленского мужества 1812 года.', 54.781831, 32.046049, { address: 'сквер Памяти Героев', locationSlug: 'smolensk-pamyatnik-blagodarnaya-rossiya-geroyam-1812-goda-pamyatnik-s-orlami', mustSeeFilter: 'monument', visitMinutes: 20, alsoMain: true }),
  place('Памятник Михаилу Глинке', 'Классический монумент композитору у сада Блонье, где звучит музыкальный Смоленск.', 54.781515, 32.047814, { address: 'ул. Глинки, сад Блонье', locationSlug: 'smolensk-pamyatnik-mihailu-glinke', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Александру Твардовскому и Василию Тёркину', 'Литературная пара на площади Победы - поэт и его солдатский герой.', 54.777931, 32.051912, { address: 'пл. Победы', locationSlug: 'smolensk-pamyatnik-tvardovskomu-i-terkinu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Олень в саду Блонье', 'Любимая фототочка сада Блонье и мягкий символ городского отдыха.', 54.7825, 32.048333, { address: 'сад Блонье', locationSlug: 'smolensk-olen-v-sadu-blone', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник зодчему Федору Коню', 'Монумент строителю Смоленской крепостной стены у Громовой башни.', 54.78082, 32.051187, { address: 'у Громовой башни', locationSlug: 'smolensk-pamyatnik-zodchemu-fedoru-konyu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Кутузову у Соборного холма', 'Фигура полководца на подъеме к Успенскому собору.', 54.787682, 32.055866, { address: 'Соборный холм', locationSlug: 'smolensk-pamyatnik-kutuzovu-u-sobornogo-holma', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Бюст М. И. Кутузова в сквере Памяти Героев', 'Камерный бюст рядом с Памятником с орлами в мемориальном сквере.', 54.781682, 32.045437, { address: 'сквер Памяти Героев', locationSlug: 'smolensk-byust-kutuzova-skver-pamyati-geroev', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Владимиру Куриленко', 'Мемориал герою-подпольщику в центре исторического Смоленска.', 54.782806, 32.049448, { address: 'центр', locationSlug: 'smolensk-pamyatnik-vladimiru-kurilenko', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Юрию Гагарину', 'Монумент первому космонавту - смоленскому уроженцу.', 54.76752, 32.04696, { address: 'пр-т Гагарина', locationSlug: 'smolensk-pamyatnik-yuriyu-gagarinu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Скульптура «Кот Смоленский»', 'Городской мем и милая точка для фото в пешеходном центре.', 54.7831, 32.0498, { address: 'центр у Блонье', locationSlug: 'smolensk-skulptura-kot-smolenskiy', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник воинам, защитникам и освободителям Смоленска', 'Мемориальный комплекс площади Победы в честь защитников и освободителей города.', 54.777712, 32.053155, { address: 'пл. Победы', locationSlug: 'smolensk-pamyatnik-voinam-zashchitnikam-osvoboditelyam', mustSeeFilter: 'monument', visitMinutes: 20 }),
  place('Памятник князю Владимиру Мономаху', 'Князь-основатель смоленской линии власти у Соборного двора.', 54.788544, 32.054366, { address: 'Соборный холм', locationSlug: 'smolensk-pamyatnik-knyazyu-vladimiru-monomahu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Арт-объект «Глобус Смоленска»', 'Современный городской арт-символ на старте неформальных маршрутов.', 54.778844, 32.046122, { address: 'центр, у пешеходных дворов', locationSlug: 'smolensk-art-globus-smolenska', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник Борису и Глебу на Смядыни', 'Мемориал святым князьям на древней Смядынской земле.', 54.784651, 32.008433, { address: 'Смядынь', locationSlug: 'smolensk-pamyatnik-borisu-i-glebu-na-smyadyni', mustSeeFilter: 'monument', visitMinutes: 20 }),
  place('Памятник М. О. Микешину', 'Монумент скульптору и автору проектов главных российских памятников.', 54.775612, 32.056022, { address: 'центр', locationSlug: 'smolensk-pamyatnik-m-o-mikeshinu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Башня Громовая', 'Музеефицированная башня крепости с экспозицией XVII века и видом на прясла стены.', 54.780653, 32.051413, { address: 'ул. Октябрьской революции, у стены', locationSlug: 'smolensk-gromovaya-bashnya', mustSeeFilter: 'houses', visitMinutes: 45, alsoMain: true }),
  place('Башня Копытенские ворота', 'Мощные воротные башни западного прясла Смоленской крепости.', 54.783422, 32.041634, { address: 'Копытенские ворота', locationSlug: 'smolensk-bashnya-kopytenskie-vorota', mustSeeFilter: 'houses', visitMinutes: 25 }),
  place('Башня Веселуха', 'Высокая угловая башня с лучшими видами на восточные холмы и Днепр.', 54.792518, 32.06456, { address: 'башня Веселуха', locationSlug: 'smolensk-bashnya-veselukha', mustSeeFilter: 'houses', visitMinutes: 30 }),
  place('Башня Заалтарная (Позднякова)', 'Оборонительная башня восточного участка стены у алтарных прясел.', 54.791322, 32.068422, { address: 'Заалтарная башня', locationSlug: 'smolensk-bashnya-zaaltarnaya-pozdnyakova', mustSeeFilter: 'houses', visitMinutes: 25 }),
  place('Королевский бастион', 'Земляной бастион польского времени внутри Лопатинского сада.', 54.781845, 32.039644, { address: 'Лопатинский сад', locationSlug: 'smolensk-korolevskiy-bastion', mustSeeFilter: 'houses', visitMinutes: 25 }),
  place('Смоленская крепостная стена', '«Ожерелье всея Руси» - самая протяженная сохранившаяся кирпичная крепость России рубежа XVI-XVII веков.', 54.7815, 32.0455, { address: 'прясла стены и сквер Памяти Героев', locationSlug: 'smolensk-smolenskaya-krepostnaya-stena', mustSeeFilter: 'houses', visitMinutes: 60, alsoMain: true }),
  place('Днепровские ворота', 'Парадный проход крепости к Днепру и Соборному холму.', 54.789122, 32.054811, { address: 'Днепровские ворота', locationSlug: 'smolensk-dneprovskie-vorota', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Здание бывшей Городской Думы', 'Купеческий фасад городского самоуправления в сердце исторического посада.', 54.782412, 32.046322, { address: 'ул. Октябрьской революции / центр', locationSlug: 'smolensk-zdanie-byvshey-gorodskoy-dumy', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Аутентичный восточный участок стены', 'Лучше всего сохранившиеся прясла восточного фронта крепости.', 54.790422, 32.071233, { address: 'восточный участок стены', locationSlug: 'smolensk-vostochnyy-uchastok-steny', mustSeeFilter: 'houses', visitMinutes: 35 }),
  place('Дом с часами', 'Ориентир Большой Советской с городскими часами на фасаде.', 54.783455, 32.052611, { address: 'ул. Большая Советская', locationSlug: 'smolensk-dom-s-chasami', mustSeeFilter: 'houses', visitMinutes: 15 }),
  place('Смоленская художественная галерея', 'Главное художественное собрание области в историческом здании центра.', 54.782531, 32.046153, { address: 'центр', venueSlug: 'smolensk-smolenskaya-hudozhestvennaya-galereya', mustSeeFilter: 'museum', visitMinutes: 75 }),
  place('Музей «Смоленщина в годы ВОВ»', 'Военно-историческая экспозиция о Смоленском сражении и освобождении области.', 54.781211, 32.044622, { address: 'сквер Памяти Героев / центр', venueSlug: 'smolensk-muzey-smolenschina-v-gody-vov', mustSeeFilter: 'museum', visitMinutes: 60 }),
  place('Исторический музей', 'Классическая краеведческая экспозиция от древнего Гнёздова до губернского Смоленска.', 54.783853, 32.049411, { address: 'центр', venueSlug: 'smolensk-istoricheskiy-muzey', mustSeeFilter: 'museum', visitMinutes: 70 }),
  place('Музей «Смоленский лен»', 'История главного промысла края - от поля до ткацкого станка.', 54.780122, 32.058311, { address: 'центр', venueSlug: 'smolensk-muzey-smolenskiy-len', mustSeeFilter: 'museum', visitMinutes: 45 }),
  place('Музей «В мире сказки»', 'Камерный музей сказочных героев и детских инсталляций.', 54.784122, 32.052144, { address: 'центр', venueSlug: 'smolensk-muzey-v-mire-skazki', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Музей-кузница XVII века', 'Действующая кузница с живыми мастер-классами и запахом угля.', 54.786512, 32.046311, { address: 'ул. Ленина / кузнечный двор', venueSlug: 'smolensk-muzey-kuznitsa-xvii-veka', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Музей скульптуры С. Т. Конёнкова', 'Мемориальный музей великого скульптора-земляка с камерной коллекцией.', 54.783411, 32.048922, { address: 'центр', venueSlug: 'smolensk-muzey-skulptury-konenkova', mustSeeFilter: 'museum', visitMinutes: 50 }),
  place('Свято-Успенский кафедральный собор', 'Бело-бирюзовый барочный собор на Соборной горе - духовный ориентир Смоленска.', 54.788644, 32.054611, { address: 'Соборный холм', venueSlug: 'smolensk-svyato-uspenskiy-kafedralnyy-sobor', mustSeeFilter: 'temple', visitMinutes: 45, alsoMain: true }),
  place('Церковь Петра и Павла на Городянке', 'Домонгольский храм XII века - один из древнейших каменных памятников Руси.', 54.791555, 32.031522, { address: 'ул. Кашена / Городянка', locationSlug: 'smolensk-tserkov-petra-i-pavla-na-gorodyanke', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Церковь Иоанна Богослова на Варяжках', 'Древний храм варяжского посада с лаконичными домонгольскими формами.', 54.790422, 32.036811, { address: 'Варяжки', locationSlug: 'smolensk-tserkov-ioanna-bogoslova-na-varyazhkah', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Церковь Архангела Михаила (Свирская)', 'Белокаменный храм XII века на высоком берегу Днепра.', 54.783611, 32.022944, { address: 'Свирская церковь', locationSlug: 'smolensk-tserkov-arhangela-mihaila-svirskaya', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Спасо-Преображенский собор Авраамиева монастыря', 'Монастырский собор с многовековой историей на восточной окраине центра.', 54.784411, 32.062822, { address: 'Авраамиев монастырь', locationSlug: 'smolensk-spaso-preobrazhenskiy-sobor-avraamieva', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Католический храм Непорочного Зачатия Девы Марии', 'Неоготический костел с высокими шпилями - редкий западный акцент в силуэте города.', 54.774411, 32.052611, { address: 'ул. Урицкого', locationSlug: 'smolensk-katolicheskiy-hram-neporochnogo-zachatiya', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Свято-Троицкий монастырь', 'Действующий монастырь на подъеме к Соборному холму.', 54.786511, 32.052922, { address: 'ул. Большая Советская / Соборный холм', locationSlug: 'smolensk-svyato-troitskiy-monastyr', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Сад Блонье', 'Центральный городской сад с фонтанами, Оленем и памятником Глинке.', 54.781911, 32.047811, { address: 'сад Блонье', locationSlug: 'smolensk-sad-blone', mustSeeFilter: 'park', visitMinutes: 40 }),
  place('Лопатинский сад', 'Старейший парк Смоленска внутри оборонительного рва с Королевским бастионом и прудом.', 54.782822, 32.040111, { address: 'Лопатинский сад', locationSlug: 'smolensk-lopatinskiy-sad', mustSeeFilter: 'park', visitMinutes: 60, alsoMain: true }),
  place('Смотровая на Соборном холме', 'Панорама крепости, Днепра и крыш исторического центра с высоты соборной площади.', 54.788911, 32.053811, { address: 'Соборный холм', locationSlug: 'smolensk-smotrovaya-na-sobornom-holme', mustSeeFilter: 'views', visitMinutes: 25 }),
  place('Набережная Владимира Крестителя', 'Променад вдоль Днепра с видами на холмы и прясла стены.', 54.790411, 32.048911, { address: 'наб. Владимира Крестителя', locationSlug: 'smolensk-naberezhnaya-vladimira-krestitelya', mustSeeFilter: 'park', visitMinutes: 45 }),
  place('Святой источник у башни Веселуха', 'Родник у восточной стены - тихая пауза после подъема к Веселухе.', 54.793311, 32.065111, { address: 'у башни Веселуха', locationSlug: 'smolensk-svyatoy-istochnik-u-bashni-veselukha', mustSeeFilter: 'views', visitMinutes: 20 }),
  place('Драмтеатр им. Грибоедова', 'Главная драматическая сцена области с классическим и современным репертуаром.', 54.782611, 32.045011, { address: 'пл. Ленина', venueSlug: 'smolensk-dramteatr-griboedova', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Кафе-кондитерская «Смоленский конфект»', 'Фирменные сладости и смоленский конфект - главный гастросувенир города.', 54.783155, 32.049311, { address: 'центр', locationSlug: 'smolensk-kafe-smolenskiy-konfekt', mustSeeFilter: 'gastro', visitMinutes: 45 }),
  place('Ресторан «Кутузов»', 'Классическая русская кухня у крепостной стены и Громовой башни.', 54.781811, 32.052111, { address: 'у крепостной стены', locationSlug: 'smolensk-restoran-kutuzov', mustSeeFilter: 'gastro', visitMinutes: 75 }),
  place('Кофейня «Эола»', 'Уютная кофейня у сада Блонье - удобная пауза дневных маршрутов.', 54.782111, 32.047422, { address: 'у сада Блонье', locationSlug: 'smolensk-kofeynya-eola', mustSeeFilter: 'gastro', visitMinutes: 40 }),
  place('Ресторан-пивоварня «Маяковский»', 'Крафтовое пиво и сытный стритфуд на улице Маяковского.', 54.783222, 32.049411, { address: 'ул. Маяковского', locationSlug: 'smolensk-restoran-pivovarnya-mayakovskiy', mustSeeFilter: 'gastro', visitMinutes: 75 }),
  place('Смоленская областная филармония', 'Концертный зал с классикой, джазом и фестивальными программами имени Глинки.', 54.781011, 32.049111, { address: 'центр', venueSlug: 'smolensk-oblastnaya-filarmoniya', mustSeeFilter: 'creative', visitMinutes: 30 }),
];

export const SMOLENSK_SUBURBS: any[] = [
  {
    name: 'Историко-архитектурный комплекс «Теремок» (Флёново / Талашкино)',
    desc: 'Усадьба меценатки Марии Тенишевой с сказочным «Теремком», мозаиками Рериха и духом художественной колонии рубежа веков.',
    locationSlug: 'smolensk-istoriko-arhitekturnyy-kompleks-teremok-flenovo',
    venueSlug: 'smolensk-istoriko-arhitekturnyy-kompleks-teremok-flenovo',
    mustSeeFilter: 'main',
    visitMinutes: '3-4 ч',
    latitude: 54.646875,
    longitude: 32.193231,
    address: 'деревня Флёново, Талашкино',
    travelVector: 'Авто / автобус 104 ~30 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль или автобус №104 около 30 минут, чтобы приехать к открытию касс и обойти весь комплекс без спешки.',
    timingNote:
      'От «Теремка» идите к Храму Святого Духа и мозаике Рериха, напоследок оставив пруды и памятник Тенишевой.',
    places: [
      place('«Теремок»', 'Сказочный неорусский дом - визитная карточка Талашкина.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-teremok', mustSeeFilter: 'houses', visitMinutes: 40 }),
      place('Музей Талашкинской школы', 'Экспозиция художественных мастерских и школы Тенишевой.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-muzey-shkoly', mustSeeFilter: 'museum', visitMinutes: 40 }),
      place('Храм Святого Духа', 'Храм усадебного комплекса с мощным духовным акцентом колонии.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-hram-svyatogo-duha', mustSeeFilter: 'temple', visitMinutes: 30 }),
      place('Мозаика Рериха', 'Знаменитая мозаика Николая Рериха на фасаде храма.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-mozaika-reriha', mustSeeFilter: 'monument', visitMinutes: 20 }),
      place('Памятник Тенишевой', 'Монумент меценатке и хозяйке художественной колонии.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-pamyatnik-tenishevoy', mustSeeFilter: 'monument', visitMinutes: 15 }),
      place('Старинные пруды', 'Тихие усадебные пруды для финальной прогулки.', 54.646875, 32.193231, { address: 'Флёново', locationSlug: 'smolensk-talashkino-starinnye-prudy', mustSeeFilter: 'park', visitMinutes: 25 }),
    ],
  },
  {
    name: 'Музей-усадьба М. И. Глинки «Новоспасское»',
    desc: 'Родовое имение композитора с господским домом, роялем, церковью и Амалиевым дубом - тихая музыкальная Смоленщина.',
    locationSlug: 'smolensk-muzey-usadba-glinki-novospasskoe',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 54.536762,
    longitude: 33.155495,
    address: 'Ельнинский район, с. Новоспасское',
    travelVector: 'Авто ~1 ч 45 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль около 1 часа 45 минут, чтобы приехать к открытию и спокойно обойти парк и дом.',
    timingNote:
      'Начните с господского дома и зала с роялем, затем церковь и святой источник, напоследок оставив Амалиев дуб.',
    places: [
      place('Господский дом', 'Главный усадебный дом с мемориальной обстановкой семьи Глинки.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-gospodskiy-dom', mustSeeFilter: 'museum', visitMinutes: 50 }),
      place('Зал с роялем', 'Музыкальный зал усадьбы - сердце экскурсии о Глинке.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-zal-s-royalem', mustSeeFilter: 'museum', visitMinutes: 30 }),
      place('Комната птиц', 'Камерная комната с птичьими мотивами усадебного быта.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-komnata-ptits', mustSeeFilter: 'museum', visitMinutes: 20 }),
      place('Церковь усадьбы', 'Храм усадебного комплекса Новоспасского.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-tserkov', mustSeeFilter: 'temple', visitMinutes: 25 }),
      place('Святой источник', 'Родник усадебного парка для тихой паузы.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-svyatoy-istochnik', mustSeeFilter: 'views', visitMinutes: 20 }),
      place('Амалиев дуб', 'Легендарный дуб усадьбы - природный финал прогулки.', 54.536762, 33.155495, { address: 'с. Новоспасское', locationSlug: 'smolensk-novospasskoe-amaliev-dub', mustSeeFilter: 'park', visitMinutes: 20 }),
    ],
  },
  {
    name: 'Национальный парк «Смоленское Поозерье» (Пржевальское)',
    desc: 'Озерный край Смоленщины: Сапшо, дом-музей Пржевальского, зубры и партизанские тропы.',
    locationSlug: 'smolensk-natspark-smolenskoe-poozerie',
    mustSeeFilter: 'main',
    visitMinutes: '6-8 ч',
    latitude: 55.506456,
    longitude: 31.846513,
    address: 'Демидовский район, п. Пржевальское',
    travelVector: 'Авто ~1 ч 30 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль около 1 часа 30 минут и полный день на озера, музеи и экотропы.',
    timingNote:
      'От озера Сапшо идите к дому-музею Пржевальского, затем зубры и музей партизанской славы, напоследок экотропа.',
    places: [
      place('Озеро Сапшо', 'Главное озеро Поозерья с чистой водой и лесными берегами.', 55.506456, 31.846513, { address: 'п. Пржевальское', locationSlug: 'smolensk-poozerie-ozero-sapsho', mustSeeFilter: 'park', visitMinutes: 60 }),
      place('Дом-музей Пржевальского', 'Мемориальный дом путешественника в поселке его имени.', 55.506456, 31.846513, { address: 'п. Пржевальское', locationSlug: 'smolensk-poozerie-dom-muzey-przhevalskogo', mustSeeFilter: 'museum', visitMinutes: 50 }),
      place('Вольеры с зубрами', 'Встреча с зубрами в охраняемой зоне парка.', 55.506456, 31.846513, { address: 'Поозерье', locationSlug: 'smolensk-poozerie-zubry', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Музей партизанской славы', 'Экспозиция о партизанском движении Смоленщины.', 55.506456, 31.846513, { address: 'Поозерье', locationSlug: 'smolensk-poozerie-muzey-partizanskoy-slavy', mustSeeFilter: 'museum', visitMinutes: 40 }),
      place('Курганный могильник', 'Древний курганный комплекс на территории парка.', 55.506456, 31.846513, { address: 'Поозерье', locationSlug: 'smolensk-poozerie-kurgannyy-mogilnik', mustSeeFilter: 'houses', visitMinutes: 30 }),
      place('Экотропа Поозерья', 'Лесная тропа с видами на озера и болота.', 55.506456, 31.846513, { address: 'Поозерье', locationSlug: 'smolensk-poozerie-ekotropa', mustSeeFilter: 'park', visitMinutes: 60 }),
    ],
  },
  {
    name: 'Историко-археологический комплекс «Гнёздово»',
    desc: 'Один из ключевых пунктов пути «из варяг в греки»: курганы, городище и реконструкции у Днепра.',
    locationSlug: 'smolensk-istoriko-arheologicheskiy-kompleks-gnezdovo',
    mustSeeFilter: 'main',
    visitMinutes: '3-4 ч',
    latitude: 54.783637,
    longitude: 31.879796,
    address: 'деревня Гнёздово',
    travelVector: 'Автобус 30 ~20 мин',
    travelVectorBlurb:
      'Закладывайте на автобус №30 около 20 минут или короткий трансфер на авто до курганного поля.',
    timingNote:
      'Начните с курганов и городища, затем реконструкция усадьбы и «горушна», напоследок пойма Днепра.',
    places: [
      place('Курганы Гнёздова', 'Масштабный курганный некрополь эпохи викингов и ранней Руси.', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-kurgany', mustSeeFilter: 'houses', visitMinutes: 40 }),
      place('Городище', 'Древнее поселение на высоком берегу Днепра.', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-gorodishche', mustSeeFilter: 'houses', visitMinutes: 35 }),
      place('Реконструкция усадьбы', 'Живая реконструкция двора эпохи пути «из варяг в греки».', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-rekonstruktsiya-usadby', mustSeeFilter: 'houses', visitMinutes: 30 }),
      place('Место «горушна»', 'Локальная точка с видом на пойму и археологический ландшафт.', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-gorushna', mustSeeFilter: 'views', visitMinutes: 20 }),
      place('Пойма Днепра', 'Речной пейзаж пути «из варяг в греки».', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-poyma-dnepra', mustSeeFilter: 'park', visitMinutes: 25 }),
      place('Археологическая база', 'Рабочая база раскопок и пояснений к находкам.', 54.783637, 31.879796, { address: 'Гнёздово', locationSlug: 'smolensk-gnezdovo-arheobaza', mustSeeFilter: 'museum', visitMinutes: 25 }),
    ],
  },
  {
    name: 'Город Вязьма',
    desc: 'Купеческий город Смоленщины с Одигитрией, Спасской башней, пряником и Аркадиевским монастырем.',
    locationSlug: 'smolensk-gorod-vyazma',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 55.211425,
    longitude: 34.288219,
    address: 'г. Вязьма',
    travelVector: '«Ласточка» ~1 ч 10 мин',
    travelVectorBlurb:
      'Удобнее всего доезжать «Ласточкой» около 1 часа 10 минут и закладывать полный день на центр Вязьмы.',
    timingNote:
      'От Одигитрии и Спасской башни идите к Аркадиевскому монастырю, затем музей пряника и памятник Ефремову.',
    places: [
      place('Храм Одигитрии', 'Уникальный трехшатровый храм - символ Вязьмы.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-odigitriya', mustSeeFilter: 'temple', visitMinutes: 40 }),
      place('Спасская башня', 'Сохранившаяся башня вяземской крепости.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-spasskaya-bashnya', mustSeeFilter: 'houses', visitMinutes: 30 }),
      place('Аркадиевский монастырь', 'Монастырский ансамбль с тихим двором и храмами.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-arkadievskiy-monastyr', mustSeeFilter: 'temple', visitMinutes: 40 }),
      place('Музей пряника', 'Дегустация вяземского пряника и история купеческой выпечки.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-muzey-pryanika', mustSeeFilter: 'museum', visitMinutes: 45 }),
      place('Памятник генералу Ефремову', 'Мемориал герою Великой Отечественной в центре Вязьмы.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-pamyatnik-efremovu', mustSeeFilter: 'monument', visitMinutes: 20 }),
      place('Краеведческий музей', 'Городская история Вязьмы от крепости до купечества.', 55.211425, 34.288219, { address: 'г. Вязьма', locationSlug: 'smolensk-vyazma-kraevedcheskiy-muzey', mustSeeFilter: 'museum', visitMinutes: 50 }),
    ],
  },
];

export const SMOLENSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'smolensk-krepostnoy-shchit',
    title: 'Крепостной щит и сердце города',
    description:
      'Классический день первого знакомства: Громовая башня, сквер Памяти Героев, Блонье, кофе в «Эоле», Лопатинский сад и пивоварня «Маяковский».',
    travelVector: 'Пешком по центру',
    timingNote:
      'Около 8-9 часов с паузами: Громовая - сквер Памяти - Блонье - «Эола» - Маяковского - Лопатинский - «Маяковский».',
    coverImageUrl: '/images/venues/smolensk/gromovaya-bashnya.jpg',
    stops: [
      {
        name: 'Башня Громовая',
        desc: '1 час на музей в башне и прясла стены.',
        locationSlug: 'smolensk-gromovaya-bashnya',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        address: 'ул. Октябрьской революции, у стены',
        latitude: 54.780653,
        longitude: 32.051413,
      },
      {
        name: 'Сквер Памяти Героев',
        desc: '40 минут у Памятника с орлами и бюста Кутузова.',
        locationSlug: 'smolensk-pamyatnik-blagodarnaya-rossiya-geroyam-1812-goda-pamyatnik-s-orlami',
        mustSeeFilter: 'monument',
        visitMinutes: 40,
        address: 'сквер Памяти Героев',
        latitude: 54.781831,
        longitude: 32.046049,
        transitTip: 'Пешком 5-7 минут вдоль стены',
      },
      {
        name: 'Сад Блонье',
        desc: '40 минут у Оленя и памятника Глинке.',
        locationSlug: 'smolensk-sad-blone',
        mustSeeFilter: 'park',
        visitMinutes: 40,
        address: 'сад Блонье',
        latitude: 54.781911,
        longitude: 32.047811,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Кофейня «Эола»',
        desc: '45 минут кофейной паузы у Блонье.',
        locationSlug: 'smolensk-kofeynya-eola',
        mustSeeFilter: 'gastro',
        visitMinutes: 45,
        address: 'у сада Блонье',
        latitude: 54.782111,
        longitude: 32.047422,
        transitTip: 'Пешком 2 минуты',
      },
      {
        name: 'Улица Маяковского',
        desc: '30 минут променада к гастрозоне.',
        locationSlug: 'smolensk-restoran-pivovarnya-mayakovskiy',
        mustSeeFilter: 'street',
        visitMinutes: 30,
        address: 'ул. Маяковского',
        latitude: 54.783222,
        longitude: 32.049411,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Лопатинский сад',
        desc: '1.5 часа у Королевского бастиона и пруда.',
        locationSlug: 'smolensk-lopatinskiy-sad',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        address: 'Лопатинский сад',
        latitude: 54.782822,
        longitude: 32.040111,
        transitTip: 'Пешком 10 минут к саду',
      },
      {
        name: 'Ресторан-пивоварня «Маяковский»',
        desc: '1.5 часа сытного ужина и крафта.',
        locationSlug: 'smolensk-restoran-pivovarnya-mayakovskiy',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Маяковского',
        latitude: 54.783222,
        longitude: 32.049411,
        transitTip: 'Пешком обратно к Маяковского',
      },
    ],
  },
  {
    id: 'smolensk-holmy-i-tayny',
    title: 'Смоленские холмы и вековые тайны',
    description:
      'Маршрут по холмам: Дом с часами, Успенский собор, смотровая, набережная, Веселуха и памятник Кутузову.',
    travelVector: 'Холмы и Днепр',
    timingNote:
      'Около 8 часов: Дом с часами - Успенский - смотровая - набережная - Веселуха - Кутузов.',
    coverImageUrl: '/images/venues/smolensk/svyato-uspenskiy-kafedralnyy-sobor.jpg',
    stops: [
      {
        name: 'Дом с часами',
        desc: '20 минут у ориентира Большой Советской.',
        locationSlug: 'smolensk-dom-s-chasami',
        mustSeeFilter: 'houses',
        visitMinutes: 20,
        address: 'ул. Большая Советская',
        latitude: 54.783455,
        longitude: 32.052611,
      },
      {
        name: 'Свято-Успенский кафедральный собор',
        desc: '1 час внутри собора и на Соборном холме.',
        venueSlug: 'smolensk-svyato-uspenskiy-kafedralnyy-sobor',
        mustSeeFilter: 'temple',
        visitMinutes: 60,
        address: 'Соборный холм',
        latitude: 54.788644,
        longitude: 32.054611,
        transitTip: 'Пешком вверх по Большой Советской ~15 минут',
      },
      {
        name: 'Смотровая на Соборном холме',
        desc: '30 минут панорамы крепости и Днепра.',
        locationSlug: 'smolensk-smotrovaya-na-sobornom-holme',
        mustSeeFilter: 'views',
        visitMinutes: 30,
        address: 'Соборный холм',
        latitude: 54.788911,
        longitude: 32.053811,
        transitTip: 'На территории холма',
      },
      {
        name: 'Набережная Владимира Крестителя',
        desc: '1 час променада вдоль Днепра.',
        locationSlug: 'smolensk-naberezhnaya-vladimira-krestitelya',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'наб. Владимира Крестителя',
        latitude: 54.790411,
        longitude: 32.048911,
        transitTip: 'Спуск к Днепру ~10 минут',
      },
      {
        name: 'Башня Веселуха',
        desc: '1 час подъема к восточной стене и видам.',
        locationSlug: 'smolensk-bashnya-veselukha',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        address: 'башня Веселуха',
        latitude: 54.792518,
        longitude: 32.06456,
        transitTip: 'Пешком вдоль стены ~20-25 минут',
      },
      {
        name: 'Памятник Кутузову у Соборного холма',
        desc: '30 минут финала у полководца на спуске с холма.',
        locationSlug: 'smolensk-pamyatnik-kutuzovu-u-sobornogo-holma',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'Соборный холм',
        latitude: 54.787682,
        longitude: 32.055866,
        transitTip: 'Возврат к Соборному холму',
      },
    ],
  },
  ...SMOLENSK_LINE_DAY_ROUTE_PRESETS,
];

export const SMOLENSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как быстрее и удобнее добраться в Смоленск из Москвы?',
    a: 'Берите «Ласточку» с Белорусского вокзала - в пути около 3 часов 40 минут, без пробок М-1. Автомобиль имеет смысл только если планируете усадьбы и Поозерье в тот же день.',
  },
  {
    q: 'Можно ли свободно гулять по Смоленской крепостной стене?',
    a: 'По необорудованным пряслам подниматься нельзя из соображений безопасности. Идите в отреставрированные башни с музеями - прежде всего в Громовую - и смотрите стену с земли вдоль скверов.',
  },
  {
    q: 'Что такое «Лапач» и стоит ли туда идти в первый визит?',
    a: 'Так местные ласково называют Лопатинский сад. Да, это must-see первого дня: Королевский бастион, пруд и зеленый ров крепости в шаговой доступности от центра.',
  },
  {
    q: 'Правда ли, что в Смоленске нужна особая обувь из-за холмов?',
    a: 'Да. Центр холмистый, мостовая и валы скользят после дождя. Берите удобные непромокаемые кроссовки - особенно осенью на подъемах к Соборному холму и Веселухе.',
  },
];

export const SMOLENSK_TRAVEL =
  'Из Москвы до Смоленска удобнее всего доезжать на «Ласточке» с Белорусского вокзала - в пути около 3 часов 40 минут. Автомобиль по М-1 имеет смысл, если в тот же день едете в усадьбы или Поозерье. Идеальный сезон для стены, набережной и Лопатинского сада - с мая по сентябрь; осенью холмы золотеют, зимой крепость особенно фотогенична в снегу.';
