/** Sochi tourist hub pack (owner 2026-08-21). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { SOCHI_LINE_DAY_ROUTE_PRESETS } from './sochi-line-presets.ts';

export const SOCHI_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник Архангелу Михаилу',
    desc: 'Главный монументальный покровитель города, венчающий высокую стелу в самом центре курорта.',
    address: 'ул. Москвина, 4',
    locationSlug: 'sochi-pamyatnik-arhangelu-mihailu',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 43.581561,
    longitude: 39.721495,
  },
  {
    name: 'Скульптурная композиция «Бриллиантовая рука»',
    desc: 'Колоритные бронзовые фигуры персонажей культовой советской комедии у причала Морвокзала.',
    address: 'ул. Войкова, 1',
    locationSlug: 'sochi-brilliantovaya-ruka',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 43.580447,
    longitude: 39.718872,
  },
  {
    name: 'Памятник Нептуну',
    desc: 'Харизматичная уличная фигура морского царя с трезубцем на Приморской набережной.',
    address: 'Приморская набережная, 11/1',
    locationSlug: 'sochi-pamyatnik-neptunu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.575971,
    longitude: 39.725176,
  },
  {
    name: 'Скульптура «Морские Сезоны»',
    desc: 'Мифологические фигуры на фасаде Морского вокзала, олицетворяющие времена года и навигацию.',
    address: 'ул. Круизная гавань, 4',
    locationSlug: 'sochi-morskie-sezony',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.580879,
    longitude: 39.718228,
  },
  {
    name: 'Памятник Петру I',
    desc: 'Крупный бронзовый монумент российскому императору у мелководного причала.',
    address: 'ул. Войкова, 1В',
    locationSlug: 'sochi-pamyatnik-petru-i',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 43.580645,
    longitude: 39.719665,
  },
  {
    name: 'Скульптура «Дама с попугаем»',
    desc: 'Популярный курортный арт-объект эпохи соцреализма на парадной Приморской улице.',
    address: 'ул. Приморская, 3/1',
    locationSlug: 'sochi-dama-s-popugaem',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.578619,
    longitude: 39.722662,
  },
  {
    name: 'Памятник многодетным отцам (Памятник Филину)',
    desc: 'Теплый парковый арт-объект в виде умудренной совы с птенцами в парке «Ривьера».',
    address: 'ул. Егорова, 1 (Парк Ривьера)',
    locationSlug: 'sochi-pamyatnik-filinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.590114,
    longitude: 39.715456,
  },
  {
    name: 'Памятник сочинскому учителю',
    desc: 'Трогательный монумент первой учительнице и ее ученикам - символ преемственности поколений.',
    address: 'ул. Орджоникидзе, 10А',
    locationSlug: 'sochi-pamyatnik-sochinskomu-uchitelyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.577903,
    longitude: 39.724508,
  },
  {
    name: 'Скульптура «Золотое руно»',
    desc: 'Композиция в виде растянутой шкуры барана между колоннами - отсылка к мифам об аргонавтах.',
    address: 'площадь Искусств, 1',
    locationSlug: 'sochi-zolotoe-runo',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.57833,
    longitude: 39.725946,
  },
  {
    name: 'Арт-объект «Ухо желаний»',
    desc: 'Массивная чугунная парковая инсталляция, в которую принято шептать заветные мечты.',
    address: 'ул. Навагинская, 7',
    locationSlug: 'sochi-uho-zhelaniy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.585721,
    longitude: 39.72481,
  },
  {
    name: 'Скульптура «Прометей»',
    desc: 'Брутальный памятник титану, разорвавшему цепи, на вершине Орлиных скал.',
    address: 'Мацестинский лесопарк, Орлиные скалы',
    locationSlug: 'sochi-skulptura-prometej',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 43.559288,
    longitude: 39.822896,
  },
  {
    name: 'Памятник «Мацеста»',
    desc: 'Культовая визитная карточка, высеченная в скале на въезде в бальнеологический район.',
    address: 'аллея Челтенхэма, 4',
    locationSlug: 'sochi-pamyatnik-matsesta',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 43.551121,
    longitude: 39.792501,
  },
  {
    name: 'Памятник Николаю Островскому',
    desc: 'Массивный гранитный бюст писателю, мужественно боровшемуся с болезнью в Сочи.',
    address: 'Курортный проспект, 39',
    locationSlug: 'sochi-pamyatnik-ostrovskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.576884,
    longitude: 39.734898,
  },
  {
    name: 'Скульптура «Пловец и дельфин»',
    desc: 'Динамичный советский фонтан-памятник, отражающий морскую спортивную эстетику Сочи.',
    address: 'ул. Черноморская, 3',
    locationSlug: 'sochi-plovets-i-delfin',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.570494,
    longitude: 39.732959,
  },
  {
    name: 'Памятник В. И. Ленину',
    desc: 'Монументальная историческая точка на одноименной площади из темного гранита.',
    address: 'ул. Навагинская, 2',
    locationSlug: 'sochi-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 43.588825,
    longitude: 39.724874,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Здание Морского вокзала',
    desc: 'Выдающийся памятник архитектуры со сталинским 71-метровым шпилем и роскошными галереями.',
    address: 'ул. Войкова, 1',
    locationSlug: 'sochi-morskoy-vokzal',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 43.580718,
    longitude: 39.718683,
  },
  {
    name: 'Дача Сталина',
    desc: 'Историческая государственная резиденция вождя в темно-зеленом маскировочном цвете среди реликтового леса.',
    address: 'Курортный проспект, 120/1',
    locationSlug: 'sochi-dacha-stalina',
    mustSeeFilter: 'houses',
    visitMinutes: 60,
    latitude: 43.545199,
    longitude: 39.791566,
  },
  {
    name: 'Форт Александрия (остатки крепостной стены)',
    desc: 'Каменные руины первой русской военной крепости 1838 года, с которой начался современный город.',
    address: 'ул. Москвина, 7',
    locationSlug: 'sochi-fort-aleksandriya',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 43.582232,
    longitude: 39.721495,
  },
  {
    name: 'Заброшенный санаторий Орджоникидзе',
    desc: 'Шедевр дворцовой советской архитектуры - культовое место для эстетичных пленочных фотосессий.',
    address: 'Курортный проспект, 96/5',
    locationSlug: 'sochi-sanatoriy-ordzhonikidze',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 43.55395,
    longitude: 39.771217,
  },
  {
    name: 'Вилла «Надежда»',
    desc: 'Старинный особняк основателя Дендрария Сергея Худекова в легком средиземноморском стиле.',
    address: 'Курортный проспект, 74',
    locationSlug: 'sochi-villa-nadezhda',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 43.572111,
    longitude: 39.742331,
  },
  {
    name: 'Дача певицы Валерии Барсовой',
    desc: 'Живописный мавританский замок-дача, где собирался цвет советской интеллигенции и оперного искусства.',
    address: 'ул. Черноморская, 11А',
    locationSlug: 'sochi-dacha-barsovoy',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 43.568478,
    longitude: 39.734612,
  },
  {
    name: 'Здание железнодорожного вокзала Сочи',
    desc: 'Архитектурный шедевр Алексея Душкина с 55-метровой часовой башней со знаками зодиака.',
    address: 'ул. Горького, 56',
    locationSlug: 'sochi-zheleznodorozhnyy-vokzal',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 43.593021,
    longitude: 39.727653,
  },

  // --- Музеи (23-27) ---
  {
    name: 'Сочинский художественный музей',
    desc: 'Исторический дворец искусств с коллекцией русской живописи от Айвазовского до Шишкина.',
    address: 'Курортный проспект, 51',
    locationSlug: 'sochi-hudozhestvennyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 43.578644,
    longitude: 39.726926,
  },
  {
    name: 'Музей истории города-курорта Сочи',
    desc: 'Главная краеведческая экспозиция региона - от древних византийцев до Олимпиады-2014.',
    address: 'ул. Воровского, 54/11',
    locationSlug: 'sochi-muzey-istorii-kurorta',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 43.590124,
    longitude: 39.728956,
  },
  {
    name: 'Литературно-мемориальный музей Н. Островского',
    desc: 'Мемориальный дом-музей, где советский писатель провел последние годы жизни.',
    address: 'ул. Павла Корчагина, 4',
    locationSlug: 'sochi-muzey-ostrovskogo',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 43.577239,
    longitude: 39.734188,
  },
  {
    name: 'Музей спортивной славы Сочи',
    desc: 'Мультимедийный музей о вкладе города в мировое спортивное и олимпийское движение.',
    address: 'ул. Советская, 26А',
    locationSlug: 'sochi-muzey-sportivnoy-slavy',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 43.585093,
    longitude: 39.727025,
  },
  {
    name: 'Этнографический музей в Лазаревском',
    desc: 'Филиал краеведческого музея о культуре и быте коренных народов - шапсугов.',
    address: 'ул. Победы, 97 (мкр. Лазаревское)',
    locationSlug: 'sochi-etnograficheskiy-muzey-lazarevskoe',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 43.910307,
    longitude: 39.324838,
  },

  // --- Храмы (28-31) ---
  {
    name: 'Собор Архангела Михаила',
    desc: 'Старейший православный кафедральный собор Черноморского округа в память о завершении Кавказской войны.',
    address: 'ул. Москвина, 12',
    locationSlug: 'sochi-sobor-arhangela-mihaila',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 43.581021,
    longitude: 39.7226,
  },
  {
    name: 'Храм Святого Владимира',
    desc: 'Нарядный золотоглавый белокаменный храм на вершине исторической горы Виноградная.',
    address: 'ул. Виноградная, 18',
    locationSlug: 'sochi-hram-svyatogo-vladimira',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 43.603348,
    longitude: 39.720516,
  },
  {
    name: 'Католическая церковь святых апостолов Фаддея и Симона',
    desc: 'Элегантный образец неоготической церковной архитектуры со строгими шпилями и органным залом.',
    address: 'ул. Параллельная, 11',
    locationSlug: 'sochi-katolicheskaya-tserkov-faddeya-i-simona',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 43.596001,
    longitude: 39.731454,
  },
  {
    name: 'Армянская Апостольская Церковь Сурб Саркис',
    desc: 'Аутентичный храм из розового туфа, построенный по классическим армянским канонам в Адлере.',
    address: 'ул. Белых акаций, 15 (мкр. Адлер)',
    locationSlug: 'sochi-tserkov-surb-sarkis',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 43.473552,
    longitude: 39.905662,
  },

  // --- Парки / Смотровые (32-39) ---
  {
    name: 'Парк «Ривьера»',
    desc: 'Исторический развлекательный парк с вековой платановой аллеей, основанный купцом Хлудовым в 1898 году.',
    address: 'ул. Егорова, 1',
    locationSlug: 'sochi-park-riviera',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 43.590822,
    longitude: 39.714343,
  },
  {
    name: 'Смотрительная башня на горе Ахун',
    desc: 'Высотная смотровая точка в романском стиле с панорамой Кавказского хребта и побережья.',
    address: 'гора Большой Ахун',
    locationSlug: 'sochi-bashnya-ahun',
    mustSeeFilter: 'views',
    visitMinutes: 40,
    latitude: 43.550389,
    longitude: 39.843606,
  },
  {
    name: 'Сочинский «Дендрарий» (Верхний парк)',
    desc: 'Крупнейший ботанический музей под открытым небом с канатной дорогой и пальмовыми аллеями.',
    address: 'Курортный проспект, 74',
    locationSlug: 'sochi-dendrariy-verhniy',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 43.570122,
    longitude: 39.743118,
  },
  {
    name: 'Нижний Дендрарий',
    desc: 'Живописная равнинная часть парка с утиными прудами, розарием и бамбуковыми рощами.',
    address: 'Курортный проспект, 74А',
    locationSlug: 'sochi-dendrariy-nizhniy',
    mustSeeFilter: 'park',
    visitMinutes: 45,
    latitude: 43.568445,
    longitude: 39.74051,
  },
  {
    name: 'Парк «Южные культуры»',
    desc: 'Староместный ботанический сад в Адлере с вековыми магнолиями и прудами с черными лебедями.',
    address: 'ул. Губернская, 13 (мкр. Адлер)',
    locationSlug: 'sochi-park-yuzhnye-kultury',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 43.418703,
    longitude: 39.935105,
  },
  {
    name: 'Олимпийский парк (Медальная площадь)',
    desc: 'Футуристический прибрежный кластер с олимпийскими стадионами и чашей Поющих фонтанов.',
    address: 'Сириус, Медальная площадь',
    locationSlug: 'sochi-olimpiyskiy-park',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 43.405076,
    longitude: 39.954605,
  },
  {
    name: 'Смотровая площадка «Роза Пик»',
    desc: 'Горная вершина на высоте 2320 метров с подвесными мостами и качелями над облаками.',
    address: 'Горный курорт Роза Хутор',
    locationSlug: 'sochi-roza-pik',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 43.625345,
    longitude: 40.311456,
  },
  {
    name: 'Орнитологический парк',
    desc: 'Дикий охраняемый природный оазис в Имеретинской низменности с редкими перелетными птицами.',
    address: 'ул. Таврическая, 1/3 (Сириус)',
    locationSlug: 'sochi-ornitologicheskiy-park',
    mustSeeFilter: 'park',
    visitMinutes: 45,
    latitude: 43.393436,
    longitude: 40.00392,
  },

  // --- Гастрономия / Театры (40-50) ---
  {
    name: 'Зимний театр',
    desc: 'Величественный академический театр с коринфской колоннадой - главная сцена культурной жизни Юга.',
    address: 'ул. Театральная, 2',
    locationSlug: 'sochi-zimniy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 43.577464,
    longitude: 39.730303,
  },
  {
    name: 'Летний театр',
    desc: 'Неоклассическая открытая концертная площадка посреди парка имени Фрунзе.',
    address: 'ул. Черноморская, 11',
    locationSlug: 'sochi-letniy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 43.569442,
    longitude: 39.735165,
  },
  {
    name: 'Ресторан «Плакучая Ива»',
    desc: 'Премиальный рыбный ресторан от White Rabbit Family с переосмысленной классикой Черноморья.',
    address: 'ул. Войкова, 3',
    locationSlug: 'sochi-plakuchaya-iva',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 43.581515,
    longitude: 39.719602,
  },
  {
    name: 'Гастробар «Баран-Рапан»',
    desc: 'Культовый ресторан авторской кавказско-черноморской кухни, отмеченный ведущими премиями.',
    address: 'ул. Театральная, 11',
    locationSlug: 'sochi-baran-rapan',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 43.578631,
    longitude: 39.729112,
  },
  {
    name: 'Ресторан «D.O.M»',
    desc: 'Четырехуровневый гранд-ресторан на первой линии у Морского вокзала с панорамной террасой.',
    address: 'ул. Набережная, 3',
    locationSlug: 'sochi-restoran-dom',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 43.580456,
    longitude: 39.717619,
  },
  {
    name: 'Ресторан «Хмели & Сунели»',
    desc: 'Стильное городское пространство с современным взглядом на кавказскую кухню и сочинское гостеприимство.',
    address: 'ул. Несебрская, 4',
    locationSlug: 'sochi-hmeli-i-suneli',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 43.582823,
    longitude: 39.718817,
  },
  {
    name: 'Кафе «Белые Ночи»',
    desc: 'Легендарное городское заведение, знаменитое лучшими хинкали на всем побережье.',
    address: 'ул. Орджоникидзе, 9',
    locationSlug: 'sochi-belye-nochi',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 43.579043,
    longitude: 39.724501,
  },
  {
    name: 'Зал органной и камерной музыки',
    desc: 'Камерный концертный зал с уникальным чехословацким органом Rieger-Kloss и отличной акустикой.',
    address: 'Курортный проспект, 32',
    locationSlug: 'sochi-zal-organnoy-muzyki',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 43.584166,
    longitude: 39.724921,
  },
  {
    name: 'Ресторан «Red Fox»',
    desc: 'Гастрономическое сердце Красной Поляны на локальных продуктах горных лесов и рек.',
    address: 'наб. Лаванда, 3 (Роза Хутор)',
    locationSlug: 'sochi-red-fox',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 43.67389,
    longitude: 40.297455,
  },
  {
    name: 'Чебуречная «У Кристины»',
    desc: 'Аутентичное гастрономическое место с многолетней историей и сочными кавказскими чебуреками.',
    address: 'ул. Виноградная, 43А',
    locationSlug: 'sochi-cheburechnaya-u-kristiny',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 43.606788,
    longitude: 39.719875,
  },
  {
    name: 'Концертный зал «Фестивальный»',
    desc: 'Открытый амфитеатр на склоне у моря, где под шум волн проходят главные летние шоу эстрады.',
    address: 'ул. Орджоникидзе, 5',
    locationSlug: 'sochi-kontsertnyy-zal-festivalnyy',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 43.580421,
    longitude: 39.721456,
  },
];

export const SOCHI_SUBURBS: any[] = [
  {
    name: 'Красная Поляна и Эстосадок',
    desc: 'Из глухого кавказского поселка вырос ультрасовременный горнолыжный кластер мирового уровня с альпийской эстетикой. Горный воздух смешивается со средиземноморским сервисом.',
    locationSlug: 'sochi-krasnaya-polyana',
    mustSeeFilter: 'main',
    visitMinutes: '8-10 ч',
    latitude: 43.672619,
    longitude: 40.296541,
    address: 'п. Эстосадок, ул. Олимпийская, 35',
    travelVector: 'Ласточка ~1 ч 15 мин',
    travelVectorBlurb:
      'Закладывайте на электропоезд «Ласточка» из Сочи ~1 час 15 минут, чтобы приехать к 08:30 утра.',
    timingNote:
      'По прибытии на станцию Роза Хутор двигайтесь вдоль набережной Лаванда к нижним станциям канатных дорог, напоследок оставив вечерний ужин в Red Fox.',
    places: [
      {
        name: 'Ратуша на площади Роза',
        desc: 'Символ курорта с часовой башней в стиле вокзала Сочи.',
        locationSlug: 'sochi-krasnaya-polyana-ratusha-roza',
        address: 'п. Эстосадок, площадь Роза',
        latitude: 43.672619,
        longitude: 40.296541,
        visitMinutes: 20,
      },
      {
        name: 'Канатная дорога «Олимпия»',
        desc: 'Масштабный подъем в кабинках над пропастью до отметки 1170 м.',
        locationSlug: 'sochi-krasnaya-polyana-kanatnaya-olimpiya',
        address: 'п. Эстосадок, Роза Хутор',
        latitude: 43.6728,
        longitude: 40.2972,
        visitMinutes: 45,
      },
      {
        name: 'Горная олимпийская деревня',
        desc: 'Эстетичный городок шале, где жили спортсмены в 2014 году.',
        locationSlug: 'sochi-krasnaya-polyana-olimpiyskaya-derevnya',
        address: 'п. Эстосадок, горный кластер',
        latitude: 43.68,
        longitude: 40.3,
        visitMinutes: 30,
      },
      {
        name: 'Смотровая Роза Пик',
        desc: 'Вершина 2320 метров с панорамой Главного Кавказского хребта.',
        locationSlug: 'sochi-krasnaya-polyana-roza-pik',
        address: 'Горный курорт Роза Хутор',
        latitude: 43.625345,
        longitude: 40.311456,
        visitMinutes: 60,
      },
      {
        name: 'Парк водопадов «Менделиха»',
        desc: 'Живописный треккинг среди диких водопадов на южном склоне горы.',
        locationSlug: 'sochi-krasnaya-polyana-mendelikha',
        address: 'п. Эстосадок, южный склон',
        latitude: 43.66,
        longitude: 40.32,
        visitMinutes: 90,
      },
      {
        name: 'Ресторан Red Fox',
        desc: 'Главный высокогорный гастрономический спот региона.',
        locationSlug: 'sochi-krasnaya-polyana-red-fox',
        address: 'наб. Лаванда, 3 (Роза Хутор)',
        latitude: 43.67389,
        longitude: 40.297455,
        visitMinutes: 90,
      },
      {
        name: 'Этнопарк «Моя Россия»',
        desc: 'Культурный комплекс с архитектурными миниатюрами регионов РФ.',
        locationSlug: 'sochi-krasnaya-polyana-moya-rossiya',
        address: 'п. Эстосадок, окраина курорта',
        latitude: 43.675,
        longitude: 40.29,
        visitMinutes: 60,
      },
    ],
  },
  {
    name: 'Сириус и Имеретинская низменность',
    desc: 'Первая федеральная территория России: наука, спорт, море и футуристичная архитектура стадионов. Плоский ландшафт, широкие пляжи без волнорезов и космический силуэт олимпийского кластера.',
    locationSlug: 'sochi-sirius',
    mustSeeFilter: 'main',
    visitMinutes: '7-8 ч',
    latitude: 43.405076,
    longitude: 39.954605,
    address: 'пгт. Сириус, Имеретинская низменность',
    travelVector: 'Такси / экспресс ~45 мин',
    travelVectorBlurb:
      'Закладывайте на такси или автобус «Экспресс» ~45 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'По Имеретинской набережной двигайтесь на электросамокатах с юга на север в сторону Медальной площади, напоследок оставив шоу Поющих фонтанов.',
    places: [
      {
        name: 'Стадион «Фишт»',
        desc: 'Грандиозная арена открытия Олимпиады и матчей Чемпионата мира по футболу.',
        locationSlug: 'sochi-sirius-stadion-fisht',
        address: 'пгт. Сириус, Олимпийский парк',
        latitude: 43.402,
        longitude: 39.956,
        visitMinutes: 30,
      },
      {
        name: 'Медальная площадь',
        desc: 'Центральная площадь кластера, где награждали олимпийских чемпионов.',
        locationSlug: 'sochi-sirius-medalnaya-ploschad',
        address: 'пгт. Сириус, Медальная площадь',
        latitude: 43.405076,
        longitude: 39.954605,
        visitMinutes: 30,
      },
      {
        name: 'Чаша Олимпийского огня',
        desc: 'Огромный монумент-стела, превращенный в гигантский музыкальный фонтан.',
        locationSlug: 'sochi-sirius-chasha-olimpiyskogo-ognya',
        address: 'пгт. Сириус, Медальная площадь',
        latitude: 43.4055,
        longitude: 39.955,
        visitMinutes: 40,
      },
      {
        name: 'Автодром Игора Драйв',
        desc: 'Гоночный трек экс-Формулы-1, обвивающий олимпийские объекты.',
        locationSlug: 'sochi-sirius-avtodrom-igora-drayv',
        address: 'пгт. Сириус, Имеретинская низменность',
        latitude: 43.41,
        longitude: 39.97,
        visitMinutes: 45,
      },
      {
        name: 'Имеретинская набережная',
        desc: 'Самый длинный благоустроенный пешеходно-велосипедный променад длиной 7 км.',
        locationSlug: 'sochi-sirius-imeretinskaya-naberezhnaya',
        address: 'пгт. Сириус, Имеретинская набережная',
        latitude: 43.4,
        longitude: 39.96,
        visitMinutes: 60,
      },
      {
        name: 'Природный орнитологический парк',
        desc: 'Охраняемые пруды с перелетными птицами посреди Имеретинки.',
        locationSlug: 'sochi-sirius-ornitologicheskiy-park',
        address: 'ул. Таврическая, 1/3 (Сириус)',
        latitude: 43.393436,
        longitude: 40.00392,
        visitMinutes: 45,
      },
      {
        name: 'Парк «Южные культуры»',
        desc: 'Вековой субтропический оазис с редкими магнолиями на границе с Адлером.',
        locationSlug: 'sochi-sirius-yuzhnye-kultury',
        address: 'ул. Губернская, 13 (мкр. Адлер)',
        latitude: 43.418703,
        longitude: 39.935105,
        visitMinutes: 60,
      },
    ],
  },
  {
    name: 'Тисо-самшитовая роща и каньон Чёртовы Ворота',
    desc: 'Доледниковый реликтовый лес возрастом более 30 миллионов лет. Вековой мох на тисах и известняковые каньоны создают атмосферу сказочного фэнтези.',
    locationSlug: 'sochi-tiso-samshitovaya-roscha',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 43.528341,
    longitude: 39.874112,
    address: 'Хостинский район, ул. Самшитовая',
    travelVector: 'Автобус 105 ~30 мин',
    travelVectorBlurb:
      'Закладывайте на автобус №105 или маршрутку до Хосты ~30 минут, чтобы приехать к 08:00 утра.',
    timingNote:
      'По Большому кольцу заповедника двигайтесь строго по маркированной тропе вглубь каньона реки Хоста, напоследок оставив купание в лазурных водах Чертовых Ворот.',
    places: [
      {
        name: 'Малое кольцо рощи',
        desc: 'Адаптированная легкая тропа среди вековых тисов для быстрой прогулки.',
        locationSlug: 'sochi-tiso-maloe-koltso',
        address: 'Хостинский район, ул. Самшитовая',
        latitude: 43.528341,
        longitude: 39.874112,
        visitMinutes: 40,
      },
      {
        name: 'Большое кольцо рощи',
        desc: 'Сложный дикий трек со спусками к горной реке и скальным обрывам.',
        locationSlug: 'sochi-tiso-bolshoe-koltso',
        address: 'Хостинский район, ул. Самшитовая',
        latitude: 43.529,
        longitude: 39.875,
        visitMinutes: 120,
      },
      {
        name: 'Ущелье «Лабиринт»',
        desc: 'Глубокий тектонический разлом в известняковых скалах, поросший редким папоротником.',
        locationSlug: 'sochi-tiso-ushchele-labirint',
        address: 'Хостинский район, Тисо-самшитовая роща',
        latitude: 43.53,
        longitude: 39.876,
        visitMinutes: 30,
      },
      {
        name: 'Развалины Хостинской крепости',
        desc: 'Древние остатки византийского оборонительного форта VII-X веков.',
        locationSlug: 'sochi-tiso-hostinskaya-krepost',
        address: 'Хостинский район, Тисо-самшитовая роща',
        latitude: 43.531,
        longitude: 39.877,
        visitMinutes: 25,
      },
      {
        name: 'Смотра «Белые скалы»',
        desc: 'Панорамная площадка над отвесным обрывом стометровой глубины.',
        locationSlug: 'sochi-tiso-belye-skaly',
        address: 'Хостинский район, Тисо-самшитовая роща',
        latitude: 43.532,
        longitude: 39.878,
        visitMinutes: 20,
      },
      {
        name: 'Река Хоста',
        desc: 'Кристально чистая холодная горная артерия, пробивающая скалы.',
        locationSlug: 'sochi-tiso-reka-hosta',
        address: 'Хостинский район, каньон реки Хоста',
        latitude: 43.527,
        longitude: 39.873,
        visitMinutes: 20,
      },
      {
        name: 'Каньон «Чёртовы Ворота»',
        desc: 'Сужение скал, образующее изумрудное глубокое озеро для купания.',
        locationSlug: 'sochi-tiso-chertovy-vorota',
        address: 'Хостинский район, каньон Чёртовы Ворота',
        latitude: 43.526,
        longitude: 39.872,
        visitMinutes: 40,
      },
    ],
  },
  {
    name: 'Гора Большой Ахун и Агурское ущелье',
    desc: 'Культовое место силы Сочи: легенды о Прометее, карстовые пещеры и лучшая панорамная точка Кавказа. Субтропическая сырость ущелья сменяется горной свежестью на вершине.',
    locationSlug: 'sochi-bolshoy-ahun',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 43.550389,
    longitude: 39.843606,
    address: 'Хостинский район, гора Большой Ахун',
    travelVector: 'Авто / трансфер ~40 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль или экскурсионный трансфер ~40 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'По Агурскому ущелью двигайтесь вверх вдоль течения реки мимо водопадов к Орлиным скалам, напоследок оставив панорамный подъем на вершину Ахуна.',
    places: [
      {
        name: 'Нижний Агурский водопад',
        desc: 'Двухкаскадный водопад с глубокой лазурной чашей.',
        locationSlug: 'sochi-ahun-nizhniy-agurskiy-vodopad',
        address: 'Хостинский район, Агурское ущелье',
        latitude: 43.55,
        longitude: 39.84,
        visitMinutes: 25,
      },
      {
        name: 'Скала «Нора Дьявола»',
        desc: 'Мрачная мистическая пещера-грот у входа в ущелье.',
        locationSlug: 'sochi-ahun-nora-dyavola',
        address: 'Хостинский район, Агурское ущелье',
        latitude: 43.549,
        longitude: 39.839,
        visitMinutes: 15,
      },
      {
        name: 'Средний и Верхний водопады',
        desc: 'Череда бурных водных порогов посреди отвесных слоистых скал.',
        locationSlug: 'sochi-ahun-sredniy-verhniy-vodopady',
        address: 'Хостинский район, Агурское ущелье',
        latitude: 43.552,
        longitude: 39.842,
        visitMinutes: 40,
      },
      {
        name: 'Орлиные скалы',
        desc: 'Величественные белые известняковые обрывы высотой 125 метров над бездной.',
        locationSlug: 'sochi-ahun-orlinye-skaly',
        address: 'Мацестинский лесопарк, Орлиные скалы',
        latitude: 43.559288,
        longitude: 39.822896,
        visitMinutes: 40,
      },
      {
        name: 'Скульптура Прометея',
        desc: 'Бронзовый монумент титану на краю Орлиных скал.',
        locationSlug: 'sochi-ahun-prometej',
        address: 'Мацестинский лесопарк, Орлиные скалы',
        latitude: 43.559288,
        longitude: 39.822896,
        visitMinutes: 15,
      },
      {
        name: 'Смотрительная башня Ахун',
        desc: '30-метровая романская башня, построенная по приказу Сталина.',
        locationSlug: 'sochi-ahun-smotritelnaya-bashnya',
        address: 'гора Большой Ахун',
        latitude: 43.550389,
        longitude: 39.843606,
        visitMinutes: 40,
      },
      {
        name: 'Ахунская пещера',
        desc: 'Дикая спелеологическая локация в недрах горы с редкими сталактитами.',
        locationSlug: 'sochi-ahun-peshchera',
        address: 'Хостинский район, гора Большой Ахун',
        latitude: 43.551,
        longitude: 39.844,
        visitMinutes: 30,
      },
    ],
  },
];

export const SOCHI_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'sochi-parade-center',
    title: 'Парадный Сочи: от Вокзала до Зимнего',
    description:
      'Емкий пешеходный трек по главным историческим точкам, променадам и визитным карточкам центрального Сочи.',
    travelVector: 'Парадный пешеходный променад',
    timingNote:
      'Около 4 часов: ж/д вокзал - Навагинская - Морвокзал - собор - «Баран-Рапан» - Зимний театр.',
    coverImageUrl: '/images/venues/sochi/morskoy-vokzal-sochi.jpg',
    stops: [
      {
        name: 'Железнодорожный вокзал Сочи',
        desc: '15 минут на осмотр башни Душкина и внутренних двориков с фонтанами.',
        locationSlug: 'sochi-zheleznodorozhnyy-vokzal',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'ул. Горького, 56',
        latitude: 43.593021,
        longitude: 39.727653,
      },
      {
        name: 'Улица Навагинская и «Ухо желаний»',
        desc: '25 минут под пальмами сочинского «Арбата» и загадывание желания у чугунного уха.',
        locationSlug: 'sochi-uho-zhelaniy',
        mustSeeFilter: 'monument',
        visitMinutes: 25,
        address: 'ул. Навагинская, 7',
        latitude: 43.585721,
        longitude: 39.72481,
        transitTip: 'Пешком 2 минуты (150 м)',
      },
      {
        name: 'Морской вокзал и «Бриллиантовая рука»',
        desc: '30 минут на шпиль, фотосет на фоне яхт и бронзовых героев фильма.',
        locationSlug: 'sochi-morskoy-vokzal',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        address: 'ул. Войкова, 1',
        latitude: 43.580718,
        longitude: 39.718683,
        transitTip: 'Пешком 10 минут (800 м)',
      },
      {
        name: 'Собор Архангела Михаила и памятник Архангелу',
        desc: '20 минут у стен старейшего собора и монумента покровителю города.',
        locationSlug: 'sochi-sobor-arhangela-mihaila',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'ул. Москвина, 12',
        latitude: 43.581021,
        longitude: 39.7226,
        transitTip: 'Пешком 8 минут (600 м)',
      },
      {
        name: '«Золотое руно» и Художественный музей',
        desc: '15 минут на фото у мифического руна и осмотр фасада музея.',
        locationSlug: 'sochi-zolotoe-runo',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'площадь Искусств, 1',
        latitude: 43.57833,
        longitude: 39.725946,
        transitTip: 'Пешком 7 минут (550 м)',
      },
      {
        name: 'Гастробар «Баран-Рапан»',
        desc: 'Час на дегустацию локальных рапанов и кавказских специалитетов.',
        locationSlug: 'sochi-baran-rapan',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Театральная, 11',
        latitude: 43.578631,
        longitude: 39.729112,
        transitTip: 'Пешком 5 минут (400 м)',
      },
      {
        name: 'Зимний театр',
        desc: '20 минут на осмотр грандиозной колоннады в лучах вечернего солнца.',
        locationSlug: 'sochi-zimniy-teatr',
        mustSeeFilter: 'creative',
        visitMinutes: 20,
        address: 'ул. Театральная, 2',
        latitude: 43.577464,
        longitude: 39.730303,
        transitTip: 'Пешком 3 минуты (200 м)',
      },
    ],
  },
  {
    id: 'sochi-boho-old-world',
    title: 'Курортный бохо-шик и Старый Свет',
    description:
      'Прогулка в размеренном темпе для ценителей эстетики сталинского ампира, ботанического искусства и знаковых гастролокаций.',
    travelVector: 'Парки, ампир и Дендрарий',
    timingNote:
      'Около 5 часов: храм Владимира - «Ривьера» - «Плакучая Ива» - Нептун - Летний театр - Дендрарий.',
    coverImageUrl: '/images/venues/sochi/dendrariy.jpg',
    stops: [
      {
        name: 'Храм Святого Владимира',
        desc: '20 минут на вершине Виноградной горы с панорамой у золотых куполов.',
        locationSlug: 'sochi-hram-svyatogo-vladimira',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'ул. Виноградная, 18',
        latitude: 43.603348,
        longitude: 39.720516,
      },
      {
        name: 'Парк «Ривьера» и Памятник Филину',
        desc: '40 минут по вековым аллеям Хлудова и фото у памятника многодетным отцам.',
        locationSlug: 'sochi-park-riviera',
        mustSeeFilter: 'park',
        visitMinutes: 40,
        address: 'ул. Егорова, 1',
        latitude: 43.590822,
        longitude: 39.714343,
        transitTip: 'Пешком 12 минут (900 м)',
      },
      {
        name: 'Ресторан «Плакучая Ива»',
        desc: 'Час на ранний обед от WRF со свежим черноморским уловом.',
        locationSlug: 'sochi-plakuchaya-iva',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Войкова, 3',
        latitude: 43.581515,
        longitude: 39.719602,
        transitTip: 'Пешком 15 минут (1.1 км) через Ривьерский мост',
      },
      {
        name: 'Памятник Нептуну',
        desc: '10 минут на снимок у повелителя волн на пляжном променаде.',
        locationSlug: 'sochi-pamyatnik-neptunu',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'Приморская набережная, 11/1',
        latitude: 43.575971,
        longitude: 39.725176,
        transitTip: 'Пешком 10 минут (800 м)',
      },
      {
        name: 'Летний театр и памятник Островскому',
        desc: '20 минут на ротонду театра в парке Фрунзе и строгий памятник писателю.',
        locationSlug: 'sochi-letniy-teatr',
        mustSeeFilter: 'creative',
        visitMinutes: 20,
        address: 'ул. Черноморская, 11',
        latitude: 43.569442,
        longitude: 39.735165,
        transitTip: 'Пешком 12 минут (950 м)',
      },
      {
        name: 'Нижний и Верхний «Дендрарий» + вилла «Надежда»',
        desc: '1.5 часа среди экзотических пальм, особняк Худекова и подъем на канатке на закате.',
        locationSlug: 'sochi-dendrariy-verhniy',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        address: 'Курортный проспект, 74',
        latitude: 43.570122,
        longitude: 39.743118,
        transitTip: 'Пешком 8 минут (650 м)',
      },
    ],
  },
  ...SOCHI_LINE_DAY_ROUTE_PRESETS,
];

export const SOCHI_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что из аэропорта Адлера до центра Сочи быстрее и дешевле доехать на такси, чем на общественном транспорте?',
    a: 'Абсолютный миф, который в разгар сезона обернется потерей 2-3 часов в мертвой пробке в районе Кудепсты и Хосты. Самый быстрый, пунктуальный и надежный способ - скоростная электричка «Ласточка». Она довезет вас от платформы в аэропорту до ж/д вокзала Сочи ровно за 40-50 минут без заторов, а билет обойдется в несколько раз дешевле, чем тарифы агрегаторов в пиковые часы.',
  },
  {
    q: 'Слышал, что на сочинских рынках местных жителей и туристов рассчитывают по разным ценам. Как не переплачивать на Центральном рынке?',
    a: 'В Сочи действительно существует скрытый «курортный налог» на харизму. Чтобы покупать чурчхелу, вяленую хурму и сыр по ценам для местных, соблюдайте три правила: никогда не заходите на рынок с чемоданом или пляжной сумкой, сразу уходите от центральных рядов вглубь к местным бабушкам и всегда уверенно торгуйтесь, называя цену на 20-30% ниже заявленной.',
  },
  {
    q: 'Местные пугают кишечной палочкой и «ротавирусом» в Черном море. Есть ли безопасные локации для купания в черте города?',
    a: 'Риск подхватить инфекцию в июле-августе на центральных забитых пляжах (вроде «Маяка» или «Ривьеры») действительно высок из-за высокой температуры воды и волнорезов, мешающих циркуляции. Секретный лайфхак местных - уезжать купаться на пляжи Имеретинской низменности (Сириус), где открытое море, нет волнорезов и идет постоянное прибрежное течение, либо выбирать дикие пляжи в районе мацестинского виадука.',
  },
  {
    q: 'Можно ли сэкономить на едином ски-пассе в Красной Поляне, если кататься на всех трех курортах по очереди?',
    a: 'Единый ски-пасс существует, но покупать его выгодно только если вы уверенный райдер и планируете фрирайд-переходы между «Роза Хутор» и «Газпром Альпика». Если вы катаетесь по подготовленным трассам, выгоднее покупать сезонные или дневные абонементы конкретно под один курорт (например, «Красная Поляна» или «Роза Хутор»), так как логистически перебираться между ними посреди дня на лыжах - долго и энергозатратно.',
  },
];

export const SOCHI_TRAVEL =
  'Из аэропорта Адлера до центра удобнее всего на «Ласточке»: 40-50 минут без пробок, дешевле такси в сезон. Внутри города и в Адлер / Красную Поляну - автобусы по «Тройке» и пакетные абонементы РЖД на «Ласточку». Зимой - горнолыжный сплит в Красной Поляне при +10 °C на побережье. Весной совмещают лыжи и пляжные прогулки, в мае - цветение и треккинг к водопадам. Лето: пик пляжа, +30 °C, море до +26 °C, высокая влажность. Осень: золотой сезон, море еще теплое (+23 °C в сентябре-октябре), гастро и спокойные выезды в заповедник.';
