/** Tula tourist hub pack (owner 2026-08-22). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { TULA_LINE_DAY_ROUTE_PRESETS } from './tula-line-presets.ts';

function place(
  name: string,
  desc: string,
  latitude: number,
  longitude: number,
  opts: {
    address: string;
    locationSlug?: string;
    venueSlug?: string;
    mustSeeFilter?: string;
    visitMinutes?: number | string;
    alsoMain?: boolean;
  },
): any {
  return {
    name,
    desc,
    address: opts.address,
    latitude,
    longitude,
    mustSeeFilter: opts.mustSeeFilter || 'main',
    visitMinutes: opts.visitMinutes ?? 20,
    ...(opts.locationSlug ? { locationSlug: opts.locationSlug } : {}),
    ...(opts.venueSlug ? { venueSlug: opts.venueSlug } : {}),
    ...(typeof opts.alsoMain === 'boolean' ? { alsoMain: opts.alsoMain } : {}),
  };
}

export const TULA_MUST_SEE: any[] = [
  place('Памятник Левше', 'Культовая фигура тульского мастера, филигранно подковавшего блоху.', 54.199182, 37.614605, { address: 'ул. Советская, 1А', locationSlug: 'tula-pamyatnik-levshe', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Скульптура «Тульский пряник»', 'Огромный бронзовый памятник главному гастрономическому бренду города весом более тонны.', 54.193181, 37.6173, { address: 'пл. Ленина', locationSlug: 'tula-skulptura-tulskiy-pryanik', mustSeeFilter: 'monument', visitMinutes: 20, alsoMain: true }),
  place('Памятник Никите Демидову', 'Монументальное изваяние основателю знаменитой династии промышленников у стен их родового храма.', 54.204561, 37.618641, { address: 'ул. Колетвинова, 2', locationSlug: 'tula-pamyatnik-nikite-demidovu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Арт-объект «Тульское чаепитие»', 'Уютная уличная сцена из бронзы: мужчина и женщина за самоваром с гармонью и собакой.', 54.195321, 37.603412, { address: 'ул. Пушкинская / ул. Лейтейзена', locationSlug: 'tula-art-tulskoe-chaepitie', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Сводному отряду чекистов', 'Мемориал в честь защитников города, насмерть стоявших в боях осенью 1941 года.', 54.194723, 37.622114, { address: 'ул. Менделеевская, 8', locationSlug: 'tula-pamyatnik-svodnomu-otryadu-chekistov', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Скульптура «Тульский динозавр» (Тёща)', 'Ироничная фигура серпентоида, которую местные регулярно наряжают в сезонные костюмы.', 54.204481, 37.620511, { address: 'ул. Октябрьская, 18А', locationSlug: 'tula-skulptura-tulskiy-dinozavr', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник В. В. Вересаеву', 'Классический монумент писателю и врачу-пушкинисту у входа в Центральный парк.', 54.183421, 37.599824, { address: 'ул. Первомайская, 13А', locationSlug: 'tula-pamyatnik-veresaevu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Петру I', 'Могучая фигура императора-реформатора, основавшего в Туле первый государственный оружейный завод.', 54.198941, 37.615144, { address: 'ул. Советская, 1А', locationSlug: 'tula-pamyatnik-petru-i', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник защитникам Тулы', 'Грандиозный мемориальный комплекс на площади Победы с Вечным огнем и стальными штыками.', 54.175112, 37.590214, { address: 'пл. Победы', locationSlug: 'tula-pamyatnik-zashchitnikam-tuly', mustSeeFilter: 'monument', visitMinutes: 20 }),
  place('Арт-объект «Еж - патриот Тулы»', 'Милая миниатюрная фигурка ежа, держащего в лапах тульский оружейный патрон.', 54.193811, 37.621415, { address: 'Кремлевский сквер', locationSlug: 'tula-art-ezh-patriot', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник хвосту', 'Ироничная 30-сантиметровая фигурка ящерицы, потерявшей хвост, установленная студентами ради удачи на экзаменах.', 54.167232, 37.587841, { address: 'пр-т Ленина, 84к2', locationSlug: 'tula-pamyatnik-hvostu', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник В. Ф. Рудневу', 'Монумент командиру легендарного крейсера «Варяг», уроженцу Тульской губернии.', 54.202312, 37.619521, { address: 'ул. Октябрьская, 2', locationSlug: 'tula-pamyatnik-rudnevu', mustSeeFilter: 'monument', visitMinutes: 15 }),
  place('Памятник Ученому коту', 'Скульптурная композиция сказочного персонажа с книгой у стен детского универмага.', 54.192843, 37.619421, { address: 'ул. Советская, 47', locationSlug: 'tula-pamyatnik-uchenomu-kotu', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Арт-объект «Грибная поляна»', 'Декоративная кованая композиция из лесных грибов на Казанской набережной.', 54.197321, 37.617812, { address: 'Казанская набережная', locationSlug: 'tula-art-gribnaya-polyana', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Памятник сотрудникам органов госбезопасности', 'Строгая мемориальная стела, посвященная подвигам тульских чекистов в тылу врага.', 54.195612, 37.620121, { address: 'Кремлевский сад', locationSlug: 'tula-pamyatnik-sotrudnikam-gosbezopasnosti', mustSeeFilter: 'monument', visitMinutes: 10 }),
  place('Тульский кремль', 'Главная древняя крепость города, ни разу не сдавшаяся врагу за всю пятивековую историю.', 54.195214, 37.617843, { address: 'ул. Менделеевская, 12А', locationSlug: 'tula-tul-skiy-kreml', mustSeeFilter: 'houses', visitMinutes: 60, alsoMain: true }),
  place('Башня Одоевских ворот', 'Парадные въездные ворота Тульского кремля, увенчанные историческим гербом города.', 54.194231, 37.617412, { address: 'ул. Менделеевская, Кремль', locationSlug: 'tula-bashnya-odoevskih-vorot', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Башня Пятницких ворот', 'Массивная оборонительная башня, где в старину хранились запасы оружия и пороха.', 54.195111, 37.615923, { address: 'ул. Металлистов, Кремль', locationSlug: 'tula-bashnya-pyatnitskih-vorot', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Ивановская башня', 'Ключевой фортификационный узел Кремля со скрытым проходом к реке Упе.', 54.196341, 37.618911, { address: 'Казанская набережная, Кремль', locationSlug: 'tula-ivanovskaya-bashnya', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Водяные ворота Кремля', 'Уникальный арочный проход, через который в древности выходили к реке во время осад.', 54.196011, 37.617214, { address: 'северная стена Кремля', locationSlug: 'tula-vodyanye-vorota', mustSeeFilter: 'houses', visitMinutes: 15 }),
  place('Улица Металлистов', 'Полностью пешеходная зона с отреставрированными купеческими особняками XVIII-XIX веков.', 54.196412, 37.614811, { address: 'ул. Металлистов', locationSlug: 'tula-ulitsa-metallistov', mustSeeFilter: 'street', visitMinutes: 45, alsoMain: true }),
  place('Торговые ряды Кремля', 'Аутентичный исторический комплекс, где сегодня покупают лучшие тульские сувениры и пряники.', 54.194912, 37.616943, { address: 'территория Тульского кремля', locationSlug: 'tula-torgovye-ryady-kremlya', mustSeeFilter: 'houses', visitMinutes: 30 }),
  place('Дом жилой оружейников Лисицыных', 'Старейшая усадьба мастеров, основавших первое в России масштабное самоварное производство.', 54.205212, 37.614911, { address: 'ул. Демидовская, 34', locationSlug: 'tula-dom-lisitsynyh', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Особняк Белолипецких', 'Монументальное эклектичное здание, принадлежавшее знаменитым тульским кондитерам и мукомолам.', 54.196614, 37.614121, { address: 'ул. Металлистов, 10', locationSlug: 'tula-osobnyak-belolipetskih', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Усадьба Ермолаева-Зверева', 'Изящный образец модерна с элементами неоклассицизма в сердце исторического посада.', 54.194411, 37.621943, { address: 'ул. Менделеевская, 8', locationSlug: 'tula-usadba-ermolaeva-zvereva', mustSeeFilter: 'houses', visitMinutes: 20 }),
  place('Тульский государственный музей оружия', 'Футуристическое здание-шлем с одной из богатейших в мире коллекций стрелкового вооружения.', 54.203841, 37.619223, { address: 'ул. Октябрьская, 2', venueSlug: 'tula-muzey-oruzhiya-shlem', mustSeeFilter: 'museum', visitMinutes: 120, alsoMain: true }),
  place('Музей «Тульские самовары»', 'Легендарная экспозиция сотен видов водогреев - от крошечных сувенирных до вокзальных гигантов.', 54.194242, 37.616611, { address: 'ул. Менделеевская, 8', venueSlug: 'tula-muzey-tulskie-samovary', mustSeeFilter: 'museum', visitMinutes: 50 }),
  place('Музей «Тульский пряник»', 'Интерактивное пространство об искусстве выпечки и кондитерских династиях с дегустацией.', 54.207812, 37.621411, { address: 'ул. Октябрьская, 45А', venueSlug: 'tula-muzey-tul-skiy-pryanik', mustSeeFilter: 'museum', visitMinutes: 45 }),
  place('Музей станка в кластере «Октава»', 'Современный мультимедийный музей индустриализации через призму искусства.', 54.190623, 37.613941, { address: 'ул. Каминского, 24', venueSlug: 'tula-muzey-stanka-oktava', mustSeeFilter: 'museum', visitMinutes: 90 }),
  place('Старая тульская аптека', 'Атмосферный музей в историческом здании с подлинными колбами, рецептами и заспиртованной блохой.', 54.192312, 37.615822, { address: 'пр-т Ленина, 27', venueSlug: 'tula-staraya-tulskaya-apteka', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Тульский областной художественный музей', 'Крупное региональное собрание живописи, включая шедевры Айвазовского, Шишкина и Серова.', 54.180421, 37.601214, { address: 'ул. Ф. Энгельса, 64', venueSlug: 'tula-oblastnoy-hudozhestvennyy-muzey', mustSeeFilter: 'museum', visitMinutes: 90 }),
  place('Музей «Гармони Деда Филимона»', 'Душевный частный музей, где экскурсоводы вживую играют на редких гармониках.', 54.194911, 37.619821, { address: 'ул. Менделеевская, 9', venueSlug: 'tula-muzey-garmoni-deda-filimona', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Дом-музей В. В. Вересаева', 'Уютный мемориальный дом, воссоздающий быт провинциальной интеллигенции начала XX века.', 54.187312, 37.605214, { address: 'ул. Гоголевская, 82', venueSlug: 'tula-dom-muzey-veresaeva', mustSeeFilter: 'museum', visitMinutes: 40 }),
  place('Музей ДПИ в Центре семейной истории', 'Филиал музея-поля Поленова, посвященный семейным архивам и старинному быту.', 54.195914, 37.612411, { address: 'ул. Благовещенская, 8Г', venueSlug: 'tula-muzey-dpi-tsentr-semeynoy-istorii', mustSeeFilter: 'museum', visitMinutes: 45 }),
  place('Историко-мемориальный музей Демидовых', 'Выставочный комплекс у родовой усыпальницы с археологическими находками эпохи первых заводов.', 54.204312, 37.618911, { address: 'ул. Демидовская, 9', venueSlug: 'tula-istoriko-memorialnyy-muzey-demidovyh', mustSeeFilter: 'museum', visitMinutes: 45 }),
  place('Успенский собор в Кремле', 'Величественный барочный храм XVIII века с тридцатиметровой колокольней и фресками ярославских мастеров.', 54.195311, 37.617943, { address: 'территория Тульского кремля', locationSlug: 'tula-uspenskiy-sobor-kremlya', mustSeeFilter: 'temple', visitMinutes: 40 }),
  place('Благовещенская церковь', 'Старейший сохранившийся православный храм Тулы в формах нарядного московского узорочья (1692).', 54.196323, 37.613312, { address: 'ул. Благовещенская, 4', locationSlug: 'tula-blagoveshchenskaya-tserkov', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Всехсвятский кафедральный собор', 'Классический храм на холме с трехъярусной колокольней, видимой из любой точки города.', 54.184311, 37.613941, { address: 'ул. Льва Толстого, 79', locationSlug: 'tula-vsekhsvyatskiy-kafedralnyy-sobor', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Николо-Зарецкая церковь', 'Родовая церковь-усыпальница промышленников Демидовых в стиле раннего барокко.', 54.204212, 37.618411, { address: 'ул. Оружейная / Демидовская, 9А', locationSlug: 'tula-nikolo-zaretskaya-tserkov', mustSeeFilter: 'temple', visitMinutes: 30 }),
  place('Храм Сергия Радонежского', 'Византийский собор в Зареченском районе с яркой колористикой и росписями.', 54.212312, 37.623114, { address: 'ул. Октябрьская, 78', locationSlug: 'tula-hram-sergiya-radonezhskogo', mustSeeFilter: 'temple', visitMinutes: 25 }),
  place('Центральный парк культуры и отдыха им. П. П. Белоусова', 'Огромный зеленый массив в черте города, входящий в топ-10 крупнейших парков Европы.', 54.181211, 37.593412, { address: 'ул. Первомайская, 13А', locationSlug: 'tula-park-belousova', mustSeeFilter: 'park', visitMinutes: 90 }),
  place('Казанская набережная', 'Современная ландшафтная зона у стен Кремля со стильными мостами, беседками и амфитеатрами у воды.', 54.196812, 37.616943, { address: 'Казанская набережная', locationSlug: 'tula-kazanskaya-naberezhnaya', mustSeeFilter: 'park', visitMinutes: 60, alsoMain: true }),
  place('Кремлевский сквер', 'Живописная ухоженная аллея с фонтанами, огибающая южную стену крепости.', 54.194211, 37.619214, { address: 'ул. Менделеевская', locationSlug: 'tula-kremlevskiy-skver', mustSeeFilter: 'park', visitMinutes: 30 }),
  place('Смотровая площадка Пролетарской набережной', 'Точка на противоположном берегу Упы для панорамы Музея оружия и Чулковского моста.', 54.199312, 37.626412, { address: 'Пролетарская набережная', locationSlug: 'tula-smotrovaya-proletarskoy-naberezhnoy', mustSeeFilter: 'views', visitMinutes: 25 }),
  place('Рогожинский парк', 'Уютный исторический парк на юге Тулы с чистыми прудами и памятными знаками Тульского рабочего полка.', 54.173812, 37.625114, { address: 'ул. Демьянова, 26', locationSlug: 'tula-rogozhinskiy-park', mustSeeFilter: 'park', visitMinutes: 45 }),
  place('Креативное пространство «Искра»', 'Главный городской гастро-хаб во дворах старинного квартала с лучшими барами и кофейнями.', 54.196411, 37.612214, { address: 'ул. Советская, 11', locationSlug: 'tula-kreativnoe-prostranstvo-iskra', mustSeeFilter: 'creative', visitMinutes: 60 }),
  place('Творческий индустриальный кластер «Октава»', 'Модное урбанистическое пространство на базе действующего завода микрофонов.', 54.190812, 37.613412, { address: 'ул. Каминского, 24', locationSlug: 'tula-tvorcheskiy-industrial-nyy-klaster-oktava', mustSeeFilter: 'creative', visitMinutes: 90, alsoMain: true }),
  place('Ресторан «Культура»', 'Современное гастрономическое место в «Искре», переосмысляющее русскую кухню.', 54.196512, 37.612514, { address: 'ул. Советская, 11', locationSlug: 'tula-restoran-kultura', mustSeeFilter: 'gastro', visitMinutes: 75 }),
  place('Тульский академический театр драмы им. М. Горького', 'Один из старейших драматических театров России с сильной труппой и классическим репертуаром.', 54.188412, 37.611114, { address: 'пр-т Ленина, 51', venueSlug: 'tula-teatr-dramy-gorkogo', mustSeeFilter: 'creative', visitMinutes: 30 }),
  place('Кафе-кондитерская «Пряности и Радости»', 'Популярное заведение с авторскими десертами и панорамным видом на исторический центр.', 54.201812, 37.618911, { address: 'ул. Октябрьская, 1Д', locationSlug: 'tula-kafe-pryanosti-i-radosti', mustSeeFilter: 'gastro', visitMinutes: 60 }),
];

export const TULA_SUBURBS: any[] = [
  {
    name: 'Музей-усадьба Л. Н. Толстого «Ясная Поляна»',
    desc: 'Родовое имение писателя с аллеей «Прешпект», прудами и строгой могилой в лесу Старый Заказ - место аскетичной природной гармонии.',
    locationSlug: 'tula-muzey-usad-ba-l-n-tolstogo-yasnaya-polyana',
    venueSlug: 'tula-muzey-usad-ba-l-n-tolstogo-yasnaya-polyana',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 54.072894,
    longitude: 37.524451,
    address: 'Щекинский район, д. Ясная Поляна',
    travelVector: 'Автобус 114 ~30 мин',
    travelVectorBlurb:
      'Закладывайте на личный автомобиль или автобус №114 ~30 минут, чтобы приехать к 09:30 утра до наплыва экскурсионных групп.',
    timingNote:
      'По территории усадьбы двигайтесь по березовой аллее «Прешпект» вглубь леса к Дому писателя, напоследок оставив уединенную могилу Льва Толстого в лесу Старый Заказ.',
    places: [
      place('Аллея «Прешпект»', 'Знаменитая березовая аллея - парадный вход в усадебный мир Толстого.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-prespekt', mustSeeFilter: 'park', visitMinutes: 20 }),
      place('Большой пруд с лебедями', 'Зеркальный пруд усадьбы с лебедями и классическим видом на усадебный пейзаж.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-prud', mustSeeFilter: 'park', visitMinutes: 20 }),
      place('Дом-музей Л. Н. Толстого', 'Главный дом с сохранившейся обстановкой кабинета, гостиных и библиотеки писателя.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-dom-muzey', mustSeeFilter: 'museum', visitMinutes: 60 }),
      place('Флигель Кузминских', 'Флигель родни писателя с камерной экспозицией семейного быта.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-fligel-kuzminskih', mustSeeFilter: 'museum', visitMinutes: 30 }),
      place('Историческая пашня и конюшня', 'Хозяйственная часть усадьбы: пашня и конюшня как часть толстовского уклада.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-pashnya', mustSeeFilter: 'park', visitMinutes: 25 }),
      place('Любимая скамейка писателя', 'Тихое место для созерцания, связанное с ежедневными прогулками Толстого.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-skameyka', mustSeeFilter: 'park', visitMinutes: 15 }),
      place('Могила Льва Толстого', 'Строгий зеленый холмик без гранитных памятников на краю оврага в лесу Старый Заказ.', 54.072894, 37.524451, { address: 'д. Ясная Поляна', locationSlug: 'tula-yasnaya-polyana-mogila', mustSeeFilter: 'park', visitMinutes: 25 }),
    ],
  },
  {
    name: 'Музей-заповедник «Куликово поле»',
    desc: 'Грандиозный мемориал под открытым небом, где в 1380 году решилась судьба русской государственности. Современный музей встроен в ландшафт и напоминает курган.',
    locationSlug: 'tula-kulikovo-pole',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 53.623412,
    longitude: 38.671231,
    address: 'Куркинский район, д. Моховое',
    travelVector: 'Авто ~1.5-2 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль ~1.5-2 часа (около 120 км от Тулы), чтобы приехать к 10:00 утра и успеть объехать масштабный комплекс.',
    timingNote:
      'От главного музейного комплекса в Моховом двигайтесь к Красному холму, напоследок оставив памятник-колонну Дмитрию Донскому и храм Сергия Радонежского.',
    places: [
      place('Музейный комплекс «Куликово поле» в Моховом', 'Современный музейный курган с экспозицией о Куликовской битве.', 53.623412, 38.671231, { address: 'д. Моховое', locationSlug: 'tula-kulikovo-pole-muzeynyy-kompleks', mustSeeFilter: 'museum', visitMinutes: 90 }),
      place('Интерактивный макет Куликовской битвы', 'Объемный макет поля сражения с пояснением тактики и сил сторон.', 53.623412, 38.671231, { address: 'д. Моховое', locationSlug: 'tula-kulikovo-pole-maket-bitvy', mustSeeFilter: 'museum', visitMinutes: 40 }),
      place('Памятник-колонна Дмитрию Донскому', 'Старейший памятник на Красном холме в честь победы 1380 года.', 53.623412, 38.671231, { address: 'Красный холм', locationSlug: 'tula-kulikovo-pole-kolonna-dmitriyu-donskomu', mustSeeFilter: 'monument', visitMinutes: 30 }),
      place('Храм-памятник Сергия Радонежского', 'Храм на поле битвы, посвященный благословению русского войска.', 53.623412, 38.671231, { address: 'Красный холм', locationSlug: 'tula-kulikovo-pole-hram-sergiya', mustSeeFilter: 'temple', visitMinutes: 30 }),
      place('Музей купеческого быта в Епифани', 'Камерный музей купеческой жизни на пути к полю битвы.', 53.623412, 38.671231, { address: 'г. Епифань', locationSlug: 'tula-kulikovo-pole-muzey-epifani', mustSeeFilter: 'museum', visitMinutes: 40 }),
      place('Слияние рек Дона и Непрядвы', 'Исторический ландшафт устья Непрядвы - природная сцена битвы.', 53.623412, 38.671231, { address: 'устье Непрядвы', locationSlug: 'tula-kulikovo-pole-slianie-don-nepryadva', mustSeeFilter: 'views', visitMinutes: 30 }),
      place('Аллея Памяти городов-участников битвы', 'Мемориальная аллея городов и земель, чьи дружины стояли на Куликовом поле.', 53.623412, 38.671231, { address: 'д. Моховое', locationSlug: 'tula-kulikovo-pole-alleya-pamyati', mustSeeFilter: 'park', visitMinutes: 20 }),
    ],
  },
  {
    name: 'Музей-усадьба В. Д. Поленова «Поленово»',
    desc: 'Усадьба, полностью спроектированная художником Василием Поленовым: европейский городок на высоком берегу Оки с видами, вдохновлявшими поколения пейзажистов.',
    locationSlug: 'tula-polenovo',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 54.749112,
    longitude: 37.241234,
    address: 'Заокский район, с. Страхово',
    travelVector: 'Авто ~1 ч 15 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль ~1 час 15 минут в сторону Серпухова, чтобы приехать к 10:00 утра, когда открываются кассы.',
    timingNote:
      'От парковки через сосновый бор двигайтесь к белоснежному Большому дому у реки Оки, напоследок оставив мастерскую «Аббатство» и Адмиралтейство.',
    places: [
      place('Большой дом с коллекциями живописи', 'Главный усадебный дом с живописью и интерьерами, задуманными самим Поленовым.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-bolshoy-dom', mustSeeFilter: 'museum', visitMinutes: 60 }),
      place('Мастерская художника «Аббатство»', 'Оригинальное здание мастерской с атмосферой поленовской творческой лаборатории.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-abbatstvo', mustSeeFilter: 'museum', visitMinutes: 40 }),
      place('Здание «Адмиралтейство»', 'Павильон со световой диорамой и видом на Оку.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-admiralteystvo', mustSeeFilter: 'museum', visitMinutes: 30 }),
      place('Фахверковый сарай', 'Хозяйственный фахверк усадьбы - деталь «европейского городка» Поленова.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-fahverkovyy-saray', mustSeeFilter: 'houses', visitMinutes: 15 }),
      place('Живописная тропа к реке Оке', 'Лесная тропа к обрыву с классическими окскими видами.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-tropa-k-oke', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Троицкая церковь в селе Бехово', 'Храм, спроектированный Поленовым, на высоком берегу над Окой.', 54.749112, 37.241234, { address: 'с. Бехово', locationSlug: 'tula-polenovo-troitskaya-tserkov-behovo', mustSeeFilter: 'temple', visitMinutes: 30 }),
      place('Святой источник и смотровая на обрыве', 'Родник и смотровая площадка с панорамой поймы Оки.', 54.749112, 37.241234, { address: 'с. Страхово', locationSlug: 'tula-polenovo-svyatoy-istochnik', mustSeeFilter: 'views', visitMinutes: 25 }),
    ],
  },
  {
    name: 'Творческий поселок и эко-парк «Ясно Поле»',
    desc: 'Эко-парк с зеленой архитектурой, арт-объектами и фермерским укладом: дома-быки, дома-ковчеги и мосты среди полей.',
    locationSlug: 'tula-yasno-pole',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 54.757812,
    longitude: 37.641214,
    address: 'Ясногорский район, д. Вележево',
    travelVector: 'Авто ~1 ч 20 мин',
    travelVectorBlurb:
      'Закладывайте на дорогу на авто ~1 час 20 минут в сторону Ясногорска, чтобы приехать к 11:00 утра на весь день эко-отдыха.',
    timingNote:
      'От главного ресторанного корпуса двигайтесь мимо футуристических арт-домов к конному двору, напоследок оставив посещение местной сыроварни.',
    places: [
      place('Отель-ковчег', 'Необычный круглый отель-ковчег - архитектурный акцент эко-парка.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-otel-kovcheg', mustSeeFilter: 'houses', visitMinutes: 30 }),
      place('Арт-объект «Дом-Бык»', 'Футуристический дом-скульптура среди полей.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-dom-byk', mustSeeFilter: 'monument', visitMinutes: 20 }),
      place('Портал времени из дерева', 'Деревянный арт-портал на эко-тропе парка.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-portal-vremeni', mustSeeFilter: 'monument', visitMinutes: 15 }),
      place('Современный конный комплекс', 'Конный двор для прогулок и знакомства с лошадьми.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-konnyy-kompleks', mustSeeFilter: 'park', visitMinutes: 45 }),
      place('Пруды для рыбалки и настилы', 'Тихие пруды с деревянными настилами для отдыха у воды.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-prudy', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Локальная эко-ферма', 'Фермерский двор с продуктами и животными эко-парка.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-eko-ferma', mustSeeFilter: 'park', visitMinutes: 40 }),
      place('Цех авторских сыров', 'Сыроварня с дегустацией локальных сыров.', 54.757812, 37.641214, { address: 'д. Вележево', locationSlug: 'tula-yasno-pole-syrovarnya', mustSeeFilter: 'gastro', visitMinutes: 40 }),
    ],
  },
];

export const TULA_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'tula-istoricheskoe-serdtse',
    title: 'Историческое сердце и тульский хайп',
    description:
      'Классический маршрут первого знакомства: древняя крепость, набережная и главный хипстерский квартал. Все точки в шаговой доступности.',
    travelVector: 'Пешком по центру',
    timingNote:
      'Около 9 часов с паузами: Одоевские ворота - пряник - Успенский - ряды - набережная - «Культура» - Металлистов - «Искра».',
    coverImageUrl: '/images/venues/tula/tul-skiy-kreml.jpg',
    stops: [
      {
        name: 'Башня Одоевских ворот',
        desc: '1 час на вход в крепость и осмотр монументальных стен.',
        locationSlug: 'tula-bashnya-odoevskih-vorot',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        address: 'ул. Менделеевская, Кремль',
        latitude: 54.194231,
        longitude: 37.617412,
      },
      {
        name: 'Скульптура «Тульский пряник»',
        desc: '30 минут на обязательное фото на площади Ленина.',
        locationSlug: 'tula-skulptura-tulskiy-pryanik',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'пл. Ленина',
        latitude: 54.193181,
        longitude: 37.6173,
        transitTip: 'Пешком 5 минут к площади Ленина',
      },
      {
        name: 'Успенский собор в Кремле',
        desc: '1 час на фрески и архитектуру барочного собора.',
        locationSlug: 'tula-uspenskiy-sobor-kremlya',
        mustSeeFilter: 'temple',
        visitMinutes: 60,
        address: 'территория Тульского кремля',
        latitude: 54.195311,
        longitude: 37.617943,
        transitTip: 'Пешком 5 минут обратно в Кремль',
      },
      {
        name: 'Торговые ряды Кремля',
        desc: '1 час на сувениры и дегустацию сладостей.',
        locationSlug: 'tula-torgovye-ryady-kremlya',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        address: 'территория Тульского кремля',
        latitude: 54.194912,
        longitude: 37.616943,
        transitTip: 'Пешком 2 минуты',
      },
      {
        name: 'Казанская набережная',
        desc: '1 час вдоль реки и фото у «Грибной поляны».',
        locationSlug: 'tula-kazanskaya-naberezhnaya',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'Казанская набережная',
        latitude: 54.196812,
        longitude: 37.616943,
        transitTip: 'Пешком 5 минут к набережной',
      },
      {
        name: 'Ресторан «Культура»',
        desc: '1.5 часа обеда с авторскими блюдами локальной кухни в «Искре».',
        locationSlug: 'tula-restoran-kultura',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Советская, 11',
        latitude: 54.196512,
        longitude: 37.612514,
        transitTip: 'Пешком 8 минут через Металлистов',
      },
      {
        name: 'Улица Металлистов',
        desc: '1.5 часа променада мимо особняка Белолипецких.',
        locationSlug: 'tula-ulitsa-metallistov',
        mustSeeFilter: 'street',
        visitMinutes: 90,
        address: 'ул. Металлистов',
        latitude: 54.196412,
        longitude: 37.614811,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Креативное пространство «Искра»',
        desc: '1.5 часа вечернего кофе, арт-инсталляций и дворов.',
        locationSlug: 'tula-kreativnoe-prostranstvo-iskra',
        mustSeeFilter: 'creative',
        visitMinutes: 90,
        address: 'ул. Советская, 11',
        latitude: 54.196411,
        longitude: 37.612214,
        transitTip: 'Пешком 2 минуты',
      },
    ],
  },
  {
    id: 'tula-mastera-stal',
    title: 'Мастера, сталь и индустриальный код',
    description:
      'Зареченский район и постиндустриальные локации: оружейники, металлурги и инноваторы от Петра I до «Октавы».',
    travelVector: 'Заречье и Октава',
    timingNote:
      'Около 8.5 часов: Петр I - Левша - Музей оружия - «Пряности и Радости» - Николо-Зарецкая - динозавр - переход к «Октаве» - Музей станка.',
    coverImageUrl: '/images/venues/tula/muzey-oruzhiya-shlem.jpg',
    stops: [
      {
        name: 'Памятник Петру I',
        desc: '30 минут у Оружейного завода - знакомство с историей кузнечного дела.',
        locationSlug: 'tula-pamyatnik-petru-i',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'ул. Советская, 1А',
        latitude: 54.198941,
        longitude: 37.615144,
      },
      {
        name: 'Памятник Левше',
        desc: '30 минут на фото символа тульской смекалки.',
        locationSlug: 'tula-pamyatnik-levshe',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'ул. Советская, 1А',
        latitude: 54.199182,
        longitude: 37.614605,
        transitTip: 'Пешком 2 минуты',
      },
      {
        name: 'Тульский государственный музей оружия',
        desc: '2 часа интерактивной экскурсии в здании-шлеме.',
        venueSlug: 'tula-muzey-oruzhiya-shlem',
        mustSeeFilter: 'museum',
        visitMinutes: 120,
        address: 'ул. Октябрьская, 2',
        latitude: 54.203841,
        longitude: 37.619223,
        transitTip: 'Пешком 8 минут через мост',
      },
      {
        name: 'Кафе-кондитерская «Пряности и Радости»',
        desc: '1 час сытного обеда у Чулковского моста.',
        locationSlug: 'tula-kafe-pryanosti-i-radosti',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Октябрьская, 1Д',
        latitude: 54.201812,
        longitude: 37.618911,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Николо-Зарецкая церковь',
        desc: '1 час в усыпальнице Демидовых и у памятника Никите Демидову.',
        locationSlug: 'tula-nikolo-zaretskaya-tserkov',
        mustSeeFilter: 'temple',
        visitMinutes: 60,
        address: 'ул. Оружейная / Демидовская, 9А',
        latitude: 54.204212,
        longitude: 37.618411,
        transitTip: 'Пешком 6 минут',
      },
      {
        name: 'Скульптура «Тульский динозавр»',
        desc: '30 минут у легендарной «Тёши» у экзотариума.',
        locationSlug: 'tula-skulptura-tulskiy-dinozavr',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        address: 'ул. Октябрьская, 18А',
        latitude: 54.204481,
        longitude: 37.620511,
        transitTip: 'Пешком 4 минуты',
      },
      {
        name: 'Творческий индустриальный кластер «Октава»',
        desc: 'Переход в центр через мост и проспект Ленина к заводскому кластеру.',
        locationSlug: 'tula-tvorcheskiy-industrial-nyy-klaster-oktava',
        mustSeeFilter: 'creative',
        visitMinutes: 50,
        address: 'ул. Каминского, 24',
        latitude: 54.190812,
        longitude: 37.613412,
        transitTip: 'Пешком или автобусом ~50 минут к «Октаве»',
      },
      {
        name: 'Музей станка в кластере «Октава»',
        desc: '2 часа иммерсивной мультимедийной экскурсии об истории заводов.',
        venueSlug: 'tula-muzey-stanka-oktava',
        mustSeeFilter: 'museum',
        visitMinutes: 120,
        address: 'ул. Каминского, 24',
        latitude: 54.190623,
        longitude: 37.613941,
        transitTip: 'На территории «Октавы»',
      },
    ],
  },
  ...TULA_LINE_DAY_ROUTE_PRESETS,
];

export const TULA_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как быстрее и дешевле всего добраться в Тулу из Москвы, чтобы не застрять на въезде?',
    a: 'Однозначно поезд «Ласточка» с Курского вокзала. Время в пути - всего 2 часа, билет стоит от 600 рублей. Автомобили и автобусы намертво встают на Симферопольском шоссе в пятницу вечером и субботу утром, теряя до 4 часов на въезде в город из-за ремонта дорог.',
  },
  {
    q: 'Правда ли, что в Кондуки (Романцевские горы) можно легко доехать на городском автобусе?',
    a: 'Нет, это опасный миф. Прямого транспорта из Тулы туда нет: автобус довезет вас только до Богородицка или Узловой, откуда придется брать дорогое местное такси (от 1500 рублей) или идти пешком более 7 км по пыльной грунтовке. Для поездки в Кондуки выбирайте личный автомобиль, каршеринг или готовый групповой тур из центра Тулы.',
  },
  {
    q: 'Где купить настоящий тульский пряник, чтобы не наткнуться на сухой фабричный фальсификат для туристов?',
    a: 'Избегайте лотков на площади Ленина и вокзале. За настоящими печатными пряниками ручной работы идите в фирменные магазины фабрики «Медовые традиции» или в торговые ряды Тульского кремля. Самый шик - брать пряники с начинкой из сосновых шишек или черной смородины, а не банальное повидло.',
  },
  {
    q: 'Можно ли обойти всю Ясную Поляну за пару часов без покупки экскурсии?',
    a: 'За пару часов вы успеете только добежать до могилы Толстого и обратно. Территория огромна (более 400 гектаров). Чтобы прочувствовать место, покупайте входной билет в заповедник в терминале на входе (около 150 рублей) и закладывайте на прогулку не менее 4-5 часов.',
  },
];

export const TULA_TRAVEL =
  'Из Москвы до Тулы удобнее и быстрее всего доезжать на скоростных поездах «Ласточка» с Курского вокзала - время в пути около 2 часов. Автомобили и автобусы в пятницу вечером часто встают на Симферопольском шоссе. Идеальный сезон для набережной и Ясной Поляны - с мая по сентябрь; зимой город манит иллюминацией Кремля, улицы Металлистов, чаем из самоваров и пряничными ярмарками.';
