/** Tyumen tourist hub pack (owner 2026-08-17). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { TYUMEN_LINE_DAY_ROUTE_PRESETS } from './tyumen-line-presets.ts';

export const TYUMEN_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Сквер сибирских кошек',
    desc: 'Золоченые кошки на пилонах: память о тюменских мурлыках, которых после блокады отправили спасать Эрмитаж от крыс.',
    address: 'ул. Первомайская',
    locationSlug: 'tyumen-skver-sibirskih-koshek',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.153912,
    longitude: 65.541112,
  },
  {
    name: 'Памятник Ермаку',
    desc: 'Монумент покорителю Сибири на Исторической площади у Ленина.',
    address: 'ул. Ленина / Историческая площадь',
    locationSlug: 'tyumen-pamyatnik-ermaku',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.161112,
    longitude: 65.522901,
  },
  {
    name: 'Памятник Распутину',
    desc: 'Скульптура Григория Распутина у дома на Даудельной - редкий городской портрет спорной фигуры.',
    address: 'ул. Даудельная, 1',
    locationSlug: 'tyumen-pamyatnik-rasputinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.154912,
    longitude: 65.548912,
  },
  {
    name: 'Памятник почтальонке',
    desc: 'Бронзовая почтальонка на Республике: городская скульптура про обычную работу и улыбку.',
    address: 'ул. Республики, 56',
    locationSlug: 'tyumen-pamyatnik-pochtalonke',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.152912,
    longitude: 65.542112,
  },
  {
    name: 'Памятник купцу',
    desc: 'Купеческая фигура на перекрестке Республики и Челюскинцев - визуальный якорь торгового центра.',
    address: 'ул. Республики / ул. Челюскинцев',
    locationSlug: 'tyumen-pamyatnik-kuptsu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.158112,
    longitude: 65.531112,
  },
  {
    name: 'Памятник продавщице семечек',
    desc: 'Народная скульптура у Гостиного двора: семечки, характер и фототочка на Республике, 2А.',
    address: 'ул. Республики, 2А',
    locationSlug: 'tyumen-pamyatnik-semechkam',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.160112,
    longitude: 65.524912,
  },
  {
    name: 'Памятник Текутьеву',
    desc: 'Монумент купцу-меценату на Текутьевском бульваре.',
    address: 'Текутьевский бульвар',
    locationSlug: 'tyumen-pamyatnik-tekutyevu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.142912,
    longitude: 65.563112,
  },
  {
    name: 'Памятник школьникам, не вернувшимся с войны',
    desc: 'Мемориал на площади Прощания: Республика и Профсоюзная.',
    address: 'площадь Прощания (ул. Республики / ул. Профсоюзная)',
    locationSlug: 'tyumen-pamyatnik-shkolnikam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.149112,
    longitude: 65.551901,
  },
  {
    name: 'Памятник дворнику',
    desc: 'Бронзовый дворник у дома Буркова на Дзержинского, 30 - улыбка Арбата.',
    address: 'ул. Дзержинского, 30',
    locationSlug: 'tyumen-pamyatnik-dvorniku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.156112,
    longitude: 65.536912,
  },
  {
    name: 'Копилка бездомной собаки',
    desc: 'Скульптура-копилка на Республике и Орджоникидзе: бросают монеты в пользу приютов.',
    address: 'ул. Республики / ул. Орджоникидзе',
    locationSlug: 'tyumen-pamyatnik-bezdomnoy-sobake',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.151912,
    longitude: 65.544912,
  },
  {
    name: 'Скульптура «Мелодия»',
    desc: 'Девочка с флейтой на Челюскинцев, 45 - тихая музыкальная точка центра.',
    address: 'ул. Челюскинцев, 45',
    locationSlug: 'tyumen-skulptura-melodiya',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.154312,
    longitude: 65.533112,
  },
  {
    name: 'Памятник Петру Ершову',
    desc: 'Автор «Конька-Горбунка» на Комсомольской площади.',
    address: 'Комсомольская площадь',
    locationSlug: 'tyumen-pamyatnik-ershovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.156912,
    longitude: 65.529112,
  },
  {
    name: 'Тюменский ключ',
    desc: 'Арт-объект-ключ на Цветном бульваре - символ города у фонтанов.',
    address: 'Цветной бульвар',
    locationSlug: 'tyumen-pamyatnik-klyuch-tyumeni',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.149912,
    longitude: 65.541212,
  },
  {
    name: 'Первая водоразборная колонка',
    desc: 'Памятник городскому водопроводу на 25 Октября, 13.',
    address: 'ул. 25 Октября, 13',
    locationSlug: 'tyumen-pervaya-vodokolonna',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.163112,
    longitude: 65.538912,
  },
  {
    name: 'Памятник Ленину',
    desc: 'Классический монумент на Центральной площади.',
    address: 'Центральная площадь',
    locationSlug: 'tyumen-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.151112,
    longitude: 65.541912,
  },

  // --- Историческое наследие (16-27) ---
  {
    name: 'Усадьба Колокольниковых',
    desc: 'Купеческие палаты на Республике, 18: интерьеры, лавка и флигель детского музея сказки.',
    address: 'ул. Республики, 18',
    locationSlug: 'tyumen-usadba-kolokolnikovyh',
    mustSeeFilter: 'houses',
    visitMinutes: 45,
    latitude: 57.1578,
    longitude: 65.5345,
  },
  {
    name: 'Дом Буркова',
    desc: 'Деревянный особняк на Дзержинского, 30 - якорь тюменского Арбата и точка у дворника.',
    address: 'ул. Дзержинского, 30',
    locationSlug: 'tyumen-dom-burkova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.156112,
    longitude: 65.536912,
  },
  {
    name: 'Гостиный двор',
    desc: 'Исторический гостиный двор на Республике, 2: торговый фасад у Исторической площади.',
    address: 'ул. Республики, 2',
    locationSlug: 'tyumen-gostinyy-dvor',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 57.1605,
    longitude: 65.525,
  },
  {
    name: 'Усадьба Машарова',
    desc: 'Купеческий дом-музей на Ленина, 24 с интерьерами промышленника.',
    address: 'ул. Ленина, 24',
    locationSlug: 'tyumen-usadba-masharova',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 57.1575,
    longitude: 65.534,
  },
  {
    name: 'Приказная изба',
    desc: 'Здание на Республике, 7: здесь в 1941-45 в комнате 15 аграрного вуза хранили тело Ленина.',
    address: 'ул. Республики, 7',
    locationSlug: 'tyumen-prikaznaya-izba',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 57.1588,
    longitude: 65.5365,
  },
  {
    name: 'Дом Поповой',
    desc: 'Деревянный особняк на Володарского, 7 с резными наличниками.',
    address: 'ул. Володарского, 7',
    locationSlug: 'tyumen-dom-popovoy',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.155,
    longitude: 65.534,
  },
  {
    name: 'Пароходная контора Колмакова',
    desc: 'Контора пароходства на 25 Октября, 23А: история реки и фудкорт у Туры.',
    address: 'ул. 25 Октября, 23А',
    locationSlug: 'tyumen-parohodnaya-kontora-kolmakova',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 57.1635,
    longitude: 65.5375,
  },
  {
    name: 'Коммерческое училище',
    desc: 'Парадное здание училища на Луначарского, 2.',
    address: 'ул. Луначарского, 2',
    locationSlug: 'tyumen-kommercheskoe-uchilishche',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.154,
    longitude: 65.528,
  },
  {
    name: 'Дворянское собрание',
    desc: 'Губернский особняк на Республике, 16 рядом с Колокольниковыми.',
    address: 'ул. Республики, 16',
    locationSlug: 'tyumen-dvoryanskoe-sobranie',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.1575,
    longitude: 65.5335,
  },
  {
    name: 'Дом Шайчика',
    desc: 'Купеческий дом на Ленина, 47 в ряду деревянного центра.',
    address: 'ул. Ленина, 47',
    locationSlug: 'tyumen-dom-shaychika',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.1545,
    longitude: 65.54,
  },
  {
    name: 'Водонапорная башня',
    desc: 'Кирпичная башня на Орджоникидзе, 56/1 - индустриальный акцент центра.',
    address: 'ул. Орджоникидзе, 56/1',
    locationSlug: 'tyumen-vodonapornaya-bashnya',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.1485,
    longitude: 65.548,
  },
  {
    name: 'Дом Чиралова',
    desc: 'Деревянный дом на Володарского, 9 рядом с домом Поповой.',
    address: 'ул. Володарского, 9',
    locationSlug: 'tyumen-dom-chiralova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.1548,
    longitude: 65.5335,
  },

  // --- Музеи (28-36) ---
  {
    name: 'Музей Словцова',
    desc: 'Главный краеведческий комплекс Сибири на Советской, 63: археология, нефть и хай-тек экспозиции.',
    address: 'ул. Советская, 63',
    venueSlug: 'tyumen-muzey-slovtsova',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 57.1536,
    longitude: 65.5473,
  },
  {
    name: 'Городская дума',
    desc: 'Историческое здание думы на Ленина, 2 у Исторической площади.',
    address: 'ул. Ленина, 2',
    venueSlug: 'tyumen-gorodskaya-duma',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 57.1615,
    longitude: 65.524,
  },
  {
    name: '«Россия - моя история»',
    desc: 'Мультимедийный парк на Орджоникидзе, 47: карта страны и сибирский сюжет.',
    address: 'ул. Орджоникидзе, 47',
    venueSlug: 'tyumen-rossiya-moya-istoriya',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 57.1495,
    longitude: 65.546,
  },
  {
    name: 'Музей кузнечного ремесла',
    desc: 'Живая кузница на Малиновского, 6/2: молот, горн и мастер-классы.',
    address: 'ул. Малиновского, 6/2',
    venueSlug: 'tyumen-muzey-kuznechnogo-remesla',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 57.125,
    longitude: 65.555,
  },
  {
    name: 'Музей ретро-техники Михайлова',
    desc: 'Частная коллекция машин на Велижанской, 69.',
    address: 'ул. Велижанская, 69',
    venueSlug: 'tyumen-muzey-retro-tehniki-mihaylova',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.165,
    longitude: 65.5,
  },
  {
    name: 'Детский музей сказки',
    desc: 'Сказочный флигель усадьбы Колокольниковых на Республике, 18.',
    address: 'ул. Республики, 18, флигель',
    venueSlug: 'tyumen-detskiy-muzey-skazki',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 57.1578,
    longitude: 65.5345,
  },
  {
    name: 'Музей науки и техники Зауралья',
    desc: 'Техника и изобретения края на Володарского, 38.',
    address: 'ул. Володарского, 38',
    venueSlug: 'tyumen-muzey-nauki-i-tehniki-zauralya',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.152,
    longitude: 65.53,
  },
  {
    name: 'Андреевское озеро',
    desc: 'Археологический комплекс в 23 км по Ялуторовскому тракту: стоянки и лесное озеро.',
    address: '23 км Ялуторовского тракта',
    locationSlug: 'tyumen-andreevskoe-ozero',
    mustSeeFilter: 'museum',
    visitMinutes: 120,
    latitude: 56.98,
    longitude: 65.85,
  },
  {
    name: 'Музей мебели Козловой',
    desc: 'Коллекция мебели на ул. Семакова, 1: резные гарнитуры и купеческий быт.',
    address: 'ул. Семакова, 1',
    venueSlug: 'tyumen-muzey-mebeli-kozlovoy',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 57.157,
    longitude: 65.5385,
  },

  // --- Храмы (37-45) ---
  {
    name: 'Троицкий монастырь',
    desc: 'Сибирское барокко на Коммунистической, 10: высокий берег Туры и белокаменный ансамбль.',
    address: 'ул. Коммунистическая, 10',
    locationSlug: 'tyumen-troitskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 57.1697,
    longitude: 65.5278,
  },
  {
    name: 'Знаменский кафедральный собор',
    desc: 'Яркий памятник сибирского барокко на Семакова, 13 с ярусной архитектурой.',
    address: 'ул. Семакова, 13',
    locationSlug: 'tyumen-znamenskiy-kafedral-nyy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 57.1575,
    longitude: 65.541,
  },
  {
    name: 'Ильинский женский монастырь',
    desc: 'Монастырский комплекс на 25 Октября, 29 у реки.',
    address: 'ул. 25 Октября, 29',
    locationSlug: 'tyumen-ilinskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 57.164,
    longitude: 65.536,
  },
  {
    name: 'Спасская церковь',
    desc: 'Камерный храм на Ленина, 43 в купеческом центре.',
    address: 'ул. Ленина, 43',
    locationSlug: 'tyumen-spasskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 57.155,
    longitude: 65.5385,
  },
  {
    name: 'Соборная мечеть',
    desc: 'Главная мечеть города на Жданова, 66.',
    address: 'ул. Жданова, 66',
    locationSlug: 'tyumen-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 57.145,
    longitude: 65.58,
  },
  {
    name: 'Костел святого Иосифа',
    desc: 'Католический храм на Ленина, 7 в историческом центре.',
    address: 'ул. Ленина, 7',
    locationSlug: 'tyumen-kostel-svyatogo-iosifa',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 57.16,
    longitude: 65.526,
  },
  {
    name: 'Храм Всех Святых',
    desc: 'Ротонда на Свердлова, 29 - редкая круглая церковь центра.',
    address: 'ул. Свердлова, 29',
    locationSlug: 'tyumen-hram-vseh-svyatyh',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 57.148,
    longitude: 65.535,
  },
  {
    name: 'Синагога «Мадрегот»',
    desc: 'Действующая синагога на Кирова, 18.',
    address: 'ул. Кирова, 18',
    locationSlug: 'tyumen-sinagoga-madregot',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 57.1505,
    longitude: 65.538,
  },
  {
    name: 'Вознесенско-Георгиевская церковь',
    desc: 'Сибирское барокко на Береговой, 77: левый берег Туры рядом с Мостом Влюбленных.',
    address: 'ул. Береговая, 77',
    locationSlug: 'tyumen-voznesensko-georgievskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 57.165768,
    longitude: 65.522038,
  },

  // --- Парки и смотровые (46-54) ---
  {
    name: 'Четырехъярусная набережная',
    desc: 'Единственная в России четырехярусная гранитная набережная: перепад около 20 м и бронзовые рельефы Сибири.',
    address: 'Набережная реки Туры',
    locationSlug: 'tyumen-chetyrehurovnevaya-naberezhnaya',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 57.1558,
    longitude: 65.5315,
  },
  {
    name: 'Затюменский экопарк',
    desc: 'Лесной экопарк с тропами, озерами и тишиной в черте города.',
    address: 'Затюменский экопарк',
    locationSlug: 'tyumen-zatyumenskiy-ekopark',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 57.165,
    longitude: 65.49,
  },
  {
    name: 'Цветной бульвар',
    desc: 'Фонтаны, цирк и тюменский ключ - прогулочная ось центра.',
    address: 'Цветной бульвар',
    locationSlug: 'tyumen-tsvetnoy-bulvar',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 57.149912,
    longitude: 65.541212,
  },
  {
    name: 'Мост Влюбленных',
    desc: 'Вантовый пешеходный мост через Туру: бесплатная панорама на четыре яруса, вечером подсветка.',
    address: 'Мост Влюбленных',
    locationSlug: 'tyumen-most-vlyublennyh',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 57.1538,
    longitude: 65.534,
  },
  {
    name: 'Комсомольская площадь',
    desc: 'Площадь у Ершова и деревянного кольца центра.',
    address: 'Комсомольская площадь',
    locationSlug: 'tyumen-komsomolskaya-ploschad',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 57.156912,
    longitude: 65.529112,
  },
  {
    name: 'Гилевская роща',
    desc: 'Сосновый массив и пруд на юге города: шаговая доступность от жилых кварталов.',
    address: 'Гилевская роща',
    locationSlug: 'tyumen-gilevskaya-roshcha',
    mustSeeFilter: 'park',
    visitMinutes: 75,
    latitude: 57.11,
    longitude: 65.54,
  },
  {
    name: 'Площадь Прощания',
    desc: 'Сквер у мемориала школьникам: тихая пауза на Республике и Профсоюзной.',
    address: 'площадь Прощания',
    locationSlug: 'tyumen-ploschad-proshchaniya',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 57.149112,
    longitude: 65.551901,
  },
  {
    name: 'Александровский сад',
    desc: 'Старый городской сад у центра: тень, лавки и короткий переход к бульвару.',
    address: 'Александровский сад',
    locationSlug: 'tyumen-aleksandrovskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 57.1525,
    longitude: 65.54,
  },
  {
    name: 'Амфитеатр нижней набережной',
    desc: 'Нижний ярус Туры: гранитный амфитеатр у воды и вечерние события.',
    address: 'Нижняя набережная Туры',
    locationSlug: 'tyumen-amfiteatr-nizhney-naberezhnoy',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 57.1555,
    longitude: 65.53,
  },
  {
    name: 'Площадь Борцов Революции',
    desc: 'Советская площадь с зеленью между Орджоникидзе и центром.',
    address: 'площадь Борцов Революции',
    locationSlug: 'tyumen-ploschad-bortsov-revolyutsii',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 57.148,
    longitude: 65.545,
  },

  // --- Театры и гастро (55-65) ---
  {
    name: 'Тюменский большой драматический театр',
    desc: 'Одно из крупнейших театральных зданий страны: около 36000 м², больше МХАТа и Большого по площади пола. ул. Республики, 129.',
    address: 'ул. Республики, 129',
    venueSlug: 'tyumen-tyumenskiy-dramaticheskiy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 57.1389,
    longitude: 65.5697,
  },
  {
    name: 'Аквапарк «ЛетоЛето»',
    desc: 'Городской аквапарк на Щербакова, 87 и точка термального сезона вместе с Верхним Бором.',
    address: 'ул. Щербакова, 87',
    locationSlug: 'tyumen-akvapark-letoleto',
    mustSeeFilter: 'main',
    visitMinutes: 150,
    latitude: 57.1094,
    longitude: 65.5706,
  },
  {
    name: 'Ресторан «Чум»',
    desc: 'Сибирская кухня на Малыгина, 59: строганина из нельмы и муксуна, дичь, ягоды с кедровым молоком.',
    address: 'ул. Малыгина, 59',
    locationSlug: 'tyumen-restoran-chum',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 57.145,
    longitude: 65.555,
  },
  {
    name: 'Ресторан «Посейдон»',
    desc: 'Рыба и сибирский стол на Луначарского, 47.',
    address: 'ул. Луначарского, 47',
    locationSlug: 'tyumen-restoran-poseydon',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 57.148,
    longitude: 65.52,
  },
  {
    name: 'Фудкорт пароходной конторы',
    desc: 'Еда у Туры в исторической конторе Колмакова: обед между ярусами набережной.',
    address: 'ул. 25 Октября, 23А',
    locationSlug: 'tyumen-fudkort-parohodnoy-kontory',
    mustSeeFilter: 'gastro',
    visitMinutes: 45,
    latitude: 57.1635,
    longitude: 65.5375,
  },
  {
    name: 'Театр кукол',
    desc: 'Кукольный театр на Кирова, 36.',
    address: 'ул. Кирова, 36',
    venueSlug: 'tyumen-teatr-kukol',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 57.149,
    longitude: 65.535,
  },
  {
    name: 'Кафе «Максим»',
    desc: 'Кафе на Семакова, 11 рядом со Знаменским собором.',
    address: 'ул. Семакова, 11',
    locationSlug: 'tyumen-kafe-maksim',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 57.1572,
    longitude: 65.5405,
  },
  {
    name: 'Ресторан «Каравелла»',
    desc: 'Стол у Гостиного двора на Республике, 1.',
    address: 'ул. Республики, 1',
    locationSlug: 'tyumen-restoran-karavella',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 57.1608,
    longitude: 65.5245,
  },
  {
    name: 'Театр «Ангажемент»',
    desc: 'Камерная сцена на Олимпийской, 8А.',
    address: 'ул. Олимпийская, 8А',
    venueSlug: 'tyumen-teatr-angazhement',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 57.12,
    longitude: 65.57,
  },
  {
    name: 'Бар «Канава»',
    desc: 'Локальный бар на Дзержинского, 38 - вечер Арбата после резного кружева.',
    address: 'ул. Дзержинского, 38',
    locationSlug: 'tyumen-bar-kanava',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 57.1558,
    longitude: 65.536,
  },
  {
    name: 'Чайная «Наличники»',
    desc: 'Чай и сладости в деревянном доме на Дзержинского, 34С.',
    address: 'ул. Дзержинского, 34С',
    locationSlug: 'tyumen-chaynaya-nalichniki',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 57.1559,
    longitude: 65.5364,
  },
  {
    name: 'Пешеходная улица Дзержинского',
    desc: 'Тюменский Арбат: музей деревянного зодчества под открытым небом, террасы и резьба.',
    address: 'ул. Дзержинского',
    locationSlug: 'tyumen-peshehodnaya-ulitsa-dzerzhinskogo',
    mustSeeFilter: 'street',
    visitMinutes: 50,
    latitude: 57.156,
    longitude: 65.5365,
  },
];

export const TYUMEN_SUBURBS: any[] = [
  {
    name: 'Верхний Бор',
    desc: 'Главный термальный выезд Тюмени: открытый бассейн +38...+40 в сосновом лесу, «Эльдорадо», Кривое озеро, спа, экотропа и воссозданная купеческая усадьба. Ориентир по цене взрослого билета на 3 часа: от 1300 ₽ в будни и от 1500 ₽ в выходные.',
    locationSlug: 'tyumen-verhniy-bor',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 57.251412,
    longitude: 65.449102,
    address: '11 км Салаирского тракта',
    travelVector: 'Автобус 135 ~30 мин',
    travelVectorBlurb:
      'Автобус 135 около 30 минут. Закладывайте выезд к 09:00, чтобы занять место у открытого бассейна.',
    timingNote:
      'Сначала открытый бассейн в соснах, затем лес, «Эльдорадо» и Кривое озеро, напоследок экотропа и усадьба.',
    gastroStop: {
      name: 'Кафе при комплексе',
      blurb: 'Горячий чай и сибирский обед после купания - на территории, не нужно возвращаться в центр.',
    },
    places: [
      {
        name: 'Открытый термальный бассейн',
        desc: 'Вода +38...+40 под открытым небом среди сосен. Ориентир: от 1300/1500 ₽ за 3 часа в будни/выходные.',
        locationSlug: 'tyumen-verhniy-bor-basseyn',
        address: '11 км Салаирского тракта',
        latitude: 57.251412,
        longitude: 65.449102,
        visitMinutes: 90,
      },
      {
        name: 'Сосновый бор',
        desc: 'Сосны вокруг бассейнов: прогулка между заплывами.',
        locationSlug: 'tyumen-verhniy-bor-sosnovyy-bor',
        address: '11 км Салаирского тракта',
        latitude: 57.2518,
        longitude: 65.4485,
        visitMinutes: 30,
      },
      {
        name: 'Эльдорадо',
        desc: 'Лесная зона отдыха рядом с термами Верхнего Бора.',
        locationSlug: 'tyumen-verhniy-bor-eldorado',
        address: '11 км Салаирского тракта',
        latitude: 57.2525,
        longitude: 65.447,
        visitMinutes: 40,
      },
      {
        name: 'Кривое озеро',
        desc: 'Лесное озеро у комплекса: тихая вода и тропа по берегу.',
        locationSlug: 'tyumen-verhniy-bor-krivoe-ozero',
        address: '11 км Салаирского тракта',
        latitude: 57.254,
        longitude: 65.451,
        visitMinutes: 30,
      },
      {
        name: 'Спа-зона',
        desc: 'Закрытые купели и спа после открытого бассейна.',
        locationSlug: 'tyumen-verhniy-bor-spa',
        address: '11 км Салаирского тракта',
        latitude: 57.2512,
        longitude: 65.4495,
        visitMinutes: 40,
      },
      {
        name: 'Экотропа',
        desc: 'Маркированная тропа по сосновому лесу вокруг терм.',
        locationSlug: 'tyumen-verhniy-bor-ekotropa',
        address: '11 км Салаирского тракта',
        latitude: 57.2505,
        longitude: 65.4478,
        visitMinutes: 40,
      },
      {
        name: 'Купеческая усадьба',
        desc: 'Воссозданная купеческая усадьба на территории комплекса.',
        locationSlug: 'tyumen-verhniy-bor-usadba',
        address: '11 км Салаирского тракта',
        latitude: 57.2508,
        longitude: 65.4502,
        visitMinutes: 25,
      },
    ],
  },
  {
    name: 'Термальные источники',
    desc: 'Практический чек-лист четырех комплексов вокруг Тюмени. Цены - ориентир, не живой прайс: сверяйте кассу в день поездки. Природная вода с глубины 1000-2500 м, +38...+43, йод и бром. Дешевле всего купаться в понедельник-среду с 08:00 до 12:00.',
    locationSlug: 'tyumen-termal-nye-istochniki',
    mustSeeFilter: 'main',
    visitMinutes: 'полдня',
    latitude: 57.251412,
    longitude: 65.449102,
    address: 'Салаирский тракт и пригород Тюмени',
    travelVector: 'Авто / автобус 30-60 мин',
    travelVectorBlurb:
      'Верхний Бор - автобус 135 около 30 минут. Советский, Аван и Тайга удобнее на машине. На открытый бассейн лучше к 09:00.',
    timingNote:
      'Сравните четыре точки по цене и формату: 3 часа в лесу, безлимит дня или купель в Каменке и Онохино.',
    gastroStop: {
      name: 'Кафе при термах',
      blurb: 'На всех четырех комплексах есть кафе: не планируйте отдельный ресторан, если едете только купаться.',
    },
    places: [
      {
        name: 'Верхний Бор',
        desc: 'Ориентир: от 1300/1500 ₽ за 3 часа (будни/выходные), взрослый. 11 км Салаирского тракта, сосны и открытый бассейн.',
        locationSlug: 'tyumen-verhniy-bor',
        address: '11 км Салаирского тракта',
        latitude: 57.251412,
        longitude: 65.449102,
        visitMinutes: 180,
      },
      {
        name: 'Советский (бывший «Дикий»)',
        desc: 'Ориентир: 450/550 ₽ безлимит на день (будни/выходные). Бассейн 600 м², +38, советский вайб. 27 км Салаирского тракта.',
        locationSlug: 'tyumen-sovetskiy-termy',
        address: '27 км Салаирского тракта',
        latitude: 57.348912,
        longitude: 65.381112,
        visitMinutes: 180,
        transitTip: 'Дальше по Салаирскому тракту, чем Верхний Бор',
      },
      {
        name: 'Аван',
        desc: 'Ориентир: 700/900 ₽ безлимит (будни/выходные). Каменка, ул. Мира, 4 стр. 2.',
        locationSlug: 'tyumen-avan-termy',
        address: 'п. Каменка, ул. Мира, 4 стр. 2',
        latitude: 57.172312,
        longitude: 65.188912,
        visitMinutes: 180,
        transitTip: 'Западный выезд в Каменку',
      },
      {
        name: 'Тайга',
        desc: 'Ориентир: 800/1100 ₽ за 3 часа (будни/выходные). Онохино, ул. Мира, 1А.',
        locationSlug: 'tyumen-tayga-termy',
        address: 'с. Онохино, ул. Мира, 1А',
        latitude: 56.953112,
        longitude: 65.581112,
        visitMinutes: 180,
        transitTip: 'Южный выезд в Онохино',
      },
    ],
  },
  {
    name: 'Ялуторовский острог',
    desc: 'Деревянная крепость, декабристы и столица блинов: гигантская сковорода и Сретенская ярмарка. Около 1 часа 15 минут от Тюмени.',
    locationSlug: 'tyumen-yalutorovsk',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 56.654912,
    longitude: 66.311112,
    address: 'г. Ялуторовск, ул. Сретенская, 1',
    travelVector: 'Авто / автобус ~1 ч 15 мин',
    travelVectorBlurb:
      'Закладывайте на автомобиль или автобус около 1 часа 15 минут, чтобы быть у острога к 09:30.',
    timingNote:
      'Сначала острог и крепостная стена, затем декабристы и гигантская сковорода, напоследок блины.',
    gastroStop: {
      name: 'Блины Ялуторовска',
      blurb: 'Город блинов: берите тарелку у острога, не оставляйте гастро на обратную дорогу в Тюмень.',
    },
    places: [
      {
        name: 'Ялуторовский острог',
        desc: 'Воссозданная деревянная крепость на Сретенской, 1.',
        locationSlug: 'tyumen-yalutorovsk-ostrog',
        address: 'г. Ялуторовск, ул. Сретенская, 1',
        latitude: 56.654912,
        longitude: 66.311112,
        visitMinutes: 60,
      },
      {
        name: 'Деревянная крепость',
        desc: 'Частокол, башни и внутренний двор острога.',
        locationSlug: 'tyumen-yalutorovsk-krepost',
        address: 'г. Ялуторовск, ул. Сретенская, 1',
        latitude: 56.6552,
        longitude: 66.3108,
        visitMinutes: 30,
      },
      {
        name: 'Музей декабристов',
        desc: 'Ссыльные декабристы Ялуторовска: дома и экспозиция рядом с острогом.',
        locationSlug: 'tyumen-yalutorovsk-dekabristy',
        address: 'г. Ялуторовск, ул. Сретенская, 1',
        latitude: 56.6545,
        longitude: 66.3115,
        visitMinutes: 40,
      },
      {
        name: 'Гигантская сковорода',
        desc: 'Фототочка столицы блинов - огромная сковорода у острога.',
        locationSlug: 'tyumen-yalutorovsk-skovoroda',
        address: 'г. Ялуторовск, ул. Сретенская, 1',
        latitude: 56.6547,
        longitude: 66.3118,
        visitMinutes: 15,
      },
      {
        name: 'Блинная',
        desc: 'Блины на месте: финал выезда до обратной дороги.',
        locationSlug: 'tyumen-yalutorovsk-blinnaya',
        address: 'г. Ялуторовск, ул. Сретенская, 1',
        latitude: 56.6543,
        longitude: 66.3105,
        visitMinutes: 40,
      },
    ],
  },
  {
    name: 'Тобольск на 2 дня',
    desc: 'Столица Сибири XVII века: кремль, Софийско-Успенский собор, Рентерея, тюремный замок и нижний посад по Прямскому взвозу. Поезд «Императорский маршрут» около 3 часов 40 минут или автомобиль по Р-404 около 3 часов. Это полноценный выезд, как отдельный город, а не часовая экскурсия.',
    locationSlug: 'tyumen-tobolsk',
    mustSeeFilter: 'main',
    visitMinutes: '2 дня',
    latitude: 58.1975,
    longitude: 68.2528,
    address: 'г. Тобольск, Красная площадь, 2',
    travelVector: 'Поезд ~3 ч 40 мин / авто Р-404 ~3 ч',
    travelVectorBlurb:
      'Поезд «Императорский маршрут» около 3 часов 40 минут или автомобиль по Р-404 около 3 часов. Ночуйте в Тобольске: за один день кремль и нижний посад не успеть спокойно.',
    timingNote:
      'День 1: кремль, Рентерея, обед, тюремный замок, 198 ступеней Прямского взвоза, Троицкая и Захария с Елисаветой, ужин. День 2: губернский музей, дом семьи Николая II, блины в Ильинском, Ермаково поле, вечерний поезд.',
    gastroStop: {
      name: 'Романов, Поварня, Марк и Лев, Ильинский',
      blurb:
        'День 1: обед в «Романове» или «Поварне» (пельмени с щукой), ужин в «Марк и Лев». День 2: блины в Ильинском.',
    },
    places: [
      {
        name: 'Тобольский кремль',
        desc: 'День 1 утром: белокаменный кремль на высоком мысу над Иртышом.',
        locationSlug: 'tyumen-tobolsk-kreml',
        address: 'г. Тобольск, Красная площадь, 2',
        latitude: 58.1975,
        longitude: 68.2528,
        visitMinutes: 60,
      },
      {
        name: 'Софийско-Успенский собор',
        desc: 'Главный собор кремля: зеленые кровли и колокольня.',
        locationSlug: 'tyumen-tobolsk-sofiysko-uspenskiy-sobor',
        address: 'г. Тобольск, Красная площадь, 2',
        latitude: 58.1978,
        longitude: 68.2535,
        visitMinutes: 30,
        transitTip: 'Внутри кремля, 3 минуты от входа',
      },
      {
        name: 'Рентерея',
        desc: 'Каменный шведский корпус-мост: казна и переход между дворами кремля.',
        locationSlug: 'tyumen-tobolsk-rentereya',
        address: 'г. Тобольск, Красная площадь, 2',
        latitude: 58.1968,
        longitude: 68.253,
        visitMinutes: 25,
      },
      {
        name: 'Тюремный замок',
        desc: 'После обеда: каторжный замок у кремля, экспозиция тюрьмы.',
        locationSlug: 'tyumen-tobolsk-tyuremnyy-zamok',
        address: 'г. Тобольск, Красная площадь',
        latitude: 58.1965,
        longitude: 68.2515,
        visitMinutes: 50,
        transitTip: 'После обеда в «Романове» или «Поварне»',
      },
      {
        name: 'Прямский взвоз',
        desc: '198 ступеней с верхнего города в нижний посад.',
        locationSlug: 'tyumen-tobolsk-pryamskiy-vzvoz',
        address: 'г. Тобольск, Прямский взвоз',
        latitude: 58.196,
        longitude: 68.2545,
        visitMinutes: 25,
      },
      {
        name: 'Троицкая церковь',
        desc: 'Нижний посад: Троицкая церковь после спуска.',
        locationSlug: 'tyumen-tobolsk-troitskaya-tserkov',
        address: 'г. Тобольск, нижний посад',
        latitude: 58.1935,
        longitude: 68.256,
        visitMinutes: 20,
        transitTip: 'Вниз по Прямскому взвозу',
      },
      {
        name: 'Храм Захарии и Елисаветы',
        desc: 'Финал дня 1 в нижнем посаде перед ужином в «Марк и Лев».',
        locationSlug: 'tyumen-tobolsk-zahariya-i-elisaveta',
        address: 'г. Тобольск, нижний посад',
        latitude: 58.1928,
        longitude: 68.2575,
        visitMinutes: 20,
      },
      {
        name: 'Губернский музей',
        desc: 'День 2 утром: один из старейших музеев Сибири у кремля.',
        locationSlug: 'tyumen-tobolsk-gubernskiy-muzey',
        address: 'г. Тобольск, Красная площадь, 1',
        latitude: 58.1985,
        longitude: 68.254,
        visitMinutes: 60,
      },
      {
        name: 'Музей семьи Николая II',
        desc: 'Дом, где жила царская семья в тобольской ссылке.',
        locationSlug: 'tyumen-tobolsk-muzey-semi-nikolaya-ii',
        address: 'г. Тобольск',
        latitude: 58.195,
        longitude: 68.249,
        visitMinutes: 50,
        transitTip: 'После губернского музея',
      },
      {
        name: 'Ильинский',
        desc: 'Блины на второй день перед выездом на Ермаково поле.',
        locationSlug: 'tyumen-tobolsk-ilinskiy',
        address: 'г. Тобольск',
        latitude: 58.194,
        longitude: 68.255,
        visitMinutes: 40,
      },
      {
        name: 'Ермаково поле',
        desc: 'Поле Ермака: финал дня 2 до вечернего поезда в Тюмень.',
        locationSlug: 'tyumen-tobolsk-ermakovo-pole',
        address: 'г. Тобольск, Ермаково поле',
        latitude: 58.185,
        longitude: 68.24,
        visitMinutes: 40,
        transitTip: 'После блинов, затем на вокзал',
      },
    ],
  },
];

export const TYUMEN_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'tyumen-merchant-tura',
    title: 'Купеческие палаты и четыре яруса Туры',
    description:
      'От Колокольниковых и Знаменского к Гостиному двору, Мосту Влюбленных и гранитным ярусам. Обед в пароходной конторе.',
    travelVector: 'Пешком по историческому центру и набережной',
    timingNote: 'Около 3 часов: Колокольниковы - Знаменский - Гостиный двор - мост - ярусы - обед.',
    coverImageUrl: '/images/venues/tyumen/usadba-kolokolnikovyh.jpg',
    stops: [
      {
        name: 'Усадьба Колокольниковых',
        desc: '45 минут на палаты и лавку.',
        locationSlug: 'tyumen-usadba-kolokolnikovyh',
        mustSeeFilter: 'houses',
        visitMinutes: 45,
        address: 'ул. Республики, 18',
        latitude: 57.1578,
        longitude: 65.5345,
      },
      {
        name: 'Знаменский кафедральный собор',
        desc: '25 минут на сибирское барокко.',
        locationSlug: 'tyumen-znamenskiy-kafedral-nyy-sobor',
        mustSeeFilter: 'temple',
        visitMinutes: 25,
        address: 'ул. Семакова, 13',
        latitude: 57.1575,
        longitude: 65.541,
        transitTip: 'Пешком 6 минут',
      },
      {
        name: 'Гостиный двор и Историческая площадь',
        desc: '20 минут на фасад, купца и Ермака.',
        locationSlug: 'tyumen-gostinyy-dvor',
        mustSeeFilter: 'houses',
        visitMinutes: 20,
        address: 'ул. Республики, 2',
        latitude: 57.1605,
        longitude: 65.525,
        transitTip: 'Пешком 10 минут к Исторической площади',
      },
      {
        name: 'Мост Влюбленных',
        desc: '20 минут на панораму ярусов.',
        locationSlug: 'tyumen-most-vlyublennyh',
        mustSeeFilter: 'views',
        visitMinutes: 20,
        address: 'Мост Влюбленных',
        latitude: 57.1538,
        longitude: 65.534,
        transitTip: 'Пешком 8 минут к Туре',
      },
      {
        name: 'Четырехъярусная набережная',
        desc: '40 минут на спуск по ярусам и рельефам.',
        locationSlug: 'tyumen-chetyrehurovnevaya-naberezhnaya',
        mustSeeFilter: 'main',
        visitMinutes: 40,
        address: 'Набережная реки Туры',
        latitude: 57.1558,
        longitude: 65.5315,
        transitTip: 'С моста на средний ярус',
      },
      {
        name: 'Пароходная контора Колмакова',
        desc: 'Обед на фудкорте у реки.',
        locationSlug: 'tyumen-parohodnaya-kontora-kolmakova',
        mustSeeFilter: 'houses',
        visitMinutes: 40,
        address: 'ул. 25 Октября, 23А',
        latitude: 57.1635,
        longitude: 65.5375,
        transitTip: 'Пешком вдоль нижнего яруса 10 минут',
      },
    ],
  },
  {
    id: 'tyumen-arbat-slovtsov',
    title: 'Тюменский Арбат, резное кружево и Словцов хай-тек',
    description:
      'Деревянный Арбат, чай в «Наличниках», Спасская, сибирские кошки, музей Словцова и ужин в «Чуме».',
    travelVector: 'Пешком по Дзержинского и центру',
    timingNote: 'Около 4 часов; вечером имеет смысл «Чум» на Малыгина.',
    coverImageUrl: '/images/venues/tyumen/dom-burkova.jpg',
    stops: [
      {
        name: 'Дом Буркова',
        desc: '15 минут на особняк и дворника.',
        locationSlug: 'tyumen-dom-burkova',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'ул. Дзержинского, 30',
        latitude: 57.156112,
        longitude: 65.536912,
      },
      {
        name: 'Чайная «Наличники»',
        desc: '30 минут на чай в деревянном доме, 34С.',
        locationSlug: 'tyumen-chaynaya-nalichniki',
        mustSeeFilter: 'gastro',
        visitMinutes: 30,
        address: 'ул. Дзержинского, 34С',
        latitude: 57.1559,
        longitude: 65.5364,
        transitTip: 'Пешком 2 минуты по Арбату',
      },
      {
        name: 'Спасская церковь',
        desc: '20 минут на храм на Ленина.',
        locationSlug: 'tyumen-spasskaya-tserkov',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'ул. Ленина, 43',
        latitude: 57.155,
        longitude: 65.5385,
        transitTip: 'Пешком 7 минут',
      },
      {
        name: 'Сквер сибирских кошек',
        desc: '15 минут на золоченых кошек.',
        locationSlug: 'tyumen-skver-sibirskih-koshek',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'ул. Первомайская',
        latitude: 57.153912,
        longitude: 65.541112,
        transitTip: 'Пешком 8 минут',
      },
      {
        name: 'Музей Словцова',
        desc: 'Час на хай-тек экспозицию.',
        venueSlug: 'tyumen-muzey-slovtsova',
        mustSeeFilter: 'museum',
        visitMinutes: 60,
        address: 'ул. Советская, 63',
        latitude: 57.1536,
        longitude: 65.5473,
        transitTip: 'Пешком 10 минут',
      },
      {
        name: 'Ресторан «Чум»',
        desc: 'Строганина, дичь и сибирский стол.',
        locationSlug: 'tyumen-restoran-chum',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Малыгина, 59',
        latitude: 57.145,
        longitude: 65.555,
        transitTip: 'Автобус или 20 минут пешком',
      },
    ],
  },
  ...TYUMEN_LINE_DAY_ROUTE_PRESETS,
];

export const TYUMEN_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Термальная вода в Тюмени природная или из бойлеров?',
    a: 'Природная. Скважины 1000-2500 м дают воду +38...+43 с йодом и бромом. Это не подогретый городской водопровод: характерный запах и минерализация - часть опыта, а не брак.',
  },
  {
    q: 'Правда ли, что в Тюмени в войну хранили тело Ленина?',
    a: 'Да. В 1941-45 забальзамированное тело находилось в здании аграрного вуза на Республике, 7, комната 15 (историческая приказная изба). Город тогда держали в секрете.',
  },
  {
    q: 'Как дешевле попасть на термы?',
    a: 'Самый выгодный слот - понедельник-среда с 08:00 до 12:00. Смотрите Верхний Бор или «Советский» (бывший «Дикий»). Цены ниже - ориентир, кассу сверяйте в день поездки.',
  },
  {
    q: 'Почему Большой драматический театр Тюмени называют огромным?',
    a: 'По площади пола здание около 36000 м² - больше МХАТа и Большого театра. Адрес: ул. Республики, 129. Имеет смысл закладывать время на само здание, а не только на спектакль.',
  },
];

export const TYUMEN_TRAVEL =
  'Аэропорт Рощино имени Д. И. Менделеева: прямые рейсы из Москвы около 2,5 часов, плюс Петербург и северные города. Тюмень - узел Транссиба. Лучшее окно для терм - поздняя осень и зима: открытые бассейны +38...+40 в соснах при -13...-17 °C, дороги чистят сразу. Лето сухое, часто около +30 °C: гранитные ярусы Туры, террасы Дзержинского, экопарки и Тобольск за ~3 часа. Весной в апреле ломает лед на Туре, в мае +15...+18 °C и лучшие прогулки по купеческим кварталам, в конце мая - речная навигация. Осень: сентябрь +14...+16 °C, бабье лето; октябрь золотит парки. Золотая логистика осени - меньше термальных туристов, дешевле перелеты из Москвы и отели.';
