/** Krasnodar tourist hub pack (owner 2026-08-15). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { KRASNODAR_LINE_DAY_ROUTE_PRESETS } from './krasnodar-line-presets.ts';

export const KRASNODAR_MUST_SEE: any[] = [
  // --- Core ---
  {
    name: 'Парк «Краснодар» (Парк Галицкого)',
    desc: 'Лучший современный парк страны: амфитеатр, зеркальные лабиринты и редкие деревья.',
    address: 'ул. Разведчика Посадского',
    locationSlug: 'krasnodar-park-galitskogo-park-krasnodar',
    mustSeeFilter: 'main',
    visitMinutes: 120,
    latitude: 45.042711,
    longitude: 39.030512,
  },
  {
    name: 'Улица Красная',
    desc: 'Главная ось города: по выходным полностью пешеходная, с музыкантами и террасами.',
    address: 'ул. Красная',
    locationSlug: 'krasnodar-ulitsa-krasnaya',
    mustSeeFilter: 'street',
    visitMinutes: 90,
    latitude: 45.031512,
    longitude: 38.972511,
  },
  {
    name: 'Александровская Триумфальная арка',
    desc: 'Неоготические Царские ворота на Красной улице.',
    address: 'ул. Красная / ул. Бабушкина',
    locationSlug: 'krasnodar-aleksandrovskaya-triumfal-naya-arka',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 45.048311,
    longitude: 38.977212,
  },
  {
    name: 'Японский сад в парке «Краснодар»',
    desc: 'Крупнейший японский сад за пределами Японии - вход по QR из инфоматов.',
    address: 'ул. Разведчика Посадского',
    locationSlug: 'krasnodar-yaponskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 45.045112,
    longitude: 39.032211,
  },
  {
    name: 'Мост Поцелуев',
    desc: 'Романтичный пешеходный мост через затон к Кубанской набережной.',
    address: 'ул. Кубанская Набережная',
    locationSlug: 'krasnodar-most-potseluev',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 45.025122,
    longitude: 38.953311,
  },
  {
    name: 'Памятник Екатерине II',
    desc: 'Монумент императрице в Екатерининском сквере - восстановлен по чертежам XIX века.',
    address: 'Екатерининский сквер (ул. Красная)',
    locationSlug: 'krasnodar-pamyatnik-ekaterine-ii',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 45.013412,
    longitude: 38.964511,
  },

  // --- Monuments ---
  {
    name: 'Памятник Кларе Лучко и кубанским казакам',
    desc: 'Актриса в образе казачки из фильма «Кубанские казаки» у гостиницы «Платан».',
    address: 'ул. Постовая',
    locationSlug: 'krasnodar-pamyatnik-klare-luchko',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.012512,
    longitude: 38.966711,
  },
  {
    name: 'Скульптура «Гуляющие собачки»',
    desc: 'Бронзовая пара собак под фонарем - трут носы и лапы на удачу.',
    address: 'ул. Красная / ул. Мира',
    locationSlug: 'krasnodar-skulptura-gulyayuschie-sobachki',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.021211,
    longitude: 38.971212,
  },
  {
    name: 'Скульптура «Студенты Лида и Шурик»',
    desc: 'Герои Гайдая с конспектом на аллее перед КубГТУ.',
    address: 'ул. Красная, 135',
    locationSlug: 'krasnodar-skulptura-lida-i-shurik',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.044112,
    longitude: 38.975611,
  },
  {
    name: 'Памятник казакам, пишущим письмо султану',
    desc: 'Бронзовая копия картины Репина со свободным стулом для фото.',
    address: 'ул. Красная / ул. Горького',
    locationSlug: 'krasnodar-pamyatnik-kazakam-pismo-sultanu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.031512,
    longitude: 38.972511,
  },
  {
    name: 'Скульптура «Гость»',
    desc: 'Путешественник с чемоданом на углу Красной.',
    address: 'ул. Красная / ул. Гаврилова',
    locationSlug: 'krasnodar-skulptura-gost',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.053112,
    longitude: 38.979112,
  },
  {
    name: 'Памятник кошельку',
    desc: 'Гранитный кошелек на брусчатке - трут для богатства.',
    address: 'ул. Гоголя, 68',
    locationSlug: 'krasnodar-pamyatnik-koshelku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.023411,
    longitude: 38.973911,
  },
  {
    name: 'Памятник Кубанскому казачеству',
    desc: 'Казак-первопоселенец на коне у краевой администрации.',
    address: 'ул. Красная, 35',
    locationSlug: 'krasnodar-pamyatnik-kubanskomu-kazachestvu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.024612,
    longitude: 38.971512,
  },
  {
    name: 'Скульптура «Аврора»',
    desc: '14-метровая советская девушка-боец у кинотеатра «Аврора».',
    address: 'ул. Красная, 169',
    locationSlug: 'krasnodar-skulptura-avrora',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 45.058342,
    longitude: 38.980511,
  },
  {
    name: 'Памятник А. С. Пушкину',
    desc: 'Классический памятник на площади у художественного музея.',
    address: 'Площадь Пушкина',
    locationSlug: 'krasnodar-pamyatnik-pushkinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.015211,
    longitude: 38.966911,
  },
  {
    name: 'Памятник Первой учительнице',
    desc: 'Скульптура педагогам Кубани у Дома книги.',
    address: 'ул. Красноармейская',
    locationSlug: 'krasnodar-pamyatnik-pervoy-uchitelnitse',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.029112,
    longitude: 38.974211,
  },
  {
    name: 'Памятник И. Е. Репину',
    desc: 'Художник, собиравший на Кубани типажи для картин.',
    address: 'ул. Красная, 13',
    locationSlug: 'krasnodar-pamyatnik-repinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.016912,
    longitude: 38.966411,
  },
  {
    name: 'Памятник генералу Корнилову',
    desc: 'Памятник лидеру Белого движения у улицы Корнилова.',
    address: 'ул. Калинина / ул. Корнилова',
    locationSlug: 'krasnodar-pamyatnik-kornilovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.041521,
    longitude: 38.928311,
  },
  {
    name: 'Скульптура «Индустрия»',
    desc: 'Советский барельеф у проходной ЗИП.',
    address: 'ул. Зиповская, 5',
    locationSlug: 'krasnodar-skulptura-industriya',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 45.061211,
    longitude: 38.989411,
  },
  {
    name: 'Памятник воинам-освободителям',
    desc: 'Мемориал на площади Победы.',
    address: 'Площадь Победы (ул. Постовая)',
    locationSlug: 'krasnodar-pamyatnik-voinam-osvoboditelyam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 45.011512,
    longitude: 38.969112,
  },

  // --- Museums / heritage ---
  {
    name: 'Музей им. Фелицына',
    desc: 'Главный музей Кубани в особняке купцов Богарсуковых.',
    address: 'ул. Гимназическая, 67',
    locationSlug: 'krasnodar-muzey-felitsyna',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 45.023342,
    longitude: 38.970611,
  },
  {
    name: 'Художественный музей им. Коваленко',
    desc: 'Старейший художественный музей юга России.',
    address: 'ул. Красная, 13',
    locationSlug: 'krasnodar-hudozhestvennyy-muzey-kovalenko',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 45.016612,
    longitude: 38.966111,
  },
  {
    name: 'Литературный музей Кубани',
    desc: 'Дом казачьего атамана Якова Кухаренко.',
    address: 'ул. Постовая, 39',
    locationSlug: 'krasnodar-literaturnyy-muzey-kubani',
    mustSeeFilter: 'literature',
    visitMinutes: 45,
    latitude: 45.012811,
    longitude: 38.962812,
  },
  {
    name: 'Дом-музей штурмана Ермолаева',
    desc: 'Небольшой мемориальный деревянный особняк.',
    address: 'ул. Кирова, 17',
    locationSlug: 'krasnodar-dom-muzey-ermolaeva',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 45.021711,
    longitude: 38.957812,
  },
  {
    name: 'Филармония им. Пономаренко',
    desc: 'Бывший Зимний театр - памятник архитектуры на Красной.',
    address: 'ул. Красная, 55',
    locationSlug: 'krasnodar-filarmoniya-ponomarenko',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 45.026112,
    longitude: 38.971912,
  },
  {
    name: 'Особняк купца Лихацкого',
    desc: 'Деревянное и кирпичное зодчество старого Екатеринодара.',
    address: 'ул. Красная, 118а',
    locationSlug: 'krasnodar-osobnyak-likhatskogo',
    mustSeeFilter: 'mansions',
    visitMinutes: 20,
    latitude: 45.039411,
    longitude: 38.975411,
  },
  {
    name: 'Дом инженера Шарданова',
    desc: 'Особняк в мавританском стиле на Красной.',
    address: 'ул. Красная, 15',
    locationSlug: 'krasnodar-dom-shardanova',
    mustSeeFilter: 'mansions',
    visitMinutes: 20,
    latitude: 45.017213,
    longitude: 38.966411,
  },
  {
    name: 'Башня Шухова',
    desc: 'Ажурная гиперболоидная стальная конструкция у ТРЦ «Галерея».',
    address: 'ул. Рашпилевская, 147',
    locationSlug: 'krasnodar-bashnya-shukhova',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 45.038511,
    longitude: 38.971812,
  },
  {
    name: 'Парк «Россия - Моя история»',
    desc: 'Интерактивный хайтек-комплекс на Конгрессной.',
    address: 'ул. Конгрессная, 2',
    locationSlug: 'krasnodar-rossiya-moya-istoriya',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 45.109112,
    longitude: 38.951211,
  },

  // --- Temples ---
  {
    name: 'Свято-Екатерининский собор',
    desc: 'Главный семиглавый храм из красного кирпича.',
    address: 'ул. Коммунаров, 52',
    locationSlug: 'krasnodar-ekaterininskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 45.019412,
    longitude: 38.974211,
  },
  {
    name: 'Войсковой собор Александра Невского',
    desc: 'Белокаменный собор кубанского казачьего войска.',
    address: 'ул. Красная, 1',
    locationSlug: 'krasnodar-voyskovoy-sobor-aleksandra-nevskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 45.011912,
    longitude: 38.964211,
  },
  {
    name: 'Свято-Троицкий собор',
    desc: 'Кирпичный храм XIX века с зелеными куполами.',
    address: 'ул. Фрунзе, 65',
    locationSlug: 'krasnodar-svyato-troitskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 45.026112,
    longitude: 38.958211,
  },
  {
    name: 'Свято-Георгиевский храм',
    desc: 'Краснокирпичная церковь, не закрывавшаяся в советские годы.',
    address: 'ул. Митрофана Седина, 170',
    locationSlug: 'krasnodar-svyato-georgievskiy-khram',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 45.041122,
    longitude: 38.979711,
  },
  {
    name: 'Армянская церковь Св. Иоанна Евангелиста',
    desc: 'Храм из туфа на Тургенева.',
    address: 'ул. Тургенева, 165',
    locationSlug: 'krasnodar-armyanskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 45.055611,
    longitude: 38.948912,
  },
  {
    name: 'Ильинская церковь',
    desc: 'Белоснежный храм у реки Кубань.',
    address: 'ул. Октябрьская, 149',
    locationSlug: 'krasnodar-ilinskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 45.028612,
    longitude: 38.961211,
  },
  {
    name: 'Храм Рождества Христова',
    desc: 'Современный комплекс в Юбилейном у воды.',
    address: 'ул. Рождественская Набережная, 1',
    locationSlug: 'krasnodar-khram-rozhdestva-khristova',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 45.031211,
    longitude: 38.905612,
  },
  {
    name: 'Храм «Целительница»',
    desc: 'Деревянный бревенчатый храм на Красных Партизан.',
    address: 'ул. Красных Партизан, 6/7',
    locationSlug: 'krasnodar-khram-tselitelnitsa',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 45.048612,
    longitude: 38.928711,
  },
  {
    name: 'Часовня Димитрия Солунского',
    desc: 'Часовня у ТРЦ «Галерея».',
    address: 'ул. Володи Головатого',
    locationSlug: 'krasnodar-chasovnya-dimitriya-solunskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 10,
    latitude: 45.038112,
    longitude: 38.972211,
  },
  {
    name: 'Свято-Покровский храм',
    desc: 'Уютный храм с благоустроенной территорией.',
    address: 'ул. Сташкова, 5',
    locationSlug: 'krasnodar-svyato-pokrovskiy-khram',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 45.016112,
    longitude: 39.028311,
  },

  // --- Parks ---
  {
    name: 'Парк «Солнечный остров»',
    desc: 'Лесной массив на острове Кубани с зоопарком «Сафари-Парк».',
    address: 'ул. Трамвайная, 2',
    locationSlug: 'krasnodar-park-solnechnyy-ostrov',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 45.009112,
    longitude: 39.051211,
  },
  {
    name: 'Чистяковская роща',
    desc: 'Старейший парк с вековыми дубами и книжным рынком.',
    address: 'ул. Колхозная, 86',
    locationSlug: 'krasnodar-chistyakovskaya-roscha',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 45.060122,
    longitude: 38.988311,
  },
  {
    name: 'Городской сад (парк Горького)',
    desc: 'Исторический парк с прудом, лебедями и колесом обозрения.',
    address: 'ул. Постовая, 34',
    locationSlug: 'krasnodar-gorodskoy-sad-park-gor-kogo',
    mustSeeFilter: 'park',
    visitMinutes: 45,
    latitude: 45.011112,
    longitude: 38.968311,
  },
  {
    name: 'Парк 30-летия Победы (Затон)',
    desc: 'Выставка «Оружие Победы» на берегу реки.',
    address: 'ул. Береговая, 146',
    locationSlug: 'krasnodar-park-30-letiya-pobedy',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 45.018612,
    longitude: 38.951211,
  },
  {
    name: 'Кубанская набережная',
    desc: 'Благоустроенный променад у затона и Моста Поцелуев.',
    address: 'ул. Кубанская Набережная',
    locationSlug: 'krasnodar-kubanskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 45.025122,
    longitude: 38.953311,
  },
  {
    name: 'Ботанический сад им. Косенко',
    desc: 'Дендрарий с редкими растениями и ручными белками - вход бесплатный.',
    address: 'ул. Калинина',
    locationSlug: 'krasnodar-botanicheskiy-sad-kosenko',
    mustSeeFilter: 'park',
    visitMinutes: 75,
    latitude: 45.044411,
    longitude: 38.929112,
  },
  {
    name: 'Главный городской фонтан',
    desc: 'Светомузыкальный фонтан перед Драмтеатром.',
    address: 'Театральная площадь',
    locationSlug: 'krasnodar-glavnyy-gorodskoy-fontan',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 45.037812,
    longitude: 38.973912,
  },
  {
    name: 'Сквер Дружбы народов',
    desc: 'Сквер со шрифтом «Краснодар», детскими и скейт-площадками.',
    address: 'ул. Рашпилевская',
    locationSlug: 'krasnodar-skver-druzhby-narodov',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 45.028711,
    longitude: 38.971112,
  },

  // --- Culture / gastro ---
  {
    name: 'Театр драмы им. Горького',
    desc: 'Главная драматическая сцена на Театральной площади.',
    address: 'Театральная площадь, 1',
    locationSlug: 'krasnodar-teatr-dramy-gorkogo',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 45.037211,
    longitude: 38.973311,
  },
  {
    name: 'Музыкальный театр «Премьера»',
    desc: 'Опера, балет и мюзиклы на Красной.',
    address: 'ул. Красная, 44',
    locationSlug: 'krasnodar-muzykalnyy-teatr-premiera',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 45.022511,
    longitude: 38.971112,
  },
  {
    name: 'Креативный кластер «Колос»',
    desc: 'Шоурумы, инди-кофейни и маркеты на территории старого хлебозавода.',
    address: 'ул. Калинина, 368',
    locationSlug: 'krasnodar-kreativnyy-klaster-kolos',
    mustSeeFilter: 'creative',
    visitMinutes: 75,
    latitude: 45.039112,
    longitude: 38.964411,
  },
  {
    name: 'Ресторан «Борщberry»',
    desc: 'Концепт кубанского борща в десятках вариаций с пампушками и салом.',
    address: 'ул. Красная, 182',
    locationSlug: 'krasnodar-restoran-borschberry',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 45.049112,
    longitude: 38.978111,
  },
  {
    name: 'Фудмаркет в Центре города',
    desc: 'Фуд-холл с более чем 30 кулинарными концепциями на Красной.',
    address: 'ул. Красная, 176',
    locationSlug: 'krasnodar-fudmarket',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 45.048111,
    longitude: 38.976712,
  },
];

export const KRASNODAR_SUBURBS: any[] = [
  {
    name: 'Горячий Ключ',
    desc: 'Бальнеологический курорт: минеральные источники, Дантово ущелье и скалы над Псекупсом.',
    locationSlug: 'krasnodar-goryachiy-klyuch',
    mustSeeFilter: 'main',
    visitMinutes: '6-8 ч',
    latitude: 44.623112,
    longitude: 39.147511,
    address: 'г. Горячий Ключ, Целебный парк (ул. Санаторная)',
    travelVector: '«Ласточка» ~1 ч',
    travelVectorBlurb:
      'Закладывайте на скоростную электричку «Ласточка» около часа, чтобы приехать к 10 утра.',
    timingNote:
      'По аллеям Целебного парка вверх к горам; Дантово ущелье и смотровые - напоследок.',
    places: [
      {
        name: 'Питьевая галерея',
        desc: 'Дегустация минеральных вод «Псекупская» разной температуры.',
        visitMinutes: 30,
      },
      {
        name: 'Иверская часовня',
        desc: 'Часовня, вырубленная в скале у подножия горы.',
        visitMinutes: 20,
      },
      {
        name: 'Дантово ущелье',
        desc: 'Узкая скальная теснина со ступенями, покрытая мхом.',
        visitMinutes: 45,
      },
      {
        name: 'Скала Петушок',
        desc: 'Отвесный утес над рекой Псекупс.',
        visitMinutes: 25,
      },
      {
        name: 'Аллея Тысячи сосен',
        desc: 'Двухкилометровый променад из пицундских сосен.',
        visitMinutes: 40,
      },
      {
        name: 'Скала Зеркало',
        desc: 'Гладкий 30-метровый скальный массив в лесу.',
        visitMinutes: 30,
      },
      {
        name: 'Подвесной мост Надежды',
        desc: 'Канатный мост через Псекупс для финального кадра на фоне гор.',
        visitMinutes: 20,
      },
    ],
  },
];

export const KRASNODAR_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'krasnodar-ekaterina-galitskiy',
    title: 'От Екатерины до Галицкого',
    description:
      'Парадный день: Екатерининский сквер, Красная улица, Царские ворота, борщ и парк Галицкого с Японским садом.',
    travelVector: 'Парадный пешеходный маршрут',
    timingNote: 'Около 8-9 часов; к парку Галицкого удобен автобус или такси.',
    stops: [
      {
        name: 'Екатерининский сквер и Екатерина II',
        desc: 'Старт у Войскового собора и памятника императрице.',
        locationSlug: 'krasnodar-pamyatnik-ekaterine-ii',
        mustSeeFilter: 'monument',
        visitMinutes: 60,
        latitude: 45.013412,
        longitude: 38.964511,
      },
      {
        name: 'Пешеходная Красная улица',
        desc: 'Купеческие особняки, собачки, Шурик с Лидой и Репин.',
        locationSlug: 'krasnodar-ulitsa-krasnaya',
        mustSeeFilter: 'street',
        visitMinutes: 90,
        latitude: 45.031512,
        longitude: 38.972511,
      },
      {
        name: 'Александровская Триумфальная арка',
        desc: 'Фото у кирпичных Царских ворот.',
        locationSlug: 'krasnodar-aleksandrovskaya-triumfal-naya-arka',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        latitude: 45.048311,
        longitude: 38.977212,
      },
      {
        name: 'Ресторан «Борщberry»',
        desc: 'Обед кубанским борщом с пампушками и салом.',
        locationSlug: 'krasnodar-restoran-borschberry',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Красная, 182',
        latitude: 45.049112,
        longitude: 38.978111,
      },
      {
        name: 'Парк «Краснодар» (Галицкого)',
        desc: 'Футуристические лабиринты у стадиона.',
        locationSlug: 'krasnodar-park-galitskogo-park-krasnodar',
        mustSeeFilter: 'main',
        visitMinutes: 120,
        latitude: 45.042711,
        longitude: 39.030512,
        transitTip: 'Переезд к стадиону / парку Галицкого',
      },
      {
        name: 'Японский сад',
        desc: 'Финал с чайными домиками и вечерней подсветкой.',
        locationSlug: 'krasnodar-yaponskiy-sad',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        latitude: 45.045112,
        longitude: 39.032211,
      },
    ],
  },
  {
    id: 'krasnodar-neformalnyy',
    title: 'Неформальный Краснодар',
    description:
      'Мост Поцелуев, Затон, кластер «Колос», башня Шухова и ужин на Фудмаркете.',
    travelVector: 'Набережные, креатив и фото-точки',
    timingNote: 'Около 6-7 часов; между Затоном и «Колосом» удобен транспорт.',
    stops: [
      {
        name: 'Мост Поцелуев',
        desc: 'Старт на пешеходном мосту с панорамой Кубани.',
        locationSlug: 'krasnodar-most-potseluev',
        mustSeeFilter: 'views',
        visitMinutes: 45,
        latitude: 45.025122,
        longitude: 38.953311,
      },
      {
        name: 'Парк «Оружие Победы»',
        desc: 'Танки, самолеты и подводная лодка на Затоне.',
        locationSlug: 'krasnodar-park-30-letiya-pobedy',
        mustSeeFilter: 'museum',
        visitMinutes: 60,
        latitude: 45.018612,
        longitude: 38.951211,
      },
      {
        name: 'Креативный кластер «Колос»',
        desc: 'Кофе и шопинг на территории старого завода.',
        locationSlug: 'krasnodar-kreativnyy-klaster-kolos',
        mustSeeFilter: 'creative',
        visitMinutes: 90,
        address: 'ул. Калинина, 368',
        latitude: 45.039112,
        longitude: 38.964411,
        transitTip: 'Переезд к Калинина',
      },
      {
        name: 'Башня Шухова и фонтан',
        desc: 'Ажурный гиперболоид и Главный городской фонтан.',
        locationSlug: 'krasnodar-bashnya-shukhova',
        mustSeeFilter: 'houses',
        visitMinutes: 60,
        latitude: 45.038511,
        longitude: 38.971812,
      },
      {
        name: 'Фудмаркет',
        desc: 'Ужин в крупнейшем фуд-холле юга.',
        locationSlug: 'krasnodar-fudmarket',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Красная, 176',
        latitude: 45.048111,
        longitude: 38.976712,
      },
    ],
  },
  ...KRASNODAR_LINE_DAY_ROUTE_PRESETS,
];

export const KRASNODAR_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что главную улицу Красную перекрывают по выходным для пешеходов?',
    a: 'Да. Каждые выходные (с вечера пятницы до конца воскресенья) центральный отрезок Красной становится полностью пешеходным: музыканты, танцоры, художники, а кафе выносят столики на дорогу.',
  },
  {
    q: 'Как работает знаменитый Японский сад в парке Галицкого и нужен ли туда билет?',
    a: 'Вход бесплатный, но пускают по одноразовым QR-кодам из-за лимита посещаемости. Коды выдают в инфоматах на входе каждые два часа (с 6:30). Лайфхак: столик в ресторане «Рётей» или чайном домике внутри сада - без QR и очереди.',
  },
  {
    q: 'Работает ли сейчас аэропорт Пашковский в Краснодаре и как добраться поездом?',
    a: 'Аэропорт Краснодара временно закрыт. Из Москвы удобны поезда «Премиум» или двухэтажные составы (около 18-24 часов до вокзала Краснодар-1). Из Сочи (Адлер) трижды в день ходит «Ласточка» - около 4 часов 40 минут.',
  },
  {
    q: 'Безопасно ли купаться в реке Кубань в черте города?',
    a: 'Официально Роспотребнадзор запрещает купание в Кубани и Карасунских озерах из-за течения, водоворотов и санитарных норм. Для воды - открытые бассейны на Затоне («Пляж в парке 30-летия Победы») или термальный комплекс «Баден-Баден» на окраине.',
  },
];

export const KRASNODAR_TRAVEL =
  'Аэропорт Пашковский временно закрыт: из Москвы удобны поезда (около 18-24 часов до Краснодар-1), из Сочи - «Ласточка» около 4 часов 40 минут. Автомобилисты едут по М-4 «Дон». Лучший сезон для прогулок - апрель-май и сентябрь-октябрь. Летом жара сильная: гуляйте вечером после 19:00. Центр удобен пешком по Красной; до парка Галицкого - автобус или такси.';
