/** Krasnoyarsk tourist hub pack (owner 2026-08-15). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { KRASNOYARSK_LINE_DAY_ROUTE_PRESETS } from './krasnoyarsk-line-presets';

export const KRASNOYARSK_MUST_SEE: any[] = [
  // --- Core ---
  {
    name: 'Национальный парк «Красноярские Столбы»',
    desc: 'Скалы-останцы в тайге у города - главный хайкинг Сибири.',
    address: 'ул. Свердловская, 273',
    locationSlug: 'krasnoyarsk-natsional-nyy-park-krasnoyarskie-stolby',
    mustSeeFilter: 'main',
    visitMinutes: 180,
    latitude: 55.915012,
    longitude: 92.735811,
  },
  {
    name: 'Караульная гора и часовня Параскевы Пятницы',
    desc: 'Символ города на 10-рублевой купюре - панорама Енисея со смотровой.',
    address: 'ул. Степана Разина, 51а',
    locationSlug: 'krasnoyarsk-karaul-naya-gora-i-chasovnya-paraskevy-pyatnitsy',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 56.024311,
    longitude: 92.868311,
  },
  {
    name: 'Центральная набережная Енисея',
    desc: 'Многоуровневый променад по Дубровинского с видами на мосты.',
    address: 'ул. Дубровинского',
    locationSlug: 'krasnoyarsk-tsentral-naya-naberezhnaya-eniseya',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 56.007811,
    longitude: 92.865611,
  },
  {
    name: 'Виноградовский пешеходный мост',
    desc: 'Вантовый мост на остров Татышев - лучший кадр на Енисей.',
    address: 'остров Татышев (западный вход)',
    locationSlug: 'krasnoyarsk-peshehodnyy-most-na-ostrov-tatyshev',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 56.015912,
    longitude: 92.898211,
  },
  {
    name: 'Музей-усадьба В. И. Сурикова',
    desc: 'Казачья усадьба XIX века, где родился художник.',
    address: 'ул. Ленина, 98',
    venueSlug: 'krasnoyarsk-muzey-usad-ba-v-i-surikova',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 56.012811,
    longitude: 92.866111,
  },
  {
    name: 'Пароход-музей «Святитель Николай»',
    desc: 'Историческое судно на вечной стоянке у Стрелки.',
    address: 'площадь Мира, 1а',
    venueSlug: 'krasnoyarsk-parohod-muzey-svyatitel-nikolay',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 56.015111,
    longitude: 92.895812,
  },
  {
    name: 'Остров Татышев',
    desc: 'Городской остров-парк посреди Енисея: велодорожки, пляжи и лес.',
    address: 'остров Татышев',
    locationSlug: 'krasnoyarsk-ostrov-tatyshev',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 56.028711,
    longitude: 92.930512,
  },
  {
    name: 'Коммунальный мост',
    desc: 'Мост с десятирублевой купюры через Енисей.',
    address: 'Коммунальный мост',
    locationSlug: 'krasnoyarsk-kommunalnyy-most',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 56.005412,
    longitude: 92.871211,
  },
  {
    name: 'Ресторан «Тунгуска»',
    desc: 'Высокая сибирская кухня: оленина, сугудай и таежные ягоды.',
    address: 'ул. Весны, 30',
    locationSlug: 'krasnoyarsk-restoran-tunguska',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 56.037211,
    longitude: 92.913311,
  },
  {
    name: 'Фанпарк «Бобровый лог»',
    desc: 'Горнолыжный курорт у Столбов: трассы зимой, канатка и виды летом.',
    address: 'ул. Сибирская, 92',
    locationSlug: 'krasnoyarsk-fanpark-bobrovyy-log',
    mustSeeFilter: 'park',
    visitMinutes: 120,
    latitude: 55.961211,
    longitude: 92.784411,
  },

  // --- Monuments ---
  {
    name: 'Памятник Андрею Дубенскому',
    desc: 'Основатель Красноярска на Покровской горе.',
    address: 'ул. Белинского / Покровская гора',
    locationSlug: 'krasnoyarsk-pamyatnik-andreyu-dubenskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 56.023342,
    longitude: 92.895611,
  },
  {
    name: 'Памятник В. И. Сурикову',
    desc: 'Художник у родной усадьбы на Ленина.',
    address: 'ул. Ленина, 98',
    locationSlug: 'krasnoyarsk-pamyatnik-surikovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.012512,
    longitude: 92.866711,
  },
  {
    name: 'Скульптура «Царь-рыба»',
    desc: 'Гигантский осетр на Слизневском утесе по дороге в Дивногорск.',
    address: 'Слизневский утес, трасса Р-257',
    locationSlug: 'krasnoyarsk-tsar-ryba',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 55.955412,
    longitude: 92.598211,
  },
  {
    name: 'Памятник Дмитрию Хворостовскому',
    desc: 'Оперный баритон на пр. Мира у филармонии города.',
    address: 'ул. Ленина, 22',
    locationSlug: 'krasnoyarsk-pamyatnik-khvorostovskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.014112,
    longitude: 92.875611,
  },
  {
    name: 'Скульптура «Похищение Европы»',
    desc: 'Современный арт на Предмостной площади.',
    address: 'Предмостная площадь',
    locationSlug: 'krasnoyarsk-pokhishchenie-evropy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.991512,
    longitude: 92.892511,
  },
  {
    name: 'Памятник Антону Чехову',
    desc: 'Писатель на Ярыгинской набережной.',
    address: 'Ярыгинская набережная',
    locationSlug: 'krasnoyarsk-pamyatnik-chekhovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.009412,
    longitude: 92.879112,
  },
  {
    name: 'Белая ротонда',
    desc: 'Пушкин и Гончарова в сквере на пересечении Мира и Кирова.',
    address: 'пр. Мира / ул. Кирова',
    locationSlug: 'krasnoyarsk-belaya-rotonda',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.012341,
    longitude: 92.863911,
  },
  {
    name: 'Памятник фотографу',
    desc: 'Фотограф с аппаратом-гармошкой на пр. Мира.',
    address: 'пр. Мира, 96',
    locationSlug: 'krasnoyarsk-pamyatnik-fotografu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.012612,
    longitude: 92.868112,
  },
  {
    name: 'Памятник архиепископу Луке',
    desc: 'Святитель и хирург эвакогоспиталя у пр. Мира.',
    address: 'ул. Горького / пр. Мира',
    locationSlug: 'krasnoyarsk-pamyatnik-arkhiepiskopu-luke',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.011842,
    longitude: 92.850511,
  },
  {
    name: 'Памятник В. П. Степанову',
    desc: 'Мемориал у Красной площади на Копылова.',
    address: 'ул. Копылова / Красная площадь',
    locationSlug: 'krasnoyarsk-pamyatnik-stepanovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.015211,
    longitude: 92.836911,
  },
  {
    name: 'Скульптура «Дядя Яша и стажер»',
    desc: 'Сантехник из люка - любимый городской жанр.',
    address: 'ул. Парижской Коммуны, 41',
    locationSlug: 'krasnoyarsk-dyadya-yasha-i-stazher',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.015112,
    longitude: 92.884211,
  },
  {
    name: 'Памятник Виктору Астафьеву',
    desc: 'Писатель у спуска к Енисею на площади Мира.',
    address: 'площадь Мира, 1',
    locationSlug: 'krasnoyarsk-pamyatnik-astafievu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.016912,
    longitude: 92.894411,
  },
  {
    name: 'Памятник каторжанину',
    desc: 'Мемориал сибирской каторге на пр. Свободный.',
    address: 'пр. Свободный',
    locationSlug: 'krasnoyarsk-pamyatnik-katorzhaninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.021521,
    longitude: 92.808311,
  },
  {
    name: 'Скульптура «Река Енисей»',
    desc: 'Фонтанная композиция на Театральной площади.',
    address: 'ул. Дубровинского',
    locationSlug: 'krasnoyarsk-skulptura-reka-enisey',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 56.009112,
    longitude: 92.869411,
  },
  {
    name: 'Памятник воинам-спортсменам',
    desc: 'Мемориал на Острове Отдыха.',
    address: 'Остров Отдыха',
    locationSlug: 'krasnoyarsk-pamyatnik-voinam-sportsmenam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.998512,
    longitude: 92.869112,
  },

  // --- Museums / heritage ---
  {
    name: 'Краеведческий музей',
    desc: 'Египетский дом на набережной - главный музей края.',
    address: 'ул. Дубровинского, 84',
    locationSlug: 'krasnoyarsk-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 56.008342,
    longitude: 92.867611,
  },
  {
    name: 'Музейный центр «Площадь Мира»',
    desc: 'Современное искусство в бруталистском здании на Стрелке.',
    address: 'площадь Мира, 1',
    locationSlug: 'krasnoyarsk-ploschad-mira-kic',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 56.015811,
    longitude: 92.893812,
  },
  {
    name: 'Литературный музей В. П. Астафьева',
    desc: 'Дом писателя с экспозицией о сибирской прозе.',
    address: 'ул. Ленина, 66',
    locationSlug: 'krasnoyarsk-literaturnyy-muzey-astafieva',
    mustSeeFilter: 'literature',
    visitMinutes: 45,
    latitude: 56.014112,
    longitude: 92.881912,
  },
  {
    name: 'Художественный музей им. Сурикова',
    desc: 'Особняк Гадалова с коллекцией живописи.',
    address: 'ул. Парижской Коммуны, 20',
    locationSlug: 'krasnoyarsk-hudozhestvennyy-muzey-surikova',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 56.013411,
    longitude: 92.884112,
  },
  {
    name: 'Органный зал (костел)',
    desc: 'Неоготика из красного кирпича и орган на Декабристов.',
    address: 'ул. Декабристов, 20',
    locationSlug: 'krasnoyarsk-organnyy-zal-kostel',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 56.010213,
    longitude: 92.848411,
  },
  {
    name: 'Купеческий квартал на пр. Мира',
    desc: 'Каменное и деревянное зодчество исторического центра.',
    address: 'пр. Мира',
    locationSlug: 'krasnoyarsk-kupecheskiy-kvartal-mira',
    mustSeeFilter: 'street',
    visitMinutes: 60,
    latitude: 56.012511,
    longitude: 92.868112,
  },
  {
    name: 'Визит-центр «Столбы» (Лалетино)',
    desc: 'Стартовая точка маршрутов: карты, экскурсии и сувениры.',
    address: 'ул. Свердловская (визит-центр Лалетино)',
    locationSlug: 'krasnoyarsk-stolby-vizit-tsentr',
    mustSeeFilter: 'museum',
    visitMinutes: 30,
    latitude: 55.955612,
    longitude: 92.788912,
  },

  // --- Architecture ---
  {
    name: 'Покровский кафедральный собор',
    desc: 'Сибирское барокко - старейшее каменное здание города.',
    address: 'ул. Сурикова, 26',
    locationSlug: 'krasnoyarsk-pokrovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 56.014112,
    longitude: 92.871112,
  },
  {
    name: 'Благовещенский собор',
    desc: 'Краснокирпичный духовный комплекс XIX века у Стрелки.',
    address: 'ул. 9 Января, 30',
    locationSlug: 'krasnoyarsk-blagoveschenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 56.016112,
    longitude: 92.891211,
  },
  {
    name: 'Музыкальный театр',
    desc: 'Советский модернизм на пр. Мира.',
    address: 'пр. Мира, 129',
    locationSlug: 'krasnoyarsk-muzykalnyy-teatr',
    mustSeeFilter: 'theatre',
    visitMinutes: 30,
    latitude: 56.011122,
    longitude: 92.839711,
  },
  {
    name: 'Электротехзавод (Гостиный двор)',
    desc: 'Классицизм XIX века на Карла Маркса.',
    address: 'ул. Карла Маркса, 96',
    locationSlug: 'krasnoyarsk-elektrotehzavod-gostinyy-dvor',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.010511,
    longitude: 92.868112,
  },
  {
    name: 'Дом офицеров',
    desc: 'Бывшее Общественное собрание на Перенсона.',
    address: 'ул. Перенсона, 20',
    locationSlug: 'krasnoyarsk-dom-ofitserov',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.011811,
    longitude: 92.865112,
  },
  {
    name: 'Драмтеатр им. Пушкина',
    desc: 'Историческое здание с колоннадой на пр. Мира.',
    address: 'пр. Мира, 73',
    locationSlug: 'krasnoyarsk-dramteatr-pushkina',
    mustSeeFilter: 'theatre',
    visitMinutes: 25,
    latitude: 56.012511,
    longitude: 92.862112,
  },
  {
    name: 'Вокзал Красноярск-Пассажирский',
    desc: 'Шпиль со львом - ворота Транссиба.',
    address: 'ул. 30 Июля, 1',
    locationSlug: 'krasnoyarsk-vokzal-passazhirskiy',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 56.011511,
    longitude: 92.829112,
  },
  {
    name: 'Успенский монастырь',
    desc: 'Монастырский комплекс на окраине у Енисея.',
    address: 'ул. Удачная, 14',
    locationSlug: 'krasnoyarsk-uspenskiy-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 55.992511,
    longitude: 92.748112,
  },

  // --- Parks ---
  {
    name: 'Николаевская сопка',
    desc: 'Лесистый холм и биатлонный комплекс с видами на город.',
    address: 'ул. Биатлонная',
    locationSlug: 'krasnoyarsk-nikolaevskaya-sopka',
    mustSeeFilter: 'park',
    visitMinutes: 75,
    latitude: 56.012411,
    longitude: 92.758311,
  },
  {
    name: 'Экопарк «Гремячая грива»',
    desc: 'Тропы, смотровые и экомаршруты у западной окраины.',
    address: 'ул. Елены Стасовой, 50',
    locationSlug: 'krasnoyarsk-ekopark-gremyachaya-griva',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 56.019122,
    longitude: 92.748311,
  },
  {
    name: 'Ярыгинская набережная',
    desc: 'Правобережный променад с Чеховым и видами на левый берег.',
    address: 'ул. Гладкова',
    locationSlug: 'krasnoyarsk-yaryginskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 55.994112,
    longitude: 92.871211,
  },
  {
    name: 'Парк флоры и фауны «Роев ручей»',
    desc: 'Крупный зоопарк у подножия Столбов.',
    address: 'ул. Свердловская, 293',
    locationSlug: 'krasnoyarsk-roev-ruchey',
    mustSeeFilter: 'park',
    visitMinutes: 120,
    latitude: 55.931211,
    longitude: 92.723311,
  },
  {
    name: 'Торгашинский хребет',
    desc: 'Гребень скал и троп напротив Столбов.',
    address: 'ул. Базайская',
    locationSlug: 'krasnoyarsk-torgashinskiy-hrebet',
    mustSeeFilter: 'park',
    visitMinutes: 120,
    latitude: 55.952122,
    longitude: 92.833311,
  },
  {
    name: 'Центральный парк им. Горького',
    desc: 'Детская железная дорога и старый городской парк.',
    address: 'ул. Карла Маркса, 151',
    locationSlug: 'krasnoyarsk-tsentralnyy-park-gorkogo',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 56.009112,
    longitude: 92.853311,
  },

  // --- Culture / gastro ---
  {
    name: 'Ресторан «0.75 Please»',
    desc: 'Новая сибирская кухня в кирпичном подвале на пр. Мира.',
    address: 'пр. Мира, 86',
    locationSlug: 'krasnoyarsk-restoran-075-please',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 56.012511,
    longitude: 92.867211,
  },
  {
    name: 'Краевая филармония (БКЗ)',
    desc: 'Модернистский концертный комплекс на Стрелке.',
    address: 'площадь Мира, 2б',
    locationSlug: 'krasnoyarsk-filarmoniya-bkz',
    mustSeeFilter: 'theatre',
    visitMinutes: 30,
    latitude: 56.016712,
    longitude: 92.896712,
  },
  {
    name: 'Арт-резиденция «Каменка»',
    desc: 'Креативное пространство и события на правом берегу.',
    address: 'ул. Павлова, 21',
    locationSlug: 'krasnoyarsk-art-rezidentsiya-kamenka',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.978111,
    longitude: 92.911712,
  },
];

export const KRASNOYARSK_SUBURBS: any[] = [
  {
    name: 'Дивногорск и Красноярская ГЭС',
    desc: 'Город у плотины: набережная, Царь-рыба, Овсянка Астафьева и смотровые ГЭС.',
    locationSlug: 'krasnoyarsk-divnogorsk-ges',
    mustSeeFilter: 'main',
    visitMinutes: '6-8 ч',
    latitude: 55.957211,
    longitude: 92.368311,
    address: 'г. Дивногорск, Красноярская ГЭС',
    travelVector: '«Ласточка» / автобус ~50 мин',
    travelVectorBlurb:
      'Закладывайте на «Ласточку» или автобус около 50 минут, чтобы приехать к 10 утра.',
    timingNote:
      'Сначала набережная и Царь-рыба, затем Овсянка; смотровая ГЭС и судоподъемник - напоследок.',
    places: [
      {
        name: 'Дивногорская набережная',
        desc: 'Променад вдоль Енисея с видами на скалы.',
        locationSlug: 'krasnoyarsk-divnogorskaya-naberezhnaya',
        visitMinutes: 40,
      },
      {
        name: 'Царь-рыба / Слизнево',
        desc: 'Скульптура осетра на утесе у трассы Р-257.',
        locationSlug: 'krasnoyarsk-tsar-ryba-sliznevo',
        visitMinutes: 25,
      },
      {
        name: 'Овсянка, музей Астафьева',
        desc: 'Дом-музей писателя в родном селе.',
        locationSlug: 'krasnoyarsk-ovsyanka-muzey-astafeva',
        visitMinutes: 50,
      },
      {
        name: 'Административная площадь',
        desc: 'Центральная площадь Дивногорска.',
        locationSlug: 'krasnoyarsk-administrativnaya-ploschad',
        visitMinutes: 20,
      },
      {
        name: 'Знаменский скит',
        desc: 'Монастырский скит в скалах над Енисеем.',
        locationSlug: 'krasnoyarsk-znamenskiy-skit',
        visitMinutes: 40,
      },
      {
        name: 'Смотровая ГЭС',
        desc: 'Панорама плотины Красноярской ГЭС.',
        locationSlug: 'krasnoyarsk-smotrovaya-ges',
        visitMinutes: 35,
      },
      {
        name: 'Судоподъемник',
        desc: 'Уникальный судоподъемник для прохода судов через плотину.',
        locationSlug: 'krasnoyarsk-sudopodemnik',
        visitMinutes: 30,
      },
    ],
  },
  {
    name: 'Овсянка и Астафьев',
    desc: 'Литературный пригород на Енисее: родное село Астафьева, тихая набережная и понятный сибирский масштаб.',
    locationSlug: 'krasnoyarsk-ovsyanka-astafev',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 55.956112,
    longitude: 92.553112,
    address: 'с. Овсянка',
    travelVector: 'Электричка / авто ~45-60 мин',
    travelVectorBlurb: 'Удобный спокойный выезд, который можно делать отдельно от большой Дивногорской поездки.',
    timingNote: 'Сначала музей Астафьева, затем берег Енисея и прогулка по селу.',
    places: [
      { name: 'Дом-музей Виктора Астафьева', desc: 'Главное ядро маршрута и самый содержательный литературный stop.', locationSlug: 'krasnoyarsk-dom-muzey-viktora-astafeva', visitMinutes: 45 },
      { name: 'Набережная Овсянки', desc: 'Спокойный Енисей без городской суеты.', locationSlug: 'krasnoyarsk-naberezhnaya-ovsyanki', visitMinutes: 30 },
      { name: 'Сельская панорама', desc: 'Точка, где особенно хорошо читается масштаб берега и воды.', locationSlug: 'krasnoyarsk-selskaya-panorama', visitMinutes: 20 },
      { name: 'Мемориальный сад', desc: 'Тихое продолжение музейного маршрута.', locationSlug: 'krasnoyarsk-memorialnyy-sad', visitMinutes: 20 },
    ],
  },
  {
    name: 'Торгашинский хребет',
    desc: 'Быстрый природный выезд ради длинной лестницы, скал и сильных видов на Красноярск и долину Енисея.',
    locationSlug: 'krasnoyarsk-torgashinskiy-hrebet',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 55.987112,
    longitude: 92.910112,
    address: 'окраина Красноярска, район Торгашино',
    travelVector: 'Такси / авто ~25-35 мин',
    travelVectorBlurb: 'Лучше ехать в ясную сухую погоду и оставлять силы на обратный спуск.',
    timingNote: 'Маршрут держится на лестнице, видовом гребне и нескольких смотровых точках.',
    places: [
      { name: 'Торгашинская лестница', desc: 'Главный вход в маршрут и уже сама по себе городская достопримечательность.', locationSlug: 'krasnoyarsk-torgashinskaya-lestnitsa', visitMinutes: 45 },
      { name: 'Смотровая на город', desc: 'Лучший городской кадр без Столбов и без долгой логистики.', locationSlug: 'krasnoyarsk-smotrovaya-na-gorod', visitMinutes: 30 },
      { name: 'Скальные выходы хребта', desc: 'Пейзажная часть маршрута выше городской кромки.', locationSlug: 'krasnoyarsk-skalnye-vyhody-hrebta', visitMinutes: 40 },
      { name: 'Лесная тропа по гребню', desc: 'Неспешный хайкинг без музеев и лишних поводов торопиться.', locationSlug: 'krasnoyarsk-lesnaya-tropa-po-grebnyu', visitMinutes: 45 },
    ],
  },
];

export const KRASNOYARSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'krasnoyarsk-imperiya-eniseya',
    title: 'Империя Енисея',
    description:
      'Часовня на Караульной, купеческий пр. Мира, сибирский обед, Стрелка и вантовый мост на Татышев.',
    travelVector: 'Центр, Стрелка и остров',
    timingNote: 'Около 7-8 часов; от Стрелки на Татышев - пешком по Виноградовскому мосту.',
    stops: [
      {
        name: 'Караульная гора и часовня Параскевы Пятницы',
        desc: 'Старт со смотровой и символа на 10-рублевой купюре.',
        locationSlug: 'krasnoyarsk-karaul-naya-gora-i-chasovnya-paraskevy-pyatnitsy',
        mustSeeFilter: 'views',
        visitMinutes: 45,
        address: 'ул. Степана Разина, 51а',
        latitude: 56.024311,
        longitude: 92.868311,
      },
      {
        name: 'Купеческий квартал на пр. Мира',
        desc: 'Каменное зодчество и витрины исторического центра.',
        locationSlug: 'krasnoyarsk-kupecheskiy-kvartal-mira',
        mustSeeFilter: 'street',
        visitMinutes: 60,
        address: 'пр. Мира',
        latitude: 56.012511,
        longitude: 92.868112,
      },
      {
        name: 'Ресторан «0.75 Please»',
        desc: 'Обед новой сибирской кухни в подвале на Мира.',
        locationSlug: 'krasnoyarsk-restoran-075-please',
        mustSeeFilter: 'gastro',
        visitMinutes: 75,
        address: 'пр. Мира, 86',
        latitude: 56.012511,
        longitude: 92.867211,
      },
      {
        name: 'Стрелка и памятник Дубенскому',
        desc: 'Слияние Качи и Енисея у БКЗ - точка с dayRoute для Стрелки.',
        dayRouteId: 'krasnoyarsk-green-dubenskiy-strelka',
        mustSeeFilter: 'monument',
        visitMinutes: 30,
        latitude: 56.016211,
        longitude: 92.894112,
        transitTip: 'Переход к Стрелке / площади Мира',
      },
      {
        name: 'Виноградовский пешеходный мост',
        desc: 'Вантовый переход на остров с панорамой реки.',
        locationSlug: 'krasnoyarsk-peshehodnyy-most-na-ostrov-tatyshev',
        mustSeeFilter: 'views',
        visitMinutes: 30,
        latitude: 56.015912,
        longitude: 92.898211,
      },
      {
        name: 'Остров Татышев',
        desc: 'Финал на городском острове-парке посреди Енисея.',
        locationSlug: 'krasnoyarsk-ostrov-tatyshev',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        latitude: 56.028711,
        longitude: 92.930512,
      },
    ],
  },
  {
    id: 'krasnoyarsk-taezhnyy-hiking',
    title: 'Таежный хайкинг',
    description:
      'Столбы, Бобровый лог, Николаевская сопка, Гремячая грива и ужин в «Тунгуске».',
    travelVector: 'Тайга у города и сибирская кухня',
    timingNote: 'Около 8-9 часов; между точками удобен такси или автобус.',
    stops: [
      {
        name: 'Национальный парк «Красноярские Столбы»',
        desc: 'Утро на скалах-останцах у центрального входа.',
        locationSlug: 'krasnoyarsk-natsional-nyy-park-krasnoyarskie-stolby',
        mustSeeFilter: 'main',
        visitMinutes: 150,
        address: 'ул. Свердловская, 273',
        latitude: 55.915012,
        longitude: 92.735811,
      },
      {
        name: 'Фанпарк «Бобровый лог»',
        desc: 'Канатка и виды на Столбы после хайкинга.',
        locationSlug: 'krasnoyarsk-fanpark-bobrovyy-log',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        address: 'ул. Сибирская, 92',
        latitude: 55.961211,
        longitude: 92.784411,
        transitTip: 'Переезд к Бобровому логу',
      },
      {
        name: 'Николаевская сопка',
        desc: 'Лесной холм и биатлонный комплекс.',
        locationSlug: 'krasnoyarsk-nikolaevskaya-sopka',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'ул. Биатлонная',
        latitude: 56.012411,
        longitude: 92.758311,
        transitTip: 'Переезд к Николаевской сопке',
      },
      {
        name: 'Экопарк «Гремячая грива»',
        desc: 'Экотропы и смотровые на западной окраине.',
        locationSlug: 'krasnoyarsk-ekopark-gremyachaya-griva',
        mustSeeFilter: 'park',
        visitMinutes: 75,
        address: 'ул. Елены Стасовой, 50',
        latitude: 56.019122,
        longitude: 92.748311,
      },
      {
        name: 'Ресторан «Тунгуска»',
        desc: 'Финал сибирской кухней на Весны.',
        locationSlug: 'krasnoyarsk-restoran-tunguska',
        mustSeeFilter: 'gastro',
        visitMinutes: 90,
        address: 'ул. Весны, 30',
        latitude: 56.037211,
        longitude: 92.913311,
        transitTip: 'Переезд к «Тунгуске»',
      },
    ],
  },
  ...KRASNOYARSK_LINE_DAY_ROUTE_PRESETS,
];

export const KRASNOYARSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что Енисей в Красноярске никогда не замерзает зимой?',
    a: 'Да. Из-за Красноярской ГЭС (около 40 км выше по течению) вода в городе остается относительно теплой: Енисей не замерзает даже при -40 °C и парит густыми туманами.',
  },
  {
    q: 'Нужно ли специальное снаряжение или гид, чтобы посетить скалы «Красноярские Столбы»?',
    a: 'Для Центрального района (Дед, Перья, Слоник) снаряжение и гид не нужны: асфальт и деревянные эко-настилы с указателями. Подниматься на вершины скал без опыта не стоит, гулять вокруг безопасно.',
  },
  {
    q: 'Как работает знаменитая самая длинная лестница в России на Торгашинском хребте?',
    a: '1683 ступени от базы «Гренада» до вершины. Подъем бесплатный до 22:00, вечером включается светодиодная подсветка. Наверху есть зоны отдыха.',
  },
  {
    q: 'Из какого ресторана лучше начать знакомство с новой сибирской кухней?',
    a: 'Флагманы - «Тунгуска» (ул. Весны, 30) и «0.75 Please» (пр. Мира, 86). Столы лучше бронировать за 3-5 дней. Бюджетный старт - местные пельменные в центре.',
  },
];

export const KRASNOYARSK_TRAVEL =
  'Международный аэропорт Красноярск имени Дмитрия Хворостовского принимает прямые рейсы из Москвы (около 4,5 часов), Санкт-Петербурга и городов Сибири. Город - крупная станция Транссиба. Лучший сезон - лето и сентябрь для Столбов; зима - «Бобровый лог» и незамерзающий Енисей с парящими туманами из-за ГЭС.';
