/** Novosibirsk tourist hub pack (owner 2026-08-16). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { NOVOSIBIRSK_LINE_DAY_ROUTE_PRESETS } from './novosibirsk-line-presets.ts';

export const NOVOSIBIRSK_MUST_SEE: any[] = [
  // --- Core / main ---
  {
    name: 'НОВАТ (Театр оперы и балета)',
    desc: 'Главный театр Сибири под серебристым чешуйчатым куполом - крупнейшее театральное здание России.',
    address: 'Красный проспект, 36',
    venueSlug: 'novosibirsk-novosibirskiy-teatr-opery-i-baleta-novat',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 55.030214,
    longitude: 82.924841,
  },
  {
    name: 'Михайловская набережная',
    desc: 'Двухуровневый променад вдоль Оби с видом на Коммунальный и Бугринский мосты.',
    address: 'ул. Обская, 2',
    locationSlug: 'novosibirsk-mihaylovskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 60,
    latitude: 55.010214,
    longitude: 82.940115,
  },
  {
    name: 'Академгородок',
    desc: 'Научный анклав среди тайги: ручные белки, НГУ и технопарк «Гуси».',
    address: 'Академгородок',
    locationSlug: 'novosibirsk-akademgorodok',
    mustSeeFilter: 'main',
    visitMinutes: 180,
    latitude: 54.849202,
    longitude: 83.106209,
  },
  {
    name: 'Новосибирский зоопарк имени Р. А. Шило',
    desc: 'Один из крупнейших зоопарков России в сосновом бору, знаменит лиграми.',
    address: 'ул. Тимирязева, 71/1',
    locationSlug: 'novosibirsk-novosibirskiy-zoopark-imeni-r-a-shilo',
    mustSeeFilter: 'science',
    visitMinutes: 150,
    latitude: 55.053145,
    longitude: 82.884112,
  },
  {
    name: 'Новосибирский государственный художественный музей',
    desc: 'Русская классика и коллекция из 60 подлинных полотен Николая Рериха.',
    address: 'Красный проспект, 5',
    venueSlug: 'novosibirsk-novosibirskiy-hudozhestvennyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.018145,
    longitude: 82.924147,
  },
  {
    name: 'Музей мировой погребальной культуры',
    desc: 'Единственный в России музей смерти при крематории - траурные традиции разных веков.',
    address: 'пос. Восход, ул. Военторговская, 4/1',
    venueSlug: 'novosibirsk-muzey-mirovoy-pogrebal-noy-kul-tury',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 55.038415,
    longitude: 83.104112,
  },

  // --- Памятники и уличные арт-объекты (15) ---
  {
    name: 'Памятник Ленину и фигурам революции',
    desc: 'Монументальный бронзовый ансамбль на главной площади города.',
    address: 'Красный проспект, 36 (Площадь Ленина)',
    locationSlug: 'novosibirsk-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.030221,
    longitude: 82.920556,
  },
  {
    name: 'Памятник лабораторной мыши',
    desc: 'Мышь, вяжущая нить ДНК - благодарность ученых лабораторным животным в Академгородке.',
    address: 'ул. Академика Лаврентьева, 6/1',
    locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.849202,
    longitude: 83.106209,
  },
  {
    name: 'Памятник светофору',
    desc: 'Постовой у первого городского светофора - фирменная фототочка.',
    address: 'пересечение ул. Серебренниковской и Сибревкома',
    locationSlug: 'novosibirsk-pamyatnik-svetoforu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.023249,
    longitude: 82.925424,
  },
  {
    name: 'Скульптура «Вовка в Тридевятом царстве»',
    desc: 'Металлический мультгерой на троне у аллеи Экономического лицея.',
    address: 'ул. Крылова, 44',
    locationSlug: 'novosibirsk-vovka-v-tridevyatom-tsarstve',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.042312,
    longitude: 82.930411,
  },
  {
    name: 'Памятник трамваю №13',
    desc: 'Железный вагон-памятник самому аварийному и легендарному маршруту города.',
    address: 'ул. Мичурина, 2 (за Оперным театром)',
    locationSlug: 'novosibirsk-pamyatnik-tramvayu-13',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.031548,
    longitude: 82.924874,
  },
  {
    name: 'Памятник Высоцкому',
    desc: 'Бронзовый силуэт поэта с гитарой у театра «Глобус».',
    address: 'ул. Каменская, 1',
    locationSlug: 'novosibirsk-pamyatnik-vysotskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.026411,
    longitude: 82.930214,
  },
  {
    name: 'Арт-объект «Шпаргалка»',
    desc: 'Бетонная скамейка у НГУ, исписанная формулами и графиками.',
    address: 'ул. Коптюга, 4 (около НГУ)',
    locationSlug: 'novosibirsk-art-obekt-shpargalka',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.843622,
    longitude: 83.094511,
  },
  {
    name: 'Арка «Колокол мира»',
    desc: 'Белоснежная арка с колоколом - символ единения и мира.',
    address: 'ул. Коммунистическая, 38',
    locationSlug: 'novosibirsk-arka-kolokol-mira',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.023124,
    longitude: 82.920447,
  },
  {
    name: 'Памятник первому свиданию',
    desc: 'Влюбленная пара под часами - традиционное место встреч.',
    address: 'Красный проспект, 38',
    locationSlug: 'novosibirsk-pamyatnik-pervomu-svidaniyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.032115,
    longitude: 82.921245,
  },
  {
    name: 'Скульптурная композиция «Сцены из кукольных спектаклей»',
    desc: 'Сказочные башенки с бронзовыми персонажами у театра кукол.',
    address: 'ул. Ленина, 22',
    locationSlug: 'novosibirsk-stseny-iz-kukolnyh-spektakley',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.031201,
    longitude: 82.910245,
  },
  {
    name: 'Скульптура «Деловая женщина»',
    desc: 'Бизнес-леди за рабочим столом у офисного центра.',
    address: 'ул. Мичурина, 12б',
    locationSlug: 'novosibirsk-skulptura-delovaya-zhenschina',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.036541,
    longitude: 82.924115,
  },
  {
    name: 'Памятник швейной машинке «Зингер»',
    desc: 'Винтажная швейная техника перед фабрикой «Синар».',
    address: 'ул. Серебренниковская, 14',
    locationSlug: 'novosibirsk-pamyatnik-shveynoy-mashinke-zinger',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.022145,
    longitude: 82.926214,
  },
  {
    name: 'Памятник первому мосту через Обь',
    desc: 'Исторический пролет старого железнодорожного моста на набережной.',
    address: 'ул. Обская, 4',
    locationSlug: 'novosibirsk-pamyatnik-pervomu-mostu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 55.011245,
    longitude: 82.935147,
  },
  {
    name: 'Памятник архитектору Андрею Крячкову',
    desc: 'Зодчий конструктивизма и классики Новосибирска на площади Свердлова.',
    address: 'Площадь Свердлова',
    locationSlug: 'novosibirsk-pamyatnik-kryachkovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.018541,
    longitude: 82.922115,
  },
  {
    name: 'Памятник тосту «За здравие»',
    desc: 'Кованый трон из бутылок и рюмки - популярная фототочка.',
    address: 'ул. Каменская, 53',
    locationSlug: 'novosibirsk-pamyatnik-tostu-za-zdravie',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 55.038145,
    longitude: 82.931241,
  },

  // --- Историческое наследие (7) ---
  {
    name: 'Стоквартирный дом',
    desc: 'Шедевр постконструктивизма Крячкова - Гран-при Парижской выставки 1937 года.',
    address: 'Красный проспект, 16',
    locationSlug: 'novosibirsk-stokvartirnyy-dom',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.018142,
    longitude: 82.923145,
  },
  {
    name: 'Дом Ленина',
    desc: 'Здание на народные пожертвования, ныне - Филармония.',
    address: 'Красный проспект, 32',
    locationSlug: 'novosibirsk-dom-lenina',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.028451,
    longitude: 82.922145,
  },
  {
    name: 'Здание Городского торгового корпуса',
    desc: 'Модерн 1911 года - символ купеческого Ново-Николаевска, сегодня краеведческий музей.',
    address: 'Красный проспект, 23',
    locationSlug: 'novosibirsk-gorodskoy-torgovyy-korpus',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 55.029841,
    longitude: 82.920145,
  },
  {
    name: 'Особняк купца Крюкова',
    desc: 'Один из первых кирпичных жилых домов с нарядным фасадом.',
    address: 'ул. Советская, 25',
    locationSlug: 'novosibirsk-osobnyak-kryukova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.027145,
    longitude: 82.917412,
  },
  {
    name: 'Дом с часами',
    desc: 'Конструктивистский жилой дом галерейного типа - символ советского авангарда.',
    address: 'Красный проспект, 11',
    locationSlug: 'novosibirsk-dom-s-chasami',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 55.021145,
    longitude: 82.922415,
  },
  {
    name: 'Главпочтамт (Контора связи)',
    desc: 'Суровый конструктивизм с часами на углу главных пешеходных траекторий.',
    address: 'ул. Советская, 33',
    locationSlug: 'novosibirsk-glavpochtamt',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 55.030541,
    longitude: 82.918412,
  },
  {
    name: 'Железнодорожный вокзал «Новосибирск-Главный»',
    desc: 'Зеленый фасад в форме мчащегося на восток паровоза.',
    address: 'ул. Шамшурина, 43',
    locationSlug: 'novosibirsk-vokzal-novosibirsk-glavnyy',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 55.035142,
    longitude: 82.897415,
  },

  // --- Музеи (7) ---
  {
    name: 'Новосибирский государственный краеведческий музей',
    desc: 'История региона, скелет мамонта Матильда и шаманские артефакты.',
    address: 'Красный проспект, 23',
    venueSlug: 'novosibirsk-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 55.029854,
    longitude: 82.920214,
  },
  {
    name: 'Музей железнодорожной техники им. Н. А. Акулинина',
    desc: 'Паровозы, тепловозы и вагоны царских поездов под открытым небом.',
    address: 'ул. Шатурская, 2/2',
    locationSlug: 'novosibirsk-muzey-zheleznodorozhnoy-tehniki',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 54.851241,
    longitude: 83.056214,
  },
  {
    name: 'Музей «Сибирская береста»',
    desc: 'Ироничные и теплые арт-объекты из березовой коры.',
    address: 'ул. Свердлова, 21',
    locationSlug: 'novosibirsk-muzey-sibirskaya-beresta',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.019412,
    longitude: 82.918451,
  },
  {
    name: 'Музей солнца',
    desc: 'Маски и артефакты солярных культов народов мира.',
    address: 'ул. Дуси Ковальчук, 274',
    locationSlug: 'novosibirsk-muzey-solntsa',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 55.056541,
    longitude: 82.918114,
  },
  {
    name: 'Музей олимпийской славы',
    desc: 'Триумфы сибирских спортсменов - от Карелина до Подгорного.',
    address: 'ул. Советская, 33',
    locationSlug: 'novosibirsk-muzey-olimpiyskoy-slavy',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 55.030412,
    longitude: 82.918541,
  },

  // --- Храмы (6) ---
  {
    name: 'Собор во имя Александра Невского',
    desc: 'Краснокирпичный византийский храм - первое каменное здание города.',
    address: 'Красный проспект, 1а',
    locationSlug: 'novosibirsk-sobor-aleksandra-nevskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.016214,
    longitude: 82.924841,
  },
  {
    name: 'Вознесенский кафедральный собор',
    desc: 'Главный собор города с золотыми куполами.',
    address: 'ул. Советская, 91',
    locationSlug: 'novosibirsk-voznesenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 55.045412,
    longitude: 82.914115,
  },
  {
    name: 'Часовня во имя Святителя Николая Чудотворца',
    desc: 'Белоснежная часовня на Красном проспекте - бывший географический центр империи.',
    address: 'Красный проспект, 17а',
    locationSlug: 'novosibirsk-chasovnya-nikolaya',
    mustSeeFilter: 'temple',
    visitMinutes: 15,
    latitude: 55.025985,
    longitude: 82.921474,
  },
  {
    name: 'Храм Покрова Пресвятой Богородицы',
    desc: 'Старейшая деревянная церковь, уцелевшая в пожаре 1909 года.',
    address: 'ул. Октябрьская, 9',
    locationSlug: 'novosibirsk-hram-pokrova',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 55.021115,
    longitude: 82.916214,
  },
  {
    name: 'Католический Кафедральный собор Преображения Господня',
    desc: 'Неоготика из темного кирпича с модернистской крышей.',
    address: 'ул. Максима Горького, 100',
    locationSlug: 'novosibirsk-katolicheskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 55.028541,
    longitude: 82.928114,
  },
  {
    name: 'Новосибирская буддийская пагода (Дацан «Ринчин»)',
    desc: 'Буддийский храмовый комплекс с духом Бурятии в Сибири.',
    address: 'ул. Зеленая горка, 1/1а',
    locationSlug: 'novosibirsk-datsan-rinchin',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 54.881241,
    longitude: 83.071415,
  },

  // --- Парки и смотровые (оставшиеся) ---
  {
    name: 'Заельцовский парк',
    desc: 'Лесной эко-парк с вековыми соснами и детской железной дорогой.',
    address: 'ул. Парковая, 88',
    locationSlug: 'novosibirsk-zaeltsovskiy-park',
    mustSeeFilter: 'park',
    visitMinutes: 90,
    latitude: 55.051145,
    longitude: 82.843115,
  },
  {
    name: 'Центральный парк',
    desc: 'Старейший зеленый оазис со светомузыкальным фонтаном и летним театром.',
    address: 'ул. Мичурина, 8',
    locationSlug: 'novosibirsk-tsentralnyy-park',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 55.034142,
    longitude: 82.925412,
  },
  {
    name: 'Сквер Героев Революции',
    desc: 'Исторический сквер с факельной рукой, пробивающей мраморную скалу.',
    address: 'Красный проспект, 32в',
    locationSlug: 'novosibirsk-skver-geroev-revolyutsii',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 55.029141,
    longitude: 82.922115,
  },
  {
    name: 'Пляж «Звезда» и Обское море',
    desc: 'Песчаное побережье Новосибирского водохранилища с сосновым лесом.',
    address: 'Бердский тупик, 10',
    locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
    mustSeeFilter: 'park',
    visitMinutes: 120,
    latitude: 54.829145,
    longitude: 83.031142,
  },
  {
    name: 'Смотровая площадка у ТРЦ «Аура»',
    desc: 'Панорама на вантовый мост и огни вечернего центра.',
    address: 'ул. Вовоенная, 5',
    locationSlug: 'novosibirsk-smotrovaya-aura',
    mustSeeFilter: 'views',
    visitMinutes: 25,
    latitude: 55.026115,
    longitude: 82.937415,
  },

  // --- Гастрономия и театры (8) ---
  {
    name: 'Театр «Глобус»',
    desc: 'Модернистское здание-корабль молодежного театра.',
    address: 'ул. Каменская, 1',
    venueSlug: 'novosibirsk-teatr-globus',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 55.025145,
    longitude: 82.931214,
  },
  {
    name: 'Драматический театр «Красный факел»',
    desc: '«Сибирский МХАТ» в историческом здании Коммерческого собрания.',
    address: 'ул. Ленина, 19',
    venueSlug: 'novosibirsk-teatr-krasnyy-fakel',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 55.031145,
    longitude: 82.912415,
  },
  {
    name: 'Центр культуры и отдыха «Победа»',
    desc: 'Кинокомплекс в сталинском ампире с фестивальным кино.',
    address: 'ул. Ленина, 7',
    locationSlug: 'novosibirsk-tsentr-pobeda',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 55.030541,
    longitude: 82.916112,
  },
  {
    name: 'Ресторан «#СибирьСибирь»',
    desc: 'Новая сибирская кухня: строганина, пельмени с лосем и настойки.',
    address: 'ул. Ленина, 21',
    locationSlug: 'novosibirsk-restoran-sibir-sibir',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 55.031245,
    longitude: 82.911412,
  },
  {
    name: 'Гастрокорт на Центральном рынке',
    desc: 'Сотня корнеров кухонь мира и живая музыка по выходным.',
    address: 'ул. Мичурина, 12',
    locationSlug: 'novosibirsk-gastrokort-tsentralnyy-rynok',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 55.038412,
    longitude: 82.925145,
  },
  {
    name: 'Бар-хоппинг дворик на Ленина, 3',
    desc: 'Закрытый двор с крафтовыми барами и рюмочными.',
    address: 'ул. Ленина, 3 (внутренний двор)',
    locationSlug: 'novosibirsk-barnyy-dvorik-lenina-3',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 55.029985,
    longitude: 82.918114,
  },
  {
    name: 'Кафе-кондитерская «ИП Федосеев»',
    desc: 'Сибирские десерты, тарты и кедровый раф.',
    address: 'ул. Коммунистическая, 45',
    locationSlug: 'novosibirsk-kafe-ip-fedoseev',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 55.024412,
    longitude: 82.921145,
  },

  // --- Семейное (доп. к зоопарку) ---
  {
    name: 'Аквапарк Новосибирск',
    desc: 'Крупнейший крытый аквапарк страны (комплекс «Аквамир») с горками и волновым бассейном.',
    address: 'ул. Яринская, 8',
    locationSlug: 'novosibirsk-akvapark',
    mustSeeFilter: 'science',
    visitMinutes: 180,
    latitude: 55.042189,
    longitude: 82.903142,
  },
  {
    name: 'Парк чудес Галилео',
    desc: 'Интерактивный музей науки: опыты, иллюзии и зеркальный лабиринт.',
    address: 'ул. Добролюбова, 16А',
    locationSlug: 'novosibirsk-park-chudes-galileo',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 55.018942,
    longitude: 82.935124,
  },
  {
    name: 'Большой новосибирский планетарий',
    desc: 'Астрофизический центр с башней Фуко и звездным залом.',
    address: 'ул. Ключ-Камышенское Плато, 1/1',
    locationSlug: 'novosibirsk-bolshoy-planetariy',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 54.981242,
    longitude: 82.972145,
  },
  {
    name: 'Дельфиния',
    desc: 'Центр океанографии: акулы, экзотические рыбы и шоу с дельфинами.',
    address: 'ул. Жуковского, 100/4',
    locationSlug: 'novosibirsk-delfiniya',
    mustSeeFilter: 'science',
    visitMinutes: 90,
    latitude: 55.068214,
    longitude: 82.895123,
  },
];

export const NOVOSIBIRSK_SUBURBS: any[] = [
  {
    name: 'Академгородок',
    desc: 'Научный пригород среди тайги: НГУ, технопарк, ручные белки и Обское море.',
    address: 'Академгородок, Новосибирск',
    locationSlug: 'novosibirsk-akademgorodok',
    latitude: 54.849202,
    longitude: 83.106209,
    travelVector: 'Южный / Академгородок',
    travelVectorBlurb:
      'Электричка от «Новосибирск-Главный» до «Сеятель» или «Обское море» - дешевле и без пробок на Большевистской.',
    timingNote: 'Закладывайте полдня: мышь ДНК, «Шпаргалка», прогулка по Морской и закат у Обского моря.',
    places: [
      {
        name: 'Памятник лабораторной мыши',
        desc: 'Мышь, вяжущая ДНК - фотосимвол Академгородка.',
        locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
        latitude: 54.849202,
        longitude: 83.106209,
      },
      {
        name: 'Арт-объект «Шпаргалка»',
        desc: 'Скамейка с формулами у НГУ.',
        locationSlug: 'novosibirsk-art-obekt-shpargalka',
        latitude: 54.843622,
        longitude: 83.094511,
      },
      {
        name: 'Улица Морская',
        desc: 'Хай-тек и вековой лес в одном кадре.',
        dayRouteId: 'novosibirsk-suburb-ulitsa-morskaya',
        latitude: 54.8475,
        longitude: 83.0985,
      },
      {
        name: 'Пляж «Звезда» / Обское море',
        desc: 'Песчаный берег водохранилища - финал дня.',
        locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
        latitude: 54.829145,
        longitude: 83.031142,
        transitTip: 'Электричка или автобус к Обскому морю',
      },
    ],
  },
];

export const NOVOSIBIRSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'novosibirsk-classic-one-day',
    title: 'Классический Новосибирск за 1 день',
    description: 'НОВАТ, Красный проспект, набережная Оби и сибирская кухня.',
    stops: [
      {
        name: 'НОВАТ (Театр оперы и балета)',
        desc: 'Старт у купола',
        venueSlug: 'novosibirsk-novosibirskiy-teatr-opery-i-baleta-novat',
      },
      {
        name: 'Памятник Ленину и фигурам революции',
        desc: 'Площадь Ленина',
        locationSlug: 'novosibirsk-pamyatnik-leninu',
      },
      {
        name: 'Часовня во имя Святителя Николая Чудотворца',
        desc: 'Центр Красного проспекта',
        locationSlug: 'novosibirsk-chasovnya-nikolaya',
      },
      {
        name: 'Новосибирский государственный художественный музей',
        desc: 'Рерих и русская классика',
        venueSlug: 'novosibirsk-novosibirskiy-hudozhestvennyy-muzey',
      },
      {
        name: 'Ресторан «#СибирьСибирь»',
        desc: 'Обед сибирской кухни',
        locationSlug: 'novosibirsk-restoran-sibir-sibir',
      },
      {
        name: 'Михайловская набережная',
        desc: 'Закат над Обью',
        locationSlug: 'novosibirsk-mihaylovskaya-naberezhnaya',
      },
    ],
  },
  {
    id: 'novosibirsk-family-day',
    title: 'Новосибирск для всей семьи',
    description:
      'Зоопарк с лиграми, аквапарк, Галилео, планетарий и дельфинарий - главные точки с детьми.',
    timingNote: 'Не пытайтесь закрыть всё за день: выберите 2-3 точки и заложите трансферы.',
    stops: [
      {
        name: 'Новосибирский зоопарк имени Р. А. Шило',
        desc: 'Лигры и сосновый бор',
        locationSlug: 'novosibirsk-novosibirskiy-zoopark-imeni-r-a-shilo',
        address: 'ул. Тимирязева, 71/1',
        latitude: 55.053145,
        longitude: 82.884112,
        mustSeeFilter: 'science',
        visitMinutes: 150,
      },
      {
        name: 'Аквапарк Новосибирск',
        desc: 'Крытый комплекс «Аквамир»',
        locationSlug: 'novosibirsk-akvapark',
        address: 'ул. Яринская, 8',
        latitude: 55.042189,
        longitude: 82.903142,
        mustSeeFilter: 'science',
        visitMinutes: 180,
        transitTip: 'Переезд к аквапарку',
      },
      {
        name: 'Парк чудес Галилео',
        desc: 'Интерактивная наука',
        locationSlug: 'novosibirsk-park-chudes-galileo',
        address: 'ул. Добролюбова, 16А',
        latitude: 55.018942,
        longitude: 82.935124,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к Галилео',
      },
      {
        name: 'Большой новосибирский планетарий',
        desc: 'Звездный зал и башня Фуко',
        locationSlug: 'novosibirsk-bolshoy-planetariy',
        address: 'ул. Ключ-Камышенское Плато, 1/1',
        latitude: 54.981242,
        longitude: 82.972145,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к планетарию',
      },
      {
        name: 'Дельфиния',
        desc: 'Шоу с дельфинами',
        locationSlug: 'novosibirsk-delfiniya',
        address: 'ул. Жуковского, 100/4',
        latitude: 55.068214,
        longitude: 82.895123,
        mustSeeFilter: 'science',
        visitMinutes: 90,
        transitTip: 'Переезд к Дельфинии',
      },
    ],
  },
  {
    id: 'novosibirsk-akadem-day',
    title: 'День в Академгородке',
    description: 'Научный пригород: мышь ДНК, «Шпаргалка», Морская и Обское море.',
    travelVectorBlurb:
      'Электричка до «Сеятель» или «Обское море» - около 40 ₽ и без пробок на Большевистской.',
    stops: [
      { name: 'Академгородок', desc: 'Въезд', locationSlug: 'novosibirsk-akademgorodok' },
      {
        name: 'Памятник лабораторной мыши',
        desc: 'Фотосимвол',
        locationSlug: 'novosibirsk-pamyatnik-laboratornoy-myshi',
      },
      {
        name: 'Арт-объект «Шпаргалка»',
        desc: 'У НГУ',
        locationSlug: 'novosibirsk-art-obekt-shpargalka',
      },
      {
        name: 'Пляж «Звезда» и Обское море',
        desc: 'Финал у воды',
        locationSlug: 'novosibirsk-plyazh-zvezda-obskoe-more',
      },
    ],
  },
  ...NOVOSIBIRSK_LINE_DAY_ROUTE_PRESETS,
];

export const NOVOSIBIRSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что Новосибирский театр оперы и балета - самый большой в России?',
    a: 'Да, здание НОВАТ - крупнейший театральный комплекс страны: под его куполом мог бы поместиться московский Большой театр вместе с площадью.',
  },
  {
    q: 'Как добраться из центра до Академгородка без такси?',
    a: 'Пригородная электричка от вокзала «Новосибирск-Главный» до станций «Сеятель» или «Обское море» - самый дешевый и быстрый способ обойти пробки на Большевистской. Альтернатива - маршрутка №35 от метро «Речной вокзал».',
  },
  {
    q: 'Чем знаменит Новосибирский зоопарк имени Р. А. Шило?',
    a: 'Это один из крупнейших зоопарков России в сосновом бору. Его визитная карточка - успешное разведение редких кошачьих, включая лигров.',
  },
  {
    q: 'Где бесплатно посмотреть панораму Оби?',
    a: 'С верхней террасы Михайловской набережной у памятника Александру III на закате открывается вид на Коммунальный и Бугринский мосты - без платных смотровых в отелях.',
  },
];

export const NOVOSIBIRSK_TRAVEL =
  'Крупнейший за Уралом аэропорт Толмачёво имени А. И. Покрышкина принимает ежедневные рейсы из Москвы (около 4 часов), Санкт-Петербурга и городов СНГ. Новосибирск - ключевой узел Транссиба с вокзалом «Новосибирск-Главный». Лучшее окно для визита - лето (июнь-август): набережная, Академгородок и Обское море. Зима морозная и снежная - время для НОВАТ, катка и крытого аквапарка.';
