/** Omsk tourist hub pack (owner 2026-08-17). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { OMSK_LINE_DAY_ROUTE_PRESETS } from './omsk-line-presets.ts';

export const OMSK_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник «Слесарь Степаныч»',
    desc: 'Сантехник выглядывает из люка на Любинском - неофициальный символ Омска.',
    address: 'ул. Ленина, 14',
    locationSlug: 'omsk-pamyatnik-slesar-stepanych',
    mustSeeFilter: 'main',
    visitMinutes: 10,
    latitude: 54.984112,
    longitude: 73.371901,
  },
  {
    name: 'Скульптура «Любочка»',
    desc: 'Бронзовая девушка с зонтиком у купеческих витрин - место встреч на Любинском.',
    address: 'ул. Ленина, 7',
    locationSlug: 'omsk-pamyatnik-lyubochka',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.983912,
    longitude: 73.373112,
  },
  {
    name: 'Памятник Достоевскому «Несущий крест»',
    desc: 'Писатель с каторжным крестом у Тарских ворот, через которые его вели в острог.',
    address: 'ул. Спартаковская, 3 / Тарские ворота',
    locationSlug: 'omsk-pamyatnik-dostoevskomu-nesuschiy-krest',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.986912,
    longitude: 73.366112,
  },
  {
    name: 'Дон Кихот из металлолома',
    desc: 'Рыцарь печального образа собран из заводского лома - ирония индустриального Омска.',
    address: 'ул. Карла Маркса, 4В',
    locationSlug: 'omsk-pamyatnik-don-kihot',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.978912,
    longitude: 73.379112,
  },
  {
    name: 'Памятник городовому',
    desc: 'Дореволюционный страж порядка на Любинском, удобная точка для фото с фуражкой.',
    address: 'ул. Ленина, 21',
    locationSlug: 'omsk-pamyatnik-gorodovomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.984912,
    longitude: 73.372312,
  },
  {
    name: 'Памятник адмиралу Колчаку',
    desc: 'Бронзовый портрет Верховного правителя у особняка Батюшкина на Иртыше.',
    address: 'Иртышская набережная, 9',
    locationSlug: 'omsk-pamyatnik-kolchaku',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.976112,
    longitude: 73.371112,
  },
  {
    name: 'Скульптура Ван Гога',
    desc: 'Художник с отрезанным ухом во дворе Камергерского - омский привет европейскому авангарду.',
    address: 'ул. Ленина, 14/1',
    locationSlug: 'omsk-pamyatnik-van-gogu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.984312,
    longitude: 73.371412,
  },
  {
    name: 'Скульптура «Книга любви»',
    desc: 'Раскрытый бронзовый том на Иртышской набережной - место для записок и фото на закате.',
    address: 'Иртышская набережная, 34',
    locationSlug: 'omsk-pamyatnik-kniga-lyubvi',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.954912,
    longitude: 73.385891,
  },
  {
    name: 'Памятник Петру и Февронии',
    desc: 'Святые покровители семьи у Никольского казачьего собора.',
    address: 'ул. Ленина, 27',
    locationSlug: 'omsk-pamyatnik-petru-i-fevronii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.988912,
    longitude: 73.368112,
  },
  {
    name: 'Памятник борцам революции',
    desc: 'Монумент на площади Борцов Революции - советский акцент рядом с купеческим центром.',
    address: 'площадь Борцов Революции',
    locationSlug: 'omsk-pamyatnik-bortsam-revolyutsii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.981112,
    longitude: 73.376912,
  },
  {
    name: 'Скульптура «Марафонец»',
    desc: 'Бегун на Тухачевской набережной - напоминание о Сибирском международном марафоне.',
    address: 'набережная Тухачевского, 1',
    locationSlug: 'omsk-pamyatnik-maratonets',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.983112,
    longitude: 73.361112,
  },
  {
    name: 'Закладной камень храма Сергия Радонежского',
    desc: 'Памятный знак на месте первой церкви Омской крепости 1716 года у Тарских ворот. Храм освятили во имя преподобного Сергия - небесного покровителя основанного здесь города.',
    address: 'ул. Спартаковская, 1',
    locationSlug: 'omsk-zakladnoy-kamen-hrama-sergiya-radonezhskogo',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.986412,
    longitude: 73.365891,
  },
  {
    name: 'Скульптура оленя',
    desc: 'Бронзовый олень у дисциплинарных казарм крепости - тихая фототочка в стороне от Любинского.',
    address: 'ул. Партизанская, 5А',
    locationSlug: 'omsk-pamyatnik-olenyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.984912,
    longitude: 73.363112,
  },
  {
    name: 'Памятник Чокану Валиханову',
    desc: 'Казахский просветитель на улице своего имени, рядом с пешеходными кристаллами-киосками.',
    address: 'ул. Валиханова, 11',
    locationSlug: 'omsk-pamyatnik-valihanovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.973912,
    longitude: 73.381112,
  },
  {
    name: 'Памятник Ленину на Ленинской площади',
    desc: 'Классический монумент у театра драмы - парадная точка советского центра.',
    address: 'ул. Ленина, 8А',
    locationSlug: 'omsk-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.985112,
    longitude: 73.373912,
  },

  // --- Историческое наследие (1-12) ---
  {
    name: 'Любинский проспект (улица Ленина)',
    desc: 'Цельный купеческий ансамбль конца XIX века: лучшая пешеходная ось Омска.',
    address: 'ул. Ленина, 10-22',
    locationSlug: 'omsk-lyubinskiy-prospekt-ulitsa-lenina',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 54.98441,
    longitude: 73.37221,
  },
  {
    name: 'Тобольские ворота',
    desc: 'Западный портал крепости XVIII века. Через них каторжан вели в острог.',
    address: 'ул. Партизанская, 5/1',
    locationSlug: 'omsk-tobolskie-vorota',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.98561,
    longitude: 73.36311,
  },
  {
    name: 'Управление Западно-Сибирской железной дороги',
    desc: 'Монументальный железнодорожный штаб на Карла Маркса - символ Транссиба в городе.',
    address: 'ул. Карла Маркса, 35',
    locationSlug: 'omsk-upravlenie-zheleznoy-dorogi',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.97281,
    longitude: 73.38521,
  },
  {
    name: 'Омский академический театр драмы',
    desc: 'Один из старейших театров Сибири на Ленинской площади.',
    address: 'ул. Ленина, 8А',
    venueSlug: 'omsk-teatr-dramy',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 54.985112,
    longitude: 73.373912,
  },
  {
    name: 'Особняк Батюшкина (дом Колчака)',
    desc: 'Особняк на Иртыше, где жил адмирал Колчак в годы Белой столицы.',
    address: 'Иртышская набережная, 9',
    locationSlug: 'omsk-osobnyak-batyushkina',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 54.976112,
    longitude: 73.371112,
  },
  {
    name: 'Тарские ворота',
    desc: 'Каменный портал XVIII века, вход в каторжный острог и визуальный маркер старого Омска. Загадывают желание под аркой.',
    address: 'ул. Спартаковская',
    locationSlug: 'omsk-tarskie-vorota',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 54.986912,
    longitude: 73.366112,
  },
  {
    name: 'Московские торговые ряды',
    desc: 'Купеческий пассаж на Любинском с аркадами и витринами начала XX века.',
    address: 'ул. Ленина, 14',
    locationSlug: 'omsk-moskovskie-torgovye-ryady',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 54.984112,
    longitude: 73.371901,
  },
  {
    name: 'Сибирский кадетский корпус',
    desc: 'Военное училище на Ленина: строгий классицизм и история сибирского офицерства.',
    address: 'ул. Ленина, 26',
    locationSlug: 'omsk-kadetskiy-korpus',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.98821,
    longitude: 73.36851,
  },
  {
    name: 'Казенная палата (казначейство)',
    desc: 'Казенный двор на крепостной линии - сосед Тобольских ворот.',
    address: 'ул. Партизанская, 5С',
    locationSlug: 'omsk-kaznacheystvo',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.98531,
    longitude: 73.36382,
  },
  {
    name: 'Судебный дом (правительство области)',
    desc: 'Дореволюционное судебное здание на Красном Пути, сегодня областная администрация.',
    address: 'ул. Красный Путь, 1',
    locationSlug: 'omsk-sudebnyy-dom',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.98221,
    longitude: 73.37741,
  },
  {
    name: 'Особняк Шаниной',
    desc: 'Купеческий особняк на Любинском с богатой лепниной и витринным первым этажом.',
    address: 'ул. Ленина, 5',
    locationSlug: 'omsk-osobnyak-shaninoy',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.98371,
    longitude: 73.37351,
  },
  {
    name: 'Дисциплинарные казармы',
    desc: 'Крепостные казармы у оленя и Тобольских ворот - слой острожной истории.',
    address: 'ул. Партизанская, 5А',
    locationSlug: 'omsk-distsiplinarnye-kazarma',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.984912,
    longitude: 73.363112,
  },

  // --- Музеи (13-21) ---
  {
    name: 'Музей изобразительных искусств имени Врубеля',
    desc: 'Главная художественная коллекция Сибири и касса билетов в Эрмитаж-Сибирь.',
    address: 'ул. Ленина, 3',
    venueSlug: 'omsk-muzey-izobrazitelnyh-iskusstv-vrubelya',
    mustSeeFilter: 'museum',
    visitMinutes: 70,
    latitude: 54.98351,
    longitude: 73.37421,
  },
  {
    name: 'Омский историко-краеведческий музей',
    desc: 'История Прииртышья: от крепости и каторги до Белой столицы и советского Омска.',
    address: 'ул. Ленина, 23А',
    venueSlug: 'omsk-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 54.98541,
    longitude: 73.37121,
  },
  {
    name: 'Литературный музей Ф. М. Достоевского',
    desc: 'Дом на улице Достоевского о четырех годах каторги и «Записках из Мертвого дома».',
    address: 'ул. Достоевского, 1',
    venueSlug: 'omsk-literaturnyy-muzey-dostoevskogo',
    mustSeeFilter: 'literature',
    visitMinutes: 50,
    latitude: 54.98741,
    longitude: 73.36421,
  },
  {
    name: 'Исторический парк «Россия - моя история»',
    desc: 'Мультимедиа-экспозиция на 70 лет Октября: удобно в дождь и с детьми.',
    address: 'ул. 70 лет Октября, 25/2',
    venueSlug: 'omsk-moya-istoriya',
    mustSeeFilter: 'museum',
    visitMinutes: 70,
    latitude: 54.98121,
    longitude: 73.40112,
  },
  {
    name: 'Музей просвещения',
    desc: 'Школьная и университетская история Омска в тихом здании на Музейной.',
    address: 'ул. Музейная, 3',
    venueSlug: 'omsk-muzey-prosvescheniya',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 54.98931,
    longitude: 73.36721,
  },
  {
    name: 'Дом-музей Кондратия Белова',
    desc: 'Мастерская сибирского пейзажиста на Валиханова - камерный зал после кристаллов бульвара.',
    address: 'ул. Валиханова, 10',
    venueSlug: 'omsk-muzey-kondratiya-belova',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 54.97371,
    longitude: 73.38141,
  },
  {
    name: 'Музей воинской славы омичей',
    desc: 'Фронтовая и тыловая история города в здании на Таубе.',
    address: 'ул. Таубе, 5',
    venueSlug: 'omsk-muzey-voinskoy-slavy',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 54.97821,
    longitude: 73.36912,
  },
  {
    name: 'Эрмитаж-Сибирь',
    desc: 'Филиал Государственного Эрмитажа. Билеты берут на сайте музея Врубеля, залы открыты со вторника.',
    address: 'ул. Музейная, 4',
    venueSlug: 'omsk-ermitazh-sibir',
    mustSeeFilter: 'museum',
    visitMinutes: 70,
    latitude: 54.98951,
    longitude: 73.36782,
  },
  {
    name: 'Музей театрального искусства',
    desc: 'Костюмы, афиши и закулисье омской сцены в здании театра драмы.',
    address: 'ул. Ленина, 8А',
    venueSlug: 'omsk-muzey-teatralnogo-iskusstva',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 54.98521,
    longitude: 73.37371,
  },

  // --- Храмы (22-30) ---
  {
    name: 'Успенский кафедральный собор',
    desc: 'Пятиглавый храм на Соборной площади, главная святыня Омска.',
    address: 'ул. Тарская, 7',
    locationSlug: 'omsk-uspenskiy-kafedral-nyy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 54.98921,
    longitude: 73.36951,
  },
  {
    name: 'Воскресенский военный собор',
    desc: 'Первый каменный храм крепости в сибирском барокко у Тобольских ворот.',
    address: 'ул. Партизанская, 16',
    locationSlug: 'omsk-voskresenskiy-voennyy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 54.98621,
    longitude: 73.36241,
  },
  {
    name: 'Часовня Серафима Саровского и царевича Алексея',
    desc: 'Небольшая часовня у начала Любинского - удобная пауза перед проспектом.',
    address: 'ул. Ленина, 1А',
    locationSlug: 'omsk-chasovnya-serafima-i-alekseya',
    mustSeeFilter: 'temple',
    visitMinutes: 10,
    latitude: 54.98291,
    longitude: 73.37451,
  },
  {
    name: 'Никольский казачий собор',
    desc: 'Казачий храм с памятником Петру и Февронии во дворе.',
    address: 'ул. Ленина, 27',
    locationSlug: 'omsk-nikolskiy-kazachiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.988912,
    longitude: 73.368112,
  },
  {
    name: 'Сибирская соборная мечеть',
    desc: 'Главная мечеть Омска на 20-й Линии - восточный силуэт за купеческим центром.',
    address: '20-я Линия, 102',
    locationSlug: 'omsk-sibirskaya-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.96821,
    longitude: 73.40112,
  },
  {
    name: 'Крестовоздвиженский собор',
    desc: 'Тихий храм на Тарской в стороне от Соборной площади.',
    address: 'ул. Тарская, 33',
    locationSlug: 'omsk-krestovozdvizhenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.99112,
    longitude: 73.36621,
  },
  {
    name: 'Лютеранская кирха',
    desc: 'Неоготическая кирха на Рождественского - редкий протестантский акцент Сибири.',
    address: 'ул. Рождественского, 2/1',
    locationSlug: 'omsk-lyuteranskaya-kirha',
    mustSeeFilter: 'temple',
    visitMinutes: 15,
    latitude: 54.97912,
    longitude: 73.37721,
  },
  {
    name: 'Храм Иоанна Крестителя',
    desc: 'Приходской храм на Красном Пути, удобен после прогулки к Пятому театру.',
    address: 'ул. Красный Путь, 53',
    locationSlug: 'omsk-hram-ioanna-krestitelya',
    mustSeeFilter: 'temple',
    visitMinutes: 15,
    latitude: 54.99221,
    longitude: 73.36981,
  },
  {
    name: 'Католический храм Сретения Господня',
    desc: 'Костел на Звездова - еще один европейский штрих многоконфессионального Омска.',
    address: 'ул. Звездова, 62',
    locationSlug: 'omsk-katolicheskiy-hram-sretenie',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.97521,
    longitude: 73.39211,
  },

  // --- Парки и виды (31-39) ---
  {
    name: 'Омская крепость',
    desc: 'Историко-культурный комплекс основания города: ворота, казармы и каток зимой.',
    address: 'ул. Партизанская, 5',
    locationSlug: 'omsk-omskaya-krepost',
    mustSeeFilter: 'park',
    visitMinutes: 50,
    latitude: 54.98551,
    longitude: 73.36351,
  },
  {
    name: 'Парк культуры им. 30-летия ВЛКСМ',
    desc: 'Большой городской парк на Масленникова: аттракционы, аллеи и тень в жаркий день.',
    address: 'ул. Масленникова, 136',
    locationSlug: 'omsk-park-30-letiya-vlksm',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 54.96921,
    longitude: 73.38621,
  },
  {
    name: 'Пешеходная улица Чокана Валиханова',
    desc: 'Бульвар со стеклянными кристаллами-киосками и вечерней подсветкой.',
    address: 'ул. Чокана Валиханова',
    locationSlug: 'omsk-ulitsa-chokana-valihanova',
    mustSeeFilter: 'street',
    visitMinutes: 30,
    latitude: 54.97451,
    longitude: 73.38121,
  },
  {
    name: 'Смотровая у речного вокзала',
    desc: 'Бесплатный закат на Иртыш, яхты у причала и старт прогулки на Любинский.',
    address: 'ул. Лермонтова, 2',
    locationSlug: 'omsk-rechnoy-vokzal',
    mustSeeFilter: 'views',
    visitMinutes: 25,
    latitude: 54.98121,
    longitude: 73.37521,
  },
  {
    name: 'Парк имени Королева',
    desc: 'Газоны и длинный свет летних вечеров - место пикников в жаркий сезон.',
    address: 'парк имени Королева',
    locationSlug: 'omsk-park-koroleva',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 54.98821,
    longitude: 73.35211,
  },
  {
    name: 'Природный парк «Птичья гавань»',
    desc: 'Городской природный парк на Енисейской: птицы, тропы и тишина в черте Омска.',
    address: 'ул. Енисейская, 1/2',
    locationSlug: 'omsk-ptichya-gavan',
    mustSeeFilter: 'park',
    visitMinutes: 50,
    latitude: 54.96812,
    longitude: 73.35121,
  },
  {
    name: 'Выставочная площадь «Флора»',
    desc: 'Площадки цветочной выставки к Дню города в первую неделю августа.',
    address: 'выставочная площадь «Флора»',
    locationSlug: 'omsk-vystavochnaya-ploschad-flora',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 54.98721,
    longitude: 73.36521,
  },
  {
    name: 'Терраса Музыкального театра',
    desc: 'Камергерские террасы у театра: вечерний свет и вид на купеческий квартал.',
    address: 'ул. Думская, 2',
    locationSlug: 'omsk-terrasa-muzykalnogo-teatra',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 54.98461,
    longitude: 73.37021,
  },
  {
    name: 'Советский парк',
    desc: 'Зеленый массив на Андрианова - спокойная альтернатива центру в жару.',
    address: 'ул. Андрианова, 3',
    locationSlug: 'omsk-sovetskiy-park',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 54.99221,
    longitude: 73.40121,
  },

  // --- Театры и гастро (40-50) ---
  {
    name: 'Омский музыкальный театр',
    desc: 'Опера, балет и оперетта на Думской - вечерняя точка после Камергерского.',
    address: 'ул. Думская, 2',
    venueSlug: 'omsk-muzykalnyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 54.98471,
    longitude: 73.37011,
  },
  {
    name: 'Камергерский переулок',
    desc: 'Петербургский дворик в Сибири: кирпич начала XX века, рестораны и Ван Гог во дворе.',
    address: 'ул. Ленина, 14/1',
    locationSlug: 'omsk-kamergerskiy-pereulok',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 54.984312,
    longitude: 73.371412,
  },
  {
    name: 'Ресторан «Сенкевич»',
    desc: 'Видовая кухня на Съездовской: закат на Валиханова логично заканчивать здесь.',
    address: 'ул. Съездовская, 1',
    locationSlug: 'omsk-restoran-senkevich',
    mustSeeFilter: 'gastro',
    visitMinutes: 70,
    latitude: 54.97321,
    longitude: 73.38021,
  },
  {
    name: '«У Квартала»',
    desc: 'Камерный стол в купеческом дворе на Ленина, 14/1А.',
    address: 'ул. Ленина, 14/1А',
    locationSlug: 'omsk-u-kvartala',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 54.98425,
    longitude: 73.37155,
  },
  {
    name: '«Соленый зефир»',
    desc: 'Десертная и кофе на Карла Либкнехта - пауза между Любинским и Валиханова.',
    address: 'ул. Карла Либкнехта, 2',
    locationSlug: 'omsk-solenyy-zefir',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 54.98221,
    longitude: 73.37611,
  },
  {
    name: 'Театр кукол «Арлекин»',
    desc: 'Кукольная сцена на Карла Маркса - семейная точка после торговых рядов.',
    address: 'ул. Карла Маркса, 15/1',
    venueSlug: 'omsk-teatr-kukol-arlekin',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 54.97921,
    longitude: 73.38121,
  },
  {
    name: 'Кофейня Skuratov',
    desc: 'Сибирский кофе на Лермонтова: фильтр, выпечка и пауза у речного вокзала.',
    address: 'ул. Лермонтова, 4Б',
    locationSlug: 'omsk-skuratov',
    mustSeeFilter: 'gastro',
    visitMinutes: 25,
    latitude: 54.98151,
    longitude: 73.37481,
  },
  {
    name: 'Рок-клуб «Викинг»',
    desc: 'Живая сцена омского панка и гаражного рока на Мира. Наследие ГрОб-рекордс рядом по духу.',
    address: 'ул. Мира, 33А',
    locationSlug: 'omsk-viking-rok-klub',
    mustSeeFilter: 'creative',
    visitMinutes: 50,
    latitude: 54.97321,
    longitude: 73.39521,
  },
  {
    name: 'Винный бар «Одно вино»',
    desc: 'Камерная карта вин на Любинском, удобно после театра драмы.',
    address: 'ул. Ленина, 10',
    locationSlug: 'omsk-odno-vino',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 54.98381,
    longitude: 73.37281,
  },
  {
    name: '«Пятый театр»',
    desc: 'Современная драма на Красном Пути - омская сцена вне парадной площади.',
    address: 'ул. Красный Путь, 153',
    venueSlug: 'omsk-pyatyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 55.00121,
    longitude: 73.36821,
  },
  {
    name: 'Гастродвор «Любинский»',
    desc: 'Фудхолл в купеческом квартале: дичь, нельма, сгущенка к чаю и большие порции.',
    address: 'ул. Ленина, 14/1, корпус Б',
    locationSlug: 'omsk-gastrodvor-lyubinskiy',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 54.98422,
    longitude: 73.37162,
  },
];

export const OMSK_SUBURBS: any[] = [
  {
    name: 'Старина Сибирская (Большеречье)',
    desc: 'Музей под открытым небом: сибирская деревня с пятистенком, кузницей, татарской усадьбой и зоопарком Большеречья. Закладывайте около 2,5 часов в пути, чтобы быть на месте к 10:00.',
    locationSlug: 'omsk-starina-sibirskaya',
    mustSeeFilter: 'main',
    visitMinutes: '7-8 ч',
    latitude: 56.103112,
    longitude: 74.621112,
    address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
    travelVector: 'Авто ~2,5 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль около 2,5 часов по трассе на Тару, чтобы приехать к 10:00 утра.',
    timingNote:
      'Начинайте с дома Гладкова и пятистенка, затем кузница и татарская усадьба, напоследок оставив зоопарк Большеречья.',
    gastroStop: {
      name: 'Чай в избе',
      blurb: 'На территории музея подают чай с томленой сгущенкой и таежным медом - берите с запасом, кафе в поселке мало.',
    },
    places: [
      {
        name: 'Дом Гладкова',
        desc: 'Купеческий дом-музей с подлинной обстановкой сибирского быта.',
        locationSlug: 'omsk-starina-dom-gladkova',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.103112,
        longitude: 74.621112,
        visitMinutes: 30,
      },
      {
        name: 'Пятистенная изба',
        desc: 'Классический сибирский пятистенок с резными наличниками.',
        locationSlug: 'omsk-starina-pyatistenok',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10321,
        longitude: 74.62121,
        visitMinutes: 20,
      },
      {
        name: 'Кузница',
        desc: 'Действующая деревенская кузница с мастер-классами в сезон.',
        locationSlug: 'omsk-starina-kuznitsa',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10331,
        longitude: 74.62131,
        visitMinutes: 20,
      },
      {
        name: 'Татарская усадьба',
        desc: 'Подворье сибирских татар: дом, хозяйство и кухня Прииртышья.',
        locationSlug: 'omsk-starina-tatarskaya-usadba',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10341,
        longitude: 74.62141,
        visitMinutes: 25,
      },
      {
        name: 'Церковь Георгия Победоносца',
        desc: 'Деревянный храм усадьбы - тихая точка маршрута.',
        locationSlug: 'omsk-starina-tserkov-georgiya',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10351,
        longitude: 74.62151,
        visitMinutes: 15,
      },
      {
        name: 'Охотничье зимовье',
        desc: 'Промысловая избушка таежного охотника.',
        locationSlug: 'omsk-starina-ohotniche-zimovye',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10361,
        longitude: 74.62161,
        visitMinutes: 15,
      },
      {
        name: 'Зоопарк Большеречья',
        desc: 'Небольшой зоопарк рядом с музеем - удобно с детьми после изб.',
        locationSlug: 'omsk-starina-zoopark-bolsherechya',
        address: 'Омская обл., р.п. Большеречье, ул. Советов, 29',
        latitude: 56.10411,
        longitude: 74.62211,
        visitMinutes: 50,
      },
    ],
  },
  {
    name: 'Чернолучье / Красноярско-Чернолученский бор',
    desc: 'Сосновый бор в часе от Омска: тропа здоровья, Черный Яр, святой источник, пляж Иртышской луки, озеро Линево, термальный бассейн «Сказка» и грибные поляны Прииртышья. Выезжайте к 09:30.',
    locationSlug: 'omsk-chernoluchye',
    mustSeeFilter: 'main',
    visitMinutes: '6-7 ч',
    latitude: 55.281112,
    longitude: 73.042312,
    address: 'Омская обл., Чернолучье',
    travelVector: 'Авто ~1 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль около часа, чтобы быть на тропе здоровья к 09:30.',
    timingNote:
      'Сначала смотровая Черный Яр и источник, днем пляж луки или Линево, к вечеру - «Сказка» или грибные поляны Прииртышья.',
    gastroStop: {
      name: 'Бассейн «Сказка»',
      blurb: 'После бора согрейтесь в термальном бассейне «Сказка»: кафе на месте, меню простое, вид на сосны.',
    },
    places: [
      {
        name: 'Тропа здоровья',
        desc: 'Хвойная экотропа по Красноярско-Чернолученскому бору.',
        locationSlug: 'omsk-chernoluchye-tropa-zdorovya',
        address: 'Омская обл., Чернолучье',
        latitude: 55.281112,
        longitude: 73.042312,
        visitMinutes: 40,
      },
      {
        name: 'Смотровая Черный Яр',
        desc: 'Обрыв над Иртышом с видом на излучину.',
        locationSlug: 'omsk-chernoluchye-chernyy-yar',
        address: 'Омская обл., Чернолучье',
        latitude: 55.28211,
        longitude: 73.04121,
        visitMinutes: 20,
      },
      {
        name: 'Святой источник',
        desc: 'Родник в бору, место короткой тихой остановки.',
        locationSlug: 'omsk-chernoluchye-svyatoy-istochnik',
        address: 'Омская обл., Чернолучье',
        latitude: 55.28011,
        longitude: 73.04321,
        visitMinutes: 15,
      },
      {
        name: 'Пляж Иртышской луки',
        desc: 'Песчаный берег на излучине - лето и закат без городской набережной.',
        locationSlug: 'omsk-chernoluchye-plyazh-luka',
        address: 'Омская обл., Чернолучье',
        latitude: 55.28311,
        longitude: 73.03921,
        visitMinutes: 40,
      },
      {
        name: 'Озеро Линево',
        desc: 'Лесное озеро для тихой стоянки и купания в жару.',
        locationSlug: 'omsk-chernoluchye-ozero-linevo',
        address: 'Омская обл., Чернолучье',
        latitude: 55.27811,
        longitude: 73.04821,
        visitMinutes: 30,
      },
      {
        name: 'Термальный бассейн «Сказка»',
        desc: 'Открытый теплый бассейн среди сосен - запасной план в ветреный день.',
        locationSlug: 'omsk-chernoluchye-skazka',
        address: 'Омская обл., Чернолучье',
        latitude: 55.27911,
        longitude: 73.04421,
        visitMinutes: 60,
      },
      {
        name: 'Грибные поляны Прииртышья',
        desc: 'Сосновые грибные места Прииртышья вокруг Чернолучья. Сезон - конец лета и сентябрь.',
        locationSlug: 'omsk-chernoluchye-gribnye-polyany',
        address: 'Омская обл., Чернолучье',
        latitude: 55.27611,
        longitude: 73.05121,
        visitMinutes: 40,
      },
    ],
  },
];

export const OMSK_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'omsk-kupecheskiy-lyubinskiy',
    title: 'Купеческий Любинский и Древняя крепость',
    description:
      'Классический день: речной вокзал, Любинский и Московские ряды, Камергерский со Skuratov, Тарские ворота, Воскресенский собор и крепость с Тобольскими воротами. Обед в Гастродворе.',
    travelVector: 'Пешком по центру и крепости',
    timingNote:
      'Около 4 часов: речной вокзал - Любинский - Камергерский - Тарские ворота - Воскресенский - крепость. Обед в Гастродворе.',
    stops: [
      {
        name: 'Смотровая у речного вокзала',
        desc: '15 минут на Иртыш и старт к Любинскому.',
        locationSlug: 'omsk-rechnoy-vokzal',
        mustSeeFilter: 'views',
        visitMinutes: 15,
        address: 'ул. Лермонтова, 2',
        latitude: 54.98121,
        longitude: 73.37521,
      },
      {
        name: 'Любинский проспект и Московские ряды',
        desc: '30 минут на купеческие фасады и Степаныча.',
        locationSlug: 'omsk-lyubinskiy-prospekt-ulitsa-lenina',
        mustSeeFilter: 'houses',
        visitMinutes: 30,
        address: 'ул. Ленина, 10-22',
        latitude: 54.98441,
        longitude: 73.37221,
        transitTip: 'Пешком 8 минут вверх от вокзала',
      },
      {
        name: 'Камергерский и Skuratov',
        desc: '25 минут на кирпичный дворик и кофе.',
        locationSlug: 'omsk-kamergerskiy-pereulok',
        mustSeeFilter: 'houses',
        visitMinutes: 25,
        address: 'ул. Ленина, 14/1',
        latitude: 54.984312,
        longitude: 73.371412,
        transitTip: 'Пешком 2 минуты во двор рядов',
      },
      {
        name: 'Тарские ворота',
        desc: '15 минут под аркой и у «Несущего крест».',
        locationSlug: 'omsk-tarskie-vorota',
        mustSeeFilter: 'main',
        visitMinutes: 15,
        address: 'ул. Спартаковская',
        latitude: 54.986912,
        longitude: 73.366112,
        transitTip: 'Пешком 8 минут к крепости',
      },
      {
        name: 'Воскресенский военный собор',
        desc: '20 минут на сибирское барокко.',
        locationSlug: 'omsk-voskresenskiy-voennyy-sobor',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'ул. Партизанская, 16',
        latitude: 54.98621,
        longitude: 73.36241,
        transitTip: 'Пешком 4 минуты вдоль крепостной линии',
      },
      {
        name: 'Крепость, Тобольские ворота и Гастродвор',
        desc: 'Час на казармы и обед в Гастродворе «Любинский».',
        locationSlug: 'omsk-omskaya-krepost',
        mustSeeFilter: 'park',
        visitMinutes: 60,
        address: 'ул. Партизанская, 5',
        latitude: 54.98551,
        longitude: 73.36351,
        transitTip: 'После крепости 10 минут назад к Гастродвору',
      },
    ],
  },
  {
    id: 'omsk-muzeynyy-avangard',
    title: 'Музейный авангард, Врубель и закат на Валиханова',
    description:
      'День для залов: Эрмитаж-Сибирь, музей Врубеля, Никольский казачий, кристаллы Валиханова и закат у «Сенкевича».',
    travelVector: 'Музеи центра и бульвар Валиханова',
    timingNote: 'Около 4 часов; билеты в Эрмитаж-Сибирь берите заранее на сайте Врубеля.',
    stops: [
      {
        name: 'Эрмитаж-Сибирь',
        desc: 'Час на филиал Эрмитажа. Вт-ср с 10:00.',
        venueSlug: 'omsk-ermitazh-sibir',
        mustSeeFilter: 'museum',
        visitMinutes: 60,
        address: 'ул. Музейная, 4',
        latitude: 54.98951,
        longitude: 73.36782,
      },
      {
        name: 'Музей Врубеля',
        desc: 'Час на сибирскую коллекцию. Третья среда месяца - льготный вход.',
        venueSlug: 'omsk-muzey-izobrazitelnyh-iskusstv-vrubelya',
        mustSeeFilter: 'museum',
        visitMinutes: 60,
        address: 'ул. Ленина, 3',
        latitude: 54.98351,
        longitude: 73.37421,
        transitTip: 'Пешком 12 минут по Любинскому',
      },
      {
        name: 'Никольский казачий собор',
        desc: '15 минут у храма и памятника Петру и Февронии.',
        locationSlug: 'omsk-nikolskiy-kazachiy-sobor',
        mustSeeFilter: 'temple',
        visitMinutes: 15,
        address: 'ул. Ленина, 27',
        latitude: 54.988912,
        longitude: 73.368112,
        transitTip: 'Пешком 8 минут вверх по Ленина',
      },
      {
        name: 'Кристаллы Валиханова',
        desc: '30 минут на пешеходный бульвар к закату.',
        locationSlug: 'omsk-ulitsa-chokana-valihanova',
        mustSeeFilter: 'street',
        visitMinutes: 30,
        address: 'ул. Чокана Валиханова',
        latitude: 54.97451,
        longitude: 73.38121,
        transitTip: 'Пешком 15 минут или трамвай 2 остановки',
      },
      {
        name: 'Закат у «Сенкевича»',
        desc: 'Ужин с видом после бульвара.',
        locationSlug: 'omsk-restoran-senkevich',
        mustSeeFilter: 'gastro',
        visitMinutes: 70,
        address: 'ул. Съездовская, 1',
        latitude: 54.97321,
        longitude: 73.38021,
        transitTip: 'Пешком 4 минуты от кристаллов',
      },
    ],
  },
  ...OMSK_LINE_DAY_ROUTE_PRESETS,
];

export const OMSK_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Правда ли, что в Омске есть метро из одной станции?',
    a: 'Официальный метрополитен так и не запустили. Построенный участок у «Библиотеки имени Пушкина» работает как подземный переход и городской арт-объект. Планы метротрама обсуждают годами, для туриста это прогулка под землей, а не транспорт.',
  },
  {
    q: 'Где искать Омск Егора Летова и «Гражданской обороны»?',
    a: 'Точка паломничества - дом на Осминина, 5 и память о студии ГрОб-рекордс. Могила Летова на Старо-Восточном кладбище. Живой гаражный рок вечером - в клубе «Викинг» на Мира, 33А.',
  },
  {
    q: 'Омск продувает пылью. Куда спрятаться в ветреный день?',
    a: 'Городской бор у Аграрного университета и Зеленый остров на Иртыше держат хвойную тень и меньше пыли, чем центр. В жару и ветер туда же: тропы, пляж острова и тише, чем на Любинском.',
  },
  {
    q: 'Как попасть в Эрмитаж-Сибирь, если касса на Музейной молчит?',
    a: 'Билеты продают через сайт музея Врубеля, не на месте. Залы обычно со вторника и среды с 10:00. В выходные слоты разбирают заранее - берите накануне вечером.',
  },
];

export const OMSK_TRAVEL =
  'В аэропорт Омск-Центральный имени Д. М. Карбышева летают прямые рейсы из Москвы (около 3,5 часов), Санкт-Петербурга и крупных сибирских городов. Через город идет Транссиб, автомобилисты используют трассы Р-254 и Р-402. Зима сухая и солнечная при -16...-20 °C: каток в крепости и заснеженный Любинский, согревают сибирские настойки и блюда из дичи. Весна: в апреле сходит снег, в мае +15...+18 °C, ледоход на Иртыше, с конца мая - навигация и яхты у речного вокзала. Лето жаркое, сухое, часто +30 °C: пляжи Иртыша, Камергерские террасы, газоны парка Королева и выезды к пяти озерам Муромцевского района. Осень: сентябрь - сибирское бабье лето около +15 °C, в октябре золотеют старые площади и набережные. Меньше транзита, дешевле перелеты и отели - удобный сезон для музеев.';
