import type { PublicSession } from '@/types';

const SIZE_SUFFIX_RE =
  /(?:[-_](?:\d{2,4}x\d{2,4}|w\d{2,4}|h\d{2,4}|q\d{2,3}|thumb|small|medium|large|cover|card|preview|resized?))+(?=\.[a-z0-9]+$)/i;

/**
 * Sharp stubs from ensure-catalog-covers (`evt-auto-*` / `venue-auto-*`).
 * Look like category color gradients - not usable in «с фото» rails.
 */
export function isEphemeralAutoGeneratedCoverUrl(imageUrl?: string | null): boolean {
  return /\/images\/(?:events|venues)\/generated\/(?:evt|venue)-auto-/i.test(
    String(imageUrl || '').trim(),
  );
}

/** Есть ли у события реальная обложка (не city/teplohod/evt-auto stub). */
export function sessionHasCoverImage(session: Pick<PublicSession, 'imageUrl'>): boolean {
  const url = String(session.imageUrl || '').trim();
  if (!url) return false;
  if (url.startsWith('/images/cities/')) return false;
  if (/placeholder\.gif/i.test(url)) return false;
  if (/api\.teplohod\.info\/v1\/image\?item=&/i.test(url)) return false;
  if (isEphemeralAutoGeneratedCoverUrl(url)) return false;
  return true;
}

function unwrapNextImageUrl(raw: string): string {
  if (!raw.includes('/_next/image') || !/[?&]url=/.test(raw)) return raw;
  try {
    const proxy = new URL(raw.replace(/&amp;/g, '&'), 'https://daibilet.ru');
    const inner = proxy.searchParams.get('url');
    return inner ? unwrapNextImageUrl(inner) : raw;
  } catch {
    return raw;
  }
}

function parseImageUrl(imageUrl: string): { pathname: string; search: string; href: string } {
  const raw = unwrapNextImageUrl(String(imageUrl || '').trim().replace(/&amp;/g, '&'));
  try {
    const parsed = new URL(raw, 'https://daibilet.ru');
    if (parsed.port === '443' || parsed.port === '80') parsed.port = '';
    return {
      pathname: parsed.pathname,
      search: parsed.search || '',
      href: parsed.href,
    };
  } catch {
    const bare = raw.split('#')[0] || raw;
    const q = bare.indexOf('?');
    return {
      pathname: q >= 0 ? bare.slice(0, q) : bare,
      search: q >= 0 ? bare.slice(q) : '',
      href: bare,
    };
  }
}

function stripImageSizeSuffixes(file: string): string {
  return file.replace(SIZE_SUFFIX_RE, '');
}

function fileStemKey(file: string): string | null {
  const cleaned = stripImageSizeSuffixes(file).toLowerCase();
  if (!cleaned) return null;
  // Teplohod upload variants only: {hex}-1.jpg / {hex}-2.jpg → same stem.
  // Do not strip trailing -N from ordinary names (unique-other-2.jpg).
  const teploVariant = cleaned.match(/^([a-f0-9]{8,})-\d+\.(jpe?g|png|webp|gif|avif|bmp|svg)$/i);
  if (teploVariant) return teploVariant[1]!.toLowerCase();
  const stem = cleaned.replace(/\.(jpe?g|png|webp|gif|avif|bmp|svg)$/i, '');
  return stem || null;
}

/**
 * Все ключи, по которым обложка считается той же самой:
 * basename, stem без size/-N, Ticketscloud asset id, dirtyAlias, локальный tc-{id}.
 */
export function collectSessionImageDedupeKeys(imageUrl?: string | null): string[] {
  const raw = String(imageUrl || '').trim();
  if (!raw) return [];

  const { pathname, search } = parseImageUrl(raw);
  const normalizedPath = pathname.replace(/\/$/, '').toLowerCase();
  const file = decodeURIComponent(normalizedPath.split('/').filter(Boolean).pop() || '').toLowerCase();
  const keys = new Set<string>();

  if (file && /\.(jpe?g|png|webp|gif|avif|bmp|svg)$/i.test(file)) {
    const stripped = stripImageSizeSuffixes(file);
    keys.add(`img:${stripped}`);
    if (stripped !== file) keys.add(`img:${file}`);

    const stem = fileStemKey(file);
    if (stem && stem.length >= 8) keys.add(`stem:${stem}`);

    // Ticketscloud CDN / production/image/.../{24hex}.ext
    const oid = stripped.match(/^([a-f0-9]{24})\.(jpe?g|png|webp|gif|avif)$/i);
    if (oid) keys.add(`tc-asset:${oid[1].toLowerCase()}`);

    // Local override: /images/events/tc-{eventId}-slug.ext
    const localTc = stripped.match(/^tc-([a-f0-9]{24})(?:-|\.|$)/i);
    if (localTc) keys.add(`tc-event:${localTc[1].toLowerCase()}`);
  }

  if (search) {
    try {
      const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search);
      const dirtyAlias = params.get('dirtyAlias') || params.get('dirty_alias');
      if (dirtyAlias?.trim()) {
        const aliasFile = decodeURIComponent(dirtyAlias.trim()).toLowerCase().split('/').pop() || '';
        if (aliasFile) {
          const stripped = stripImageSizeSuffixes(aliasFile);
          keys.add(`img:${stripped}`);
          const stem = fileStemKey(aliasFile);
          if (stem && stem.length >= 8) keys.add(`stem:${stem}`);
        }
      }
      const item = params.get('item') || params.get('id') || params.get('key');
      if (item?.trim()) keys.add(`img:q:${item.trim().toLowerCase()}`);
    } catch {
      // ignore
    }
  }

  if (!keys.size && normalizedPath) keys.add(`path:${normalizedPath}`);
  return [...keys];
}

/** Нормализованный ключ картинки для сравнения дубликатов (primary). */
export function normalizeSessionImageKey(imageUrl?: string | null): string | null {
  const keys = collectSessionImageDedupeKeys(imageUrl);
  if (!keys.length) return null;
  // Prefer content-ish keys first for adjacent spread
  return (
    keys.find((key) => key.startsWith('tc-asset:')) ||
    keys.find((key) => key.startsWith('stem:')) ||
    keys.find((key) => key.startsWith('img:') && !key.startsWith('img:q:')) ||
    keys[0] ||
    null
  );
}

export function filterSessionsWithCoverImage<T extends Pick<PublicSession, 'imageUrl'>>(sessions: T[]): T[] {
  return sessions.filter(sessionHasCoverImage);
}

function coverKeysEqual(
  a: string | null | undefined,
  b: string | null | undefined,
  fingerprints?: Map<string, string>,
): boolean {
  if (!a && !b) return false;
  const aKeys = new Set(collectSessionImageDedupeKeys(a));
  const bKeys = collectSessionImageDedupeKeys(b);
  if (bKeys.some((key) => aKeys.has(key))) return true;
  if (!fingerprints || !a || !b) return false;
  const fa = fingerprints.get(a);
  const fb = fingerprints.get(b);
  return Boolean(fa && fb && fa === fb);
}

/** Не ставит карточки с одинаковой обложкой подряд (сохраняет относительный порядок где возможно). */
export function spreadCatalogSessionsByCoverImage<T extends Pick<PublicSession, 'imageUrl'>>(
  sessions: T[],
  fingerprints?: Map<string, string>,
): T[] {
  if (sessions.length <= 1) return sessions;

  const pool = [...sessions];
  const result: T[] = [];

  while (pool.length > 0) {
    const lastUrl = result.length ? result[result.length - 1]!.imageUrl : null;
    let pickIndex = 0;

    if (lastUrl) {
      if (coverKeysEqual(pool[0]!.imageUrl, lastUrl, fingerprints)) {
        const alternateIndex = pool.findIndex(
          (session) => !coverKeysEqual(session.imageUrl, lastUrl, fingerprints),
        );
        if (alternateIndex > 0) pickIndex = alternateIndex;
      }
    }

    result.push(pool.splice(pickIndex, 1)[0]!);
  }

  return result;
}

/** Разносит одинаковые обложки в сетке (соседи по строке и столбцу). */
export function spreadSessionsForGrid<T extends Pick<PublicSession, 'imageUrl'>>(
  sessions: T[],
  columns = 3,
  fingerprints?: Map<string, string>,
): T[] {
  if (sessions.length <= 1 || columns <= 1) {
    return spreadCatalogSessionsByCoverImage(sessions, fingerprints);
  }

  let result = spreadCatalogSessionsByCoverImage(sessions, fingerprints);
  const maxPasses = result.length * columns;

  for (let pass = 0; pass < maxPasses; pass += 1) {
    let fixed = false;

    for (let i = 0; i < result.length; i += 1) {
      const url = result[i]!.imageUrl;
      if (!url) continue;

      const neighbors = [i + 1, i - 1, i + columns, i - columns].filter(
        (idx) => idx >= 0 && idx < result.length && idx !== i,
      );

      for (const neighborIndex of neighbors) {
        if (Math.abs(neighborIndex - i) === 1 && Math.floor(neighborIndex / columns) !== Math.floor(i / columns)) {
          continue;
        }

        if (!coverKeysEqual(result[neighborIndex]!.imageUrl, url, fingerprints)) continue;

        const swapIndex = result.findIndex((item, idx) => {
          if (idx === i || idx === neighborIndex) return false;
          if (coverKeysEqual(item.imageUrl, url, fingerprints)) return false;
          const wouldConflict = [idx + 1, idx - 1, idx + columns, idx - columns].some((testIdx) => {
            if (testIdx < 0 || testIdx >= result.length || testIdx === idx) return false;
            if (Math.abs(testIdx - idx) === 1 && Math.floor(testIdx / columns) !== Math.floor(idx / columns)) {
              return false;
            }
            return coverKeysEqual(result[testIdx]!.imageUrl, item.imageUrl, fingerprints);
          });
          return !wouldConflict;
        });

        if (swapIndex === -1) continue;
        [result[i], result[swapIndex]] = [result[swapIndex]!, result[i]!];
        fixed = true;
        break;
      }

      if (fixed) break;
    }

    if (!fixed) break;
  }

  return result;
}

export function arrangeCatalogSessions<T extends Pick<PublicSession, 'imageUrl'>>(
  sessions: T[],
  sort: 'time' | 'price' | 'popular',
): T[] {
  const withCover = filterSessionsWithCoverImage(sessions);
  if (sort === 'price' || sort === 'time') return withCover;
  return spreadCatalogSessionsByCoverImage(withCover);
}
