/** Ufa tourist hub pack (owner 2026-08-17). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { UFA_LINE_DAY_ROUTE_PRESETS } from './ufa-line-presets';

export const UFA_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник Салавату Юлаеву',
    desc: 'Самая большая конная статуя в России, стоящая на высоком утесе над рекой Белой.',
    address: 'ул. Набережная (Площадь Салавата Юлаева)',
    locationSlug: 'ufa-pamyatnik-salavatu-yulaevu',
    mustSeeFilter: 'main',
    visitMinutes: 20,
    latitude: 54.718612,
    longitude: 55.926111,
  },
  {
    name: 'Монумент Дружбы',
    desc: 'Величественная 35-метровая стела в честь 400-летия присоединения Башкирии к России.',
    address: 'ул. Сочинская / Первомайская площадь',
    locationSlug: 'ufa-monument-druzhby',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.711102,
    longitude: 55.963891,
  },
  {
    name: 'Памятник Мустаю Кариму',
    desc: 'Скульптурная композиция башкирскому поэту с летящими страницами книг.',
    address: 'ул. Кирова, 1 (перед Домом профсоюзов)',
    locationSlug: 'ufa-pamyatnik-mustayu-karimu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.726612,
    longitude: 55.946905,
  },
  {
    name: 'Памятник Федору Шаляпину',
    desc: 'Мраморная скульптура великого баса, который начинал карьеру именно в Уфе.',
    address: 'ул. Ленина, 5/1 (у концертного зала)',
    locationSlug: 'ufa-pamyatnik-fedoru-shalyapinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.724102,
    longitude: 55.943112,
  },
  {
    name: 'Памятник кунице',
    desc: 'Бронзовый символ города: две куницы на ветке дерева у Гостиного двора.',
    address: 'ул. Ленина, 50 (у Гостиного двора)',
    locationSlug: 'ufa-pamyatnik-kunitse',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.726891,
    longitude: 55.948312,
  },
  {
    name: 'Памятник генералу Шаймуратову',
    desc: 'Конный памятник командиру 112-й Башкирской кавдивизии на Советской площади.',
    address: 'Советская площадь',
    locationSlug: 'ufa-pamyatnik-generalu-shaymuratovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 54.719891,
    longitude: 55.949102,
  },
  {
    name: 'Арт-объект «Три шурупа»',
    desc: 'Каменная надпись названия города на башкирском языке (ӨФӨ), визуально похожая на шурупы.',
    address: 'ул. Ленина (сквер перед Гостиным двором)',
    locationSlug: 'ufa-art-obyekt-tri-shurupa',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.726412,
    longitude: 55.947901,
  },
  {
    name: 'Памятник дворнику',
    desc: 'Бронзовая фигура уфимского труженика с метлой на пешеходной зоне.',
    address: 'проспект Октября, 4/1 (у ЦТиР «Мир»)',
    locationSlug: 'ufa-pamyatnik-dvorniku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.743112,
    longitude: 55.989801,
  },
  {
    name: 'Памятник героям Октябрьской революции и гражданской войны',
    desc: 'Монументальная многофигурная скульптурная группа советской эпохи.',
    address: 'ул. Ленина (сквер Маяковского)',
    locationSlug: 'ufa-pamyatnik-geroyam-oktyabrskoy-revolyutsii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.729102,
    longitude: 55.952312,
  },
  {
    name: 'Памятник В. И. Ленину',
    desc: 'Один из первых и редких памятников Ленину, выполненный в сидячем положении.',
    address: 'ул. Ленина / ул. Коммунистическая (сквер Ленина)',
    locationSlug: 'ufa-pamyatnik-leninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.727102,
    longitude: 55.945891,
  },
  {
    name: 'Скульптура «Дом куницы»',
    desc: 'Маленький кованый домик-теремок со зверьками, популярное место для загадывания желаний.',
    address: 'ул. Менделеева, 137А (у ТРК «Иремель»)',
    locationSlug: 'ufa-skulptura-dom-kunitsy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.714902,
    longitude: 56.004891,
  },
  {
    name: 'Памятник А. С. Пушкину',
    desc: 'Классический бюст поэта в тихой аллее Пушкинского сквера.',
    address: 'ул. Пушкина / ул. Цюрупы',
    locationSlug: 'ufa-pamyatnik-pushkinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.721901,
    longitude: 55.943891,
  },
  {
    name: 'Памятник Салавату Юлаеву у Госсобрания',
    desc: 'Второй, менее известный, но изящный памятник герою перед Курултаем.',
    address: 'ул. Заки Валиди, 40',
    locationSlug: 'ufa-pamyatnik-salavatu-yulaevu-u-gossobraniya',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.716901,
    longitude: 55.938912,
  },
  {
    name: 'Памятник землякам, ушедшим на фронт',
    desc: 'Скульптурная композиция прощания солдата с семьей у железнодорожного вокзала.',
    address: 'ул. Вокзальная, 1 (у ж/д вокзала)',
    locationSlug: 'ufa-pamyatnik-zemlyakam-ushedshim-na-front',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.735891,
    longitude: 55.935102,
  },
  {
    name: 'Памятник Мифтахетдину Акмулле',
    desc: 'Башкирский поэт-просветитель сидит среди учеников на ступенях университета.',
    address: 'ул. Заки Валиди, 47 (перед БГПУ)',
    locationSlug: 'ufa-pamyatnik-akmulle',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 54.723112,
    longitude: 55.941901,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Гостиный двор',
    desc: 'Обновленный торговый и общественный комплекс XIX века, сердце исторического центра.',
    address: 'ул. Верхнеторговая площадь, 1',
    locationSlug: 'ufa-gostinyy-dvor',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 54.725891,
    longitude: 55.947891,
  },
  {
    name: 'Дом-коммуна',
    desc: 'Памятник советского конструктивизма 1930-х, яркий образец авангардной жилой архитектуры.',
    address: 'ул. Ленина, 9/11',
    locationSlug: 'ufa-dom-kommuna',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.724901,
    longitude: 55.944112,
  },
  {
    name: 'Особняк Костерина и Черникова',
    desc: 'Роскошное здание в стиле модерн с богатой лепниной, бывший купеческий дом.',
    address: 'ул. Пушкина, 86',
    locationSlug: 'ufa-osobnyak-kosterina-i-chernikova',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.726112,
    longitude: 55.945102,
  },
  {
    name: 'Здание Дворянского собрания',
    desc: 'Архитектурный шедевр, где сейчас располагается Академия искусств им. Исмагилова.',
    address: 'ул. Ленина, 14',
    locationSlug: 'ufa-zdanie-dvoryanskogo-sobraniya',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.723891,
    longitude: 55.943431,
  },
  {
    name: 'Дом Губернатора',
    desc: 'Бывшее административное сердце Уфимской губернии, строгое классическое трехэтажное здание.',
    address: 'ул. Советская, 18',
    locationSlug: 'ufa-dom-gubernatora',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.718901,
    longitude: 55.944112,
  },
  {
    name: 'Здание Крестьянского поземельного банка',
    desc: 'Живописный замок в неорусском стиле с элементами модерна, ныне Национальный музей.',
    address: 'ул. Советская, 14',
    locationSlug: 'ufa-zdanie-krestyanskogo-pozemelnogo-banka',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.719412,
    longitude: 55.946312,
  },
  {
    name: 'Уфимская Демидовская преемственность',
    desc: 'Группа старинных деревянных и полукаменных жилых домов купеческой застройки.',
    address: 'ул. Октябрьской Революции, 10',
    locationSlug: 'ufa-ufimskaya-demidovskaya-preemstvennost',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 54.721112,
    longitude: 55.952901,
  },

  // --- Музеи (23-29) ---
  {
    name: 'Национальный музей Республики Башкортостан',
    desc: 'Главный музей края с коллекцией сарматского золота и этнографии.',
    address: 'ул. Советская, 14',
    locationSlug: 'ufa-natsionalnyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 54.719612,
    longitude: 55.946111,
  },
  {
    name: 'Башкирский государственный художественный музей им. М. В. Нестерова',
    desc: 'Собрание русского искусства и картин Нестерова в купеческом особняке Лаптева.',
    address: 'ул. Гоголя, 27',
    locationSlug: 'ufa-hudozhestvennyy-muzey-nesterova',
    mustSeeFilter: 'museum',
    visitMinutes: 50,
    latitude: 54.723891,
    longitude: 55.938912,
  },
  {
    name: 'Музей археологии и этнографии',
    desc: 'Хранилище «Золота сарматов» - коллекции золотых фигурок оленей IV века до н.э.',
    address: 'ул. Карла Маркса, 6',
    locationSlug: 'ufa-muzey-arheologii-i-etnografii',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 54.721412,
    longitude: 55.937212,
  },
  {
    name: 'Дом-музей В. И. Ленина',
    desc: 'Мемориальная усадьба, воссоздающая быт Уфы начала XX века.',
    address: 'ул. Достоевского, 78',
    locationSlug: 'ufa-dom-muzey-lenina',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 54.731901,
    longitude: 55.952312,
  },
  {
    name: 'Музей рока в кинотеатре «Родина»',
    desc: 'Камерная экспозиция уфимского периода Юрия Шевчука и ДДТ в сталинском ампире 1953 года.',
    address: 'ул. Ленина, 42',
    locationSlug: 'ufa-muzey-roka-kinoteatr-rodina',
    mustSeeFilter: 'museum',
    visitMinutes: 30,
    latitude: 54.728901,
    longitude: 55.950112,
  },
  {
    name: 'Республиканский музей Боевой Славы',
    desc: 'Экспозиция военной техники и диорам в Парке Победы.',
    address: 'ул. Комарова, 7 (Парк Победы)',
    locationSlug: 'ufa-muzey-boevoy-slavy',
    mustSeeFilter: 'museum',
    visitMinutes: 50,
    latitude: 54.809112,
    longitude: 56.062312,
  },
  {
    name: 'Дом-музей С. Т. Аксакова',
    desc: 'Деревянный дом на берегу реки, посвященный детству знаменитого русского писателя.',
    address: 'ул. Зайнуллы Расулева, 4',
    locationSlug: 'ufa-dom-muzey-aksakova',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 54.712901,
    longitude: 55.932312,
  },

  // --- Храмы (30-36) ---
  {
    name: 'Мечеть-медресе «Ляля-Тюльпан»',
    desc: 'Современный исламский центр Уфы с минаретами в форме бутонов тюльпанов.',
    address: 'ул. Комарова, 5',
    locationSlug: 'ufa-mechet-medrese-lyalya-tyul-pan',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 54.805833,
    longitude: 56.055833,
  },
  {
    name: 'Первая соборная мечеть Уфы',
    desc: 'Старейшая действующая мечеть города, основанная в 1830 году по указу Александра I.',
    address: 'ул. Тукаева, 52',
    locationSlug: 'ufa-pervaya-sobornaya-mechet',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.713901,
    longitude: 55.935891,
  },
  {
    name: 'Сергиевский кафедральный собор',
    desc: 'Уютный деревянный православный храм, не закрывавшийся в советские годы.',
    address: 'ул. Бехтерева, 2',
    locationSlug: 'ufa-sergievskiy-kafedralnyy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.709112,
    longitude: 55.972312,
  },
  {
    name: 'Рождество-Богородицкий храм',
    desc: 'Главный и самый вместительный православный собор Уфы с лазурными куполами.',
    address: 'ул. Кирова, 102',
    locationSlug: 'ufa-rozhdestvo-bogoroditskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 54.731412,
    longitude: 55.971901,
  },
  {
    name: 'Спасский храм',
    desc: 'Церковь XIX века с колоннадой, архитектурно напоминающая Казанский собор в Санкт-Петербурге.',
    address: 'ул. Октябрьской Революции, 37А',
    locationSlug: 'ufa-spasskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.716912,
    longitude: 55.958901,
  },
  {
    name: 'Мечеть «Ихлас»',
    desc: 'Современный мусульманский культурно-просветительский центр с собственной радиостудией.',
    address: 'ул. Сочинская, 43',
    locationSlug: 'ufa-mechet-ihlas',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.708901,
    longitude: 55.969112,
  },
  {
    name: 'Покровский храм',
    desc: 'Старейшая из сохранившихся каменных церквей Уфы, построенная в стиле классицизма.',
    address: 'ул. Мингажева, 4',
    locationSlug: 'ufa-pokrovskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 54.714102,
    longitude: 55.965891,
  },

  // --- Парки и смотровые (37-43) ---
  {
    name: 'Парк культуры и отдыха им. Мажита Гафури',
    desc: 'Сосновый бор аттракционов с гигантским колесом обозрения «Седьмое небо».',
    address: 'проспект Октября, 77/1',
    locationSlug: 'ufa-park-mazhita-gafuri',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 54.771912,
    longitude: 56.022312,
  },
  {
    name: 'Парк Победы',
    desc: 'Мемориальный комплекс на высоком берегу Белой с танками и панорамой на Черниковку.',
    address: 'ул. Комарова, 7',
    locationSlug: 'ufa-park-pobedy',
    mustSeeFilter: 'park',
    visitMinutes: 50,
    latitude: 54.808912,
    longitude: 56.061112,
  },
  {
    name: 'Сад культуры и отдыха им. С. Т. Аксакова',
    desc: 'Исторический парк с живописным озером, где круглый год живут белые лебеди.',
    address: 'ул. Пушкина, 112/1',
    locationSlug: 'ufa-sad-aksakova',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 54.718102,
    longitude: 55.941912,
  },
  {
    name: 'Смотровая площадка у памятника Салавату Юлаеву',
    desc: 'Главная смотровая точка Уфы: излучина Белой и башкирские степи.',
    address: 'площадь Салавата Юлаева',
    locationSlug: 'ufa-smotrovaya-u-pamyatnika-salavatu',
    mustSeeFilter: 'views',
    visitMinutes: 25,
    latitude: 54.718312,
    longitude: 55.925102,
  },
  {
    name: 'Арт-квадрат',
    desc: 'Городской культурный центр под открытым небом, переделанный из старых купеческих дворов.',
    address: 'ул. Чернышевского, 88',
    locationSlug: 'ufa-art-kvadrat',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 54.728912,
    longitude: 55.945112,
  },
  {
    name: 'Случевская гора (Сад Салавата Юлаева)',
    desc: 'Тихий парк на холме со знаменитым висячим мостиком влюбленных.',
    address: 'ул. Тукаева, 48',
    locationSlug: 'ufa-sluchevskaya-gora',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 54.714902,
    longitude: 55.932901,
  },
  {
    name: 'Новая Уфимская Набережная',
    desc: 'Многоуровневый бетонный променад вдоль Белой для велосипедных и пеших прогулок.',
    address: 'ул. Набережная',
    locationSlug: 'ufa-novaya-ufimskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 54.710212,
    longitude: 55.943112,
  },

  // --- Гастрономия и театры (44-50) ---
  {
    name: 'Башкирский государственный академический театр драмы им. Мажита Гафури',
    desc: 'Главная театральная сцена республики в монументальном здании.',
    address: 'ул. Заки Валиди, 34',
    venueSlug: 'ufa-bashkirskiy-teatr-dramy-gafuri',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 54.719612,
    longitude: 55.940512,
  },
  {
    name: 'Башкирский государственный театр оперы и балета',
    desc: 'Историческое здание, где начинал мировой путь танцовщик Рудольф Нуреев.',
    address: 'ул. Ленина, 5/1',
    venueSlug: 'ufa-bashkirskiy-teatr-opery-i-baleta',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 54.724312,
    longitude: 55.943891,
  },
  {
    name: 'Ресторан «Kumpan Cafe»',
    desc: 'Культовая местная сеть со спешелти-кофе и пиццей на башкирском меду.',
    address: 'ул. Ленина, 60',
    locationSlug: 'ufa-kumpan-cafe',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 54.727912,
    longitude: 55.949801,
  },
  {
    name: 'Ресторан башкирской кухни «Aibat Hallyar»',
    desc: 'Современный фастфуд локальной кухни: башкирские кыстыбыи с кониной.',
    address: 'ул. Свердлова, 60/1',
    locationSlug: 'ufa-aibat-hallyar',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 54.723112,
    longitude: 55.944902,
  },
  {
    name: 'Ресторан «MusicHall27»',
    desc: 'Музыкальный ресторан и бар со стейками, винной картой и живыми рок-концертами.',
    address: 'ул. Кирова, 27',
    locationSlug: 'ufa-musichall27',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 54.727912,
    longitude: 55.955891,
  },
  {
    name: 'Музыкально-драматический театр «Нур»',
    desc: 'Татарский государственный театр в футуристичном здании на холме.',
    address: 'ул. 50 лет СССР, 36',
    venueSlug: 'ufa-teatr-nur',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 54.755891,
    longitude: 56.022312,
  },
  {
    name: 'Чайная «Матча комната»',
    desc: 'Скрытый минималистичный спот во дворах Арт-квадрата с азиатскими чаями и десертами.',
    address: 'ул. Чернышевского, 88 (блок Арт-Квадрат)',
    locationSlug: 'ufa-matcha-komnata',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 54.729112,
    longitude: 55.945891,
  },

  // --- Уникальные дополнения из второго списка (без дублей первого 50) ---
  {
    name: 'Уфимский Дом Союзов',
    desc: 'Величественное здание сталинского ампира с монументальной колоннадой на фасаде.',
    address: 'ул. Кирова, 1',
    locationSlug: 'ufa-dom-soyuzov',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.725901,
    longitude: 55.946811,
  },
  {
    name: 'Дом Шамовых',
    desc: 'Образец деревянного уфимского зодчества с пропильной резьбой на карнизах.',
    address: 'ул. Октябрьской Революции, 53',
    locationSlug: 'ufa-dom-shamovyh',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.716112,
    longitude: 55.959902,
  },
  {
    name: 'Дом жилой Поносовой-Молло',
    desc: 'Изящный особняк начала XX века, первый образец чистого модерна в Уфе.',
    address: 'ул. Карла Маркса, 6',
    locationSlug: 'ufa-dom-ponosovoy-mollo',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 54.721202,
    longitude: 55.936901,
  },
  {
    name: 'Театральный сквер',
    desc: 'Зеленая аллея с каскадом светомузыкальных фонтанов «Семь девушек» перед Оперным театром.',
    address: 'ул. Ленина / ул. Пушкина',
    locationSlug: 'ufa-fontan-sem-devushek',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 54.724811,
    longitude: 55.943112,
  },
  {
    name: 'Конгресс-холл «Торатау»',
    desc: 'Современное здание из стекла, напоминающее каплю или щит, у склонов парка «Ватан».',
    address: 'ул. Заки Валиди, 2',
    locationSlug: 'ufa-kongress-holl-toratau',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 54.718212,
    longitude: 55.923901,
  },
];

export const UFA_SUBURBS: any[] = [
  {
    name: 'Шульган-Таш (Капова пещера)',
    desc: 'Памятник палеолита мирового значения: подлинные наскальные рисунки охрой, энергия эпоса «Урал-батыр» и дикая уральская тайга.',
    locationSlug: 'ufa-shulgan-tash',
    mustSeeFilter: 'main',
    visitMinutes: '10-12 ч',
    latitude: 53.044102,
    longitude: 57.063891,
    address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
    travelVector: 'Авто ~4 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль ~4 часа, чтобы приехать к 11:00 утра.',
    timingNote:
      'По оборудованным тропам биосферного заповедника двигайтесь на восток вдоль скал к гигантскому порталу пещеры, напоследок оставив интерактивную экспозицию суперсовременного хай-тек музея.',
    places: [
      {
        name: 'Главный научно-музейный комплекс «Шульган-Таш»',
        desc: 'Футуристичное здание с мультимедийными залами, воссоздающими пещеру в 3D.',
        locationSlug: 'ufa-shulgan-tash-muzeynyy-kompleks',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 60,
      },
      {
        name: 'Портал Каповой пещеры',
        desc: 'Впечатляющая тридцатиметровая входная арка в скале.',
        locationSlug: 'ufa-shulgan-tash-portal-kapovoy-peschery',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 20,
      },
      {
        name: 'Зал наскальной живописи',
        desc: 'Внутренние галереи с копиями рисунков мамонтов и лошадей. Оригиналы закрыты ради сохранности.',
        locationSlug: 'ufa-shulgan-tash-zal-naskalnoy-zhivopisi',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 40,
      },
      {
        name: 'Голубое озеро',
        desc: 'Карстовый глубокий водоем у входа в пещеру с кристально чистой минеральной водой.',
        locationSlug: 'ufa-shulgan-tash-goluboe-ozero',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 15,
      },
      {
        name: 'Музей башкирской бортевой пчелы',
        desc: 'Деревянный интерактивный павильон о добыче дикого меда.',
        locationSlug: 'ufa-shulgan-tash-muzey-bortevoy-pchely',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 25,
      },
      {
        name: 'Смотровой мост через реку Белую',
        desc: 'Пешеходный подвесной переход с видом на горные хребты.',
        locationSlug: 'ufa-shulgan-tash-smotrovoy-most',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 15,
      },
      {
        name: 'Колода-борть',
        desc: 'Исторический улей, вырубленный прямо в стволе живого дерева.',
        locationSlug: 'ufa-shulgan-tash-koloda-bort',
        address: 'Башкортостан, Бурзянский район, дер. Иргизлы',
        latitude: 53.044102,
        longitude: 57.063891,
        visitMinutes: 10,
      },
    ],
  },
  {
    name: 'Шихан Торатау',
    desc: 'Священный древний шихан - остаток рифа доисторического океана 250 миллионов лет назад. С вершины открывается космический вид на башкирскую степь.',
    locationSlug: 'ufa-toratau',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 53.554312,
    longitude: 56.101112,
    address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
    travelVector: 'Авто / автобус ~1.5 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль или экспресс-автобус до Стерлитамака ~1.5 часа, чтобы приехать к 09:30 утра.',
    timingNote:
      'По экологической деревянной лестнице на склоне двигайтесь строго вверх на вершину горы, напоследок оставив осмотр руин лагеря ГУЛАГа у подножия.',
    places: [
      {
        name: 'Экотропа Торатау',
        desc: 'Благоустроенная лестница, защищающая редкие эндемичные растения горы от вытаптывания.',
        locationSlug: 'ufa-toratau-ekotropa',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 40,
      },
      {
        name: 'Вершина шихана',
        desc: 'Плоская каменистая смотровая площадка на высоте более 400 метров.',
        locationSlug: 'ufa-toratau-vershina',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 30,
      },
      {
        name: 'Остатки построек Салаватского отделения ГУЛАГа',
        desc: 'Тяжелое историческое место - руины бараков у подножия скалы.',
        locationSlug: 'ufa-toratau-gulag',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 20,
      },
      {
        name: 'Визит-центр «Торатау»',
        desc: 'Круглый павильон с кофейней, сувенирами и туалетами.',
        locationSlug: 'ufa-toratau-vizit-tsentr',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 20,
      },
      {
        name: 'Озеро Тугар-Салган',
        desc: 'Глубокое карстовое озеро круглой формы у самого основания шихана.',
        locationSlug: 'ufa-toratau-ozero-tugar-salgan',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 20,
      },
      {
        name: 'Площадка парапланеристов',
        desc: 'Место старта экстремалов, парящих на фоне степных просторов.',
        locationSlug: 'ufa-toratau-paraplan',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 15,
      },
      {
        name: 'Кочевье Торатау',
        desc: 'Юртовый комплекс, где можно примерить башкирские костюмы и пострелять из традиционного лука.',
        locationSlug: 'ufa-toratau-kochevye',
        address: 'Башкортостан, Ишимбайский район, близ деревни Урман-Бишкадаш',
        latitude: 53.554312,
        longitude: 56.101112,
        visitMinutes: 30,
      },
    ],
  },
  {
    name: 'Мурадымовское ущелье',
    desc: 'Большой природный выезд в известняковое ущелье с пещерами, рекой и лучшими известными видами южного Урала.',
    locationSlug: 'ufa-muradymovskoe-ushchele',
    mustSeeFilter: 'main',
    visitMinutes: '10-12 ч',
    latitude: 52.587112,
    longitude: 56.628112,
    address: 'Башкортостан, природный парк «Мурадымовское ущелье»',
    travelVector: 'Только авто ~4-5 ч',
    travelVectorBlurb: 'Это дальний маршрут на целый день. Выезд рано утром обязателен.',
    timingNote: 'Сначала визит-центр и экотропы, затем пещеры и смотровые над рекой.',
    places: [
      { name: 'Главное ущелье', desc: 'Ключевой ландшафт с известняковыми бортами и рекой Бол. Ик.', locationSlug: 'ufa-glavnoe-uschele', visitMinutes: 50 },
      { name: 'Ново-Мурадымовская пещера', desc: 'Самая известная пещера парка с оборудованным подходом.', locationSlug: 'ufa-novo-muradymovskaya-peschera', visitMinutes: 40 },
      { name: 'Смотровая над долиной', desc: 'Лучший кадр на изгибы ущелья и леса.', locationSlug: 'ufa-smotrovaya-nad-dolinoy', visitMinutes: 30 },
      { name: 'Экотропа вдоль реки', desc: 'Пеший маршрут, который лучше всего объясняет масштаб парка.', locationSlug: 'ufa-ekotropa-vdol-reki', visitMinutes: 60 },
    ],
  },
  {
    name: 'Розовые скалы и Инзер',
    desc: 'Редкий башкирский маршрут ради каменных гребней, речных видов и длинного пейзажного выезда в горную часть региона.',
    locationSlug: 'ufa-rozovye-skaly-inzer',
    mustSeeFilter: 'main',
    visitMinutes: '10-12 ч',
    latitude: 54.233112,
    longitude: 57.612112,
    address: 'Башкортостан, район Инзера',
    travelVector: 'Электричка + авто или авто ~4 ч',
    travelVectorBlurb: 'Маршрут длинный, но очень фотогеничный. Лучше ехать в сухую погоду.',
    timingNote: 'Утром к скалам, затем виды на реку Инзер и длинная пешая часть по лесу.',
    places: [
      { name: 'Розовые скалы', desc: 'Главная геологическая цель маршрута с узнаваемым цветом породы.', locationSlug: 'ufa-rozovye-skaly', visitMinutes: 45 },
      { name: 'Панорама Инзера', desc: 'Обзорная точка над рекой и лесистыми склонами.', locationSlug: 'ufa-panorama-inzera', visitMinutes: 30 },
      { name: 'Лесная тропа к хребту', desc: 'Переход без городской инфраструктуры, ради которого и едут.', locationSlug: 'ufa-lesnaya-tropa-k-hrebtu', visitMinutes: 60 },
      { name: 'Береговая поляна', desc: 'Тихая остановка у воды перед дорогой обратно.', locationSlug: 'ufa-beregovaya-polyana', visitMinutes: 25 },
    ],
  },
];

export const UFA_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'ufa-agidel-heart',
    title: 'Сердце Агидели и башкирский масштаб',
    description:
      'Ознакомительный классический трек по главным парадным видовым точкам Уфы, спускающийся от правительственного квартала к речным просторам.',
    travelVector: 'Парадный пешеходный променад',
    timingNote:
      'Около 3 часов: Шаймуратов - Национальный музей - опера - Aibat Hallyar - Салават и смотровая.',
    stops: [
      {
        name: 'Памятник генералу Шаймуратову',
        desc: '15 минут на осмотр грандиозной колоннады на Советской площади.',
        locationSlug: 'ufa-pamyatnik-generalu-shaymuratovu',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'Советская площадь',
        latitude: 54.719891,
        longitude: 55.949102,
      },
      {
        name: 'Национальный музей Республики Башкортостан',
        desc: 'Час на изучение золота сарматов и древних юрт.',
        locationSlug: 'ufa-natsionalnyy-muzey',
        mustSeeFilter: 'museum',
        visitMinutes: 60,
        address: 'ул. Советская, 14',
        latitude: 54.719612,
        longitude: 55.946111,
        transitTip: 'Пешком 7 минут',
      },
      {
        name: 'Башкирский театр оперы и балета',
        desc: '10 минут на осмотр барельефов Рудольфа Нуреева.',
        venueSlug: 'ufa-bashkirskiy-teatr-opery-i-baleta',
        mustSeeFilter: 'creative',
        visitMinutes: 10,
        address: 'ул. Ленина, 5/1',
        latitude: 54.724312,
        longitude: 55.943891,
        transitTip: 'Пешком 6 минут',
      },
      {
        name: 'Ресторан башкирской кухни «Aibat Hallyar»',
        desc: '30 минут на обед быстрыми башкирскими кыстыбыями.',
        locationSlug: 'ufa-aibat-hallyar',
        mustSeeFilter: 'gastro',
        visitMinutes: 30,
        address: 'ул. Свердлова, 60/1',
        latitude: 54.723112,
        longitude: 55.944902,
        transitTip: 'Пешком 4 минуты',
      },
      {
        name: 'Памятник Салавату Юлаеву и смотровая площадка',
        desc: '40 минут на фото у культового всадника и панораму реки Белой.',
        locationSlug: 'ufa-pamyatnik-salavatu-yulaevu',
        mustSeeFilter: 'main',
        visitMinutes: 40,
        address: 'ул. Набережная (Площадь Салавата Юлаева)',
        latitude: 54.718612,
        longitude: 55.926111,
        transitTip: 'Пешком 12 минут через сквер',
      },
    ],
  },
  {
    id: 'ufa-avantgarde-rock',
    title: 'Уфимский авангард, рок и Арт-квадрат',
    description:
      'Молодежный творческий трек: столица уральского музыкального бунта, модерн и урбанистика дворов.',
    travelVector: 'Рок, модерн и стрит-арт',
    timingNote: 'Около 3 часов; вечером стоит задержаться в Арт-квадрате или MusicHall27.',
    stops: [
      {
        name: 'Памятник Мустаю Кариму',
        desc: '15 минут у памятника с каскадными книжными листами.',
        locationSlug: 'ufa-pamyatnik-mustayu-karimu',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'ул. Кирова, 1 (перед Домом профсоюзов)',
        latitude: 54.726612,
        longitude: 55.946905,
      },
      {
        name: 'Особняк Костерина и Черникова',
        desc: '15 минут на уфимский модерн.',
        locationSlug: 'ufa-osobnyak-kosterina-i-chernikova',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'ул. Пушкина, 86',
        latitude: 54.726112,
        longitude: 55.945102,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Музей рока в кинотеатре «Родина»',
        desc: '30 минут на историю Шевчука и Земфиры.',
        locationSlug: 'ufa-muzey-roka-kinoteatr-rodina',
        mustSeeFilter: 'museum',
        visitMinutes: 30,
        address: 'ул. Ленина, 42',
        latitude: 54.728901,
        longitude: 55.950112,
        transitTip: 'Пешком 4 минуты',
      },
      {
        name: 'Арт-квадрат',
        desc: 'Полтора часа на стрит-арт, секретные дворики и сувениры.',
        locationSlug: 'ufa-art-kvadrat',
        mustSeeFilter: 'park',
        visitMinutes: 90,
        address: 'ул. Чернышевского, 88',
        latitude: 54.728912,
        longitude: 55.945112,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Чайная «Матча комната»',
        desc: '30 минут на матча-латте во дворе-колодце.',
        locationSlug: 'ufa-matcha-komnata',
        mustSeeFilter: 'gastro',
        visitMinutes: 30,
        address: 'ул. Чернышевского, 88 (блок Арт-Квадрат)',
        latitude: 54.729112,
        longitude: 55.945891,
        transitTip: 'Пешком 2 минуты внутри кластера',
      },
    ],
  },
  ...UFA_LINE_DAY_ROUTE_PRESETS,
];

export const UFA_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Почему в Уфе ж/д вокзал находится в таком неудобном месте и как от него уехать в центр без штурма холмов?',
    a: 'Уфимский вокзал отрезан от центра крутым Случевским холмом. Подниматься пешком с чемоданами по лестницам тяжело. Главный лайфхак: прямо от терминала садитесь на трамвай №1 или №10 - они медленно, но верно поднимут вас по пологому склону к Гостиному двору. Также работают автобусы №74 и №101.',
  },
  {
    q: 'Что за история со строящейся мечетью «Ар-Рахим» и почему её никак не могут открыть?',
    a: 'Мечеть «Ар-Рахим» на въезде в город - главный архитектурный долгострой Уфы. Строительство гигантского собора с куполом в виде ханской шапки началось еще в 2007 году, но постоянно замораживалось из-за финансовых скандалов и судов застройщиков. Мечеть почти готова снаружи, но внутренняя отделка ждет своего часа годами.',
  },
  {
    q: 'Где в Уфе найти те самые дворы и места, связанные с Земфирой и Юрием Шевчуком?',
    a: 'Дом, где росла Земфира Рамазанова, находится в спальном районе Черниковка по адресу ул. Ушакова, 64: в подъезде фанаты устроили неофициальную стену памяти. Юрий Шевчук и группа ДДТ репетировали и давали первые концерты в ДК «Авангард» на Левом берегу. Дух уфимского рока лучше всего искать на выставке в Музее рока в кинотеатре «Родина».',
  },
  {
    q: 'Правда ли, что Уфа - самый просторный и растянутый город-миллионник России?',
    a: 'Почти правда. Уфа входит в топ-5 самых протяженных городов страны. Город вытянут по хребту полуострова между реками более чем на 50 километров. Из-за этой линейной структуры здесь два обособленных центра - исторический южный (Гостиный двор) и индустриальный северный (Черниковка). На такси и автобусы между районами закладывайте не менее 40-50 минут.',
  },
];

export const UFA_TRAVEL =
  'Международный аэропорт Уфы имени Мустая Карима: прямые рейсы из Москвы около 2 часов, плюс Петербург и курорты. Железная дорога на ходе Транссиба, авто - трассы М-5 «Урал» и М-7 «Волга». Зима -12...-15 °C: «Олимпик Парк» в черте города и ледовые городки у площади Салавата Юлаева. Весна: черемуха и к маю +18 °C, в мае запускают прогулки по Белой и Уфе. Лето часто за +30 °C: веранды Чернышевского, озера и шиханы. Осень: золото и багрянец, меньше очередей на смотровых, перелеты и отели дешевле.';
