/** Volgograd tourist hub pack (owner 2026-08-21). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { VOLGOGRAD_LINE_DAY_ROUTE_PRESETS } from './volgograd-line-presets.ts';

export const VOLGOGRAD_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Скульптура «Родина-мать зовёт!»',
    desc: 'Главный монумент Мамаева кургана: 85-метровый стальной силуэт женщины с мечом.',
    address: 'Мамаев курган',
    locationSlug: 'volgograd-mamaev-kurgan',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 48.74241,
    longitude: 44.537021,
  },
  {
    name: 'Скульптура «Стоять насмерть»',
    desc: 'Брутальный образ воина-богатыря у подножия кургана.',
    address: 'Мамаев курган, площадь Стоявших насмерть',
    locationSlug: 'volgograd-stoyat-nasmert',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 48.741912,
    longitude: 44.540115,
  },
  {
    name: 'Памятник Михаилу Паникахе',
    desc: 'Драматический монумент морскому пехотинцу, бросившемуся под танк в пламени.',
    address: 'пересечение ул. Таращанцев и ул. Богунской',
    locationSlug: 'volgograd-pamyatnik-panikakhe',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 48.767812,
    longitude: 44.549812,
  },
  {
    name: 'Скульптурная композиция «Скорбь матери»',
    desc: 'Фигура матери у озера Слёз на площади Скорби.',
    address: 'Мамаев курган, площадь Скорби',
    locationSlug: 'volgograd-skorb-materi',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 48.742314,
    longitude: 44.538511,
  },
  {
    name: 'Памятник Хользунову',
    desc: 'Бронзовый монумент летчику-герою Гражданской войны у центральной набережной.',
    address: 'ул. Маршала Чуйкова (у центральной набережной)',
    locationSlug: 'volgograd-pamyatnik-holzunovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.704212,
    longitude: 44.519912,
  },
  {
    name: 'Памятник мирным жителям Сталинграда',
    desc: 'Строгий гранитный монумент женщинам и детям, погибшим под бомбардировками.',
    address: 'ул. Маршала Чуйкова / ул. Комсомольская',
    locationSlug: 'volgograd-pamyatnik-mirnym-zhitelyam',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 48.707125,
    longitude: 44.524114,
  },
  {
    name: 'Арт-объект «Клеймо войны»',
    desc: 'Деформированные конструкции на месте боев за завод «Красный Октябрь».',
    address: 'просп. им. В.И. Ленина, 110',
    locationSlug: 'volgograd-kleymo-voyny',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 48.762145,
    longitude: 44.551235,
  },
  {
    name: 'Памятник собакам-подрывникам',
    desc: 'Единственный в России памятник четвероногим бойцам 10-й дивизии НКВД.',
    address: 'площадь Чекистов',
    locationSlug: 'volgograd-pamyatnik-sobakam-podryvnikam',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.697812,
    longitude: 44.509614,
  },
  {
    name: 'Памятник Александру Невскому',
    desc: 'Бронзовый образ небесного покровителя города у кафедрального собора.',
    address: 'площадь Павших Борцов',
    locationSlug: 'volgograd-pamyatnik-aleksandru-nevskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.708812,
    longitude: 44.514515,
  },
  {
    name: 'Памятник Виктору Хользунову на набережной',
    desc: 'Копия монумента на обновленной террасе Набережной 62-й Армии.',
    address: 'Набережная 62-й Армии',
    locationSlug: 'volgograd-pamyatnik-holzunovu-naberezhnaya',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.703456,
    longitude: 44.52112,
  },
  {
    name: 'Скульптура «Знамя Победы»',
    desc: 'Арт-объект у музея-панорамы, символизирующий водружение штурмового флага.',
    address: 'ул. имени Маршала Чуйкова, 47',
    locationSlug: 'volgograd-znamya-pobedy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.71512,
    longitude: 44.53389,
  },
  {
    name: 'Памятник Т-34 «Челябинский колхозник»',
    desc: 'Исторический танк на северо-западном склоне Мамаева кургана.',
    address: 'Мамаев курган, верхний плато-сквер',
    locationSlug: 'volgograd-t-34-chelyabinskiy-kolkhoznik',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 48.743112,
    longitude: 44.535124,
  },
  {
    name: 'Памятник Засекину',
    desc: 'Монумент первому воеводе Царицына Григорию Засекину.',
    address: 'пересечение просп. им. Ленина и ул. Порт-Саида',
    locationSlug: 'volgograd-pamyatnik-zasekinu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.711112,
    longitude: 44.519812,
  },
  {
    name: 'Памятник Сантехнику',
    desc: 'Ироничный уличный арт-объект: мастер выглядывает из канализационного люка.',
    address: 'просп. имени В.И. Ленина, 2А',
    locationSlug: 'volgograd-pamyatnik-santekhniku',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 48.703145,
    longitude: 44.512812,
  },
  {
    name: 'Памятник Ленину у Волго-Донского канала',
    desc: 'Крупнейший в мире памятник реально жившему человеку у шлюзов канала.',
    address: 'ул. Фадеева, Красноармейский район',
    locationSlug: 'volgograd-pamyatnik-leninu-volgo-don',
    mustSeeFilter: 'monument',
    visitMinutes: 20,
    latitude: 48.528114,
    longitude: 44.556124,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Мельница Гергардта',
    desc: 'Полуразрушенное краснокирпичное здание, оставленное как свидетель Сталинградской битвы.',
    address: 'ул. имени Маршала Чуйкова, 47А',
    locationSlug: 'volgograd-mel-nitsa-gergardta',
    mustSeeFilter: 'houses',
    visitMinutes: 25,
    latitude: 48.716112,
    longitude: 44.532345,
  },
  {
    name: 'Дом Павлова',
    desc: 'Жилой дом, гарнизон которого держал оборону 58 дней.',
    address: 'ул. Советская, 39',
    locationSlug: 'volgograd-dom-pavlova',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 48.716214,
    longitude: 44.530956,
  },
  {
    name: 'Центральный Универмаг (подвал ЦУМа)',
    desc: 'Место, где в январе 1943 года пленили фельдмаршала Паулюса.',
    address: 'площадь Павших Борцов, 2',
    locationSlug: 'volgograd-tsentralnyy-univermag',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 48.708212,
    longitude: 44.513512,
  },
  {
    name: 'Пожарная каланча Царицына',
    desc: 'Отреставрированное краснокирпичное здание пожарной части конца XIX века.',
    address: 'ул. Коммунистическая, 5',
    locationSlug: 'volgograd-pozharnaya-kalancha',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 48.711345,
    longitude: 44.513612,
  },
  {
    name: 'Мемориально-исторический музей (Особняк Репниковой)',
    desc: 'Единственный в городе купеческий особняк начала XX века, уцелевший в войну.',
    address: 'ул. Гоголя, 10',
    locationSlug: 'volgograd-osobnyak-repnikovoy',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 48.712125,
    longitude: 44.512812,
  },
  {
    name: 'Сталинградский тополь',
    desc: 'Черный тополь на Аллее Героев с сотнями осколков в стволе.',
    address: 'Аллея Героев',
    locationSlug: 'volgograd-stalingradskiy-topol',
    mustSeeFilter: 'houses',
    visitMinutes: 10,
    latitude: 48.707312,
    longitude: 44.515125,
  },
  {
    name: 'Железнодорожный вокзал Волгоград-1',
    desc: 'Шедевр сталинского ампира с башней, шпилем и потолочными фресками.',
    address: 'Привокзальная площадь, 1',
    locationSlug: 'volgograd-vokzal-volgograd-1',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 48.712915,
    longitude: 44.511125,
  },

  // --- Музеи (23-27) ---
  {
    name: 'Музей-панорама «Сталинградская битва»',
    desc: 'Грандиозный комплекс с крупнейшим в РФ живописным полотном панорамы и техникой.',
    address: 'ул. имени Маршала Чуйкова, 47',
    venueSlug: 'volgograd-muzey-panorama-stalingradskaya-bitva',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 48.715444,
    longitude: 44.532626,
  },
  {
    name: 'Музей изобразительных искусств им. И.И. Машкова',
    desc: 'Главная художественная галерея города с коллекцией русского авангарда.',
    address: 'просп. имени В.И. Ленина, 21',
    venueSlug: 'volgograd-muzey-mashkova',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 48.709124,
    longitude: 44.521956,
  },
  {
    name: 'Музей «Память»',
    desc: 'Экспозиция в аутентичном подвале ЦУМа на месте пленения генералитета 6-й армии.',
    address: 'площадь Павших Борцов, 2 (подвал)',
    venueSlug: 'volgograd-muzey-pamyat',
    mustSeeFilter: 'museum',
    visitMinutes: 40,
    latitude: 48.708239,
    longitude: 44.513488,
  },
  {
    name: 'Волгоградский планетарий',
    desc: 'Здание сталинской эпохи с куполом и скульптурой Веры Мухиной «Мир».',
    address: 'ул. Гагарина, 14',
    venueSlug: 'volgograd-planetariy',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 48.714093,
    longitude: 44.524025,
  },
  {
    name: 'Музей-заповедник «Старая Сарепта»',
    desc: 'Архитектурный комплекс из 26 зданий бывшей колонии гернгутеров XVIII века.',
    address: 'ул. Изобильная, 10 (Красноармейский район)',
    locationSlug: 'volgograd-staraya-sarepta',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 48.517307,
    longitude: 44.517838,
  },

  // --- Храмы (28-31) ---
  {
    name: 'Кафедральный собор Александра Невского',
    desc: 'Золотоглавый собор византийского стиля, воссозданный в центре площади Павших Борцов.',
    address: 'площадь Павших Борцов',
    locationSlug: 'volgograd-sobor-aleksandra-nevskogo',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 48.708621,
    longitude: 44.5141,
  },
  {
    name: 'Храм Иоанна Предтечи',
    desc: 'Первая каменная церковь Царицына, заново отстроенная на склоне набережной.',
    address: 'ул. Краснопитерская, 1А',
    locationSlug: 'volgograd-hram-ioanna-predtechi',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 48.702148,
    longitude: 44.516516,
  },
  {
    name: 'Казанский кафедральный собор',
    desc: 'Дореволюционный псевдорусский собор из красного кирпича, переживший войну.',
    address: 'ул. Липецкая, 10',
    locationSlug: 'volgograd-kazanskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 48.692801,
    longitude: 44.491354,
  },
  {
    name: 'Никитская церковь',
    desc: 'Старейший сохранившийся храм Волгограда (1795 год) в Кировском районе.',
    address: 'ул. Абганеровская, 110А (Кировский район)',
    locationSlug: 'volgograd-nikitskaya-tserkov',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 48.591552,
    longitude: 44.431662,
  },

  // --- Парки и смотровые (32-39) ---
  {
    name: 'Центральная набережная им. 62-й Армии',
    desc: 'Двухъярусный речной променад с парадной пропилейной лестницей и фонтаном «Искусство».',
    address: 'Набережная 62-й Армии',
    locationSlug: 'volgograd-tsentral-naya-naberezhnaya-imeni-62-y-armii',
    mustSeeFilter: 'main',
    visitMinutes: 45,
    latitude: 48.704422,
    longitude: 44.522343,
  },
  {
    name: 'Зал Воинской Славы',
    desc: 'Круглый пантеон на Мамаевом кургане со скорбной рукой и Вечным огнем.',
    address: 'Мамаев курган, центральная площадь',
    locationSlug: 'volgograd-zal-voinskoy-slavy',
    mustSeeFilter: 'main',
    visitMinutes: 30,
    latitude: 48.742389,
    longitude: 44.537606,
  },
  {
    name: 'Комсомольский сад',
    desc: 'Старейший зеленый парк в центре, уцелевший от исторического Царицына.',
    address: 'ул. Коммунистическая / ул. Володарского',
    locationSlug: 'volgograd-komsomolskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 48.708122,
    longitude: 44.511118,
  },
  {
    name: 'Центральный парк культуры и отдыха (ЦПКиО)',
    desc: 'Прибрежный ландшафтный парк с колесом обозрения и видом на «Волгоград Арену».',
    address: 'ул. Батальонная, 4',
    locationSlug: 'volgograd-tspkio',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 48.730445,
    longitude: 44.54451,
  },
  {
    name: 'Аллея Героев',
    desc: 'Широкий пешеходный бульвар с тополем-героем и светящимся небом.',
    address: 'Аллея Героев',
    locationSlug: 'volgograd-alleya-geroev',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 48.707703,
    longitude: 44.516105,
  },
  {
    name: 'Смотровая площадка Мамаева кургана',
    desc: 'Верхняя точка у подножия Родины-матери: панорама Волги и стадиона.',
    address: 'Мамаев курган, вершина',
    locationSlug: 'volgograd-smotrovaya-mamaeva-kurgana',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 48.742076,
    longitude: 44.536605,
  },
  {
    name: 'Парк «Раздолье»',
    desc: 'Современный эко-парк в пойме реки Царицы с сухими фонтанами и зонами отдыха.',
    address: 'пойма реки Царицы',
    locationSlug: 'volgograd-park-razdole',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 48.702045,
    longitude: 44.511456,
  },
  {
    name: 'Сквер имени Саши Филиппова',
    desc: 'Уютный сквер в Ворошиловском районе в честь юного разведчика Сталинграда.',
    address: 'ул. Рабоче-Крестьянская',
    locationSlug: 'volgograd-skver-sashi-filippova',
    mustSeeFilter: 'park',
    visitMinutes: 20,
    latitude: 48.699436,
    longitude: 44.50592,
  },

  // --- Гастрономия и театры (40-50) ---
  {
    name: 'Новый экспериментальный театр (НЭТ)',
    desc: 'Театр драмы в историческом неоклассическом здании Дома науки Репникова.',
    address: 'ул. Мира, 5',
    locationSlug: 'volgograd-net-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 48.708464,
    longitude: 44.512303,
  },
  {
    name: 'Царицынская опера',
    desc: 'Оперный театр в помпезном сталинском дворце культуры с коринфскими колоннами.',
    address: 'просп. имени В.И. Ленина, 97',
    venueSlug: 'volgograd-tsaritsynskaya-opera',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 48.756442,
    longitude: 44.548165,
  },
  {
    name: 'Ресторан «Волгоград»',
    desc: 'Легендарный ресторан с советскими дворцовыми интерьерами на площади Павших Борцов.',
    address: 'ул. Мира, 12',
    locationSlug: 'volgograd-restoran-volgograd',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 48.708115,
    longitude: 44.512602,
  },
  {
    name: 'Ресторан «Река»',
    desc: 'Панорамный ресторан высокой кухни в шайбе речного вокзала над Волгой.',
    address: 'Набережная 62-й Армии, 6',
    locationSlug: 'volgograd-restoran-reka',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 48.701631,
    longitude: 44.520112,
  },
  {
    name: 'Гастробар «Булгаков»',
    desc: 'Авторские коктейли и переосмысленная русская кухня в центре.',
    address: 'ул. Ополовникова, 1',
    locationSlug: 'volgograd-gastrobar-bulgakov',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 48.709456,
    longitude: 44.518619,
  },
  {
    name: 'Ресторан «Швейн»',
    desc: 'Пивной трактир с сытными немецкими блюдами и крафтом.',
    address: 'ул. Краснознаменская, 7',
    locationSlug: 'volgograd-restoran-shveyn',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 48.702823,
    longitude: 44.511817,
  },
  {
    name: 'Кофейня «Angel Cakes»',
    desc: 'Спешелти-кофе и десерты со светлым интерьером на набережной.',
    address: 'ул. имени Маршала Чуйкова, 19',
    locationSlug: 'volgograd-angel-cakes',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 48.706043,
    longitude: 44.519501,
  },
  {
    name: 'Волгоградский музыкальный театр',
    desc: 'Старейший музыкальный театр на Волге, сцена прямо на набережной.',
    address: 'ул. имени Маршала Чуйкова, 4',
    venueSlug: 'volgograd-muzykalnyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 48.703166,
    longitude: 44.517921,
  },
  {
    name: 'Стейк-хаус «Bar&Grill»',
    desc: 'Премиальное мясное заведение с открытым грилем в центре.',
    address: 'ул. Мира, 20',
    locationSlug: 'volgograd-bar-and-grill',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 48.71189,
    longitude: 44.515455,
  },
  {
    name: 'Кафе «Маруся»',
    desc: 'Семейное кафе с современной русской кухней и завтраками у Комсомольского сада.',
    address: 'ул. Мира, 26',
    locationSlug: 'volgograd-kafe-marusya',
    mustSeeFilter: 'gastro',
    visitMinutes: 45,
    latitude: 48.712788,
    longitude: 44.516875,
  },
  {
    name: 'Волгоградский областной театр кукол',
    desc: 'Камерный театр с богатой историей в красивом историческом здании.',
    address: 'просп. имени В.И. Ленина, 15',
    venueSlug: 'volgograd-teatr-kukol',
    mustSeeFilter: 'creative',
    visitMinutes: 60,
    latitude: 48.707421,
    longitude: 44.518456,
  },

  // --- Доп. точка для идентики / Красной линии ---
  {
    name: 'Волгоградский метротрам',
    desc: 'Единственная в РФ подземка-метротрам: мраморные станции и чехословацкие вагоны Татра.',
    address: 'линия скоростного трамвая (станция «Комсомольская»)',
    locationSlug: 'volgograd-volgogradskiy-metrotram',
    mustSeeFilter: 'main',
    visitMinutes: 30,
    latitude: 48.70932,
    longitude: 44.51785,
  },
  {
    name: 'Арт-пространство «Икра»',
    desc: 'Креативный кластер с галереями, студиями и кофейнями в речном вокзале.',
    address: 'Набережная 62-й Армии, 6',
    locationSlug: 'volgograd-art-prostranstvo-ikra',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 48.70185,
    longitude: 44.51934,
  },
];

export const VOLGOGRAD_SUBURBS: any[] = [
  {
    name: 'Музей-заповедник «Старая Сарепта»',
    desc: 'Идеально сохранившийся уголок Европы XVIII века посреди степного Поволжья: колония гернгутеров, кирха, горчица и мистические подвалы.',
    locationSlug: 'volgograd-suburb-staraya-sarepta',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 48.517307,
    longitude: 44.517838,
    address: 'Волгоград, ул. Изобильная, 10',
    travelVector: 'Электричка ~50 мин',
    travelVectorBlurb:
      'Закладывайте на городскую электричку из центра Волгограда ~50 минут, чтобы приехать к 09:30 утра.',
    timingNote:
      'От ж/д станции Красноармейская двигайтесь пешком на восток к площади Свободы, напоследок оставив покупку аутентичного горчичного масла в местной лавке.',
    places: [
      {
        name: 'Сарептская кирха',
        desc: 'Старейшая действующая лютеранская церковь региона с подлинным органом.',
        locationSlug: 'volgograd-sarepta-kirkha',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.517307,
        longitude: 44.517838,
        visitMinutes: 30,
      },
      {
        name: 'Дом сарептского аптекаря',
        desc: 'Аутентичная лаборатория с сушеными травами и старинными весами.',
        locationSlug: 'volgograd-sarepta-dom-aptekaarya',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.5174,
        longitude: 44.518,
        visitMinutes: 25,
      },
      {
        name: 'Мистические подвалы Рейнгольда',
        desc: 'Подземные хранилища с легендами о местных привидениях.',
        locationSlug: 'volgograd-sarepta-podvaly-reyngolda',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.5172,
        longitude: 44.5177,
        visitMinutes: 30,
      },
      {
        name: 'Музей горчицы',
        desc: 'Экспозиция об истории первой русской горчицы и отжиме масла.',
        locationSlug: 'volgograd-sarepta-muzey-gorchitsy',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.5175,
        longitude: 44.5179,
        visitMinutes: 25,
      },
      {
        name: 'Дом холостых братьев',
        desc: 'Историческое общинное здание с бытом колонистов.',
        locationSlug: 'volgograd-sarepta-dom-holostyh-bratyev',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.5171,
        longitude: 44.5181,
        visitMinutes: 20,
      },
      {
        name: 'Винокурня',
        desc: 'Каменная постройка, где производили сарептские бальзамы.',
        locationSlug: 'volgograd-sarepta-vinokurnya',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.5176,
        longitude: 44.5176,
        visitMinutes: 20,
      },
      {
        name: 'Памятник Горчичному зерну',
        desc: 'Маленький уличный арт-объект, исполняющий желания.',
        locationSlug: 'volgograd-sarepta-pamyatnik-gorchichnomu-zernu',
        address: 'Волгоград, ул. Изобильная, 10',
        latitude: 48.51735,
        longitude: 44.51795,
        visitMinutes: 10,
      },
    ],
  },
  {
    name: 'Волжская ГЭС и город Волжский',
    desc: 'Колоссальный памятник советскому гидростроению: плотина, шлюзы Волго-Дона и соцгород Волжский с ретро-парками.',
    locationSlug: 'volgograd-suburb-volzhskaya-ges',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 48.823412,
    longitude: 44.671114,
    address: 'г. Волжский, проспект им. Ленина, 1А',
    travelVector: 'Такси / маршрутка 160 ~35 мин',
    travelVectorBlurb:
      'Закладывайте на такси или маршрутку №160 ~35 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'На автомобиле двигайтесь по плотине через русло Волги, сделав остановку на смотровой площадке, напоследок оставив прогулку по историческому первому кварталу соцгорода Волжского.',
    places: [
      {
        name: 'Смотровая площадка ГЭС',
        desc: 'Точка на левом берегу с видом на водосбросы плотины.',
        locationSlug: 'volgograd-ges-smotrovaya',
        address: 'г. Волжский, плотина Волжской ГЭС',
        latitude: 48.823412,
        longitude: 44.671114,
        visitMinutes: 30,
      },
      {
        name: 'Монумент строителям коммунизма',
        desc: 'Гигантская 10-метровая стальная скульптура на въезде в Волжский.',
        locationSlug: 'volgograd-ges-monument-stroitelyam',
        address: 'г. Волжский, въезд',
        latitude: 48.785,
        longitude: 44.775,
        visitMinutes: 15,
      },
      {
        name: 'Шлюзы Волго-Донского канала',
        desc: 'Массивные бетонные камеры для прохода барж и теплоходов.',
        locationSlug: 'volgograd-ges-shlyuzy-volgo-don',
        address: 'Волго-Донской судоходный канал',
        latitude: 48.5285,
        longitude: 44.5565,
        visitMinutes: 30,
      },
      {
        name: 'Дворец культуры ВГС',
        desc: 'Шедевр дворцового советского классицизма в старой части Волжского.',
        locationSlug: 'volgograd-ges-dvorets-kultury-vgs',
        address: 'г. Волжский, старая часть',
        latitude: 48.7855,
        longitude: 44.7762,
        visitMinutes: 25,
      },
      {
        name: 'Парк «Гидростроитель»',
        desc: 'Ретро-парк со старинными фонтанами и гипсовыми статуями.',
        locationSlug: 'volgograd-ges-park-gidrostroitel',
        address: 'г. Волжский, парк «Гидростроитель»',
        latitude: 48.7862,
        longitude: 44.7771,
        visitMinutes: 30,
      },
      {
        name: 'Краеведческий музей Волжского',
        desc: 'Экспозиция о быте первых палаточных строителей плотины.',
        locationSlug: 'volgograd-ges-kraevedcheskiy-muzey',
        address: 'г. Волжский',
        latitude: 48.7848,
        longitude: 44.7745,
        visitMinutes: 40,
      },
      {
        name: 'Парк «Новый город»',
        desc: 'Современное урбанистическое пространство с видом на пойму.',
        locationSlug: 'volgograd-ges-park-novyy-gorod',
        address: 'г. Волжский, парк «Новый город»',
        latitude: 48.787,
        longitude: 44.778,
        visitMinutes: 30,
      },
    ],
  },
];

export const VOLGOGRAD_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'volgograd-triumph-stalingrad',
    title: 'Триумф Сталинграда: от вокзала до панорамы',
    description:
      'Выверенный пешеходный трек по монументальному центру: вокзал, подвал ЦУМа, собор Невского, Аллея Героев, набережная и музей-панорама с мельницей Гергардта.',
    travelVector: 'Парадный пешеходный променад',
    timingNote: 'Около 4-5 часов пешком по центру и улице Чуйкова.',
    coverImageUrl: '/images/venues/volgograd/muzey-panorama-stalingradskaya-bitva.jpg',
    stops: [
      {
        name: 'Железнодорожный вокзал Волгоград-1',
        desc: '15 минут на осмотр башни со шпилем и потолочных росписей.',
        locationSlug: 'volgograd-vokzal-volgograd-1',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'Привокзальная площадь, 1',
        latitude: 48.712915,
        longitude: 44.511125,
      },
      {
        name: 'Особняк Репниковой и музей «Память»',
        desc: '40 минут: особняк и спуск в подвал, где пленили Паулюса.',
        locationSlug: 'volgograd-osobnyak-repnikovoy',
        mustSeeFilter: 'houses',
        visitMinutes: 40,
        address: 'ул. Гоголя, 10',
        latitude: 48.712125,
        longitude: 44.512812,
        transitTip: 'Пешком 4 минуты (350 м) по улице Гоголя',
      },
      {
        name: 'Собор Александра Невского и памятник Невскому',
        desc: '20 минут на осмотр византийского храма в сердце города.',
        locationSlug: 'volgograd-sobor-aleksandra-nevskogo',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'площадь Павших Борцов',
        latitude: 48.708621,
        longitude: 44.5141,
        transitTip: 'Пешком 2 минуты (150 м)',
      },
      {
        name: 'Аллея Героев и Сталинградский тополь',
        desc: '15 минут по триумфальному променаду к дереву-герою.',
        locationSlug: 'volgograd-stalingradskiy-topol',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'Аллея Героев',
        latitude: 48.707312,
        longitude: 44.515125,
        transitTip: 'Пешком 3 минуты (250 м)',
      },
      {
        name: 'Центральная набережная и «Angel Cakes»',
        desc: 'Час: променад по верхнему ярусу и легкий бранч с видом на Волгу.',
        locationSlug: 'volgograd-tsentral-naya-naberezhnaya-imeni-62-y-armii',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'Набережная 62-й Армии',
        latitude: 48.704422,
        longitude: 44.522343,
        transitTip: 'Пешком 5 минут (400 м) вниз к Волге',
      },
      {
        name: 'Музей-панорама и Мельница Гергардта',
        desc: '1,5 часа на панораму и краснокирпичного свидетеля войны.',
        venueSlug: 'volgograd-muzey-panorama-stalingradskaya-bitva',
        mustSeeFilter: 'main',
        visitMinutes: 90,
        address: 'ул. имени Маршала Чуйкова, 47',
        latitude: 48.715444,
        longitude: 44.532626,
        transitTip: 'Пешком 12 минут (1 км) по улице Чуйкова',
      },
    ],
  },
  {
    id: 'volgograd-mamaev-height',
    title: 'Высота 102: Мамаев курган',
    description:
      'Мемориальный день на главной высоте России: «Стоять насмерть», Зал Воинской Славы, Родина-мать, смотровая и танк Т-34. Финал - ЦПКиО с видом на арену.',
    travelVector: 'Мемориальный подъем',
    timingNote: 'Около 3-4 часов на кургане плюс короткая прогулка к парку.',
    coverImageUrl: '/images/venues/volgograd/mamaev-kurgan.jpg',
    stops: [
      {
        name: 'Скульптура «Стоять насмерть»',
        desc: '20 минут у бассейна у подножия кургана.',
        locationSlug: 'volgograd-stoyat-nasmert',
        mustSeeFilter: 'monument',
        visitMinutes: 20,
        address: 'Мамаев курган, площадь Стоявших насмерть',
        latitude: 48.741912,
        longitude: 44.540115,
      },
      {
        name: 'Зал Воинской Славы',
        desc: '30 минут в пантеоне с Вечным огнем.',
        locationSlug: 'volgograd-zal-voinskoy-slavy',
        mustSeeFilter: 'main',
        visitMinutes: 30,
        address: 'Мамаев курган, центральная площадь',
        latitude: 48.742389,
        longitude: 44.537606,
        transitTip: 'Пешком вверх по лестницам кургана',
      },
      {
        name: 'Скульптура «Родина-мать зовёт!»',
        desc: '45 минут у главного монумента и площади у меча.',
        locationSlug: 'volgograd-mamaev-kurgan',
        mustSeeFilter: 'main',
        visitMinutes: 45,
        address: 'Мамаев курган',
        latitude: 48.74241,
        longitude: 44.537021,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Смотровая площадка Мамаева кургана',
        desc: '20 минут на панораму Волги и стадиона.',
        locationSlug: 'volgograd-smotrovaya-mamaeva-kurgana',
        mustSeeFilter: 'views',
        visitMinutes: 20,
        address: 'Мамаев курган, вершина',
        latitude: 48.742076,
        longitude: 44.536605,
        transitTip: 'Пешком 2 минуты',
      },
      {
        name: 'Памятник Т-34 «Челябинский колхозник»',
        desc: '15 минут на исторический танк на склоне.',
        locationSlug: 'volgograd-t-34-chelyabinskiy-kolkhoznik',
        mustSeeFilter: 'monument',
        visitMinutes: 15,
        address: 'Мамаев курган, верхний плато-сквер',
        latitude: 48.743112,
        longitude: 44.535124,
        transitTip: 'Пешком 5 минут по плато',
      },
      {
        name: 'ЦПКиО',
        desc: '45 минут в прибрежном парке с колесом обозрения.',
        locationSlug: 'volgograd-tspkio',
        mustSeeFilter: 'park',
        visitMinutes: 45,
        address: 'ул. Батальонная, 4',
        latitude: 48.730445,
        longitude: 44.54451,
        transitTip: 'Пешком или трамвай ~15 минут вниз к парку',
      },
    ],
  },
  ...VOLGOGRAD_LINE_DAY_ROUTE_PRESETS,
];

export const VOLGOGRAD_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Сколько времени нужно, чтобы подняться на Мамаев курган?',
    a: 'Пеший подъем от подножия холма до подножия монумента «Родина-мать зовёт!» с осмотром площадей занимает около 1-1,5 часов. Закладывайте еще полчаса на Зал Воинской Славы и смотровую.',
  },
  {
    q: 'Что такое метротрам и где на него сесть?',
    a: 'Это уникальная для России система скоростного трамвая: в центре линии уходят под землю по принципу метро. Удобные точки посадки - станции «Площадь Ленина» и «Комсомольская». Оплата картой «Волна» обычно дешевле наличных.',
  },
  {
    q: 'Когда лучше ехать в Волгоград, если не хочется жары и мошки?',
    a: 'Оптимальные окна - май (День Победы и мягкое тепло) и сентябрь-октябрь (+18 °C, Волга еще теплая). Июнь портит волжская мошка, июль-август - степное пекло до +35...+40 °C.',
  },
  {
    q: 'Какое локальное блюдо и продукт обязательно попробовать?',
    a: 'Горчичное масло и сарептские пряники из наследия немецкой колонии, котлету по-волгоградски в городских кулинариях и летом - быковские арбузы. В Сарепте можно купить масло прямо в музейной лавке.',
  },
];

export const VOLGOGRAD_TRAVEL =
  'Аэропорт Гумрак принимает прямые рейсы из Москвы (около 2 часов), Санкт-Петербурга и других крупных городов. Ж/д до Волгоград-1 регулярное; на автомобиле из Москвы - около 12-14 часов по трассе Р-22 «Каспий». Лучшие окна для осмотра - май (День Победы) и сентябрь-октябрь, когда спадает жара. Летом берите ранние часы на Мамаев курган и метротрам от ветра зимой. Выезды дня: Старая Сарепта на электричке (~50 мин) и Волжская ГЭС / Волжский (~35 мин).';
