/** Voronezh tourist hub pack (owner 2026-08-17). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { VORONEZH_LINE_DAY_ROUTE_PRESETS } from './voronezh-line-presets.ts';

export const VORONEZH_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник Петру I',
    desc: 'Старейший монумент города и его главный визуальный символ.',
    address: 'Петровский сквер',
    locationSlug: 'voronezh-pamyatnik-petru-i',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 51.671911,
    longitude: 39.209867,
  },
  {
    name: 'Памятник Белому Биму Черное Ухо',
    desc: 'Контактная скульптура верного пса прямо на плитке у кукольного театра.',
    address: 'проспект Революции, 50',
    locationSlug: 'voronezh-pamyatnik-belomu-bimu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.666111,
    longitude: 39.205556,
  },
  {
    name: 'Памятник Котенку с улицы Лизюкова',
    desc: 'Мультяшный Василий и ворона на железном дереве.',
    address: 'ул. Генерала Лизюкова, 4',
    locationSlug: 'voronezh-pamyatnik-kotenku-s-ulitsy-lizyukova',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.706782,
    longitude: 39.171853,
  },
  {
    name: 'Скульптура «Незнакомка»',
    desc: 'Бронзовая дама начала XX века, присевшая на стул у магазина «Часы».',
    address: 'проспект Революции, 41',
    locationSlug: 'voronezh-skulptura-neznakomka',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.668102,
    longitude: 39.208119,
  },
  {
    name: 'Памятник С. Есенину',
    desc: 'Памятник поэту на одноименном пешеходном бульваре.',
    address: 'ул. Карла Маркса, 114А',
    locationSlug: 'voronezh-pamyatnik-eseninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.662719,
    longitude: 39.198305,
  },
  {
    name: 'Памятник А. Платонову',
    desc: 'Монумент писателю-земляку на пешеходной части проспекта.',
    address: 'проспект Революции, 24',
    locationSlug: 'voronezh-pamyatnik-platonovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.671403,
    longitude: 39.21147,
  },
  {
    name: 'Макет корабля «Меркурий»',
    desc: 'Скульптура корабля на высоком постаменте посреди Воронежского моря.',
    address: 'Воронежское водохранилище (у ВоГРЭСовского моста)',
    locationSlug: 'voronezh-maket-korablya-merkuriy',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 51.644342,
    longitude: 39.219502,
  },
  {
    name: 'Памятник О. Мандельштаму',
    desc: 'Авангардный монумент поэту у входа в парк «Орлёнок».',
    address: 'ул. Чайковского, 8',
    locationSlug: 'voronezh-pamyatnik-mandelshtamu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.674315,
    longitude: 39.207883,
  },
  {
    name: 'Памятник В. Высоцкому',
    desc: 'Улыбающийся бард с гитарой, сидящий на стуле.',
    address: 'ул. Карла Маркса, 59',
    locationSlug: 'voronezh-pamyatnik-vysotskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.663189,
    longitude: 39.201479,
  },
  {
    name: 'Памятник И. Бунину',
    desc: 'Бронзовая фигура писателя, присевшего в раздумьях на поваленное дерево.',
    address: 'Бунинский сквер (ул. Плехановская, 7Б)',
    locationSlug: 'voronezh-pamyatnik-buninu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.662241,
    longitude: 39.19965,
  },
  {
    name: 'Скульптура «Продавец и Покупатель»',
    desc: 'Забавный интерактивный арт-объект у входа на рынок.',
    address: 'ул. Челюскинцев, 101 (у Центрального рынка)',
    locationSlug: 'voronezh-skulptura-prodavets-i-pokupatel',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.66442,
    longitude: 39.196924,
  },
  {
    name: 'Памятник Митрофану Пятницкому',
    desc: 'Бронзовый бюст основателя русского народного хора.',
    address: 'проспект Революции, 32',
    locationSlug: 'voronezh-pamyatnik-pyatnitskomu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.669527,
    longitude: 39.209633,
  },
  {
    name: 'Памятник фронтовому почтальону',
    desc: 'Единственный в мире монумент в честь подвига военных связистов.',
    address: 'проспект Революции, 19 (у Главпочтамта)',
    locationSlug: 'voronezh-pamyatnik-frontovomu-pochtalonu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.670698,
    longitude: 39.211438,
  },
  {
    name: 'Памятник Юрию Хою',
    desc: 'Скульптура лидера «Сектора Газа» на его родине, на левом берегу.',
    address: 'ул. Остужева, 5А',
    locationSlug: 'voronezh-pamyatnik-yuriyu-hoyu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 51.681121,
    longitude: 39.262444,
  },
  {
    name: 'Памятник лечебному стулу',
    desc: 'Креативный железный стул в центре, «исцеляющий от жлобства».',
    address: 'сквер за Домом правительства (Платоновский сквер)',
    locationSlug: 'voronezh-pamyatnik-lechebnomu-stulu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 51.664811,
    longitude: 39.203023,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Здание Управления ЮВЖД',
    desc: 'Величественная 68-метровая башня со шпилем - главный символ советского ампира в городе.',
    address: 'проспект Революции, 18',
    locationSlug: 'voronezh-zdanie-upravleniya-yuvzhd',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.672322,
    longitude: 39.213233,
  },
  {
    name: 'Гостиница «Бристоль»',
    desc: 'Архитектурный шедевр чистого модерна с первыми в городе лифтами.',
    address: 'проспект Революции, 43',
    locationSlug: 'voronezh-gostinitsa-bristol',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.667822,
    longitude: 39.207914,
  },
  {
    name: 'Дом Казенной палаты',
    desc: 'Историческое здание конца XVIII века, образец строгого классицизма.',
    address: 'проспект Революции, 21',
    locationSlug: 'voronezh-dom-kazennoy-palaty',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.670412,
    longitude: 39.211104,
  },
  {
    name: 'Каменный мост',
    desc: 'Небольшой арочный виадук XIX века - место паломничества воронежских молодоженов.',
    address: 'пересечение ул. Карла Маркса и ул. Чернышевского',
    locationSlug: 'voronezh-kamennyy-most',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.665798,
    longitude: 39.202354,
  },
  {
    name: 'Дом губернатора',
    desc: 'Бывшая резиденция высших чинов Воронежской губернии.',
    address: 'проспект Революции, 22',
    locationSlug: 'voronezh-dom-gubernatora',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.671801,
    longitude: 39.211831,
  },
  {
    name: 'Авиационный завод (ВАСО)',
    desc: 'Историческое предприятие, где собирали Ту-144 и Ил-96.',
    address: 'ул. Циолковского, 27',
    locationSlug: 'voronezh-aviatsionnyy-zavod-vaso',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 51.644102,
    longitude: 39.248312,
  },
  {
    name: 'Мещанская полицейская часть',
    desc: 'Памятник архитектуры XIX века с высокой кирпичной каланчой.',
    address: 'ул. Карла Маркса, 32',
    locationSlug: 'voronezh-meshchanskaya-politseyskaya-chast',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 51.668541,
    longitude: 39.20911,
  },

  // --- Музеи (23-29) ---
  {
    name: 'Корабль-музей «Гото Предестинация»',
    desc: 'Действующая историческая копия петровского линкора 1700 года на воде.',
    address: 'Петровская набережная, 21А',
    venueSlug: 'voronezh-korabl-muzey-goto-predestinatsiya',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 51.654812,
    longitude: 39.215287,
  },
  {
    name: 'Областной художественный музей им. И.Н. Крамского',
    desc: 'Музей в барочном «Воронежском дворце» с коллекцией древнеегипетского искусства.',
    address: 'проспект Революции, 18Г',
    venueSlug: 'voronezh-hudozhestvennyy-muzey-kramskogo',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 51.671911,
    longitude: 39.213791,
  },
  {
    name: 'Краеведческий музей',
    desc: 'Главное хранилище артефактов края от палеолита до космической эпохи.',
    address: 'ул. Плехановская, 29',
    venueSlug: 'voronezh-kraevedcheskiy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 75,
    latitude: 51.667791,
    longitude: 39.192305,
  },
  {
    name: 'Музей-диорама',
    desc: 'Центр военно-патриотического воспитания с уличной выставкой танков и самолетов.',
    address: 'Ленинский проспект, 94',
    venueSlug: 'voronezh-muzey-diorama',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 51.674902,
    longitude: 39.245891,
  },
  {
    name: 'Литературный музей им. И.Н. Никитина',
    desc: 'Экспозиция о литераторах воронежской земли в здании мещанской управы.',
    address: 'ул. Плехановская, 3',
    venueSlug: 'voronezh-literaturnyy-muzey-nikitina',
    mustSeeFilter: 'museum',
    visitMinutes: 45,
    latitude: 51.660721,
    longitude: 39.201723,
  },
  {
    name: 'Арсенал',
    desc: 'Отдел краеведческого музея о Великой Отечественной войне в здании бывшей суконной фабрики.',
    address: 'ул. Степана Разина, 43',
    venueSlug: 'voronezh-arsenal',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 51.672901,
    longitude: 39.215124,
  },
  {
    name: 'Музей забытой музыки',
    desc: 'Интерактивная коллекция старинных музыкальных инструментов со всего мира.',
    address: 'ул. 9 Января, 108',
    venueSlug: 'voronezh-muzey-zabytoy-muzyki',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 51.673891,
    longitude: 39.172905,
  },

  // --- Храмы (30-36) ---
  {
    name: 'Благовещенский кафедральный собор',
    desc: 'Третий по величине православный храм в России, русско-византийский стиль.',
    address: 'Первомайский сад (проспект Революции, 14В)',
    locationSlug: 'voronezh-blagoveschenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 51.675541,
    longitude: 39.210512,
  },
  {
    name: 'Успенский Адмиралтейский храм',
    desc: 'Старейшая сохранившаяся церковь города: здесь Петр I освящал первые русские корабли.',
    address: 'ул. Софьи Перовской, 9',
    locationSlug: 'voronezh-uspenskiy-admiralteyskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.655891,
    longitude: 39.214432,
  },
  {
    name: 'Покровский собор',
    desc: 'Живописный классический храм, бывший кафедральным в советские годы.',
    address: 'ул. Бехтерева, 36',
    locationSlug: 'voronezh-pokrovskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.660102,
    longitude: 39.209801,
  },
  {
    name: 'Алексеево-Акатов монастырь',
    desc: 'Один из старейших монастырей Черноземья с тихой территорией и старинной колокольней.',
    address: 'ул. Освобождения Труда, 1В',
    locationSlug: 'voronezh-alekseevo-akatov-monastyr',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 51.666901,
    longitude: 39.222312,
  },
  {
    name: 'Ильинский храм',
    desc: 'Уютная барочная церковь XVIII века на историческом холме у реки.',
    address: 'ул. Севастьяновский Съезд, 26',
    locationSlug: 'voronezh-ilinskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.65691,
    longitude: 39.206902,
  },
  {
    name: 'Казанский храм',
    desc: 'Краснокирпичная двухэтажная церковь в псевдорусском стиле на левом берегу.',
    address: 'ул. Суворова, 79',
    locationSlug: 'voronezh-kazanskiy-hram',
    mustSeeFilter: 'temple',
    visitMinutes: 25,
    latitude: 51.691891,
    longitude: 39.256891,
  },
  {
    name: 'Лютеранская кирха святой Марии',
    desc: 'Действующий евангелическо-лютеранский храм начала XIX века в стиле классицизма.',
    address: 'ул. Карла Маркса, 65',
    locationSlug: 'voronezh-kirha-svyatoy-marii',
    mustSeeFilter: 'temple',
    visitMinutes: 20,
    latitude: 51.664112,
    longitude: 39.202901,
  },

  // --- Парки и смотровые (37-43) ---
  {
    name: 'Адмиралтейская площадь',
    desc: 'Огромное общественное пространство на берегу водохранилища, эпицентр городских фестивалей.',
    address: 'Петровская набережная',
    locationSlug: 'voronezh-admiralteyskaya-ploschad',
    mustSeeFilter: 'main',
    visitMinutes: 45,
    latitude: 51.656312,
    longitude: 39.214911,
  },
  {
    name: 'Парк «Алые паруса»',
    desc: 'Современный сосновый парк на левом берегу с пляжем и лучшим видом на правый берег.',
    address: 'ул. Арзамасская, 4Д',
    locationSlug: 'voronezh-park-alye-parusa',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 51.651901,
    longitude: 39.242312,
  },
  {
    name: 'Центральный парк («Динамо»)',
    desc: 'Зеленый массив в лощине с озерами, фонтанами и амфитеатром.',
    address: 'ул. Ленина, 10',
    locationSlug: 'voronezh-tsentralnyy-park-dinamo',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 51.692312,
    longitude: 39.222912,
  },
  {
    name: 'Парк «Орлёнок»',
    desc: 'Обновленный футуристичный парк в центре города с мостами и кофейнями.',
    address: 'ул. Чайковского, 6',
    locationSlug: 'voronezh-park-orlyonok',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 51.674901,
    longitude: 39.208902,
  },
  {
    name: 'Петровская набережная',
    desc: 'Протяженная пешеходная зона вдоль Воронежского моря для самокатов и закатных прогулок.',
    address: 'Петровская набережная',
    locationSlug: 'voronezh-petrovskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 51.65123,
    longitude: 39.21142,
  },
  {
    name: 'Смотровая площадка у парка им. Дурова',
    desc: 'Видовое место на возвышении: панорама левого берега и водохранилища.',
    address: 'ул. Ворошилова, 1Д',
    locationSlug: 'voronezh-smotrovaya-park-durova',
    mustSeeFilter: 'views',
    visitMinutes: 20,
    latitude: 51.655102,
    longitude: 39.183421,
  },
  {
    name: 'Чернавская дамба',
    desc: 'Спортивный кластер на намывном острове прямо посреди Чернавского моста.',
    address: 'Чернавский мост',
    locationSlug: 'voronezh-chernavskaya-damba',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 51.666112,
    longitude: 39.229105,
  },

  // --- Гастрономия и театры (44-50) ---
  {
    name: 'Воронежский Камерный театр',
    desc: 'Один из лучших провинциальных театров России в ультрасовременном здании.',
    address: 'ул. Карла Маркса, 55А',
    venueSlug: 'voronezh-kamernyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 51.664431,
    longitude: 39.203812,
  },
  {
    name: 'Театр кукол «Шут»',
    desc: 'Сказочное здание с часами и фигурами персонажей, перед которым сидит Белый Бим.',
    address: 'проспект Революции, 50',
    venueSlug: 'voronezh-teatr-kukol-shut',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 51.666321,
    longitude: 39.205791,
  },
  {
    name: 'Ресторан «El Chico»',
    desc: 'Премиальный стейкхаус с открытой кухней и эталонным воронежским мясом dry-age.',
    address: 'ул. Красноармейская, 62',
    locationSlug: 'voronezh-restoran-el-chico',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 51.656312,
    longitude: 39.19391,
  },
  {
    name: 'Гастромаркет «Центральный рынок»',
    desc: 'Двухэтажный фудхолл: фермерские сыры и запеченное мясо.',
    address: 'ул. Пушкинская, 8',
    locationSlug: 'voronezh-gastro-tsentralnyy-rynok',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 51.663112,
    longitude: 39.197212,
  },
  {
    name: 'Бар «Хлам»',
    desc: 'Легендарный локальный рок-бар с шумными вечеринками и авторскими настойками.',
    address: 'ул. Плехановская, 16',
    locationSlug: 'voronezh-bar-hlam',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 51.66421,
    longitude: 39.200311,
  },
  {
    name: 'Театр драмы им. А. Кольцова',
    desc: 'Исторический «Зимний театр», бережно отреставрированный внутри.',
    address: 'проспект Революции, 55',
    venueSlug: 'voronezh-teatr-dramy-koltsova',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 51.665912,
    longitude: 39.204512,
  },
  {
    name: 'Кофейня «Промка»',
    desc: 'Хипстерский кофейный спот в индустриальном стиле с лучшим фильтр-кофе в городе.',
    address: 'проспект Революции, 39',
    locationSlug: 'voronezh-kofeynya-promka',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 51.668541,
    longitude: 39.208451,
  },

  // --- Секретные бары Красной линии (не раздувают IA: 4 точки) ---
  {
    name: 'Рюмочная «Культурно Коротко»',
    desc: 'Авторские настойки («борщ», «копченая груша», «щавель») и бутерброды на бородинском. Во дворе проспекта Революции, в 3 минутах от «Шута».',
    address: 'проспект Революции, 39',
    locationSlug: 'voronezh-ryumochnaya-kulturno-korotko',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 51.668212,
    longitude: 39.208105,
  },
  {
    name: 'Спикизи-бар «Архив»',
    desc: 'Секретный коктейльный бар без вывески: полумрак, винтаж и меню в виде архивных карточек. Между памятником Высоцкому и Камерным театром.',
    address: 'ул. Карла Маркса, 56',
    locationSlug: 'voronezh-spikizi-bar-arhiv',
    mustSeeFilter: 'gastro',
    visitMinutes: 50,
    latitude: 51.663911,
    longitude: 39.202912,
  },
  {
    name: 'Крафтовый бар «Цензура»',
    desc: 'Андерграунд в кирпичных арках: редкий крафт на кранах и брутальный стритфуд. Сосед «Хлама».',
    address: 'проспект Революции, 39Б',
    locationSlug: 'voronezh-bar-tsenzura',
    mustSeeFilter: 'gastro',
    visitMinutes: 40,
    latitude: 51.66871,
    longitude: 39.208812,
  },
  {
    name: 'Рюмочная «Зюзя»',
    desc: 'Ироничное советское ретро: домашние наливки, соленья в граненых стаканчиках и винил. У лечебного стула, к Никитинской площади.',
    address: 'ул. Пушкинская, 1',
    locationSlug: 'voronezh-ryumochnaya-zyuzya',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 51.661902,
    longitude: 39.19911,
  },
];

export const VORONEZH_SUBURBS: any[] = [
  {
    name: 'Рамонь',
    desc: 'Дворцовый комплекс Ольденбургских: неоготический замок, редкий для средней полосы памятник императорской архитектуры XIX века. Принцесса Евгения превратила усадьбу в европейский кластер с первой в стране паровой фабрикой шоколада.',
    locationSlug: 'voronezh-ramon',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 51.908051,
    longitude: 39.340552,
    address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
    travelVector: 'Автобус 111 ~1 ч',
    travelVectorBlurb:
      'Закладывайте на автомобиль или автобус №111 с Центрального автовокзала ~1 час, чтобы приехать к 09:30 утра.',
    timingNote:
      'По территории усадьбы двигайтесь вглубь французского парка к каскадным террасам, напоследок оставив глубокие подвалы Свитского корпуса с их мистическими легендами.',
    places: [
      {
        name: 'Дворец Ольденбургских',
        desc: 'Главное трехэтажное здание с зубчатыми башнями, каминами и винтовыми лестницами.',
        locationSlug: 'voronezh-ramon-dvorets-oldenburgskih',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 60,
      },
      {
        name: 'Свитский корпус',
        desc: 'Флигель, где останавливалась свита императорской семьи, сейчас здесь интерактивные выставки.',
        locationSlug: 'voronezh-ramon-svitskiy-korpus',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 40,
      },
      {
        name: 'Грот с водопадом',
        desc: 'Отреставрированное гидротехническое сооружение в ландшафтном парке.',
        locationSlug: 'voronezh-ramon-grot-s-vodopadom',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 20,
      },
      {
        name: 'Дом с ризалитами',
        desc: 'Образец парадной жилой архитектуры усадебного комплекса.',
        locationSlug: 'voronezh-ramon-dom-s-rizalitami',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 20,
      },
      {
        name: 'Вековые дубы у террасы',
        desc: 'Старинные деревья, заставшие первых коронованных владельцев имения.',
        locationSlug: 'voronezh-ramon-vekovye-duby',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 15,
      },
      {
        name: 'Мостик любви',
        desc: 'Небольшой кованый виадук через замковый овраг с видом на реку Воронеж.',
        locationSlug: 'voronezh-ramon-mostik-lyubvi',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 15,
      },
      {
        name: 'Ворота с башней-часами',
        desc: 'Парадный въезд в усадьбу с восстановленным часовым механизмом швейцарской работы.',
        locationSlug: 'voronezh-ramon-vorota-s-bashney-chasov',
        address: 'Воронежская обл., пгт. Рамонь, ул. Мосина, 21',
        latitude: 51.908051,
        longitude: 39.340552,
        visitMinutes: 15,
      },
    ],
  },
  {
    name: 'Дивногорье',
    desc: 'Место силы региона: белоснежные меловые столбы-дивы над Доном и пещерные храмы, вырубленные монахами внутри скал.',
    locationSlug: 'voronezh-divnogor-e',
    mustSeeFilter: 'main',
    visitMinutes: '7-8 ч',
    latitude: 50.963491,
    longitude: 39.296541,
    address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
    travelVector: 'Электричка / авто ~2 ч',
    travelVectorBlurb:
      'Закладывайте на электричку «напрямую» в выходные или автомобиль ~2 часа, чтобы приехать к 10:00 утра.',
    timingNote:
      'По высокой деревянной лестнице на холм двигайтесь на восток вдоль меловых каньонов, напоследок оставив развалины средневековой Маяцкой крепости на плато.',
    places: [
      {
        name: 'Церковь Сицилийской иконы Божьей Матери',
        desc: 'Уникальный двухэтажный пещерный храм внутри Большой Дивы.',
        locationSlug: 'voronezh-divnogore-tserkov-sitsiliyskoy-ikony',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 40,
      },
      {
        name: 'Маяцкое городище',
        desc: 'Остатки белокаменной хазарской крепости IX-X веков и древнего некрополя.',
        locationSlug: 'voronezh-divnogore-mayatskoe-gorodishche',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 30,
      },
      {
        name: 'Дива «Шапка»',
        desc: 'Одиночный меловой останец причудливой формы на вершине склона.',
        locationSlug: 'voronezh-divnogore-diva-shapka',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 15,
      },
      {
        name: 'Археологический парк «Детство земли»',
        desc: 'Интерактивная площадка под открытым небом, воссоздающая быт древних кочевников.',
        locationSlug: 'voronezh-divnogore-detstvo-zemli',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 30,
      },
      {
        name: 'Каньон в Больших Дивах',
        desc: 'Глубокий тектонический разлом в меловой горе с уникальным микроклиматом.',
        locationSlug: 'voronezh-divnogore-kanon-bolshie-divy',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 25,
      },
      {
        name: 'Пещерная церковь Иоанна Предтечи',
        desc: 'Малый пещерный комплекс в Малых Дивах с подземными галереями.',
        locationSlug: 'voronezh-divnogore-tserkov-ioanna-predtechi',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 30,
      },
      {
        name: 'Смотровая на слияние Дона и Тихой Сосны',
        desc: 'Высшая точка маршрута с видом на речные излучины.',
        locationSlug: 'voronezh-divnogore-smotrovaya-don-tihaya-sosna',
        address: 'Воронежская обл., Лискинский район, хутор Дивногорье',
        latitude: 50.963491,
        longitude: 39.296541,
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Костёнки / Колыбель европейской цивилизации',
    desc: 'Палеолитический комплекс мирового значения: подлинные следы древнего человека и музей над раскопом.',
    locationSlug: 'voronezh-kostenki',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 51.391212,
    longitude: 39.049112,
    address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
    travelVector: 'Автомобиль или пригородный автобус №141 ~50 минут',
    travelVectorBlurb:
      'Закладывайте на автомобиль или пригородный автобус №141 от Юго-Западного автовокзала ~50 минут, чтобы приехать к 10:00 утра.',
    timingNote:
      'По оборудованным тропам археологического раскопа двигайтесь внутрь главного здания-павильона, напоследок оставив селфи на фоне полноразмерной реконструкции мамонта.',
    places: [
      {
        name: 'Подлинное жилище из костей мамонта',
        desc: 'Уникальный круговой раскоп внутри главного зала музея.',
        locationSlug: 'voronezh-kostenki-podlinnoe-zhilishche-iz-kostey-mamont',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 40,
      },
      {
        name: 'Скульптура мамонта «Степан»',
        desc: 'Реалистичный уличный арт-объект в натуральную величину перед входом.',
        locationSlug: 'voronezh-kostenki-skulptura-mamont-stepan',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 20,
      },
      {
        name: 'Коллекция палеолитических венер',
        desc: 'Выставка редких женских статуэток из бивня мамонта и мергеля.',
        locationSlug: 'voronezh-kostenki-paleoliticheskie-veneri',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 30,
      },
      {
        name: 'Экспозиция древних орудий труда',
        desc: 'Витрины с подлинными каменными наконечниками стрел, скребками и иглами.',
        locationSlug: 'voronezh-kostenki-ekspozitsiya-drevnih-orudiy-truda',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 25,
      },
      {
        name: 'Костёнские меловые холмы',
        desc: 'Живописные склоны Дона вокруг археологического парка с редкими степными травами.',
        locationSlug: 'voronezh-kostenki-melovye-holmy',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 30,
      },
      {
        name: 'Смотровая площадка на излучину Дона',
        desc: 'Высшая точка холма с панорамным видом на речные просторы.',
        locationSlug: 'voronezh-kostenki-smotrovaya-izluchina-dona',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 15,
      },
      {
        name: 'Интерактивная археологическая песочница',
        desc: 'Зона, где дети и взрослые могут попробовать себя в роли исследователей.',
        locationSlug: 'voronezh-kostenki-interaktivnaya-arheologicheskaya-pesochnitsa',
        address: 'Воронежская обл., Хохольский район, с. Костёнки, ул. Кирова, 6А',
        latitude: 51.391212,
        longitude: 39.049112,
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Усадьба Веневитиновых (дворцово-парковый комплекс)',
    desc: 'Единственная сохранившаяся усадьба XVIII века в стиле классицизма с дворцом, ротондой и садом.',
    locationSlug: 'voronezh-usadba-venevitinovyh',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 51.888912,
    longitude: 39.161112,
    address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
    travelVector: 'Авто / автобус в сторону Рамони ~30 минут',
    travelVectorBlurb:
      'Закладывайте на автомобиль или автобус в сторону Рамони ~30 минут, чтобы приехать к 09:30 утра.',
    timingNote:
      'По тенистым парковым аллеям усадьбы двигайтесь на восток к парадному господскому дому с ротондой, напоследок оставив закат на деревянной террасе над рекой Воронеж.',
    places: [
      {
        name: 'Господский дом Веневитиновых',
        desc: 'Парадный двухэтажный каменный особняк с подлинной мебелью, картинами и книгами.',
        locationSlug: 'voronezh-venevitinovy-gospodskiy-dom',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 60,
      },
      {
        name: 'Ампирная ротонда',
        desc: 'Живописная полукруглая беседка в парке для поэтических чтений.',
        locationSlug: 'voronezh-venevitinovy-ampirnaya-rotonda',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 20,
      },
      {
        name: 'Партерный усадебный сад',
        desc: 'Геометрически выверенные аллеи со столетними липами и розариями.',
        locationSlug: 'voronezh-venevitinovy-parternyy-usadebnyy-sad',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 30,
      },
      {
        name: 'Музыкальная гостиная',
        desc: 'Зал с роялем, где регулярно проходят камерные дворянские концерты при свечах.',
        locationSlug: 'voronezh-venevitinovy-muzykalnaya-gostinaya',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 30,
      },
      {
        name: 'Деревянный пирс Веневитиновых',
        desc: 'Оборудованный спуск к реке Воронеж с видовой зоной.',
        locationSlug: 'voronezh-venevitinovy-derevyannyy-pirs',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 20,
      },
      {
        name: 'Экспозиция «Поэзия мысли»',
        desc: 'Литературные залы, посвященные творчеству Дмитрия Веневитинова и его дружбе с Пушкиным.',
        locationSlug: 'voronezh-venevitinovy-poeziya-mysli',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 45,
      },
      {
        name: 'Исторический кухонный флигель',
        desc: 'Бревенчатая постройка, раскрывающая секреты старинной усадебной кулинарии.',
        locationSlug: 'voronezh-venevitinovy-kuhonnyy-fligel',
        address: 'Воронежская обл., Рамонский район, с. Новоживотинное, ул. Школьная, 18',
        latitude: 51.888912,
        longitude: 39.161112,
        visitMinutes: 25,
      },
    ],
  },
];

export const VORONEZH_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'voronezh-parade-fleet',
    title: 'Парадный проспект и Петровский флот',
    description:
      'Классический ознакомительный трек по главной артерии города с плавным спуском к колыбели русского флота у реки.',
    travelVector: 'Парадный пешеходный променад',
    timingNote: 'Около 3 часов пешком: Петр - ЮВЖД - «Промка» - Бим - Успенский - Адмиралтейская.',
    stops: [
      {
        name: 'Памятник Петру I',
        desc: '15 минут на осмотр и фото в Петровском сквере.',
        locationSlug: 'voronezh-pamyatnik-petru-i',
        mustSeeFilter: 'main',
        visitMinutes: 15,
        address: 'Петровский сквер',
        latitude: 51.671911,
        longitude: 39.209867,
      },
      {
        name: 'Здание Управления ЮВЖД',
        desc: '10 минут на осмотр монументального фасада.',
        locationSlug: 'voronezh-zdanie-upravleniya-yuvzhd',
        mustSeeFilter: 'houses',
        visitMinutes: 10,
        address: 'проспект Революции, 18',
        latitude: 51.672322,
        longitude: 39.213233,
        transitTip: 'Пешком 3 минуты',
      },
      {
        name: 'Кофейня «Промка»',
        desc: '20 минут на утренний кофе с выпечкой.',
        locationSlug: 'voronezh-kofeynya-promka',
        mustSeeFilter: 'gastro',
        visitMinutes: 20,
        address: 'проспект Революции, 39',
        latitude: 51.668541,
        longitude: 39.208451,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Театр кукол «Шут» и Белый Бим',
        desc: '20 минут на фото с Бимом и осмотр сказочных часов на фасаде.',
        locationSlug: 'voronezh-pamyatnik-belomu-bimu',
        mustSeeFilter: 'monument',
        visitMinutes: 20,
        address: 'проспект Революции, 50',
        latitude: 51.666111,
        longitude: 39.205556,
        transitTip: 'Пешком 6 минут',
      },
      {
        name: 'Успенский Адмиралтейский храм',
        desc: '25 минут на осмотр старейшей церкви города.',
        locationSlug: 'voronezh-uspenskiy-admiralteyskiy-hram',
        mustSeeFilter: 'temple',
        visitMinutes: 25,
        address: 'ул. Софьи Перовской, 9',
        latitude: 51.655891,
        longitude: 39.214432,
        transitTip: 'Пешком 12 минут через Каменный мост вниз',
      },
      {
        name: 'Адмиралтейская площадь и «Гото Предестинация»',
        desc: 'Час на прогулку по площади и экскурсию по петровскому линкору.',
        venueSlug: 'voronezh-korabl-muzey-goto-predestinatsiya',
        mustSeeFilter: 'main',
        visitMinutes: 60,
        address: 'Петровская набережная, 21А',
        latitude: 51.654812,
        longitude: 39.215287,
        transitTip: 'Пешком 2 минуты',
      },
    ],
  },
  {
    id: 'voronezh-avantgarde-gastro',
    title: 'Культурный авангард и гастро-гедонизм',
    description:
      'Маршрут для ценителей неочевидной архитектуры, концептуального искусства и знаменитого воронежского мяса.',
    travelVector: 'Арт, модерн и фудхолл',
    timingNote: 'Около 3 часов; вечером стоит вернуться в Камерный на спектакль.',
    stops: [
      {
        name: 'Парк «Орлёнок» и памятник Мандельштаму',
        desc: '30 минут на утреннюю прогулку по мостам.',
        locationSlug: 'voronezh-park-orlyonok',
        mustSeeFilter: 'park',
        visitMinutes: 30,
        address: 'ул. Чайковского, 6',
        latitude: 51.674901,
        longitude: 39.208902,
      },
      {
        name: 'Гостиница «Бристоль»',
        desc: '15 минут на детали воронежского модерна.',
        locationSlug: 'voronezh-gostinitsa-bristol',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'проспект Революции, 43',
        latitude: 51.667822,
        longitude: 39.207914,
        transitTip: 'Пешком 8 минут',
      },
      {
        name: 'Воронежский Камерный театр',
        desc: '15 минут на фото у футуристичного здания.',
        venueSlug: 'voronezh-kamernyy-teatr',
        mustSeeFilter: 'creative',
        visitMinutes: 15,
        address: 'ул. Карла Маркса, 55А',
        latitude: 51.664431,
        longitude: 39.203812,
        transitTip: 'Пешком 5 минут',
      },
      {
        name: 'Каменный мост',
        desc: '15 минут на классическую видовую точку Воронежа.',
        locationSlug: 'voronezh-kamennyy-most',
        mustSeeFilter: 'houses',
        visitMinutes: 15,
        address: 'пересечение ул. Карла Маркса и ул. Чернышевского',
        latitude: 51.665798,
        longitude: 39.202354,
        transitTip: 'Пешком 7 минут',
      },
      {
        name: 'Гастромаркет «Центральный рынок»',
        desc: 'Час на дегустацию локальных продуктов и сытный обед на фудхолле.',
        locationSlug: 'voronezh-gastro-tsentralnyy-rynok',
        mustSeeFilter: 'gastro',
        visitMinutes: 60,
        address: 'ул. Пушкинская, 8',
        latitude: 51.663112,
        longitude: 39.197212,
        transitTip: 'Пешком 10 минут',
      },
      {
        name: 'Памятник лечебному стулу',
        desc: '10 минут на веселое фото в Платоновском сквере.',
        locationSlug: 'voronezh-pamyatnik-lechebnomu-stulu',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'сквер за Домом правительства (Платоновский сквер)',
        latitude: 51.664811,
        longitude: 39.203023,
        transitTip: 'Пешком 4 минуты',
      },
    ],
  },
  ...VORONEZH_LINE_DAY_ROUTE_PRESETS,
];

export const VORONEZH_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'В Воронеже закрыт аэропорт. Как сейчас удобнее и быстрее всего добраться до города?',
    a: 'Самый надежный и быстрый способ - двухэтажные фирменные поезда «сидячего» типа №738/740 из Москвы. Они идут с Казанского вокзала до станции Воронеж-1 всего за 6 часов 20 минут. Также работает трасса М-4 «Дон»: на машине или регулярных автобусах путь займет около 6-7 часов.',
  },
  {
    q: 'Правда ли, что в Воронежском водохранилище категорически запрещено купаться?',
    a: 'Да. Воронежское море - крупнейший в мире искусственный водоем в черте города, но из-за малой глубины, слабого течения и сине-зеленых водорослей купание официально запрещено Роспотребнадзором. Для пляжного отдыха местные ездят на реки Усмань, Воронеж или Дон.',
  },
  {
    q: 'Как посмотреть корабль «Гото Предестинация», если билеты в кассе постоянно раскуплены?',
    a: 'Попасть внутрь линкора спонтанно в выходные почти нереально - пускают только экскурсионными группами по 15 человек. Билеты на сайте Краеведческого музея выкладывают ровно за две недели до даты. Если не успели, приходите к кассе на набережной к 09:45 - там продают утренний лимит невыкупленных броней.',
  },
  {
    q: 'Где искать неформальный Воронеж и рок-культуру Юрия Хоя («Сектор Газа»)?',
    a: 'Официального музея группы нет. Фанаты едут на левый берег («сектор газа» в песне - дымящий промрайон ВАСО). Главная точка паломничества - могила Юрия Хоя на Левобережном (Бакинском) кладбище. За живым воронежским роком и крафтом - в бар «Хлам» в центре.',
  },
];

export const VORONEZH_TRAVEL =
  'Местный аэропорт временно закрыт. Самый быстрый путь из Москвы - двухэтажные фирменные поезда №738/740 с Казанского вокзала до Воронеж-1 за 6 часов 20 минут. На автомобиле или автобусе по трассе М-4 «Дон» - около 6-7 часов. Лучшее окно - май-сентябрь: навигация и сап по водохранилищу (купание запрещено), веранды на Карла Маркса, выезды в Рамонь и Дивногорье. Осенью (+12...+18 °C) золотеют «Алые паруса», меньше транзита на юг, отели дешевле. Зимой - снег около -5...-9 °C, тюбинги в Чертовицах и стейкхаусы после прогулок.';
