/** Yaroslavl tourist hub pack (owner 2026-08-21). Hyphen-only copy. */
/* eslint-disable @typescript-eslint/no-explicit-any */

import { YAROSLAVL_LINE_DAY_ROUTE_PRESETS } from './yaroslavl-line-presets.ts';

export const YAROSLAVL_MUST_SEE: any[] = [
  // --- Памятники и уличные арт-объекты (1-15) ---
  {
    name: 'Памятник Ярославу Мудрому',
    desc: 'Главный монумент основателю города на Богоявленской площади, знакомый по 1000-рублевой купюре.',
    address: 'Богоявленская площадь',
    locationSlug: 'yaroslavl-pamyatnik-yaroslavu-mudromu',
    mustSeeFilter: 'main',
    visitMinutes: 15,
    latitude: 57.62143,
    longitude: 39.889312,
  },
  {
    name: 'Памятник Рычащему Медведю',
    desc: 'Интерактивный бронзовый символ города: каждый ровный час издает мощный естественный рык.',
    address: 'ул. Первомайская, 15А',
    locationSlug: 'yaroslavl-pamyatnik-rychashemu-medvedyu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.622612,
    longitude: 39.886345,
  },
  {
    name: 'Памятник Федору Волкову',
    desc: 'Монумент основателю первого русского профессионального театра в сквере перед его детищем.',
    address: 'площадь Волкова, 1',
    locationSlug: 'yaroslavl-pamyatnik-fedoru-volkovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.626815,
    longitude: 39.884511,
  },
  {
    name: 'Скульптура «Афоня и Коля»',
    desc: 'Уличный памятник персонажам советской комедии во дворике, где проходили съемки фильма.',
    address: 'ул. Нахимсона, 21А',
    locationSlug: 'yaroslavl-skulptura-afonya-i-kolya',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.623412,
    longitude: 39.889912,
  },
  {
    name: 'Памятник Некрасову',
    desc: 'Мемориальный комплекс на Волжской набережной, посвященный поэту, воспевшему Волгу.',
    address: 'Волжская набережная, 45',
    locationSlug: 'yaroslavl-pamyatnik-nekrasovu',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.635812,
    longitude: 39.884122,
  },
  {
    name: 'Скульптурная композиция «Троица»',
    desc: 'Единственный в России скульптурный памятник, визуализирующий икону Андрея Рублева у стен Стрелки.',
    address: 'площадь Челюскинцев, 15',
    locationSlug: 'yaroslavl-skulptura-troitsa',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.622145,
    longitude: 39.901235,
  },
  {
    name: 'Памятник Копейке 1612 года',
    desc: 'Арт-объект в виде гигантской монеты: Ярославль был временной столицей Руси и чеканил свою монету.',
    address: 'ул. Первомайская, 2А (у стен Спасского монастыря)',
    locationSlug: 'yaroslavl-pamyatnik-kopeyke-1612',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.620812,
    longitude: 39.889614,
  },
  {
    name: 'Скульптура «Медведь с рыбой»',
    desc: 'Добродушный парковый арт-объект: нос и хвост затерты туристами до блеска.',
    address: 'ул. Кирова, 10',
    locationSlug: 'yaroslavl-skulptura-medved-s-ryboy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.625124,
    longitude: 39.887115,
  },
  {
    name: 'Памятник Леониду Собинову',
    desc: 'Памятник оперному тенору, уроженцу Ярославля, у филармонии.',
    address: 'ул. Максимова, 13',
    locationSlug: 'yaroslavl-pamyatnik-sobinovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.624812,
    longitude: 39.885912,
  },
  {
    name: 'Демидовский столп',
    desc: 'Высокая гранитная дорическая колонна с бронзовым орлом в центре старого плац-парада.',
    address: 'Демидовский сад',
    locationSlug: 'yaroslavl-demidovskiy-stolp',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.623456,
    longitude: 39.89712,
  },
  {
    name: 'Арт-объект «Стрелка»',
    desc: 'Стела в честь 1000-летия Ярославля с фигурой ратника и барельефами главных вех истории.',
    address: 'нижний партер парка на Стрелке',
    locationSlug: 'yaroslavl-stela-strelka-1000',
    mustSeeFilter: 'monument',
    visitMinutes: 15,
    latitude: 57.62012,
    longitude: 39.90389,
  },
  {
    name: 'Памятник святым Петру и Февронии',
    desc: 'Парковый памятник покровителям семьи и верности у Которосльной набережной.',
    address: 'ул. Чайковского, 1А',
    locationSlug: 'yaroslavl-pamyatnik-petru-i-fevronii',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.619812,
    longitude: 39.876124,
  },
  {
    name: 'Памятник Савве Мамонтову',
    desc: 'Монумент меценату и промышленнику, построившему Северную железную дорогу, у ж/д вокзала.',
    address: 'площадь Ярославль-Главный, 1',
    locationSlug: 'yaroslavl-pamyatnik-savve-mamontovu',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.624112,
    longitude: 39.839812,
  },
  {
    name: 'Скульптура «Постовой у заставы»',
    desc: 'Уличный арт-объект: городовой царских времен у исторического здания заставы.',
    address: 'ул. Первомайская, 1',
    locationSlug: 'yaroslavl-skulptura-postovoy-u-zastavy',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.632145,
    longitude: 39.887812,
  },
  {
    name: 'Памятник Ленину на Красной площади',
    desc: 'Монументальный памятник советской эпохи на месте разрушенного Семеновского храма.',
    address: 'Красная площадь',
    locationSlug: 'yaroslavl-pamyatnik-leninu-krasnaya-ploschad',
    mustSeeFilter: 'monument',
    visitMinutes: 10,
    latitude: 57.631812,
    longitude: 39.886124,
  },

  // --- Историческое наследие (16-22) ---
  {
    name: 'Ярославский музей-заповедник (Спасский монастырь)',
    desc: 'Белокаменный укрепленный комплекс, который туристы часто называют «Ярославским Кремлем».',
    address: 'Богоявленская площадь, 25',
    locationSlug: 'yaroslavl-yaroslavskiy-kreml-spaso-preobrazhenskiy-monastyr',
    mustSeeFilter: 'main',
    visitMinutes: 90,
    latitude: 57.621214,
    longitude: 39.888514,
  },
  {
    name: 'Митрополичьи палаты',
    desc: 'Редкий образец гражданской жилой архитектуры XVII века - парадная резиденция ростовских митрополитов.',
    address: 'Волжская набережная, 1',
    locationSlug: 'yaroslavl-mitropolichi-palaty',
    mustSeeFilter: 'houses',
    visitMinutes: 40,
    latitude: 57.622915,
    longitude: 39.900956,
  },
  {
    name: 'Знаменская (Власьевская) башня',
    desc: 'Массивная каменная проездная башня XVII века, уцелевшая от укреплений Земляного города.',
    address: 'Первомайская ул., 2А',
    locationSlug: 'yaroslavl-znamenskaya-bashnya',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 57.626712,
    longitude: 39.883912,
  },
  {
    name: 'Ротонда Гостиного двора',
    desc: 'Элегантный неоклассический круглый павильон купеческих торговых рядов начала XIX века.',
    address: 'ул. Комсомольская, 4',
    locationSlug: 'yaroslavl-rotonda-gostinogo-dvora',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.625345,
    longitude: 39.885612,
  },
  {
    name: 'Дом Болконского',
    desc: 'Особняк на набережной, описанный Львом Толстым в «Войне и мире» как место кончины героя.',
    address: 'Волжская набережная, 7',
    locationSlug: 'yaroslavl-dom-bolkonskogo',
    mustSeeFilter: 'houses',
    visitMinutes: 15,
    latitude: 57.624125,
    longitude: 39.899812,
  },
  {
    name: 'Губернаторский дом',
    desc: 'Императорский путевой дворец XIX века, принимавший государей от Александра I до Николая II.',
    address: 'Волжская набережная, 23',
    locationSlug: 'yaroslavl-gubernatorskiy-dom',
    mustSeeFilter: 'houses',
    visitMinutes: 30,
    latitude: 57.628312,
    longitude: 39.895125,
  },
  {
    name: 'Усадьба Матвеевских',
    desc: 'Купеческий ансамбль в стиле строгого классицизма с аутентичными лепными пилястрами.',
    address: 'ул. Советская, 8',
    locationSlug: 'yaroslavl-usadba-matveevskih',
    mustSeeFilter: 'houses',
    visitMinutes: 20,
    latitude: 57.628915,
    longitude: 39.894125,
  },

  // --- Музеи (23-27) ---
  {
    name: 'Ярославский художественный музей',
    desc: 'Главное собрание русского искусства в Поволжье, расположенное в Губернаторском доме.',
    address: 'Волжская набережная, 23',
    venueSlug: 'yaroslavl-yaroslavskiy-hudozhestvennyy-muzey',
    mustSeeFilter: 'museum',
    visitMinutes: 90,
    latitude: 57.628544,
    longitude: 39.895626,
  },
  {
    name: 'Музей «Музыка и время»',
    desc: 'Первый частный музей с коллекцией старинных часов, музыкальных инструментов и колоколов.',
    address: 'Волжская набережная, 33А',
    venueSlug: 'yaroslavl-muzey-muzyka-i-vremya',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.631124,
    longitude: 39.891956,
  },
  {
    name: 'Музей истории города Ярославля',
    desc: 'Купеческий особняк Кузнецова: экспозиция о 1000-летней истории полиса.',
    address: 'Волжская набережная, 17',
    venueSlug: 'yaroslavl-muzey-istorii-goroda',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.626239,
    longitude: 39.897888,
  },
  {
    name: 'Шоу-макет «Золотое кольцо»',
    desc: 'Интерактивный миниатюрный макет, собравший города маршрута в одном движущемся пространстве.',
    address: 'Советский переулок, 2/23',
    venueSlug: 'yaroslavl-shou-maket-zolotoe-koltso',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.625093,
    longitude: 39.894025,
  },
  {
    name: 'Музей зарубежного искусства',
    desc: 'Филиал Худмузея: западноевропейская живопись, мебель и графика в старинном особняке.',
    address: 'Советская площадь, 2',
    venueSlug: 'yaroslavl-muzey-zarubezhnogo-iskusstva',
    mustSeeFilter: 'museum',
    visitMinutes: 60,
    latitude: 57.626307,
    longitude: 39.893838,
  },

  // --- Храмы (28-31) ---
  {
    name: 'Церковь Ильи Пророка',
    desc: 'Шедевр русского узорочья XVII века с уникальными росписями на центральной площади города.',
    address: 'Советская площадь, 7',
    locationSlug: 'yaroslavl-tserkov-il-i-proroka',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 57.626221,
    longitude: 39.8941,
  },
  {
    name: 'Церковь Иоанна Предтечи в Толчкове',
    desc: 'Уникальный 15-главый изразцовый храм, изображенный на оборотной стороне 1000-рублевой купюры.',
    address: '2-я Закоторосльная набережная, 69',
    locationSlug: 'yaroslavl-tserkov-ioanna-predtechi-tolchkovo',
    mustSeeFilter: 'temple',
    visitMinutes: 40,
    latitude: 57.611148,
    longitude: 39.856516,
  },
  {
    name: 'Успенский кафедральный собор',
    desc: 'Золотоглавый собор, заново возведенный к 1000-летию города на Стрелке.',
    address: 'Почтовая ул., 3',
    locationSlug: 'yaroslavl-uspenskiy-sobor',
    mustSeeFilter: 'temple',
    visitMinutes: 30,
    latitude: 57.621801,
    longitude: 39.901354,
  },
  {
    name: 'Церковь Иоанна Златоуста в Коровниках',
    desc: 'Храмовый ансамбль на берегу Волги с гигантским пятиметровым керамическим изразцовым окном.',
    address: 'Портовая набережная, 2',
    locationSlug: 'yaroslavl-tserkov-ioanna-zlatousta-korovniki',
    mustSeeFilter: 'temple',
    visitMinutes: 35,
    latitude: 57.611552,
    longitude: 39.901662,
  },

  // --- Парки и смотровые (32-39) ---
  {
    name: 'Губернаторский сад',
    desc: 'Регулярный парк с французскими партерами и современной выставкой скульптур под открытым небом.',
    address: 'Волжская набережная, 23',
    locationSlug: 'yaroslavl-gubernatorskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 40,
    latitude: 57.628422,
    longitude: 39.894343,
  },
  {
    name: 'Парк на Стрелке (Нижний партер)',
    desc: 'Ландшафтный парк с поющими светодинамическими фонтанами на слиянии Волги и Которосли.',
    address: 'Коса Стрелки',
    locationSlug: 'yaroslavl-strelka-rek-volgi-i-kotorosli',
    mustSeeFilter: 'main',
    visitMinutes: 60,
    latitude: 57.619389,
    longitude: 39.904606,
  },
  {
    name: 'Волжская набережная (верхний ярус)',
    desc: 'Один из красивейших прибрежных променадов России с чугунными решетками и беседками-ротондами.',
    address: 'Волжская набережная',
    locationSlug: 'yaroslavl-volzhskaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 45,
    latitude: 57.626122,
    longitude: 39.897118,
  },
  {
    name: 'Даманский остров',
    desc: 'Главный городской парк развлечений и аттракционов, соединенный пешеходным мостом с Которосльной набережной.',
    address: 'остров Даманский',
    locationSlug: 'yaroslavl-damanskiy-ostrov',
    mustSeeFilter: 'park',
    visitMinutes: 60,
    latitude: 57.618445,
    longitude: 39.89951,
  },
  {
    name: 'Демидовский сад',
    desc: 'Старинный липовый бульвар со светомузыкальным фонтаном в самом сердце города.',
    address: 'ул. Почтовая / пл. Челюскинцев',
    locationSlug: 'yaroslavl-demidovskiy-sad',
    mustSeeFilter: 'park',
    visitMinutes: 30,
    latitude: 57.623703,
    longitude: 39.896105,
  },
  {
    name: 'Которосльная набережная',
    desc: 'Уединенный променад вдоль малой реки с видами на старинные монастыри.',
    address: 'Которосльная набережная',
    locationSlug: 'yaroslavl-kotoroslnaya-naberezhnaya',
    mustSeeFilter: 'views',
    visitMinutes: 40,
    latitude: 57.619076,
    longitude: 39.886605,
  },
  {
    name: 'Смотровая площадка на звоннице Спасского монастыря',
    desc: 'Высочайшая легальная панорамная точка исторического центра с углом обзора 360 градусов.',
    address: 'Богоявленская площадь, 25',
    locationSlug: 'yaroslavl-smotrovaya-zvonitsa-spasskogo',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 57.621045,
    longitude: 39.888456,
  },
  {
    name: 'Бульвар на Первомайской (Казанский бульвар)',
    desc: 'Длинный зеленый сквер на месте старинного оборонительного рва.',
    address: 'ул. Первомайская',
    locationSlug: 'yaroslavl-bulvar-pervomayskaya',
    mustSeeFilter: 'park',
    visitMinutes: 25,
    latitude: 57.626436,
    longitude: 39.88592,
  },

  // --- Гастрономия и театры (40-50) ---
  {
    name: 'Театр драмы имени Федора Волкова',
    desc: 'Старейший профессиональный театр страны в здании в стиле ампир.',
    address: 'площадь Волкова, 1',
    venueSlug: 'yaroslavl-teatr-volkova',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 57.626464,
    longitude: 39.884303,
  },
  {
    name: 'Ярославская государственная филармония',
    desc: 'Главный академический концертный зал региона с органом и отличной акустикой.',
    address: 'ул. Комсомольская, 22',
    venueSlug: 'yaroslavl-filarmoniya',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 57.623442,
    longitude: 39.884165,
  },
  {
    name: 'Ресторан «Иоанн Васильевич»',
    desc: 'Трактир с интерьером по мотивам комедии «Иван Васильевич меняет профессию» и купеческой кухней.',
    address: 'ул. Революционная, 34',
    locationSlug: 'yaroslavl-restoran-ioann-vasilevich',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 57.623115,
    longitude: 39.889602,
  },
  {
    name: 'Ресторан «Пенаты»',
    desc: 'Премиальный гастрономический ресторан высокой авторской кухни на локальных продуктах.',
    address: 'ул. Свободы, 2/40',
    locationSlug: 'yaroslavl-restoran-penaty',
    mustSeeFilter: 'gastro',
    visitMinutes: 90,
    latitude: 57.626631,
    longitude: 39.882112,
  },
  {
    name: 'Ресторан «Собрание»',
    desc: 'Традиционная русская кухня прямо на территории Спасского монастыря.',
    address: 'Богоявленская площадь, 25, стр. 3',
    locationSlug: 'yaroslavl-restoran-sobranie',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 57.621456,
    longitude: 39.888619,
  },
  {
    name: 'Пивоварня «План Б»',
    desc: 'Культовое место для любителей крафтового пива от локальной ярославской пивоварни.',
    address: 'ул. Победы, 38/27',
    locationSlug: 'yaroslavl-pivovarnya-plan-b',
    mustSeeFilter: 'gastro',
    visitMinutes: 60,
    latitude: 57.632823,
    longitude: 39.878817,
  },
  {
    name: 'Кофейня «Утро»',
    desc: 'Спешелти-кофейня с минималистичным интерьером и завтраками весь день.',
    address: 'ул. Нахимсона, 16',
    locationSlug: 'yaroslavl-kofeynya-utro',
    mustSeeFilter: 'gastro',
    visitMinutes: 30,
    latitude: 57.624043,
    longitude: 39.891501,
  },
  {
    name: 'Ресторан «Мамука»',
    desc: 'Популярный ресторан современной грузинской кухни со своей сыроварней.',
    address: 'Первомайский бульвар, 1',
    locationSlug: 'yaroslavl-restoran-mamuka',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 57.628166,
    longitude: 39.884921,
  },
  {
    name: 'Ресторан «Честный Стейк»',
    desc: 'Мясное заведение со стейками сухого вызревания в центре пешеходной зоны.',
    address: 'ул. Кирова, 12В',
    locationSlug: 'yaroslavl-restoran-chestnyy-steyk',
    mustSeeFilter: 'gastro',
    visitMinutes: 75,
    latitude: 57.62589,
    longitude: 39.886455,
  },
  {
    name: 'Кафе «Багет, паштет и желтый плед»',
    desc: 'Семейное городское кафе с панорамными окнами на историческую улицу.',
    address: 'ул. Собинова, 41Б',
    locationSlug: 'yaroslavl-kafe-baget-pashtet',
    mustSeeFilter: 'gastro',
    visitMinutes: 45,
    latitude: 57.625788,
    longitude: 39.881875,
  },
  {
    name: 'Ярославский камерный театр',
    desc: 'Частный репертуарный театр под руководством Владимира Воронцова в историческом здании.',
    address: 'ул. Свердлова, 9',
    venueSlug: 'yaroslavl-kamernyy-teatr',
    mustSeeFilter: 'creative',
    visitMinutes: 90,
    latitude: 57.627421,
    longitude: 39.879456,
  },

  // --- Точки Красной линии (не раздувают IA) ---
  {
    name: 'Арт-пространство «Тепло»',
    desc: 'Креативный лофт-кластер в зданиях старых складов с шоурумами, кофейнями и мастерскими.',
    address: 'ул. Собинова, район бывшей мануфактуры',
    locationSlug: 'yaroslavl-art-prostranstvo-teplo',
    mustSeeFilter: 'creative',
    visitMinutes: 40,
    latitude: 57.62511,
    longitude: 39.88123,
  },
  {
    name: 'Стрит-арт стена за ТЦ «Аура»',
    desc: 'Легальная галерея масштабных граффити от поволжских райтеров.',
    address: 'за ТЦ «Аура»',
    locationSlug: 'yaroslavl-strit-art-aura',
    mustSeeFilter: 'creative',
    visitMinutes: 20,
    latitude: 57.62612,
    longitude: 39.87381,
  },
  {
    name: 'Волжская набережная (нижний ярус)',
    desc: 'Неформальный променад у воды: лонгбордисты, уличные музыканты и художники.',
    address: 'Волжская набережная, нижний ярус',
    locationSlug: 'yaroslavl-volzhskaya-naberezhnaya-nizhniy-yarus',
    mustSeeFilter: 'views',
    visitMinutes: 30,
    latitude: 57.62912,
    longitude: 39.89683,
  },
  {
    name: 'Арт-платформа «Миллениум»',
    desc: 'Футуристичный концертный центр - площадка современного искусства и фестивалей.',
    address: 'Которосльная набережная, КЗЦ «Миллениум»',
    locationSlug: 'yaroslavl-art-platforma-millennium',
    mustSeeFilter: 'creative',
    visitMinutes: 30,
    latitude: 57.61412,
    longitude: 39.86412,
  },
];

export const YAROSLAVL_SUBURBS: any[] = [
  {
    name: 'Историко-культурный комплекс Вятское',
    desc: '«Самая красивая деревня России»: полностью отреставрированное торгово-промысловое село XIX века, превращенное в живой музейный кластер без заброшенных зданий.',
    locationSlug: 'yaroslavl-vyatskoe',
    mustSeeFilter: 'main',
    visitMinutes: '5-6 ч',
    latitude: 57.863412,
    longitude: 40.268114,
    address: 'Ярославская область, Некрасовский район, с. Вятское',
    travelVector: 'Автобус №123 ~45 мин',
    travelVectorBlurb:
      'Закладывайте на пригородный автобус №123 или личный автомобиль ~45 минут, чтобы приехать к 09:30 утра.',
    timingNote:
      'По центральной купеческой улице вдоль речки Ухтомки двигайтесь на север к площади Согласия, напоследок оставив омовение в святом Еретьевском источнике.',
    places: [
      {
        name: 'Музей забавных и непослушных вещей',
        desc: 'Интерактивное юмористическое пространство старого деревенского быта.',
        locationSlug: 'yaroslavl-vyatskoe-muzey-zabavnyh-veshchey',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 40,
      },
      {
        name: 'Музей русской предприимчивости',
        desc: 'Экспозиция о ярославских отходниках, строителях и купеческих секретах богатства.',
        locationSlug: 'yaroslavl-vyatskoe-muzey-russkoy-predpriimchivosti',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 35,
      },
      {
        name: 'Музей кухонной машинерии',
        desc: 'Коллекция старинных тостеров, миксеров и кулинарных гаджетов прошлого.',
        locationSlug: 'yaroslavl-vyatskoe-muzey-kuhonnoy-mashinerii',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 30,
      },
      {
        name: 'Храм Воскресения Христова',
        desc: 'Храм 1750 года с 30-метровой колокольней и чудотворным распятием.',
        locationSlug: 'yaroslavl-vyatskoe-hram-voskreseniya',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 30,
      },
      {
        name: 'Музей «Звуки времени»',
        desc: 'Собрание действующих старинных музыкальных автоматов, органов и шарманок.',
        locationSlug: 'yaroslavl-vyatskoe-zvuki-vremeni',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 35,
      },
      {
        name: 'Антикварная купеческая пекарня',
        desc: 'Выпекают хлеб по старинным местным закваскам.',
        locationSlug: 'yaroslavl-vyatskoe-kupecheskaya-pekarniya',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 25,
      },
      {
        name: 'Еретьевский источник',
        desc: 'Старинная купель-ротонда с минеральной целебной водой.',
        locationSlug: 'yaroslavl-vyatskoe-eretievskiy-istochnik',
        address: 'Ярославская область, Некрасовский район, с. Вятское',
        latitude: 57.863412,
        longitude: 40.268114,
        visitMinutes: 20,
      },
    ],
  },
  {
    name: 'Музей-усадьба Н.А. Некрасова «Карабиха»',
    desc: 'Единственная сохранившаяся в Ярославской области дворянская усадьба дворцового типа с регулярными парками. Здесь Некрасов создавал поэмы «Кому на Руси жить хорошо» и «Русские женщины».',
    locationSlug: 'yaroslavl-karabikha',
    mustSeeFilter: 'main',
    visitMinutes: '4-5 ч',
    latitude: 57.511235,
    longitude: 39.754112,
    address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
    travelVector: 'Автобус №105 ~25 мин',
    travelVectorBlurb:
      'Закладывайте на автобус №105 или маршрутку в южном направлении ~25 минут, чтобы приехать к 09:00 утра.',
    timingNote:
      'Через парадные въездные ворота двигайтесь мимо Большого дома в глубину Нижнего парка к каскадным прудам, напоследок оставив посещение Восточного флигеля.',
    places: [
      {
        name: 'Большой господский дом',
        desc: 'Двухэтажный классический дворец с бельведером и сохранившимися интерьерами поэта.',
        locationSlug: 'yaroslavl-karabikha-bolshoy-gospodskiy-dom',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 50,
      },
      {
        name: 'Восточный и Западный флигели',
        desc: 'Жилые постройки усадьбы с личными вещами семьи писателя.',
        locationSlug: 'yaroslavl-karabikha-fligeli',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 35,
      },
      {
        name: 'Верхний регулярный французский парк',
        desc: 'Строгий геометрический сад с вековыми липами перед парадным фасадом.',
        locationSlug: 'yaroslavl-karabikha-verhniy-frantsuzskiy-park',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 30,
      },
      {
        name: 'Нижний пейзажный английский парк',
        desc: 'Полудикий романтический лес с вековыми дубами для уединенных прогулок.',
        locationSlug: 'yaroslavl-karabikha-nizhniy-angliyskiy-park',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 40,
      },
      {
        name: 'Каскад трех родниковых прудов',
        desc: 'Живописная водная система в низине парковой зоны.',
        locationSlug: 'yaroslavl-karabikha-kaskad-prudov',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 25,
      },
      {
        name: 'Музей дедушки Мазая',
        desc: 'Интерактивная детская экспозиция по мотивам знаменитого стихотворения.',
        locationSlug: 'yaroslavl-karabikha-muzey-dedushki-mazaya',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 30,
      },
      {
        name: 'Исторический винный склад',
        desc: 'Сохранившееся каменное здание дореволюционного производства князей Голицыных.',
        locationSlug: 'yaroslavl-karabikha-vinnyy-sklad',
        address: 'Ярославский район, д. Карабиха, ул. Школьная, 2А',
        latitude: 57.511235,
        longitude: 39.754112,
        visitMinutes: 20,
      },
    ],
  },
];

export const YAROSLAVL_DAY_ROUTE_PRESETS: any[] = [
  {
    id: 'yaroslavl-gosudareva-volga',
    title: 'Государева Волга: от Медведя до Стрелки',
    description:
      'Линейный маршрут по парадным набережным, музеям и древним храмам центра: от Рычащего Медведя через Спасский монастырь и Илью Пророка к закату на Стрелке.',
    travelVector: 'Парадный пешеходный променад',
    timingNote:
      'Около 4 часов пешком: Медведь - монастырь - «Афоня» - Илья Пророк - набережная - Успенский - Стрелка.',
    coverImageUrl: '/images/venues/yaroslavl/strelka-rek-volgi-i-kotorosli.jpg',
    stops: [
      {
        name: 'Памятник Рычащему Медведю',
        desc: '10 минут: слушаем рык ярославского тотема и трем лапу на удачу.',
        locationSlug: 'yaroslavl-pamyatnik-rychashemu-medvedyu',
        mustSeeFilter: 'monument',
        visitMinutes: 10,
        address: 'ул. Первомайская, 15А',
        latitude: 57.622612,
        longitude: 39.886345,
      },
      {
        name: 'Спасский монастырь и смотровая звонницы',
        desc: '45 минут на осмотр древнейшего собора и панораму 360 градусов.',
        locationSlug: 'yaroslavl-yaroslavskiy-kreml-spaso-preobrazhenskiy-monastyr',
        mustSeeFilter: 'main',
        visitMinutes: 45,
        address: 'Богоявленская площадь, 25',
        latitude: 57.621214,
        longitude: 39.888514,
        transitTip: 'Пешком 2 минуты (150 м)',
      },
      {
        name: 'Скульптура «Афоня и Коля» и обед в «Иоанне Васильевиче»',
        desc: '1 час 15 минут: фото с киногероями и купеческий обед в тематическом трактире.',
        locationSlug: 'yaroslavl-skulptura-afonya-i-kolya',
        mustSeeFilter: 'main',
        visitMinutes: 75,
        address: 'ул. Нахимсона, 21А',
        latitude: 57.623412,
        longitude: 39.889912,
        transitTip: 'Пешком 5 минут (400 м) по Революционной',
      },
      {
        name: 'Церковь Ильи Пророка',
        desc: '25 минут на изразцы и подлинные фрески XVII века на главной площади.',
        locationSlug: 'yaroslavl-tserkov-il-i-proroka',
        mustSeeFilter: 'temple',
        visitMinutes: 25,
        address: 'Советская площадь, 7',
        latitude: 57.626221,
        longitude: 39.8941,
        transitTip: 'Пешком 4 минуты (350 м) через Демидовский сад',
      },
      {
        name: 'Волжская набережная и Губернаторский дом',
        desc: '40 минут: верхний ярус набережной, картинная галерея и парк скульптур.',
        locationSlug: 'yaroslavl-volzhskaya-naberezhnaya',
        mustSeeFilter: 'views',
        visitMinutes: 40,
        address: 'Волжская набережная',
        latitude: 57.626122,
        longitude: 39.897118,
        transitTip: 'Пешком 3 минуты (250 м) к кромке реки',
      },
      {
        name: 'Успенский собор и скульптура «Троица»',
        desc: '20 минут на монументальный собор и трехмерный памятник Троице.',
        locationSlug: 'yaroslavl-uspenskiy-sobor',
        mustSeeFilter: 'temple',
        visitMinutes: 20,
        address: 'Почтовая ул., 3',
        latitude: 57.621801,
        longitude: 39.901354,
        transitTip: 'Пешком 6 минут (500 м) по бульвару к мысу',
      },
      {
        name: 'Парк на Стрелке',
        desc: '30 минут: вечерний закат на слиянии двух рек у танцующих светомузыкальных фонтанов.',
        locationSlug: 'yaroslavl-strelka-rek-volgi-i-kotorosli',
        mustSeeFilter: 'main',
        visitMinutes: 30,
        address: 'Коса Стрелки',
        latitude: 57.619389,
        longitude: 39.904606,
        transitTip: 'Пешком 5 минут (400 м) спуск по ступеням на косу',
      },
    ],
  },
  ...YAROSLAVL_LINE_DAY_ROUTE_PRESETS,
];

export const YAROSLAVL_FAQ: Array<{ q: string; a: string }> = [
  {
    q: 'Как быстрее всего добраться до Ярославля из Москвы?',
    a: 'Самый удобный путь - фирменные дневные экспресс-поезда до вокзала «Ярославль-Главный» примерно за 3 часа 20 минут. Также ходят регулярные автобусы, а автомобилисты едут по трассе М-8 «Холмогоры».',
  },
  {
    q: 'Правда ли, что исторический центр Ярославля под защитой ЮНЕСКО?',
    a: 'Да. Центральная часть с регулярной радиальной планировкой XVIII века и десятками каменных храмов официально включена в список Всемирного наследия ЮНЕСКО.',
  },
  {
    q: 'Что из Ярославля изображено на 1000-рублевой купюре?',
    a: 'На банкноте узнают памятник Ярославу Мудрому на Богоявленской площади, часовню Казанской иконы Божией Матери на набережной и церковь Иоанна Предтечи в Толчкове с 15 главами.',
  },
  {
    q: 'Это Кремль или Спасский монастырь?',
    a: 'Белокаменный комплекс на Богоявленской площади - Ярославский музей-заповедник (Спасо-Преображенский монастырь). Туристы часто называют его «Кремлем», но исторически это монастырская цитадель, а не княжеский кремль.',
  },
];

export const YAROSLAVL_TRAVEL =
  'Из Москвы быстрее всего - фирменные дневные экспрессы до «Ярославль-Главный» примерно за 3 часа 20 минут; также автобусы и трасса М-8 «Холмогоры». Лучшее окно - конец мая-сентябрь: навигация по Волге, променад по Стрелке и храмы центра ЮНЕСКО. Зимой город похож на палехскую миниатюру: каток на Советской, медовуха и сани на Стрелке около -10 °C. Весной к маю +17 °C и День города с салютом над рекой. Осенью (+15 °C в сентябре) золотеет Губернаторский сад, меньше экскурсионных автобусов, удобнее театр и музеи.';
